**Necessary imports**

In [22]:
import subprocess
import os
import pandas as pd
import json

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

**Setting parameters**

In [23]:
simple_render_raw_data_dir = "/dlabdata1/tsoares/wikidumps/"
root_processing_dir = "/dlabdata1/boulenge/wikidumps_data"
experiment_name = "selected_langs_small_sample_3"
processed_data_dir = os.path.join(root_processing_dir, experiment_name)
server_out_dir = os.path.join("/var/www/html/wikinsert", experiment_name)
processes = 48
min_nb_samples = 5
revisions_sampling_size = 0.0003 #10% of the revisions 

#For all possible languages
all_langs = sorted(set([filename.split("wiki")[0] for filename in os.listdir(simple_render_raw_data_dir) if "wiki" in filename]))

selected_langs_path = 'selected_languages.json'

with open(selected_langs_path, 'r') as f:
   langs = json.load(f)

side_context_sizes = [5]  #List of context size to try
second_month = "20231001"
third_month = "20231101"

langs_to_remove = ["war", "ky", "nds-nl"] #These languages do not work

for lang in langs_to_remove:
    if lang in all_langs:
        all_langs.remove(lang)


#langs = langs[:2] #For testing purposes

print("Will process languages:\n" + '\n'.join(langs))

Will process languages:
af
ar
cs
cy
de
en
es
fa
fr
ga
gu
he
hi
is
it
ja
jv
kk
kn
ms
pt
ru
simple
sk
sw
tr
ur
uz
vi
zh

**Defining data paths**

In [24]:
# Define directories
all_revisions_dir = os.path.join(root_processing_dir, "all_revisions")
rev_files_dir = os.path.join(processed_data_dir, "revisions_files")
parsed_htmls_dir = os.path.join(processed_data_dir, "parsed_htmls")
contexts_splitted_data_dir = os.path.join(processed_data_dir, "contexts_splitted_data")
ready_to_score_data_dir = os.path.join(processed_data_dir, "ready_to_score_data")
scored_data_dir = os.path.join(processed_data_dir, "scored_data")
#crawling_output_dir = os.path.join(processed_data_dir, "crawled_pages")
crawling_output_dir = os.path.join(server_out_dir, "crawled_pages")

scripts_dir = "scripts"

# Create necessary directories if they don't exist
os.makedirs(all_revisions_dir, exist_ok=True)
os.makedirs(rev_files_dir, exist_ok=True)
os.makedirs(parsed_htmls_dir, exist_ok=True)
os.makedirs(contexts_splitted_data_dir, exist_ok=True)
os.makedirs(ready_to_score_data_dir, exist_ok=True)
os.makedirs(scored_data_dir, exist_ok=True)
os.makedirs(crawling_output_dir, exist_ok=True)
os.makedirs(server_out_dir, exist_ok=True)

**Prepare files to be crawled and parsed**

**Carefull, the following is only needed to be ran once for all (common for any experiment), so was probably ran before**

It generates the diffenret pages ids we will crawl, using data from the previous study

In [25]:
"""for lang in all_langs:
        print(f"Processing language: {lang}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{all_revisions_dir}/revisions_{lang}.parquet"
        if not os.path.exists(save_path):
            print("Generating revisions file")    
            subprocess.run([
                "python", f"{scripts_dir}/generate_revisions_file.py",
                "--versions_file", f"{second_month_path}/eval/link_versions",
                "--html_dir", f"{second_month_path}/eval/pages",
                "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
                "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",
                "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",
                "--save_path", save_path
            ])
        else:
            print("Revisions file already exists")"""

'for lang in all_langs:\n        print(f"Processing language: {lang}")\n        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"\n        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"\n        save_path = f"{all_revisions_dir}/revisions_{lang}.parquet"\n        if not os.path.exists(save_path):\n            print("Generating revisions file")    \n            subprocess.run([\n                "python", "generate_revisions_file.py",\n                "--versions_file", f"{second_month_path}/eval/link_versions",\n                "--html_dir", f"{second_month_path}/eval/pages",\n                "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",\n                "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",\n                "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",\n                "--save_path", save_path\n            ])\n        else:\n            print("Revisions file already exists")'

**Sampling**

In [26]:
langs_stats = []

for lang in langs:
    full_revisions_path = f"{all_revisions_dir}/revisions_{lang}.parquet"
    full_revisions_df = pd.read_parquet(full_revisions_path)
    print(f"Sampling language: {lang}")
    nb_total = len(full_revisions_df)
    pre_min_to_sample = 2*min_nb_samples #we take twice the number to prevent future loss of data
    if nb_total > pre_min_to_sample:
        pre_nb_samples = max(pre_min_to_sample, int(revisions_sampling_size*2*nb_total))
    else:
        pre_nb_samples = nb_total

    if nb_total > min_nb_samples:
        nb_samples = max(min_nb_samples, int(revisions_sampling_size*nb_total))
    else:
        nb_samples = nb_total

    langs_stats.append({
        "lang": lang,
        "orig_nb_revisions": nb_total,
        "pre_nb_samples": pre_nb_samples,
        "nb_samples": nb_samples
    })

    sampled_revisions_path = f"{rev_files_dir}/revisions_{lang}.parquet"
    sampled_revisions = full_revisions_df.sample(n=pre_nb_samples, random_state=42)
    sampled_revisions.to_parquet(sampled_revisions_path)

display(pd.DataFrame(langs_stats))
display(pd.DataFrame(langs_stats).sum())

Sampling language: af

Sampling language: ar
Sampling language: cs
Sampling language: cy
Sampling language: de
Sampling language: en
Sampling language: es
Sampling language: fa
Sampling language: fr
Sampling language: ga
Sampling language: gu
Sampling language: he
Sampling language: hi
Sampling language: is
Sampling language: it
Sampling language: ja
Sampling language: jv
Sampling language: kk
Sampling language: kn
Sampling language: ms
Sampling language: pt
Sampling language: ru
Sampling language: simple
Sampling language: sk
Sampling language: sw
Sampling language: tr
Sampling language: ur
Sampling language: uz
Sampling language: vi
Sampling language: zh

      lang  orig_nb_revisions  pre_nb_samples  nb_samples
0       af                707              10           5
1       ar               6700              10           5
2       cs               4391              10           5
3       cy                238              10           5
4       de              49899              29          14
5       en             194300             116          58
6       es              29970              17           8
7       fa               7967              10           5
8       fr              26847              16           8
9       ga                109              10           5
10      gu                 16              10           5
11      he              17938              10           5
12      hi                745              10           5
13      is                285              10           5
14      it              22827              13           6
15      ja              36301              21          10
16      jv                 95              10           5
17      kk               1019              10           5
18      kn                199              10           5
19      ms               1526              10           5
20      pt               8520              10           5
21      ru              20743              12           6
22  simple               1841              10           5
23      sk               1286              10           5
24      sw                170              10           5
25      tr               6811              10           5
26      ur               3287              10           5
27      uz               1343              10           5
28      vi               3716              10           5
29      zh              18087              10           5

lang                 afarcscydeenesfafrgaguhehiisitjajvkkknmsptrusi...
orig_nb_revisions                                               467883
pre_nb_samples                                                     454
nb_samples                                                         225
dtype: object

**Crawling first versions only**

There is no need to re-crawl the second version with all its files as the index is sufficent for these.

In [27]:
for lang in langs:
    print(f"Processing language: {lang}")
    subprocess.run([
        "python", f"{scripts_dir}/crawl.py",
        "--revisions_path", f"{rev_files_dir}/revisions_{lang}.parquet",
        "--output_dir", f"{crawling_output_dir}/{lang}",
        "--n_processes", str(processes),
        "--lang", lang
    ])

Processing language: af

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.06668637990951538 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 6760.64it/s]

Processing language: ar
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.16956610282262166 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 1828.78it/s]

Processing language: cs
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.060522409280141194 minutes, post processing...
Processing language: cy

Moving files: 100%|██████████| 10/10 [00:00<00:00, 7305.88it/s]

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.10672356287638346 minutes, post processing...
Processing language: de

Moving files: 100%|██████████| 10/10 [00:00<00:00, 7402.58it/s]

Total number of pages to crawl: 29
Running crawling on 48 processes
Crawling finished in 0.17985773086547852 minutes, post processing...
Processing language: en

Moving files: 100%|██████████| 29/29 [00:00<00:00, 9058.30it/s]

Total number of pages to crawl: 116
Running crawling on 48 processes
Crawling finished in 0.5091101288795471 minutes, post processing...
Processing language: es

Moving files: 100%|██████████| 116/116 [00:00<00:00, 6734.48it/s]

Total number of pages to crawl: 17
Running crawling on 48 processes
Crawling finished in 0.17784680525461832 minutes, post processing...
Processing language: fa

Moving files: 100%|██████████| 17/17 [00:00<00:00, 2738.64it/s]

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.16898154417673747 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 3582.73it/s]

Processing language: fr
Total number of pages to crawl: 16
Running crawling on 48 processes
Crawling finished in 0.239244012037913 minutes, post processing...

Moving files: 100%|██████████| 16/16 [00:00<00:00, 2175.19it/s]

Processing language: ga
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.17513572772343952 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 4560.51it/s]

Processing language: gu
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.10219168265660604 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 5058.25it/s]

Processing language: he
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.14130326509475707 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 5677.95it/s]

Processing language: hi
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.14560966491699218 minutes, post processing...
Processing language: is

Moving files: 100%|██████████| 10/10 [00:00<00:00, 6095.49it/s]

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.13876300652821857 minutes, post processing...
Processing language: it

Moving files: 100%|██████████| 10/10 [00:00<00:00, 5954.43it/s]

Total number of pages to crawl: 13
Running crawling on 48 processes
Crawling finished in 0.12721843322118123 minutes, post processing...

Moving files: 100%|██████████| 13/13 [00:00<00:00, 7024.73it/s]

Processing language: ja
Total number of pages to crawl: 21
Running crawling on 48 processes
Crawling finished in 0.14758358001708985 minutes, post processing...
Processing language: jv

Moving files: 100%|██████████| 21/21 [00:00<00:00, 10383.16it/s]

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.13457308212916055 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 8871.20it/s]

Processing language: kk
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.14490206638971964 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 3611.11it/s]

Processing language: kn
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.09019449154535929 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 4374.53it/s]

Processing language: ms
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.12511589924494426 minutes, post processing...
Processing language: pt

Moving files: 100%|██████████| 10/10 [00:00<00:00, 8333.61it/s]

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.10461553335189819 minutes, post processing...
Processing language: ru

Moving files: 100%|██████████| 10/10 [00:00<00:00, 4987.28it/s]

Total number of pages to crawl: 12
Running crawling on 48 processes
Crawling finished in 0.12404929002126058 minutes, post processing...

Moving files: 100%|██████████| 12/12 [00:00<00:00, 8172.05it/s]

Processing language: simple
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.14014660120010375 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 6101.69it/s]

Processing language: sk
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.10320559740066529 minutes, post processing...
Processing language: sw

Moving files: 100%|██████████| 10/10 [00:00<00:00, 6566.94it/s]

Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.08933457930882772 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 5556.11it/s]

Processing language: tr
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.1322333852450053 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 4445.47it/s]

Processing language: ur
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.1328275243441264 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 3109.66it/s]

Processing language: uz
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.09501281579335531 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 4829.37it/s]

Processing language: vi
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.1813191254933675 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 3077.71it/s]

Processing language: zh
Total number of pages to crawl: 10
Running crawling on 48 processes
Crawling finished in 0.149397873878479 minutes, post processing...

Moving files: 100%|██████████| 10/10 [00:00<00:00, 8586.09it/s]

**Parsing of the htmls and sentence tokenizing**

In [28]:
for lang in langs:
    print(f"Processing language: {lang}")
    second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
    first_version_specific_html_dir = f"{crawling_output_dir}/{lang}"
    save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
    output_dir = f"{parsed_htmls_dir}/{lang}_v2"
    first_version_specific_output_dir = f"{parsed_htmls_dir}/{lang}_v1"
        
    subprocess.run([
        "python", f"{scripts_dir}/parsing.py",
        "--revisions_path", save_path,        
        "--html_dir", f"{second_month_path}/eval/pages",
        "--first_versions_specific_html_dir", first_version_specific_html_dir,
        "--output_dir", output_dir,
        "--first_versions_specific_output_dir", first_version_specific_output_dir,
        "--lang", lang,
        "--n_processes", str(processes)
    ])

    parsed_htmls_paths = os.listdir(first_version_specific_output_dir)
    sentences_path = list(
        filter(
            lambda x: (
                x.endswith("sentences.jsonl") and ("raw" not in x)
                ),
            parsed_htmls_paths
            )
        )[0]
    links_path = list(filter(lambda x: x.endswith("links.jsonl"), parsed_htmls_paths))[0]
    sentences_df = pd.read_json(f"{first_version_specific_output_dir}/{sentences_path}")
    links_df = pd.read_json(f"{first_version_specific_output_dir}/{links_path}")

    display(sentences_df.head(5))
    display(links_df.head(5))

Processing language: af
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/af
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 41.77it/s]

Time taken for v1: 10.453876972198486
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 39.72it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,1509afbe912fc0e70ec3d7a083f7e21b,0,Piket-Bo-Berg is 'n plaasgemeenskap geleë in d...,34245,34372,Lead,"[{'start': 34245, 'end': 34258}, {'start': 342..."
1,c771bb69375660fb63a2c352317aafc7,1,Die gemeenskap lê bo-op die Piketberge en is n...,34372,34523,Lead,"[{'start': 34372, 'end': 34440}, {'start': 344..."
2,47b40cd8340f99c7be3ce1ea8b867e63,2,Dit is oor tyd deur 'n verskeidenheid boere be...,34523,34635,Lead,"[{'start': 34523, 'end': 34635}]"
3,49a811f19c48f823bf7f53ecdee39c16,3,"Voorheen is die Bo-Berg bewoon deur Boesmanne,...",34635,34729,Lead,"[{'start': 34635, 'end': 34729}]"
4,166bf21d3b5aa648f209a64e799810a6,4,In 1810 was daar vyf plase wat daar op die Ber...,34729,34797,Lead,"[{'start': 34736, 'end': 34797}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Russies,59270,Russies,59321,Lead,0
1,file:///wiki/11_Maart,59858,11 Maart,59912,Lead,0
2,file:///wiki/1818,59913,1818,59955,Lead,0
3,file:///wiki/14_Julie,60116,14 Julie,60170,Lead,0
4,file:///wiki/Ou_Styl-_en_Nuwe_Styl-datums,60172,1 Julie,60265,Lead,0

Processing language: ar
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/ar
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 46.55it/s]

Time taken for v1: 36.22678470611572
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 40.41it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c27eb9685a5f1a1eb3ac0779e8acc780,0,هل تقصد:\n\nميدان الشهداء أكبر ميادين الإسكندر...,45768,46175,Lead,"[{'start': 45768, 'end': 45777}, {'start': 457..."
1,3221f2aca4efbf9cf967f7d8b35fd4f5,1,\nميدان الشهداء في العاصمة الليبية طرابلس.,46175,46526,Lead,"[{'start': 46180, 'end': 46181}, {'start': 463..."
2,e0c8e70c897fc102d57200ce83426f37,2,\nميدان الشهداء في العاصمة اللبنانية بيروت.,46526,46939,Lead,"[{'start': 46531, 'end': 46532}, {'start': 467..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A7%D9%84%D9%84%D8%BA%D8%A9_%D...,87052,بالإنجليزية,87200,Lead,0
1,file:///wiki/%D8%B9%D8%AF%D8%AF_%D8%AA%D8%A7%D...,87297,عدد سيارة الأجرة,87422,Lead,0
2,file:///wiki/%D8%B9%D8%AF%D8%AF_%D8%B7%D8%A8%D...,87432,عدد طبيعي,87529,Lead,0
3,file:///wiki/%D8%B9%D8%AF%D8%AF_%D8%AA%D8%A7%D...,89565,عدد سيارة الأجرة,89690,انظر أيضا,1
4,file:///wiki/%D8%A8%D9%88%D8%A7%D8%A8%D8%A9:%D...,98001,بوابة رياضيات,98130,وصلات خارجية,2

Processing language: cs
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/cs
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 89.17it/s]

Time taken for v1: 17.850936889648438
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 86.81it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,0393d7ca354d0aeeb40dc4a7c9fc2e05,0,O&nbsp;českém lékaři a poslanci ČNR za KSČ poj...,40096,40273,Lead,"[{'start': 40096, 'end': 40156}, {'start': 402..."
1,9268f483e9dbf84d7c1eac3ae6dfc436,1,\n\nVladimír Balaš (* 20.,40273,48349,Lead,"[{'start': 40279, 'end': 40280}, {'start': 482..."
2,be08cfbf99eb4d8f2cfd6300a9b7e64e,2,dubna 1959 Prostějov) je český právník a vysok...,48349,48606,Lead,"[{'start': 48349, 'end': 48354}, {'start': 483..."
3,32f775b61dc3351c07697178a3f48457,3,Od června 2022 do května 2023 byl ministrem šk...,48606,49270,Lead,"[{'start': 48606, 'end': 48640}, {'start': 488..."
4,ed7d90c68a46cd4f53b7d4241ac36c30,4,Zabývá se ústavním právem a mezinárodním práve...,49270,49328,Lead,"[{'start': 49270, 'end': 49328}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/30._%C4%8Dervenec,42653,30. července,42724,Lead,1
1,file:///wiki/1970,42725,1970,42767,Lead,1
2,file:///wiki/Plze%C5%88,42769,Plzeň,42819,Lead,1
3,file:///wiki/Mal%C3%AD%C5%99,42830,malíř,42885,Lead,1
4,file:///wiki/Grafika,42888,grafik,42938,Lead,1

Processing language: cy
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/cy
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 125.86it/s]

Time taken for v1: 4.506501197814941
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 120.72it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c46ff863a2f663576c1fd396a587f7d7,0,\nFfilm ddogfen gan y cyfarwyddwr Philippe Mor...,45067,45383,Lead,"[{'start': 45066, 'end': 45067}, {'start': 450..."
1,9e192b36bc9e2bcf21a472294ef50a2d,1,Fe'i cynhyrchwyd yn y Deyrnas Gyfunol.,45383,45506,Lead,"[{'start': 45383, 'end': 45403}, {'start': 454..."
2,5f7b9a71e9447167116dd0f2fa36c391,2,Sgwennwyd y sgript yn wreiddiol yn Saesneg.,45506,45594,Lead,"[{'start': 45506, 'end': 45541}, {'start': 455..."
3,2b673e7761f64ee5ff1eac524319ee1b,3,Y prif actorion yn y ffilm hon yw Charlie Chap...,45594,47352,Lead,"[{'start': 45601, 'end': 45823}, {'start': 458..."
4,c7233a14e9557b69c278bc5f552ed735,4,"Fel y nodwyd, cyhoeddwyd y ffilm yn 1975.",47352,47401,Lead,"[{'start': 47359, 'end': 47401}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Sosialaeth,91867,sosialaidd,91927,Lead,2
1,file:///wiki/Ewrop,92005,Ewrop,92050,Lead,2
2,file:///wiki/Rwsia,92053,Rwsia,92098,Lead,2
3,file:///wiki/Hawliau_dynol,92266,hawliau dynol,92335,Lead,3
4,file:///wiki/Clara_Zetkin,93385,Clara Zetkin,93451,Hanes y diwrnod,6

Processing language: de
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/de
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 29/29 [00:00<00:00, 36.16it/s]

Time taken for v1: 26.180115222930908
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 29/29 [00:00<00:00, 40.76it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,3adc323b94f5bb2bc00fbc78b36133d3,0,Maria Louise Eleonore von Hessen-Rotenburg (* 18.,10318,10416,Lead,"[{'start': 10318, 'end': 10360}, {'start': 103..."
1,06bd0d2d3f7c228b86f5b0adfa7074da,1,April 1729 auf Schloss Rotenburg; † 6.,10416,10605,Lead,"[{'start': 10416, 'end': 10421}, {'start': 104..."
2,4b2b253ec49f8652656e6cbb14cc6986,2,Januar 1800 auf Schloss Anholt) war eine landg...,10605,10937,Lead,"[{'start': 10605, 'end': 10611}, {'start': 106..."
3,1e26a67984f28b0086918d4824206afe,3,\nMaria Louise wurde als Tochter des Erbprinze...,10942,11483,Lead,"[{'start': 10941, 'end': 10942}, {'start': 110..."
4,983bc2984debb2edc4d71aa6bc08cee9,4,Am 16. März 1756 heiratete sie in Hoogstraten ...,11483,11947,Leben,"[{'start': 11490, 'end': 11524}, {'start': 116..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Besatzungszone,12283,Besatzungszonen,12356,Lead,0
1,file:///wiki/Deutschland_1945_bis_1949,12360,besetzten Deutschland,12461,Lead,0
2,file:///wiki/Territorium,12492,territorialen,12557,Lead,1
3,file:///wiki/Harz_(Mittelgebirge),12575,Harz,12649,Lead,1
4,file:///wiki/Vereinigtes_K%C3%B6nigreich,15255,Briten,15340,Geschichte,2

Processing language: en
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/en
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 116/116 [00:02<00:00, 52.83it/s]

Time taken for v1: 88.59375500679016
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 116/116 [00:02<00:00, 47.48it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c6a44f55f7e71837145ce9f653763b34,0,\nThalapathy 68 is the working title of an upc...,43033,43431,Lead,"[{'start': 43032, 'end': 43033}, {'start': 430..."
1,f977de3d97c855a76fc4626032a05c6e,1,"The film stars Vijay, leading an ensemble cast...",43431,44519,Lead,"[{'start': 43431, 'end': 43446}, {'start': 434..."
2,a5be16b7c0ca211aaa61f485f84e5a72,2,"Initially, Atlee was reported to direct the pr...",44519,44688,Lead,"[{'start': 44526, 'end': 44537}, {'start': 445..."
3,727435c628daccbc79a242d2e2814892,3,The film was announced in May 2023 under the t...,44688,44817,Lead,"[{'start': 44688, 'end': 44749}, {'start': 447..."
4,02ff19da1c68b6dab91b58016facede6,4,Principal photography began in October 2023.,44817,44934,Lead,"[{'start': 44885, 'end': 44906}, {'start': 449..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Borough_(Pennsylvania),63615,borough,63696,Lead,0
1,"file:///wiki/Somerset_County,_Pennsylvania",63700,Somerset County,63803,Lead,0
2,file:///wiki/Pennsylvania,63805,Pennsylvania,63871,Lead,0
3,file:///wiki/2020_United_States_census,63918,2020 census,64009,Lead,1
4,"file:///wiki/Johnstown,_Pennsylvania",64216,"Johnstown, Pennsylvania",64315,Lead,2

Processing language: es
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/es
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 17/17 [00:00<00:00, 64.45it/s]

Time taken for v1: 23.49346137046814
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 17/17 [00:00<00:00, 50.22it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,cbcfd33e992ebd1b250c43e5e71ffab1,0,\nLos ataques contra palestinos que evacuan la...,44670,45342,Lead,"[{'start': 44669, 'end': 44670}, {'start': 446..."
1,b3d089df616633a155288473e4f0ac8e,1,​ Estos ataques tuvieron lugar después de una ...,45342,45698,Lead,"[{'start': 45510, 'end': 45698}]"
2,b52618dbf4f6f0d985bc27c0c9489307,2,​\n,45698,45873,Lead,"[{'start': 45866, 'end': 45868}, {'start': 458..."
3,b0b732950c5771dd51015835acf590c1,3,Las tensiones aumentaron cuando milicianos pal...,45989,46311,Antecedentes,"[{'start': 45988, 'end': 45989}, {'start': 459..."
4,7edb8084e65d6309021d301676963578,4,El país Hebreo respondió con una serie de ataq...,46311,46528,Antecedentes,"[{'start': 46311, 'end': 46353}, {'start': 464..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Bowling,39721,bowling,39772,Lead,1
1,file:///wiki/Kingstree_(Carolina_del_Sur),40136,"Kingstree, Carolina del Sur",40249,Biografía,3
2,file:///wiki/Pittsburgh,40679,Pittsburgh,40739,Biografía,6
3,file:///wiki/S%C3%B3ftbol,40837,sóftbol,40893,Biografía,7
4,file:///wiki/Baloncesto,40896,baloncesto,40956,Biografía,7

Processing language: fa
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/fa
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 50.20it/s]

Time taken for v1: 25.44888401031494
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 62.36it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,d714e3d52507b683d2660dd2cac4d7e8,0,\nنمایش امینم (به انگلیسی: The Eminem Show) چه...,68453,68823,Lead,"[{'start': 68452, 'end': 68453}, {'start': 684..."
1,ae1968a0c63bee72118a7f6d8b839a99,1,پس از اینکه در ابتدا برای انتشار در ۴ ژوئن ۲۰۰...,68823,69452,Lead,"[{'start': 68823, 'end': 68982}, {'start': 691..."
2,7ad402eebac3bc8c8faf47f19e053201,2,در این مجموعه امینم نقش مهمی را در تولید ایفا ...,69452,69503,Lead,"[{'start': 69452, 'end': 69503}]"
3,920999aeb590eaa280ae77a1d4630dec,3,همکاران قدیمی او جف باس و دکتر دره تهیه‌کننده ...,69503,69658,Lead,"[{'start': 69503, 'end': 69520}, {'start': 695..."
4,d70dfe57f9d9984d1af1a3dfbbd43bc5,4,در این اثر هنرمندانی به مانند اوبی ترایس، دی۱۲...,69658,70020,Lead,"[{'start': 69658, 'end': 69688}, {'start': 697..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86_%D...,90381,ایران بزرگ,90486,Lead,0
1,file:///wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86,90497,ایران,90567,Lead,0
2,file:///wiki/%D8%B1%D8%AE%D8%AC,90608,رُخَج,90664,Lead,1
3,file:///wiki/%D9%82%D9%86%D8%AF%D9%87%D8%A7%D8%B1,90680,قندهار,90758,Lead,1
4,file:///wiki/%D8%B2%D8%A7%D8%A8%D9%84%D8%B3%D8...,90765,زابُلِستان,90861,Lead,1

Processing language: fr
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/fr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 16/16 [00:00<00:00, 42.99it/s]

Time taken for v1: 32.291869163513184
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 16/16 [00:00<00:00, 38.51it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,54b9f040c8ba7ad8e0dfa6fdaa37d709,0,\n\n\nLe gouffre Jean-Bernard est une cavité s...,45283,54521,Lead,"[{'start': 45282, 'end': 45283}, {'start': 460..."
1,c7825cf868041a46c91a6b64e542784c,1,Le gouffre a été ainsi baptisé par les spéléos...,54638,55048,Historique,"[{'start': 54637, 'end': 54638}, {'start': 546..."
2,c970acaf91137ff64724a613cd77b70f,2,Le gouffre (V4) est trouvé en 1963 et arrêté à...,55048,55157,Historique,"[{'start': 55055, 'end': 55157}]"
3,b881ef8a8fe8ed71418bbb38c833edfc,3,Le collecteur est atteint à −210&nbsp;mètres e...,55157,55211,Historique,"[{'start': 55157, 'end': 55211}]"
4,c36a8f933241cfb8c04f479fb60b23a5,4,"Toujours en été, en 1965 et 1966, l'arrêt est ...",55211,55305,Historique,"[{'start': 55211, 'end': 55305}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Rouergue,56788,Rouergue,56842,Lead,1
1,file:///wiki/Aveyron_(d%C3%A9partement),56876,Aveyron,56960,Lead,1
2,file:///wiki/Saint-Georges-de-Luzen%C3%A7on,57262,Saint-Georges-de-Luzençon,57372,Histoire,4
3,file:///wiki/Millau,57382,Millau,57430,Histoire,4
4,file:///wiki/Bourgeoisie,57531,bourgeoisie,57594,Histoire,6

Processing language: ga
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/ga
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 84.43it/s]

Time taken for v1: 6.607049942016602
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 91.70it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,44f0f855f113dda4a1d8ccffeb946682,0,"\nBa shagart, urscéalaí, drámadóir, aistrithe...",45283,46029,Lead,"[{'start': 45281, 'end': 45283}, {'start': 452..."
1,d52203052ca557f7d0986b4f636ba543,1,\nBhí sé ina Ollamh le Fraincis i Maigh Nuad ...,46029,46463,Lead,"[{'start': 46172, 'end': 46174}, {'start': 461..."
2,20d3e09db4c99afc58c9c564a66eedaf,2,Néal Maidine agus Tine Oíche (1964) agus An Br...,46463,46654,Lead,"[{'start': 46466, 'end': 46494}, {'start': 464..."
3,96ce206d343e396a6663b2f656157003,3,Ba cheannródaí i gcritic na Gaeilge é Breandán...,46654,46719,Lead,"[{'start': 46661, 'end': 46719}]"
4,c5104f865dfd4cf5ba22bb93a8fb0e92,4,"Bhunaigh sé Scoil Chritice Mhá Nuad, a chuir ...",46719,47110,Lead,"[{'start': 46862, 'end': 46926}, {'start': 469..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/R%C3%ADocht_Aontaithe,109148,Ríocht Aontaithe,109251,Féilte,2
1,file:///wiki/1739,109460,1739,109502,Daoine a rugadh ar an lá seo,3
2,file:///wiki/Luis_de_Alburquerque_de_Melo_Pere...,109505,Luis de Alburquerque de Melo Pereira y Cáceres,109678,Daoine a rugadh ar an lá seo,3
3,file:///wiki/1797,109745,1797,109787,Daoine a rugadh ar an lá seo,4
4,file:///wiki/1790,109798,1790,109840,Daoine a rugadh ar an lá seo,4

Processing language: gu
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/gu
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 91.47it/s]

Time taken for v1: 8.502439260482788
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 90.43it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,43c8fc14e5c1b2f11c03ac57d51965ea,0,ઇમામશાહ બાવા દરગાહ (ઉર્દૂ امام شاہ باوا درگاہ)...,41390,41618,Lead,"[{'start': 41390, 'end': 41408}, {'start': 414..."
1,a4875fbf62407c72cc2a65775ed7a730,1,પીર ઇમામ શાહ બાવાએ લગભગ ૬૦૦ વર્ષ પહેલાં સતપંથ ...,41618,41702,Lead,"[{'start': 41618, 'end': 41702}]"
2,c71bb1bed1f577479ceeabfc4e56430d,2,તેમણે ધર્મોની સાર્વત્રિકતા પર સહિષ્ણુતા શીખવી ...,41702,41752,Lead,"[{'start': 41702, 'end': 41752}]"
3,7542a3075d32077d115eb29070c45d2d,3,"૧૯૩૧ સુધી, આ સંકુલ એક ખાનગી સંપત્તિ હતી જે સૈ...",41752,41987,Lead,"[{'start': 41895, 'end': 41987}]"
4,6df19688d00a30f54cd2bbe0233401d5,4,સંકુલમાં એક જૂની મસ્જિદ પણ અસ્તિત્વમાં હતી.,41987,42174,Lead,"[{'start': 42130, 'end': 42174}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%AA%87%E0%AA%A8%E0%AB%8D%E0%AA...,53917,IMDb,54145,બાહ્ય કડીઓ,18
1,file:///wiki/%E0%AA%97%E0%AB%81%E0%AA%9C%E0%AA...,54158,ગુજરાતી વિશ્વકોશમાં,54359,બાહ્ય કડીઓ,18

Processing language: he
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/he
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 61.60it/s]

Time taken for v1: 12.936527729034424
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:03<00:00,  2.58it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b70ab151c7eec68fc1ee5275beb9e6b6,0,\n\n\nלדאק היא טריטוריית איחוד השוכנת בצפון הו...,76859,78183,Lead,"[{'start': 76858, 'end': 76859}, {'start': 772..."
1,dac62cfc014ff66501c339773fe8c87f,1,"עד 2019 הייתה חלק ממדינת ג'אמו וקשמיר, והפחות ...",78183,78417,Lead,"[{'start': 78183, 'end': 78186}, {'start': 782..."
2,c1d808845931cc1c8eeaa87df315135b,2,"לדאק מחולקת לשני מחוזות, קרגיל ולה, ובירתו היא...",78417,78944,Lead,"[{'start': 78417, 'end': 78442}, {'start': 786..."
3,2a3f983bc2f8c3791402e184686566a0,3,ב-31 באוקטובר 2019 קיבלה לדאק מעמד של טריטוריי...,78944,79408,Lead,"[{'start': 78944, 'end': 78946}, {'start': 790..."
4,d671d09778241cc46b291d9af478d4ab,4,"גובה החבל נע בין 3,000 מטר מעל פני הים בעמקים ...",79588,79673,גאוגרפיה,"[{'start': 79587, 'end': 79588}, {'start': 795..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D7%91%D7%95%D7%91_%D7%9E%D7%95%D...,93749,בוב מורלי,93846,Lead,0
1,file:///wiki/%D7%90%D7%A0%D7%92%D7%9C%D7%99%D7%AA,104483,אנגלית,104561,Lead,1
2,file:///wiki/6_%D7%91%D7%A4%D7%91%D7%A8%D7%95%...,104592,6 בפברואר,104684,Lead,1
3,file:///wiki/1945,104685,1945,104727,Lead,1
4,file:///wiki/11_%D7%91%D7%9E%D7%90%D7%99,104730,11 במאי,104801,Lead,1

Processing language: hi
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/hi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 72.33it/s]

Time taken for v1: 16.421783447265625
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 84.81it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,38521dc2fdf86c3205efe818c5ca0c76,0,एकयान ( परम्परागत चीनी&nbsp;: 一乘&nbsp;; फीनयिन...,45039,45986,Lead,"[{'start': 45039, 'end': 45044}, {'start': 450..."
1,e8ad036a22c7c8744e7cb30a7b268a8f,1,यह एक म्हत्वपूर्ण अवधारण आ है जिसका उपयोग उपनि...,45986,46176,Lead,"[{'start': 45986, 'end': 46028}, {'start': 461..."
2,3eaccc283c9f5f561709b7d852b45826,2,"बृहदारण्यक उपनिषद में ""एकयान"" को आध्यात्मिक या...",46416,46723,उपनिषदों में,"[{'start': 46415, 'end': 46416}, {'start': 466..."
3,0c0028957fe9fe4c476e5aed9eaf975f,3,"वेदानां वाक् एकयानम् वाक्यांश का अनुवाद लगभग ""...",46723,46866,उपनिषदों में,"[{'start': 46726, 'end': 46746}, {'start': 467..."
4,0237c4b1e1485968e578f0f51c1e3413,4,"\nसद्धर्मपुण्डरीकत्र, श्रीमालादेवी सिंहनाद सूत...",47159,47942,उपनिषदों में,"[{'start': 47158, 'end': 47159}, {'start': 474..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A4%B0%E0%A5%89%E0%A4%AF%E0%A4...,82797,रॉयटर्स,82904,वार्ता,10
1,file:///wiki/%E0%A4%8F%E0%A4%B8%E0%A5%8B%E0%A4...,83512,एसोसिएटेड प्रेस,83699,वार्ता,10
2,file:///wiki/%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A4...,85110,स्काई न्यूज़,85254,वार्ता,10

Processing language: is
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/is
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 93.77it/s]

Time taken for v1: 5.563772439956665
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 109.91it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c3d342708c4cb4abe4e61332f0f24a48,0,Jakob Þór Einarsson (14.,37222,37302,Lead,"[{'start': 37222, 'end': 37241}, {'start': 372..."
1,fc4859eb95d1bb196799daa2a3aee590,1,janúar 1957) er íslenskur leikari.,37302,37470,Lead,"[{'start': 37302, 'end': 37308}, {'start': 373..."
2,94ac6d6e564f6e9e878ef698603fdb44,2,Jakob Þór Einarsson á Internet Movie Database\...,38803,40151,Tenglar,"[{'start': 38802, 'end': 38803}, {'start': 388..."
3,68618ddd561f224e9abbe3f631c4d000,3,Þú getur hjálpað til með því að bæta við grein...,40151,40360,Tenglar,"[{'start': 40151, 'end': 40183}, {'start': 403..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/R%C3%B3mverskar_t%C3%B6lur,101620,rómverskum tölum,101728,Lead,0
1,file:///wiki/1._jan%C3%BAar,101983,1. janúar,102045,Ísland,2
2,file:///wiki/Metrakerfi%C3%B0,102048,Metrakerfið,102116,Ísland,2
3,file:///wiki/22._jan%C3%BAar,102146,22. janúar,102211,Ísland,4
4,file:///wiki/%C3%96xarfj%C3%B6r%C3%B0ur,102334,Öxarfirðinum,102413,Ísland,5

Processing language: it
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/it
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 13/13 [00:00<00:00, 64.79it/s]

Time taken for v1: 14.438036918640137
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 13/13 [00:00<00:00, 54.43it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,1ab14f597fd04d4d2287cf4bad563301,0,\n\n\n Voce principale: 18 settembre.,8531,9774,Lead,"[{'start': 8530, 'end': 8531}, {'start': 9289,..."
1,dc05f6d2b68f00ed3b416ce98f514680,1,"96 - Domiziano, imperatore romano (n.",14304,14451,I secolo (1),"[{'start': 14303, 'end': 14304}, {'start': 143..."
2,c335481f1c356e6ca30bcd449550a623,2,51)\n,14451,14675,I secolo (1),"[{'start': 14499, 'end': 14501}, {'start': 145..."
3,10ea57aa6433763c9934231c5d0c2b52,3,"644 - Goerico di Metz, vescovo franco\n",14675,15002,VII secolo (1),"[{'start': 14735, 'end': 14738}, {'start': 147..."
4,9061874654386923c0c1f1a27fe47ee5,4,"887 - Pietro I Candiano, doge (n.",15002,15167,IX secolo (1),"[{'start': 15066, 'end': 15069}, {'start': 150..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Aiuto:Voce,9304,voci,9358,Lead,0
1,file:///wiki/Aiuto:Disambiguazione,9440,pagina di disambiguazione,9537,Lead,1
2,file:///wiki/Aiuto:Wikilink,9570,collegamento,9640,Lead,1
3,file:///wiki/Speciale:Prefissi/Tempio_di_Minerva,9748,iniziano con,9860,Lead,2
4,file:///wiki/Speciale:Ricerca/intitle:%22Tempi...,9863,contengono,10005,Lead,2

Processing language: ja
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/ja
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 21/21 [00:00<00:00, 65.90it/s]

Time taken for v1: 22.020331382751465
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 21/21 [00:00<00:00, 57.42it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,a499cdce40e2985fc9f3ad47bcbb91d0,0,\n\nナガスクジラ（長須鯨、長鬚鯨、Balaenoptera physalus）は、哺乳綱...,70994,80858,Lead,"[{'start': 70993, 'end': 70994}, {'start': 802..."
1,aaaa26d876c9aa6b287ff7325a230dfc,1,日本では、シロナガスクジラにも「長須鯨」という呼称が使われる場合が散見されたため、両種が混同...,80996,81325,名称,"[{'start': 80995, 'end': 80996}, {'start': 809..."
2,394d651673d0d2340de0a1467242449f,2,英語では少なくとも5つの呼称が存在し、遊泳の速さから「海のグレイハウンド」という異名がある。,81325,81988,名称,"[{'start': 81378, 'end': 81380}, {'start': 813..."
3,e7571f084275c4eef5d59b1b9fbcd121,3,中国語では、「长须鲸」や「剃刀鲸」など英語や日本語に準拠した呼称になっている。,81988,82095,名称,"[{'start': 82051, 'end': 82054}, {'start': 820..."
4,6f9ae6324d7d86932a2c4f773f6611b8,4,韓国語ではセミクジラと呼称が混同される場合が非常に多かったが、2015年にセミクジラが41年...,82095,83345,名称,"[{'start': 82178, 'end': 82181}, {'start': 821..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E8%97%A4%E5%AD%90%E4%B8%8D%E4%BA...,52497,藤子不二雄,52582,Lead,0
1,file:///wiki/%E8%97%A4%E5%AD%90%E3%83%BBF%E3%8...,52590,藤子・F・不二雄,52700,Lead,0
2,file:///wiki/%E6%97%A5%E6%9C%AC,52704,日本,52756,Lead,0
3,file:///wiki/%E3%82%B5%E3%82%A4%E3%82%A8%E3%83...,52757,SF,52909,Lead,0
4,file:///wiki/%E6%BC%AB%E7%94%BB,52909,漫画,52961,Lead,0

Processing language: jv
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/jv
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 22.14it/s]

Time taken for v1: 89.1963951587677
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 14.31it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,d9948346e3399d4deb5e312a722d3522,0,"\nRichard Buckminster ""Bucky"" Fuller (12 Juli ...",208248,209195,Lead,"[{'start': 208247, 'end': 208248}, {'start': 2..."
1,7707ed0de6e242456df7b6fe238ff6cb,1,Pratélan paten: http://www.bfi.org/patentlist....,209324,209520,Konsep lan yasan,"[{'start': 209323, 'end': 209324}, {'start': 2..."
2,54d134459b42a12a2a3f2a09723469a4,2,Rumah dymaxion (1928)\nMobil dymaxion aerodina...,209520,211465,Konsep lan yasan,"[{'start': 209652, 'end': 209666}, {'start': 2..."
3,a19881eba8d6bdd9f146b4ae471b0d0d,3,Karyané kang diterbitaké antarané:\n,211465,211508,None,"[{'start': 211468, 'end': 211503}, {'start': 2..."
4,5fcf48e9eb1e50cd4a3563cf23fae0dd,4,4-D Timelock (1928)\nNine Chains to the Moon (...,211508,212414,None,"[{'start': 211519, 'end': 211531}, {'start': 2..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Salya,38327,Prabu Salya,38378,Lead,0
1,file:///wiki/Mahabharata,38383,Mahabharata,38446,Lead,0
2,file:///wiki/Endang_Pujawati,38469,Endang Pujawati,38544,Lead,1
3,file:///wiki/Astina,38747,Astina,38815,Lead,2
4,file:///wiki/Banowati,38904,Déwi Banowati,38963,Lead,4

Processing language: kk
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/kk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 78.04it/s]

Time taken for v1: 14.345139265060425
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 71.70it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,0ac4aec7d25d5e9d2fa621d2cea15f04,0,Джек Стайнбергер (ағылш.,11335,11468,Lead,"[{'start': 11335, 'end': 11351}, {'start': 113..."
1,fc1d401f49ffef7b2489247029994213,1,"Jack Steinberger; 25 мамыр 1921, Бад Киссинге...",11468,12839,Lead,"[{'start': 11472, 'end': 11473}, {'start': 114..."
2,3b5083499b0f895a2cee990555fcc486,2,Еврей отбасында дүниеге келген — әкесі Бад Кис...,14090,14378,Өмірбаяны,"[{'start': 14089, 'end': 14090}, {'start': 141..."
3,a0bd4335c5593d11f04f209d864cb0d2,3,1935 жылы Стейнбергер нацистік Германияны таст...,14378,14958,Өмірбаяны,"[{'start': 14378, 'end': 14400}, {'start': 144..."
4,b379da0693fec30262d03813861a4a7d,4,Ол Иллинойс технологиялық институтында екі жыл...,14958,15247,Өмірбаяны,"[{'start': 14958, 'end': 15024}, {'start': 151..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%90%D2%93%D1%8B%D0%BB%D1%88%D1...,11357,ағылш.,11472,Lead,1
1,file:///wiki/25_%D0%BC%D0%B0%D0%BC%D1%8B%D1%80,11521,25 мамыр,11600,Lead,1
2,file:///wiki/1921_%D0%B6%D1%8B%D0%BB,11601,1921,11666,Lead,1
3,file:///wiki/%D0%91%D0%B0%D0%B4-%D0%9A%D0%B8%D...,11668,Бад Киссинген,11797,Lead,1
4,file:///wiki/%D0%93%D0%B5%D1%80%D0%BC%D0%B0%D0...,11799,Германия,11893,Lead,1

Processing language: kn
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/kn
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 98.26it/s]

Time taken for v1: 6.996989011764526
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 87.27it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,5ad4fd44ae40f449d4e0a29472904b67,0,\n\n\nಗೋಧಿ ಪ್ರಪಂಚ ಎಲ್ಲೆಡೆ ಬಳಕೆಯಲ್ಲಿರುವ ಒಂದು ಏಕ...,93236,101665,Lead,"[{'start': 93235, 'end': 93236}, {'start': 101..."
1,3a2c3ce3ab68876fc92b111b8523c61d,1,ಪ್ರಪಂಚ ಅತ್ಯಂತ ಹೆಚ್ಚು ಬೆಳೆಸುವ ಧಾನ್ಯಗಳಲ್ಲಿ ಮೂರನೆ...,101665,101718,Lead,"[{'start': 101665, 'end': 101718}]"
2,786fe316e480c6f190cabd8bff92f718,2,ವಾರ್ಷಿಕ ಉತ್ಪಾದನೆ ಸುಮಾರು ೬೫೧ ಮಿಲಿಯನ್ ಟನ್‍ಗಳು.(೨...,101718,101770,Lead,"[{'start': 101718, 'end': 101770}]"
3,1f5625d82aec1ef61e5ebedd9e2e1505,3,ಜೋಳ ಮತ್ತು ಅಕ್ಕಿ ಗಿಂತ ಹೆಚ್ಚು ಪ್ರೋಟೀನ್‍ನ್ನು ಹೊಂದ...,101770,102141,Lead,"[{'start': 101826, 'end': 101829}, {'start': 1..."
4,e45b55f65c047e669f39e68ab7233978,4,ಗೋಧಿಯು ಅದರ ಬೀಜಕ್ಕಾಗಿ ವ್ಯಾಪಕವಾಗಿ ಬೆಳೆಸಲಾಗುದ ಹುಲ...,102141,102199,Lead,"[{'start': 102148, 'end': 102199}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%B2%B9%E0%B2%BF%E0%B2%82%E0%B2...,40910,ಹಿಂದೂ ಪುರಾಣ,41053,Lead,0
1,file:///wiki/%E0%B2%85%E0%B2%B8%E0%B3%81%E0%B2%B0,41059,ಅಸುರ,41133,Lead,0
2,file:///wiki/%E0%B2%AD%E0%B2%97%E0%B2%A6%E0%B2...,41144,ಭಗದತ್ತ,41240,Lead,1
3,file:///wiki/%E0%B2%B5%E0%B3%87%E0%B2%A6%E0%B2...,41375,ವೇದಗಳು,41491,Lead,2
4,file:///wiki/%E0%B2%AC%E0%B3%83%E0%B2%B9%E0%B2...,41493,ಬೃಹಸ್ಪತಿ,41611,Lead,2

Processing language: ms
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/ms
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 78.62it/s]

Time taken for v1: 29.362386226654053
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 95.94it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b1d0838f7e1f4fc9f6319aefb07ccc3b,0,\nDatuk Haji Pkharuddin bin Haji Ghazali (Jawi...,42861,64851,Lead,"[{'start': 42860, 'end': 42861}, {'start': 428..."
1,fba2ec9520ad5d988b8a5c852a6c7f74,1,"Pkharuddin dilahirkan di Kampung Selising, Pas...",65246,65433,Kehidupan awal dan pendidikan,"[{'start': 65245, 'end': 65246}, {'start': 652..."
2,264de2b993a9ef330670b57e7a1efa20,2,Beliau mempunyai sembilan orang adik beradik d...,65433,65525,Kehidupan awal dan pendidikan,"[{'start': 65433, 'end': 65525}]"
3,06f1e582e70db5eeccb4ffacd9beb3ee,3,Pkharuddin memulakan pelajaran di Sekolah Keba...,65525,65792,Kehidupan awal dan pendidikan,"[{'start': 65532, 'end': 65566}, {'start': 656..."
4,55d0cb719167500776e029adcf591dc0,4,Beliau merupakan seorang ahli pengakap pada za...,65792,66196,Kehidupan awal dan pendidikan,"[{'start': 65792, 'end': 65906}, {'start': 659..."

                         link  startIdx   text  endIdx section  sentid
0  file:///wiki/Templat:Tunas     44494  tunas   44555    Lead       7

Processing language: pt
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/pt
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 84.90it/s]

Time taken for v1: 14.2662832736969
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 95.11it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,95386b4c242f5bb4144a3b8448fce568,0,\n\n\nIpuiuna é um município brasileiro locali...,50576,67561,Lead,"[{'start': 50575, 'end': 50576}, {'start': 505..."
1,1efee6236d51cb07979ecb1fa3f2c527,1,Localizado na Mesorregião do Sul e Sudoeste de...,67561,67649,Lead,"[{'start': 67561, 'end': 67649}]"
2,161806b88982093377a09695ad506517,2,Pode se dizer que a história do município se m...,67794,68118,História,"[{'start': 67793, 'end': 67794}, {'start': 677..."
3,a3ffdb08891d20833c3ca09158a5e8c6,3,Teve início a partir da descoberta do planalto...,68118,68318,História,"[{'start': 68118, 'end': 68318}]"
4,f816615303344cdb3d194c69ca812347,4,"A abertura, iniciada em Ouro Fino, transpôs a ...",68318,68504,História,"[{'start': 68318, 'end': 68504}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Munic%C3%ADpio,67388,município,67450,Lead,0
1,file:///wiki/Minas_Gerais,67493,Minas Gerais,67559,Lead,0
2,file:///wiki/Caldas,67944,Caldas,67992,História,2
3,file:///wiki/Santa_Rita_de_Caldas,68026,Santa Rita de Caldas,68116,História,2
4,file:///wiki/Caldas,70706,Caldas,70754,História,19

Processing language: ru
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/ru
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 12/12 [00:00<00:00, 55.31it/s]

Time taken for v1: 18.90978693962097
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 12/12 [00:00<00:00, 55.40it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b459cfa4e21d45eac24b08ee98036734,0,"У этого топонима есть и другие значения, см. П...",16807,17074,Lead,"[{'start': 16807, 'end': 16852}, {'start': 170..."
1,9fc7114432a074efd9c9f1ec4b5125a0,1,\n\nПреображе́нская площадь&nbsp;— площадь Сан...,17074,27326,Lead,"[{'start': 17080, 'end': 17081}, {'start': 271..."
2,66b8daaee0747ccd270845b3a4518b4e,2,"Расположена на пересечении улицы Рылеева, Коро...",27326,28608,Lead,"[{'start': 27326, 'end': 27353}, {'start': 275..."
3,09a3102b52e0cb84fe354adb5459a8ae,3,Первоначальное название с 1836 года площадь Пр...,30414,30851,Наименование,"[{'start': 30413, 'end': 30414}, {'start': 304..."
4,97f205253481f3ef312e899e9be411cc,4,Одновременно существовали названия с 1840-х го...,30851,31195,Наименование,"[{'start': 30851, 'end': 30908}, {'start': 309..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%90%D1%80%D0%B0%D0%B1%D1%81%D0...,34547,араб.,34668,Lead,1
1,file:///wiki/15_%D0%B8%D1%8E%D0%BB%D1%8F,34792,15 июля,34863,Lead,1
2,file:///wiki/1949,34864,1949,34926,Lead,1
3,file:///wiki/%D0%A8%D0%B8%D0%BD%D0%B4%D0%B0%D0...,34928,Шиндагха,35022,Lead,1
4,file:///wiki/%D0%94%D1%83%D0%B1%D0%B0%D0%B9,35024,Дубай,35094,Lead,1

Processing language: simple
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/simple
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 48.16it/s]

Time taken for v1: 23.320494651794434
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 46.07it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,d8ff307a770c928c5c73042bbd86f70d,0,\n\n\n\n\nwww.gurjari.net\nThe Brahma-Samhita ...,74271,79264,Lead,"[{'start': 74270, 'end': 74271}, {'start': 746..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Roman_numeral,100517,MMXXIII,100600,Lead,0
1,file:///wiki/Common_year,100611,common year,100674,Lead,0
2,file:///wiki/Common_year_starting_on_Sunday,100675,starting on Sunday,100783,Lead,0
3,file:///wiki/Gregorian_calendar,100791,Gregorian calendar,100875,Lead,0
4,file:///wiki/Common_Era,100900,Common Era,100960,Lead,0

Processing language: sk
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/sk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 70.71it/s]

Time taken for v1: 8.13271951675415
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 83.51it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,12a28de35fd8ec20dc8c88a1f54fbc79,0,\n\nTento index bol automaticky vygenerovaný p...,37035,37833,Lead,"[{'start': 37034, 'end': 37035}, {'start': 376..."
1,79941c7cc3096a2c3639142867773fea,1,Obsahuje 193 článkov.,37833,37862,Lead,"[{'start': 37833, 'end': 37842}, {'start': 378..."
2,27d2bf2ed1ad2f0e4486f6bb5819dad7,2,"Aby sa nové články zobrazili v tomto indexe, m...",37862,37968,Lead,"[{'start': 37862, 'end': 37968}]"
3,268f2af31e24b28101aa440caca66abc,3,Nové a upravené kategórie sa zohľadnia pri nas...,37968,38036,Lead,"[{'start': 37968, 'end': 38036}]"
4,8b7eaaf86acc6de473e1ca8ba13c804f,4,\n\nĽadový potok (prítok Popradu)\n,38036,38270,Lead,"[{'start': 38040, 'end': 38041}, {'start': 381..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Profesor_(vedecko-pedagogick%C3%A...,55036,Prof.,55157,Lead,1
1,file:///wiki/Doktor_pr%C3%A1v,55158,JUDr.,55220,Lead,2
2,file:///wiki/Doktor_vied,55240,DrSc.,55297,Lead,3
3,file:///wiki/Doctor_honoris_causa,55299,mult. Dr. h. c.,55400,Lead,4
4,file:///wiki/2._janu%C3%A1r,55404,2. január,55466,Lead,5

Processing language: sw
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/sw
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 106.85it/s]

Time taken for v1: 4.161128759384155
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 128.09it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,8e4417fde47fd3d51b8c833e9ec7f771,0,\nGodefrid Duynen (1502 - 1572) alikuwa padri ...,35690,36534,Lead,"[{'start': 35689, 'end': 35690}, {'start': 356..."
1,43681e69a6efd2d1fbb311f86610a368,1,Anaheshimiwa na Kanisa Katoliki kama mtakatifu...,36534,36752,Lead,"[{'start': 36541, 'end': 36557}, {'start': 366..."
2,66741ab5efb0693e9b3939feab7eda58,2,Kwanza alitangazwa na Papa Klement X kuwa mwen...,36752,37238,Lead,"[{'start': 36752, 'end': 36774}, {'start': 368..."
3,2a7b4199b542fe0fa0449eade84d3de3,3,\nWatakatifu wa Agano la Kale\nOrodha ya Watak...,37243,37916,Lead,"[{'start': 37242, 'end': 37243}, {'start': 373..."

                       link  startIdx         text  endIdx section  sentid
0         file:///wiki/Jina     34247         jina   34289    Lead       0
1  file:///wiki/20_Februari     34312  20 Februari   34375    Lead       0
2         file:///wiki/1952     34376         1952   34418    Lead       0
3         file:///wiki/Lamu     34461         Lamu   34503    Lead       0

Processing language: tr
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/tr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 71.33it/s]

Time taken for v1: 16.340067148208618
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 72.72it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c0cd3df692b00181e66275ddbb43e313,0,\nTovbolat Kurchaloevsky (Tovbolat Hacı; Çeçen...,43073,43467,Lead,"[{'start': 43072, 'end': 43073}, {'start': 430..."
1,0056461c5ec20ede39233a9e2eeb235f,1,Kurchaloy taipa temsilcisi.,43467,43495,Lead,"[{'start': 43467, 'end': 43495}]"
2,0ffe7c0e6bfcf1c1c3d9b9d9620ef1c5,2,\n1830’larda Kurçaloy’da Kurçaloy [ru] aşireti...,43610,44640,Biyografi,"[{'start': 43609, 'end': 43610}, {'start': 444..."
3,ad22fc94e7e36ef3fa94153a4bf3b7c0,3,"Babası Sülim, İmam Şamil’in yanında Kafkas Sav...",44640,44749,Biyografi,"[{'start': 44640, 'end': 44749}]"
4,6ec687cd0e9cd6aec5edace267c3fb05,4,Rus kuvvetleriyle yapılan savaşta ölmüştür.,44749,44793,Biyografi,"[{'start': 44749, 'end': 44793}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%C4%B0srail,50514,İsrail,50567,7 Ekim,3
1,file:///wiki/Hamas,50592,Hamas,50637,7 Ekim,3
2,file:///wiki/Muhammed_Deif,50813,Muhammed Deif,50902,7 Ekim,4
3,file:///wiki/Re%27im_m%C3%BCzik_festivali_katl...,51383,Re'im,51490,7 Ekim,6
4,file:///wiki/%C4%B0srail_Savunma_Kuvvetleri,51901,İsrail Savunma Kuvvetleri,52011,7 Ekim,8

Processing language: ur
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/ur
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 17.03it/s]

Time taken for v1: 33.77743411064148
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 23.77it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,bea863d3f024b7b66cc013733052dcd1,0,\nمعاذ بن جبل انصاری خزرجی (22ق.ھ / 18ھ) ،حضور...,68097,68839,Lead,"[{'start': 68096, 'end': 68097}, {'start': 681..."
1,5d744758c0cb8d28302103c31c1b9f11,1,سعد بن علی کے دو بیٹے تھے سلمہ اور ادی، سلمہ ک...,68839,69661,Lead,"[{'start': 68839, 'end': 68915}, {'start': 690..."
2,b109aaddba761b471ad5e7a5212ffab1,2,امام سمعانی نے کتاب الانساب میں حسین بن محمد ب...,69661,69945,Lead,"[{'start': 69661, 'end': 69709}, {'start': 698..."
3,e50c940daa47d4e29ecb546e56f9ad80,3,بنوادی کے مکانات ان کے بنو اعمام (بنو سلمہ) کے...,69945,70189,Lead,"[{'start': 69945, 'end': 70010}, {'start': 701..."
4,5bbc8b8ba28cefc46a3aeb4d712926c4,4,معاذ نام ، ابو عبدالرحمن کنیت ،امام الفقہا ءکن...,70496,70839,Lead,"[{'start': 70495, 'end': 70496}, {'start': 704..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%B5%D8%A7%D8%B1%D9%81:Tahir697,82731,صارف:Tahir697,82820,Lead,0
1,file:///wiki/%D8%B9%D8%B1%D8%A8%DB%8C_%D8%B2%D...,93218,عربی,93310,Lead,0
2,file:///wiki/%D8%BA%D8%B2%D9%88%DB%81_%D9%85%D...,95132,موتہ کی جنگ,95231,Lead,7
3,file:///wiki/%D9%81%D8%AA%D8%AD_%D9%85%DA%A9%D...,95325,مکہ کی مسلمانوں کی فتح,95421,Lead,8
4,file:///wiki/%D8%BA%D8%B2%D9%88%DB%81_%D8%AD%D...,95436,حنین کی جنگ,95535,Lead,8

Processing language: uz
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/uz
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 75.32it/s]

Time taken for v1: 10.008826971054077
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 83.89it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,38c02cf8fba873ab2026274dfe7ab4a5,0,\nFazliddin Jaloliddinovich Hojimuhammedov (oʻ...,40005,40293,Lead,"[{'start': 40004, 'end': 40005}, {'start': 400..."
1,ffd8006d32718ed9b4b2d1cb0696f7ae,1,\n\n\n2005-yilda Toshkent shahridagi 193-makta...,40293,40551,Lead,"[{'start': 40297, 'end': 40298}, {'start': 403..."
2,9a1073a107b484aa56dca23c144c1ad9,2,2009-yilda Toshkent davlat iqtisodiyot univers...,40551,40775,Biografiyasi,"[{'start': 40558, 'end': 40569}, {'start': 406..."
3,c354e76d36618c87f86b22de96d2602f,3,2010-yilda harbiy xizmatni oʻtagan.,40775,40811,Biografiyasi,"[{'start': 40775, 'end': 40811}]"
4,519fb9ab059adffff0ebf941c80a4da6,4,2009-yildan 2013-yilgacha&nbsp;– xususiy sekto...,40811,40880,Biografiyasi,"[{'start': 40818, 'end': 40880}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/O%CA%BBzbek_tili,40057,oʻzbekcha,40123,Lead,0
1,file:///wiki/Toshkent_shahri,40428,Toshkent shahridagi,40527,Biografiyasi,1
2,file:///wiki/Toshkent_davlat_iqtisodiyot_unive...,40569,Toshkent davlat iqtisodiyot universitetining,40723,Biografiyasi,2
3,file:///wiki/Uchtepa_tumani,40906,Uchtepa tumanidagi,40982,Biografiyasi,5
4,file:///wiki/O%CA%BBzbekiston_futbol_assotsiat...,41118,Oʻzbekiston futbol assotsiatsiyasi,41255,Biografiyasi,7

Processing language: vi
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/vi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 51.54it/s]

Time taken for v1: 37.288190603256226
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 59.31it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,88146ae3da8d7d16c437b65401c54e6e,0,\nVictoria Adelaide của Liên hiệp Anh và Irela...,90110,91624,Lead,"[{'start': 90109, 'end': 90110}, {'start': 901..."
1,fa39fdc0d49218e40a18e1eed2083321,1,Bà là con gái trưởng của Nữ vương Victoria với...,91624,92060,Lead,"[{'start': 91624, 'end': 91649}, {'start': 917..."
2,b2ab1741515b408e895ec043d3d7801b,2,Từ nhỏ bà được cha mẹ nuôi dưỡng trong môi trư...,92060,92439,Lead,"[{'start': 92067, 'end': 92304}, {'start': 923..."
3,917ebf6e344173edcca9fb98d14ba247,3,Bị phê bình về quan điểm tự do và nguồn gốc xu...,92439,92670,Lead,"[{'start': 92439, 'end': 92518}, {'start': 926..."
4,2c2b08b208ea77910699aa5df68639ef,4,Sự đối lập ngày càng dữ dội từ năm 1862 khi Ot...,92670,92956,Lead,"[{'start': 92670, 'end': 92705}, {'start': 927..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/X%C3%A3_(Vi%E1%BB%87t_Nam),42965,xã,43036,Lead,0
1,file:///wiki/M%C6%B0%E1%BB%9Dng_Ch%C3%A0,43049,Mường Chà,43124,Lead,0
2,file:///wiki/%C4%90i%E1%BB%87n_Bi%C3%AAn,43131,Điện Biên,43206,Lead,0
3,file:///wiki/Vi%E1%BB%87t_Nam,43208,Việt Nam,43270,Lead,0
4,file:///wiki/H%27M%C3%B4ng,43739,Dân tộc (cộng đồng),43807,Lead,5

Processing language: zh
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages/zh
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 70.19it/s]

Time taken for v1: 28.62204122543335
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 10/10 [00:00<00:00, 74.76it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,a87b7f9939b52e11c45b15832a61fbe3,0,"\n未入流是明、清兩代對於低於從九品的官吏的稱呼，在唐代則被稱為""流外""。",45736,45842,Lead,"[{'start': 45735, 'end': 45736}, {'start': 457..."
1,4f2ce8202fa1e68690e4e85d6d10612d,1,\n\n\n清代:\n文官\n,45842,46104,Lead,"[{'start': 45846, 'end': 45847}, {'start': 458..."
2,1573eef75b4096959a9ecb691587fbd3,2,武官\n,56576,56587,文武官職,"[{'start': 56575, 'end': 56576}, {'start': 565..."
3,9a8d45681362a72287918ad2de8cede3,3,《明史．卷七二．職官志一》：「凡文官之品九，品有正從，為級一十八。,58254,58290,文獻提及,"[{'start': 58253, 'end': 58254}, {'start': 582..."
4,decd6e782d8676fe47b96b8b6eb645cf,4,不及九品曰未入流。,58290,58299,文獻提及,"[{'start': 58290, 'end': 58299}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E7%83%8F%E5%85%8B%E8%98%AD%E8%AA%9E,46591,烏克蘭語,46685,Lead,0
1,file:///wiki/%E7%83%8F%E5%85%8B%E8%98%AD,46719,烏克蘭,46802,Lead,0
2,file:///wiki/%E5%88%87%E7%88%BE%E5%B0%BC%E6%88...,46812,切爾尼戈夫州,46908,Lead,0
3,file:///wiki/%E4%BC%8A%E5%A5%87%E5%B0%BC%E4%BA...,46910,伊奇尼亞區,46995,Lead,0
4,file:///wiki/%E4%BA%92%E8%81%94%E7%BD%91%E6%A1...,47502,互联网档案馆,47598,參考資料,1

**Preprocessing**

It included all preprocessing parts but the merging

In [29]:
for lang in langs:
    for side_context_size in side_context_sizes:
        print(f"Processing language: {lang} with side context size {side_context_size}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
        output_dir = f"{contexts_splitted_data_dir}/{lang}/context_size_{side_context_size}"
        
        subprocess.run([
            "python", f"{scripts_dir}/preprocessing.py",
            "--revisions_path", save_path,
            "--parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v2",
            "--first_versions_specific_parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v1",
            "--n_processes", str(processes),
            "--output_dir", output_dir,
            "--side_contexts_size", str(side_context_size),
            "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
            "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet"
        ])

        #preprocessed_data_path = os.path.join(output_dir, f'test_data.parquet')

        #preprocessed_data = pd.read_parquet(preprocessed_data_path)
        #display(preprocessed_data.head(5))

Processing language: af with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 27.10it/s]
100%|██████████| 42/42 [00:00<00:00, 8427.13it/s]

The length of the output is 42
Processing language: ar with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:08<00:00,  1.17it/s]

The length of the output is 16

100%|██████████| 16/16 [00:00<00:00, 4130.54it/s]

Processing language: cs with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:02<00:00,  4.37it/s]

The length of the output is 45

100%|██████████| 45/45 [00:00<00:00, 11539.02it/s]

Processing language: cy with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 108.94it/s]

The length of the output is 18

100%|██████████| 18/18 [00:00<00:00, 8290.96it/s]

Processing language: de with side context size 5
Running on 48 processes

100%|██████████| 29/29 [00:17<00:00,  1.68it/s]

The length of the output is 69

100%|██████████| 69/69 [00:00<00:00, 3979.52it/s]

Processing language: en with side context size 5
Running on 48 processes

100%|██████████| 116/116 [01:40<00:00,  1.16it/s]

The length of the output is 432

100%|██████████| 432/432 [00:00<00:00, 20423.12it/s]

Processing language: es with side context size 5
Running on 48 processes

100%|██████████| 17/17 [00:12<00:00,  1.36it/s]

The length of the output is 45

100%|██████████| 45/45 [00:00<00:00, 5337.02it/s]

Processing language: fa with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:14<00:00,  1.46s/it]

The length of the output is 40

100%|██████████| 40/40 [00:00<00:00, 8309.67it/s]

Processing language: fr with side context size 5
Running on 48 processes

100%|██████████| 16/16 [00:11<00:00,  1.37it/s]

The length of the output is 32

100%|██████████| 32/32 [00:00<00:00, 11122.71it/s]

Processing language: ga with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 108.96it/s]
100%|██████████| 22/22 [00:00<00:00, 12787.51it/s]

The length of the output is 22
Processing language: gu with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 97.39it/s]
100%|██████████| 43/43 [00:00<00:00, 20833.44it/s]

The length of the output is 43
Processing language: he with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:01<00:00,  7.09it/s]

The length of the output is 20

100%|██████████| 20/20 [00:00<00:00, 7911.54it/s]

Processing language: hi with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 32.68it/s]

The length of the output is 31

100%|██████████| 31/31 [00:00<00:00, 8257.03it/s]

Processing language: is with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 72.90it/s]

The length of the output is 91
Processing language: it with side context size 5

100%|██████████| 91/91 [00:00<00:00, 23774.86it/s]

Running on 48 processes

100%|██████████| 13/13 [00:06<00:00,  1.95it/s]

The length of the output is 24

100%|██████████| 24/24 [00:00<00:00, 18854.34it/s]

Processing language: ja with side context size 5
Running on 48 processes

100%|██████████| 21/21 [00:06<00:00,  3.26it/s]

The length of the output is 106

100%|██████████| 106/106 [00:00<00:00, 31243.59it/s]

Processing language: jv with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 20.69it/s]
100%|██████████| 30/30 [00:00<00:00, 10189.42it/s]

The length of the output is 30
Processing language: kk with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 56.75it/s]

The length of the output is 10
Processing language: kn with side context size 5

100%|██████████| 10/10 [00:00<00:00, 11637.91it/s]

Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 76.09it/s]
100%|██████████| 30/30 [00:00<00:00, 10580.10it/s]

The length of the output is 30
Processing language: ms with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 44.62it/s]
100%|██████████| 16/16 [00:00<00:00, 7035.21it/s]

The length of the output is 16
Processing language: pt with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:04<00:00,  2.17it/s]

The length of the output is 43

100%|██████████| 43/43 [00:00<00:00, 12232.44it/s]

Processing language: ru with side context size 5
Running on 48 processes

100%|██████████| 12/12 [00:22<00:00,  1.90s/it]

The length of the output is 31

100%|██████████| 31/31 [00:00<00:00, 5986.62it/s]

Processing language: simple with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 22.81it/s]

The length of the output is 23
Processing language: sk with side context size 5

100%|██████████| 23/23 [00:00<00:00, 7434.99it/s]

Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 44.13it/s]

The length of the output is 44
Processing language: sw with side context size 5

100%|██████████| 44/44 [00:00<00:00, 3936.97it/s]

Running on 48 processes

100%|██████████| 10/10 [00:00<00:00, 155.90it/s]
100%|██████████| 31/31 [00:00<00:00, 6922.77it/s]

The length of the output is 31
Processing language: tr with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:01<00:00,  5.15it/s]

The length of the output is 23
Processing language: ur with side context size 5

100%|██████████| 23/23 [00:00<00:00, 6923.78it/s]

Running on 48 processes

100%|██████████| 10/10 [00:01<00:00,  6.60it/s]

The length of the output is 13

100%|██████████| 13/13 [00:00<00:00, 3190.89it/s]

Processing language: uz with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:01<00:00,  6.03it/s]

The length of the output is 51

100%|██████████| 51/51 [00:00<00:00, 2221.21it/s]

Processing language: vi with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:01<00:00,  5.74it/s]

The length of the output is 48

100%|██████████| 48/48 [00:00<00:00, 8876.83it/s]

Processing language: zh with side context size 5
Running on 48 processes

100%|██████████| 10/10 [00:08<00:00,  1.15it/s]

The length of the output is 20

100%|██████████| 20/20 [00:00<00:00, 10042.63it/s]

**Merging**

In [30]:
test_data_dir = contexts_splitted_data_dir
output_dir = ready_to_score_data_dir

subprocess.run([
    "python", f"{scripts_dir}/merge_data.py",
    "--test_data_dir", test_data_dir,
    "--raw_data_dir", simple_render_raw_data_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--output_dir", output_dir,
    "--ignore_warnings"
])

first_lang = langs[0]
first_context_size = str(side_context_sizes[0])
scored_files_example = os.listdir(output_dir)
scored_files_example = list(filter(lambda x: (first_lang in x and first_context_size in x), scored_files_example))
final_input_data_path = os.path.join(output_dir, scored_files_example[0])

final_input_data_df = pd.read_parquet(final_input_data_path)
display(final_input_data_df.head(5))

Saving mention maps:
Processing language af (1/30)
Finished processing language af
Processing language ar (2/30)
Finished processing language ar
Processing language cs (3/30)
Finished processing language cs
Processing language cy (4/30)
Finished processing language cy
Processing language de (5/30)
Finished processing language de
Processing language en (6/30)
Finished processing language en
Processing language es (7/30)
Finished processing language es
Processing language fa (8/30)
Finished processing language fa
Processing language fr (9/30)
Finished processing language fr
Processing language ga (10/30)
Finished processing language ga
Processing language gu (11/30)
Finished processing language gu
Processing language he (12/30)
Finished processing language he
Processing language hi (13/30)
Finished processing language hi
Processing language is (14/30)
Finished processing language is
Processing language it (15/30)
Finished processing language it
Processing language ja (16/30)
Finished processing language ja
Processing language jv (17/30)
Finished processing language jv
Processing language kk (18/30)
Finished processing language kk
Processing language kn (19/30)
Finished processing language kn
Processing language ms (20/30)
Finished processing language ms
Processing language pt (21/30)
Finished processing language pt
Processing language ru (22/30)
Finished processing language ru
Processing language simple (23/30)
Finished processing language simple
Processing language sk (24/30)
Finished processing language sk
Processing language sw (25/30)
Finished processing language sw
Processing language tr (26/30)
Finished processing language tr
Processing language ur (27/30)
Finished processing language ur
Processing language uz (28/30)
Finished processing language uz
Processing language vi (29/30)
Finished processing language vi
Processing language zh (30/30)
Finished processing language zh
Done saving mention maps:
Processing language af (1/30)
Loaded pages
Loaded redirects

100%|██████████| 110890/110890 [00:00<00:00, 728902.88it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 42 links for language af
Removed 0 links because of empty contexts
Removed 13 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 29 links for language af
Finished processing language af
Processing language ar (2/30)
Loaded pages
Loaded redirects

100%|██████████| 1209639/1209639 [00:01<00:00, 855963.38it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 16 links for language ar
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 11 links for language ar
Finished processing language ar
Processing language cs (3/30)
Loaded pages
Loaded redirects

100%|██████████| 529676/529676 [00:00<00:00, 925307.71it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 45 links for language cs
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 26 links because of missing section
After cleaning, there are 14 links for language cs
Finished processing language cs
Processing language cy (4/30)
Loaded pages
Loaded redirects

100%|██████████| 269727/269727 [00:00<00:00, 808140.17it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 18 links for language cy
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 16 links for language cy
Finished processing language cy
Processing language de (5/30)
Loaded pages
Loaded redirects

100%|██████████| 2826417/2826417 [00:03<00:00, 830037.27it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 69 links for language de
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 13 links because of missing section
After cleaning, there are 44 links for language de
Finished processing language de
Processing language en (6/30)
Loaded pages
Loaded redirects

100%|██████████| 6708565/6708565 [00:09<00:00, 711450.51it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 432 links for language en
Removed 0 links because of empty contexts
Removed 50 links because target title is not in source titles
Removed 175 links because of missing section
After cleaning, there are 207 links for language en
Finished processing language en
Processing language es (7/30)
Loaded pages
Loaded redirects

100%|██████████| 1829995/1829995 [00:02<00:00, 802389.85it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 45 links for language es
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 4 links because of missing section
After cleaning, there are 35 links for language es
Finished processing language es
Processing language fa (8/30)
Loaded pages
Loaded redirects

100%|██████████| 967157/967157 [00:01<00:00, 801689.34it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 40 links for language fa
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 6 links because of missing section
After cleaning, there are 19 links for language fa
Finished processing language fa
Processing language fr (9/30)
Loaded pages
Loaded redirects

100%|██████████| 2515482/2515482 [00:03<00:00, 820441.36it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 32 links for language fr
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 24 links for language fr
Finished processing language fr
Processing language ga (10/30)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 22 links for language ga
Removed 0 links because of empty contexts

100%|██████████| 55867/55867 [00:00<00:00, 855375.16it/s]

Removed 9 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 10 links for language ga
Finished processing language ga
Processing language gu (11/30)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 43 links for language gu
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 35 links for language gu

100%|██████████| 30230/30230 [00:00<00:00, 743440.69it/s]

Finished processing language gu
Processing language he (12/30)
Loaded pages
Loaded redirects

100%|██████████| 339595/339595 [00:00<00:00, 905537.73it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 20 links for language he
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 17 links for language he
Finished processing language he
Processing language hi (13/30)
Loaded pages
Loaded redirects

100%|██████████| 156710/156710 [00:00<00:00, 721321.05it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 31 links for language hi
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 28 links for language hi
Finished processing language hi
Processing language is (14/30)
Loaded pages
Loaded redirects

100%|██████████| 56361/56361 [00:00<00:00, 674010.90it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 91 links for language is
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 46 links because of missing section
After cleaning, there are 40 links for language is
Finished processing language is
Processing language it (15/30)
Loaded pages
Loaded redirects

100%|██████████| 1775929/1775929 [00:02<00:00, 880956.22it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 24 links for language it
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 18 links for language it
Finished processing language it
Processing language ja (16/30)
Loaded pages
Loaded redirects

100%|██████████| 1369610/1369610 [00:01<00:00, 882345.23it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 106 links for language ja
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 97 links for language ja
Finished processing language ja
Processing language jv (17/30)
Loaded pages
Loaded redirects

100%|██████████| 70540/70540 [00:00<00:00, 874017.26it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 30 links for language jv
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 2 links because of missing section
After cleaning, there are 21 links for language jv
Finished processing language jv
Processing language kk (18/30)
Loaded pages
Loaded redirects

100%|██████████| 233608/233608 [00:00<00:00, 801347.63it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 10 links for language kk
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 8 links for language kk
Finished processing language kk
Processing language kn (19/30)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 30 links for language kn
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 11 links because of missing section
After cleaning, there are 18 links for language kn

100%|██████████| 27889/27889 [00:00<00:00, 593287.54it/s]

Finished processing language kn
Processing language ms (20/30)
Loaded pages
Loaded redirects

100%|██████████| 362531/362531 [00:00<00:00, 924250.13it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 16 links for language ms
Removed 0 links because of empty contexts
Removed 0 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 16 links for language ms
Finished processing language ms
Processing language pt (21/30)
Loaded pages
Loaded redirects

100%|██████████| 1103653/1103653 [00:01<00:00, 913745.23it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 43 links for language pt
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 15 links because of missing section
After cleaning, there are 13 links for language pt
Finished processing language pt
Processing language ru (22/30)
Loaded pages
Loaded redirects

100%|██████████| 1920674/1920674 [00:02<00:00, 733845.87it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 31 links for language ru
Removed 0 links because of empty contexts
Removed 23 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 8 links for language ru
Finished processing language ru
Processing language simple (23/30)
Loaded pages
Loaded redirects

100%|██████████| 238680/238680 [00:00<00:00, 864415.15it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 23 links for language simple
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 20 links for language simple
Finished processing language simple
Processing language sk (24/30)
Loaded pages
Loaded redirects

100%|██████████| 242165/242165 [00:00<00:00, 838107.02it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 44 links for language sk
Removed 0 links because of empty contexts
Removed 9 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 28 links for language sk
Finished processing language sk
Processing language sw (25/30)
Loaded pages
Loaded redirects

100%|██████████| 74218/74218 [00:00<00:00, 685827.21it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 31 links for language sw
Removed 0 links because of empty contexts
Removed 0 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 31 links for language sw
Finished processing language sw
Processing language tr (26/30)
Loaded pages
Loaded redirects

100%|██████████| 528537/528537 [00:00<00:00, 945627.06it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 23 links for language tr
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 4 links because of missing section
After cleaning, there are 13 links for language tr
Finished processing language tr
Processing language ur (27/30)
Loaded pages
Loaded redirects

100%|██████████| 188553/188553 [00:00<00:00, 892318.61it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 13 links for language ur
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 4 links for language ur
Finished processing language ur
Processing language uz (28/30)
Loaded pages
Loaded redirects

100%|██████████| 229168/229168 [00:00<00:00, 783205.14it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 51 links for language uz
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 19 links because of missing section
After cleaning, there are 30 links for language uz
Finished processing language uz
Processing language vi (29/30)
Error reading file /dlabdata1/tsoares/wikidumps/viwiki-NS0-20231001/processed_data/good_pages/good_pages_55.parquet
Loaded pages
Loaded redirects

100%|██████████| 1273459/1273459 [00:01<00:00, 866354.41it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 48 links for language vi
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 16 links because of missing section
After cleaning, there are 26 links for language vi
Finished processing language vi
Processing language zh (30/30)
Loaded pages
Loaded redirects

100%|██████████| 1344667/1344667 [00:01<00:00, 827062.92it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 20 links for language zh
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 19 links for language zh
Finished processing language zh

,source_title,source_ID,target_title,context,insert_indices,moved_insertion_marker,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts,target_lead
0,1942,486,9_Julie,None,[62],None,"9 Julie - Richard Roundtree, Amerikaanse akteu...",9 Julie,Geboortes,None,Die jaar 1942 was 'n gewone jaar wat volgens d...,2622176,2624839,None,missing_sentence,[{'context': 'Die jaar 1942 was 'n gewone jaar...,9 Julie is die 190ste dag van die jaar in die ...
1,Marius_Petipa,407068,Pjotr_Tsjaikofski,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Tsjaikofski,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,"Pjotr Iljitsj Tsjaikofski, Wotkinsk, 7 Mei 184..."
2,Marius_Petipa,407068,Groothertog_Aleksander_Michailowitsj_van_Rusland,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Groothertog Aleksander Michailowitsj van Rusland,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,Hierdie naam is volgens die Oos-Slawiese gebru...
3,Marius_Petipa,407068,Nikolaas_II_van_Rusland,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Keiser Nikolaas II,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,Nikolaas II Aleksandrowitsj was die laaste kei...
4,Marius_Petipa,407068,Giuseppe_Verdi,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Verdi,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,Giuseppe Fortunino Francesco Verdi was 'n Ital...

**Scoring the contexts**

In [31]:
data_dir = ready_to_score_data_dir
output_dir = scored_data_dir

for lang in langs:
    for side_context_size in side_context_sizes:
        print(f"Processing language: {lang} with side context size {side_context_size}")

        subprocess.run([
            "python", f"{scripts_dir}/get_llm_scores.py",
            "--data_dir", data_dir,
            "--output_dir", output_dir,
            "--lang", lang,
            "--side_contexts_size", str(side_context_size),
            "--model_dir", "/dlabdata1/tsoares/models",
            "--model_prefix", "roberta_full",
            "--use_section_title",
            "--batch_size", "128",
            "--use_mentions",
            "--use_cuda",
            "--multilingual",
            "--multilingual_name", "multilingual-all"
        ])

scored_files_example = os.listdir(output_dir)[0]
scored_data = pd.read_parquet(f"{output_dir}/{scored_files_example}")

exemple = scored_data['all_contexts'][0][0]

for key in exemple.keys():
    print(f"{key}:\n{exemple[key]}\n")

Processing language: af with side context size 5
Processing context size 5

100%|██████████| 40/40 [03:06<00:00,  4.65s/it]

Processing language: ar with side context size 5
Processing context size 5

100%|██████████| 15/15 [01:05<00:00,  4.40s/it]

Processing language: cs with side context size 5
Processing context size 5

100%|██████████| 4/4 [00:16<00:00,  4.18s/it]

Processing language: cy with side context size 5
Processing context size 5

100%|██████████| 3/3 [00:09<00:00,  3.22s/it]

Processing language: de with side context size 5
Processing context size 5

100%|██████████| 66/66 [04:58<00:00,  4.52s/it]

Processing language: en with side context size 5
Processing context size 5

100%|██████████| 177/177 [13:10<00:00,  4.47s/it]

Processing language: es with side context size 5
Processing context size 5

100%|██████████| 38/38 [02:42<00:00,  4.29s/it]

Processing language: fa with side context size 5
Processing context size 5

100%|██████████| 6/6 [00:26<00:00,  4.43s/it]

Processing language: fr with side context size 5
Processing context size 5

100%|██████████| 21/21 [01:30<00:00,  4.30s/it]

Processing language: ga with side context size 5
Processing context size 5

100%|██████████| 2/2 [00:06<00:00,  3.29s/it]

Processing language: gu with side context size 5
Processing context size 5

100%|██████████| 6/6 [00:26<00:00,  4.41s/it]

Processing language: he with side context size 5
Processing context size 5

100%|██████████| 13/13 [00:56<00:00,  4.34s/it]

Processing language: hi with side context size 5
Processing context size 5

100%|██████████| 13/13 [01:00<00:00,  4.63s/it]

Processing language: is with side context size 5
Processing context size 5

100%|██████████| 12/12 [00:53<00:00,  4.45s/it]

Processing language: it with side context size 5
Processing context size 5

100%|██████████| 6/6 [00:25<00:00,  4.21s/it]

Processing language: ja with side context size 5
Processing context size 5

100%|██████████| 89/89 [06:54<00:00,  4.66s/it]

Processing language: jv with side context size 5
Processing context size 5

100%|██████████| 4/4 [00:16<00:00,  4.16s/it]

Processing language: kk with side context size 5
Processing context size 5

100%|██████████| 3/3 [00:11<00:00,  3.92s/it]

Processing language: kn with side context size 5
Processing context size 5

100%|██████████| 7/7 [00:30<00:00,  4.29s/it]

Processing language: ms with side context size 5
Processing context size 5

100%|██████████| 3/3 [00:13<00:00,  4.46s/it]

Processing language: pt with side context size 5
Processing context size 5

100%|██████████| 2/2 [00:09<00:00,  4.55s/it]

Processing language: ru with side context size 5
Processing context size 5

100%|██████████| 4/4 [00:17<00:00,  4.38s/it]

Processing language: simple with side context size 5
Processing context size 5

100%|██████████| 11/11 [00:45<00:00,  4.17s/it]

Processing language: sk with side context size 5
Processing context size 5

100%|██████████| 17/17 [01:15<00:00,  4.43s/it]

Processing language: sw with side context size 5
Processing context size 5

100%|██████████| 2/2 [00:06<00:00,  3.08s/it]

Processing language: tr with side context size 5
Processing context size 5

100%|██████████| 8/8 [00:36<00:00,  4.52s/it]

Processing language: ur with side context size 5
Processing context size 5

100%|██████████| 25/25 [01:54<00:00,  4.59s/it]

Processing language: uz with side context size 5
Processing context size 5

100%|██████████| 22/22 [01:35<00:00,  4.36s/it]

Processing language: vi with side context size 5
Processing context size 5

100%|██████████| 24/24 [01:43<00:00,  4.33s/it]

Processing language: zh with side context size 5
Processing context size 5

100%|██████████| 9/9 [00:39<00:00,  4.43s/it]

context:
Ma Thì Hồ là một xã thuộc huyện Mường Chà, tỉnh Điện Biên, Việt Nam. Xã Ma Thì Hồ có diện tích 139,9&nbsp;km², dân số năm 2006 là 3.087 người, mật độ dân số đạt 22 người/km². Người dân xã Ma Thì Hồ vẫn còn khá là nghèo. Do trình độ hiểu biết và dân trí còn thấp. Chủ yếu dựa vào nghề trồng trọt. Chiếm đa số dân hiện nay trong xã Ma Thì Hồ là người  Dân tộc (cộng đồng) Mông.

middle_sentence:
{'clean_sentence': 'Ma Thì Hồ là một xã thuộc huyện Mường Chà, tỉnh Điện Biên, Việt Nam.', 'clean_sentence2': None, 'endIdx1': 43272, 'endIdx2': 43708.0, 'ids1': array([0]), 'ids2': array([0]), 'index': 0, 'locList1': array([{'end': 42938, 'start': 42937}, {'end': 42953, 'start': 42944},
       {'end': 42965, 'start': 42957}, {'end': 43032, 'start': 43030},
       {'end': 43049, 'start': 43036}, {'end': 43120, 'start': 43111},
       {'end': 43131, 'start': 43124}, {'end': 43202, 'start': 43193},
       {'end': 43208, 'start': 43206}, {'end': 43266, 'start': 43258},
       {'end': 43272, 'start': 43270}], dtype=object), 'locList2': array([{'end': 43374, 'start': 43373}, {'end': 43389, 'start': 43380},
       {'end': 43401, 'start': 43393}, {'end': 43468, 'start': 43466},
       {'end': 43485, 'start': 43472}, {'end': 43556, 'start': 43547},
       {'end': 43567, 'start': 43560}, {'end': 43638, 'start': 43629},
       {'end': 43644, 'start': 43642}, {'end': 43702, 'start': 43694},
       {'end': 43708, 'start': 43706}], dtype=object), 'modifications': None, 'moved_to': None, 'section1': 'Lead', 'section2': 'Lead', 'startIdx1': 42938, 'startIdx2': 43374.0, 'status': 'neutral'}

score:
13.85611343383789

section:
Lead

**Colouring the pages**

In [32]:
sorted_link_output_dir = os.path.join(server_out_dir, "colored_pages")
soft_links_dir = os.path.join(server_out_dir, "soft_links")

# Run the coloring script
subprocess.run([
    "python", f"{scripts_dir}/color_pages.py",
    "--scored_data_dir", scored_data_dir,
    "--html_dir", crawling_output_dir,
    "--sorted_links_output_dir", sorted_link_output_dir,
    #"--soft_links_dir", soft_links_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--extra_crawled_files_dir", crawling_output_dir,
    "--full_model_name", "roberta_full_multilingual-all"
])

Processing language af with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 29/29 [00:00<00:00, 4897.32it/s]
100%|██████████| 29/29 [00:00<00:00, 902.23it/s]
  0%|          | 0/29 [00:00<?, ?it/s]

Style: highlight

100%|██████████| 29/29 [00:02<00:00, 11.14it/s]
100%|██████████| 11/11 [00:00<00:00, 7628.53it/s]
100%|██████████| 11/11 [00:00<00:00, 973.18it/s]
  0%|          | 0/11 [00:00<?, ?it/s]

Processing language ar with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 11/11 [00:01<00:00,  9.20it/s]
100%|██████████| 14/14 [00:00<00:00, 13409.51it/s]
100%|██████████| 14/14 [00:00<00:00, 1231.76it/s]
  0%|          | 0/14 [00:00<?, ?it/s]

Processing language cs with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 14/14 [00:01<00:00, 13.89it/s]
100%|██████████| 16/16 [00:00<00:00, 10871.35it/s]
100%|██████████| 16/16 [00:00<00:00, 1239.34it/s]
  0%|          | 0/16 [00:00<?, ?it/s]

Processing language cy with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 16/16 [00:01<00:00, 14.85it/s]

100%|██████████| 16/16 [00:01<00:00, 14.45it/s]

Processing language de with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 44/44 [00:00<00:00, 9724.38it/s]
100%|██████████| 44/44 [00:00<00:00, 960.43it/s]
100%|██████████| 44/44 [00:04<00:00,  9.77it/s]

Processing language en with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 207/207 [00:00<00:00, 14455.65it/s]
100%|██████████| 207/207 [00:00<00:00, 825.05it/s]
  0%|          | 0/207 [00:00<?, ?it/s]

Style: highlight

100%|██████████| 207/207 [00:17<00:00, 11.51it/s]

Processing language es with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 35/35 [00:00<00:00, 10128.37it/s]
100%|██████████| 35/35 [00:00<00:00, 1042.59it/s]
100%|██████████| 35/35 [00:03<00:00, 10.74it/s]
100%|██████████| 19/19 [00:00<00:00, 14348.54it/s]
100%|██████████| 19/19 [00:00<00:00, 1291.60it/s]
  0%|          | 0/19 [00:00<?, ?it/s]

Processing language fa with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 19/19 [00:01<00:00, 13.10it/s]
  0%|          | 0/24 [00:00<?, ?it/s]

Processing language fr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 24/24 [00:00<00:00, 6271.86it/s]
100%|██████████| 24/24 [00:00<00:00, 1050.39it/s]
100%|██████████| 24/24 [00:02<00:00, 10.69it/s]
100%|██████████| 10/10 [00:00<00:00, 13281.52it/s]
100%|██████████| 10/10 [00:00<00:00, 1268.66it/s]
  0%|          | 0/10 [00:00<?, ?it/s]

Processing language ga with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 10/10 [00:00<00:00, 13.47it/s]
100%|██████████| 35/35 [00:00<00:00, 11066.77it/s]
100%|██████████| 35/35 [00:00<00:00, 1206.04it/s]
  0%|          | 0/35 [00:00<?, ?it/s]

Processing language gu with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 35/35 [00:02<00:00, 13.59it/s]
100%|██████████| 17/17 [00:00<00:00, 6161.17it/s]
100%|██████████| 17/17 [00:00<00:00, 1053.19it/s]
  0%|          | 0/17 [00:00<?, ?it/s]

Processing language he with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 17/17 [00:01<00:00, 11.47it/s]
100%|██████████| 28/28 [00:00<00:00, 15410.12it/s]
100%|██████████| 28/28 [00:00<00:00, 1259.94it/s]
  0%|          | 0/28 [00:00<?, ?it/s]

Processing language hi with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 28/28 [00:02<00:00, 11.02it/s]
100%|██████████| 40/40 [00:00<00:00, 17669.53it/s]
100%|██████████| 40/40 [00:00<00:00, 1292.10it/s]
  0%|          | 0/40 [00:00<?, ?it/s]

Processing language is with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 40/40 [00:03<00:00, 13.16it/s]
100%|██████████| 18/18 [00:00<00:00, 13829.91it/s]
100%|██████████| 18/18 [00:00<00:00, 1240.16it/s]
  0%|          | 0/18 [00:00<?, ?it/s]

Processing language it with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 18/18 [00:01<00:00, 12.80it/s]

Processing language ja with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 97/97 [00:00<00:00, 11011.06it/s]
100%|██████████| 97/97 [00:00<00:00, 1138.94it/s]
100%|██████████| 97/97 [00:08<00:00, 11.75it/s]

Processing language jv with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 21/21 [00:00<00:00, 15833.25it/s]
100%|██████████| 21/21 [00:00<00:00, 1350.76it/s]
100%|██████████| 21/21 [00:01<00:00, 14.02it/s]
100%|██████████| 8/8 [00:00<00:00, 6204.59it/s]
100%|██████████| 8/8 [00:00<00:00, 847.01it/s]
  0%|          | 0/8 [00:00<?, ?it/s]

Processing language kk with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 8/8 [00:00<00:00, 13.32it/s]
100%|██████████| 18/18 [00:00<00:00, 8607.62it/s]
  0%|          | 0/18 [00:00<?, ?it/s]

Processing language kn with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 18/18 [00:00<00:00, 1106.42it/s]
100%|██████████| 18/18 [00:01<00:00, 13.58it/s]
100%|██████████| 16/16 [00:00<00:00, 10128.11it/s]
100%|██████████| 16/16 [00:00<00:00, 1286.67it/s]
  0%|          | 0/16 [00:00<?, ?it/s]

Processing language ms with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 16/16 [00:01<00:00, 13.36it/s]
100%|██████████| 13/13 [00:00<00:00, 9433.56it/s]
100%|██████████| 13/13 [00:00<00:00, 1028.56it/s]
 23%|██▎       | 3/13 [00:00<00:00, 20.61it/s]

Processing language pt with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 13/13 [00:00<00:00, 13.39it/s]
100%|██████████| 8/8 [00:00<00:00, 5617.68it/s]
100%|██████████| 8/8 [00:00<00:00, 834.02it/s]
  0%|          | 0/8 [00:00<?, ?it/s]

Processing language ru with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 8/8 [00:00<00:00, 12.48it/s]

Processing language simple with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 20/20 [00:00<00:00, 8194.40it/s]
100%|██████████| 20/20 [00:00<00:00, 1187.55it/s]
100%|██████████| 20/20 [00:01<00:00, 12.20it/s]
100%|██████████| 28/28 [00:00<00:00, 9745.29it/s]
100%|██████████| 28/28 [00:00<00:00, 1185.62it/s]
  0%|          | 0/28 [00:00<?, ?it/s]

Processing language sk with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 28/28 [00:02<00:00, 13.10it/s]

Processing language sw with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 31/31 [00:00<00:00, 18432.58it/s]
100%|██████████| 31/31 [00:00<00:00, 1388.55it/s]
100%|██████████| 31/31 [00:02<00:00, 13.42it/s]
100%|██████████| 13/13 [00:00<00:00, 8086.30it/s]
100%|██████████| 13/13 [00:00<00:00, 947.54it/s]
  0%|          | 0/13 [00:00<?, ?it/s]

Processing language tr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 13/13 [00:01<00:00, 12.33it/s]
100%|██████████| 4/4 [00:00<00:00, 1939.56it/s]
100%|██████████| 4/4 [00:00<00:00, 420.31it/s]
  0%|          | 0/4 [00:00<?, ?it/s]

Processing language ur with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 4/4 [00:00<00:00,  6.74it/s]

Processing language uz with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 30/30 [00:00<00:00, 12765.46it/s]
100%|██████████| 30/30 [00:00<00:00, 1142.23it/s]
100%|██████████| 30/30 [00:02<00:00, 12.81it/s]

Processing language vi with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 26/26 [00:00<00:00, 9014.04it/s]
100%|██████████| 26/26 [00:00<00:00, 1121.32it/s]
100%|██████████| 26/26 [00:02<00:00, 11.14it/s]
100%|██████████| 19/19 [00:00<00:00, 12494.79it/s]
100%|██████████| 19/19 [00:00<00:00, 1130.14it/s]
  0%|          | 0/19 [00:00<?, ?it/s]

Processing language zh with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 19/19 [00:01<00:00, 12.10it/s]

CompletedProcess(args=['python', 'color_pages.py', '--scored_data_dir', '/dlabdata1/boulenge/wikidumps_data/selected_langs_small_sample_3/scored_data', '--html_dir', '/var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages', '--sorted_links_output_dir', '/var/www/html/wikinsert/selected_langs_small_sample_3/colored_pages', '--langs', 'af,ar,cs,cy,de,en,es,fa,fr,ga,gu,he,hi,is,it,ja,jv,kk,kn,ms,pt,ru,simple,sk,sw,tr,ur,uz,vi,zh', '--side_contexts_sizes', '5', '--extra_crawled_files_dir', '/var/www/html/wikinsert/selected_langs_small_sample_3/crawled_pages', '--full_model_name', 'roberta_full_multilingual-all'], returncode=0)