**Necessary imports**

In [2]:
import subprocess
import os
import pandas as pd

%load_ext autoreload
%autoreload 2

**Setting parameters**

In [3]:
simple_render_raw_data_dir = "/dlabdata1/tsoares/wikidumps/"
processed_data_dir = "/dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2"
processes = 48
max_samples_per_lang = 25
langs =  sorted(set([filename.split("wiki")[0] for filename in os.listdir(simple_render_raw_data_dir) if "wiki" in filename]))
side_context_sizes = [5]  # Example context sizes
second_month = "20231001"
third_month = "20231101"

langs_to_remove = ["war", "ky", "nds-nl"]

for lang in langs_to_remove:
    langs.remove(lang)

**Defining data paths**

In [4]:
# Define directories
rev_files_dir = os.path.join(processed_data_dir, "revisions_files")
parsed_htmls_dir = os.path.join(processed_data_dir, "parsed_htmls")
contexts_splitted_data_dir = os.path.join(processed_data_dir, "contexts_splitted_data")
ready_to_score_data_dir = os.path.join(processed_data_dir, "ready_to_score_data")
scored_data_dir = os.path.join(processed_data_dir, "scored_data")
crawling_output_dir = os.path.join(processed_data_dir, "crawled_pages")

# Create necessary directories if they don't exist
os.makedirs(rev_files_dir, exist_ok=True)
os.makedirs(parsed_htmls_dir, exist_ok=True)
os.makedirs(contexts_splitted_data_dir, exist_ok=True)
os.makedirs(ready_to_score_data_dir, exist_ok=True)
os.makedirs(scored_data_dir, exist_ok=True)
os.makedirs(crawling_output_dir, exist_ok=True)

**Prepare files to be crawled and parsed**

In [5]:
for lang in langs:
    try:
        print(f"Processing language: {lang}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
            
        subprocess.run([
            "python", "generate_revisions_file.py",
            "--versions_file", f"{second_month_path}/eval/link_versions",
            "--html_dir", f"{second_month_path}/eval/pages",
            "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
            "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",
            "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",
            "--max_samples", str(max_samples_per_lang),
            "--save_path", save_path
        ])

        #revisions = pd.read_parquet(save_path)
        #display(revisions.head(5))
    except Exception as e:
        print(f"Error processing language {lang}: {e}")
        continue

Processing language: af

Creating revisions dictionary: 100%|██████████| 2082/2082 [00:00<00:00, 434995.81it/s]
Checking revisions: 100%|██████████| 707/707 [00:03<00:00, 226.49it/s]

Processing language: am

Creating revisions dictionary: 100%|██████████| 24/24 [00:00<00:00, 303202.70it/s]
Checking revisions: 100%|██████████| 18/18 [00:00<00:00, 216.87it/s]

Processing language: an

Creating revisions dictionary: 100%|██████████| 93/93 [00:00<00:00, 568615.56it/s]
Checking revisions: 100%|██████████| 12/12 [00:00<00:00, 244.19it/s]

Processing language: ar

Creating revisions dictionary: 100%|██████████| 24525/24525 [00:00<00:00, 487980.46it/s]
Checking revisions: 100%|██████████| 6700/6700 [00:19<00:00, 342.60it/s]

Processing language: ary

Creating revisions dictionary: 100%|██████████| 152/152 [00:00<00:00, 563690.72it/s]
Checking revisions: 100%|██████████| 77/77 [00:00<00:00, 346.76it/s]

Processing language: as

Creating revisions dictionary: 100%|██████████| 496/496 [00:00<00:00, 736937.58it/s]
Checking revisions: 100%|██████████| 185/185 [00:00<00:00, 274.28it/s]

Processing language: ast

Creating revisions dictionary: 100%|██████████| 56/56 [00:00<00:00, 411350.30it/s]
Checking revisions: 100%|██████████| 39/39 [00:00<00:00, 294.13it/s]

Processing language: az

Creating revisions dictionary: 100%|██████████| 8019/8019 [00:00<00:00, 721576.50it/s]
Checking revisions: 100%|██████████| 2821/2821 [00:07<00:00, 396.85it/s]

Processing language: azb

Creating revisions dictionary: 100%|██████████| 42/42 [00:00<00:00, 433893.52it/s]
Checking revisions: 100%|██████████| 25/25 [00:00<00:00, 316.12it/s]

Processing language: ba

Creating revisions dictionary: 100%|██████████| 878/878 [00:00<00:00, 836954.30it/s]
Checking revisions: 100%|██████████| 250/250 [00:00<00:00, 404.14it/s]

Processing language: bar

Creating revisions dictionary: 100%|██████████| 24/24 [00:00<00:00, 253559.94it/s]
Checking revisions: 100%|██████████| 16/16 [00:00<00:00, 461.82it/s]

Processing language: be

Creating revisions dictionary: 100%|██████████| 4191/4191 [00:00<00:00, 873327.11it/s]
Checking revisions: 100%|██████████| 1609/1609 [00:04<00:00, 360.67it/s]

Processing language: bg

Creating revisions dictionary: 100%|██████████| 6108/6108 [00:00<00:00, 1017588.53it/s]
Checking revisions: 100%|██████████| 1893/1893 [00:05<00:00, 371.72it/s]

Processing language: br

Creating revisions dictionary: 100%|██████████| 1494/1494 [00:00<00:00, 1006309.65it/s]
Checking revisions: 100%|██████████| 489/489 [00:01<00:00, 368.40it/s]

Processing language: bs

Creating revisions dictionary: 100%|██████████| 1255/1255 [00:00<00:00, 766989.88it/s]
Checking revisions: 100%|██████████| 339/339 [00:00<00:00, 355.26it/s]

Processing language: ca

Creating revisions dictionary: 100%|██████████| 28516/28516 [00:00<00:00, 628598.92it/s]
Checking revisions: 100%|██████████| 7147/7147 [00:20<00:00, 350.52it/s]

Processing language: ce

Creating revisions dictionary: 100%|██████████| 1631/1631 [00:00<00:00, 890279.78it/s]
Checking revisions: 100%|██████████| 106/106 [00:00<00:00, 401.66it/s]

Processing language: cs

Creating revisions dictionary: 100%|██████████| 17059/17059 [00:00<00:00, 1013536.82it/s]
Checking revisions: 100%|██████████| 4391/4391 [00:15<00:00, 291.30it/s]

Processing language: cv

Creating revisions dictionary: 100%|██████████| 603/603 [00:00<00:00, 601609.26it/s]
Checking revisions: 100%|██████████| 144/144 [00:00<00:00, 377.59it/s]

Processing language: cy

Creating revisions dictionary: 100%|██████████| 526/526 [00:00<00:00, 540868.82it/s]
Checking revisions: 100%|██████████| 238/238 [00:00<00:00, 286.55it/s]

Processing language: da

Creating revisions dictionary: 100%|██████████| 3377/3377 [00:00<00:00, 930200.60it/s]
Checking revisions: 100%|██████████| 1042/1042 [00:02<00:00, 353.44it/s]

Processing language: de

Creating revisions dictionary: 100%|██████████| 118669/118669 [00:00<00:00, 574120.61it/s]
Checking revisions: 100%|██████████| 49899/49899 [02:52<00:00, 289.70it/s]

Processing language: el

Creating revisions dictionary: 100%|██████████| 8960/8960 [00:00<00:00, 683911.99it/s]
Checking revisions: 100%|██████████| 2191/2191 [00:06<00:00, 353.64it/s]

Processing language: en

Creating revisions dictionary: 100%|██████████| 448605/448605 [00:01<00:00, 431620.81it/s]
Checking revisions: 100%|██████████| 194300/194300 [10:15<00:00, 315.63it/s]

Processing language: eo

Creating revisions dictionary: 100%|██████████| 8385/8385 [00:00<00:00, 1045552.19it/s]
Checking revisions: 100%|██████████| 2340/2340 [00:06<00:00, 347.18it/s]

Processing language: es

Creating revisions dictionary: 100%|██████████| 86000/86000 [00:00<00:00, 724834.26it/s]
Checking revisions: 100%|██████████| 29970/29970 [01:39<00:00, 302.38it/s]

Processing language: et

Creating revisions dictionary: 100%|██████████| 6043/6043 [00:00<00:00, 990123.80it/s]
Checking revisions: 100%|██████████| 2026/2026 [00:06<00:00, 292.63it/s]

Processing language: eu

Creating revisions dictionary: 100%|██████████| 7960/7960 [00:00<00:00, 1068099.68it/s]
Checking revisions: 100%|██████████| 2155/2155 [00:07<00:00, 296.63it/s]

Processing language: fa

Creating revisions dictionary: 100%|██████████| 25510/25510 [00:00<00:00, 465059.46it/s]
Checking revisions: 100%|██████████| 7967/7967 [00:27<00:00, 294.55it/s]

Processing language: fi

Creating revisions dictionary: 100%|██████████| 17062/17062 [00:00<00:00, 961225.18it/s]
Checking revisions: 100%|██████████| 6203/6203 [00:18<00:00, 333.65it/s]

Processing language: fr

Creating revisions dictionary: 100%|██████████| 112993/112993 [00:00<00:00, 810239.64it/s]
Checking revisions: 100%|██████████| 26847/26847 [01:29<00:00, 299.89it/s]

Processing language: fy

Creating revisions dictionary: 100%|██████████| 731/731 [00:00<00:00, 829330.87it/s]
Checking revisions: 100%|██████████| 149/149 [00:00<00:00, 385.95it/s]

Processing language: ga

Creating revisions dictionary: 100%|██████████| 259/259 [00:00<00:00, 637514.52it/s]
Checking revisions: 100%|██████████| 109/109 [00:00<00:00, 297.15it/s]

Processing language: gd

Creating revisions dictionary: 100%|██████████| 21/21 [00:00<00:00, 218020.75it/s]
Checking revisions: 100%|██████████| 13/13 [00:00<00:00, 279.00it/s]

Processing language: gl

Creating revisions dictionary: 100%|██████████| 6132/6132 [00:00<00:00, 784345.46it/s]
Checking revisions: 100%|██████████| 1749/1749 [00:04<00:00, 352.89it/s]

Processing language: gu

Creating revisions dictionary: 100%|██████████| 50/50 [00:00<00:00, 367277.06it/s]
Checking revisions: 100%|██████████| 16/16 [00:00<00:00, 306.65it/s]

Processing language: ha

Creating revisions dictionary: 100%|██████████| 382/382 [00:00<00:00, 550592.48it/s]
Checking revisions: 100%|██████████| 180/180 [00:00<00:00, 434.98it/s]

Processing language: he

Creating revisions dictionary: 100%|██████████| 45686/45686 [00:00<00:00, 816057.77it/s]
Checking revisions: 100%|██████████| 17938/17938 [00:53<00:00, 333.34it/s]

Processing language: hi

Creating revisions dictionary: 100%|██████████| 3193/3193 [00:00<00:00, 821116.66it/s]
Checking revisions: 100%|██████████| 745/745 [00:02<00:00, 331.21it/s]

Processing language: hr

Creating revisions dictionary: 100%|██████████| 5426/5426 [00:00<00:00, 1000760.45it/s]
Checking revisions: 100%|██████████| 1469/1469 [00:04<00:00, 344.62it/s]

Processing language: hu

Creating revisions dictionary: 100%|██████████| 11973/11973 [00:00<00:00, 945447.73it/s]
Checking revisions: 100%|██████████| 4830/4830 [00:14<00:00, 326.59it/s]

Processing language: hy

Creating revisions dictionary: 100%|██████████| 4489/4489 [00:00<00:00, 999640.60it/s]
Checking revisions: 100%|██████████| 952/952 [00:03<00:00, 304.25it/s]

Processing language: id

Creating revisions dictionary: 100%|██████████| 21284/21284 [00:00<00:00, 1008706.87it/s]
Checking revisions: 100%|██████████| 5934/5934 [00:18<00:00, 325.09it/s]

Processing language: io

Creating revisions dictionary: 100%|██████████| 269/269 [00:00<00:00, 678045.54it/s]
Checking revisions: 100%|██████████| 92/92 [00:00<00:00, 357.97it/s]

Processing language: is

Creating revisions dictionary: 100%|██████████| 1243/1243 [00:00<00:00, 787540.77it/s]
Checking revisions: 100%|██████████| 285/285 [00:01<00:00, 269.88it/s]

Processing language: it

Creating revisions dictionary: 100%|██████████| 62268/62268 [00:00<00:00, 846023.77it/s]
Checking revisions: 100%|██████████| 22827/22827 [01:15<00:00, 302.90it/s]

Processing language: ja

Creating revisions dictionary: 100%|██████████| 136125/136125 [00:00<00:00, 808645.24it/s]
Checking revisions: 100%|██████████| 36301/36301 [01:45<00:00, 342.89it/s]

Processing language: jv

Creating revisions dictionary: 100%|██████████| 5865/5865 [00:00<00:00, 951886.12it/s]
Checking revisions: 100%|██████████| 95/95 [00:00<00:00, 354.18it/s]

Processing language: ka

Creating revisions dictionary: 100%|██████████| 2517/2517 [00:00<00:00, 781425.85it/s]
Checking revisions: 100%|██████████| 600/600 [00:01<00:00, 309.58it/s]

Processing language: kk

Creating revisions dictionary: 100%|██████████| 2282/2282 [00:00<00:00, 761205.80it/s]
Checking revisions: 100%|██████████| 1019/1019 [00:03<00:00, 315.58it/s]

Processing language: km

Creating revisions dictionary: 100%|██████████| 162/162 [00:00<00:00, 602373.45it/s]
Checking revisions: 100%|██████████| 58/58 [00:00<00:00, 377.76it/s]

Processing language: kn

Creating revisions dictionary: 100%|██████████| 676/676 [00:00<00:00, 701992.94it/s]
Checking revisions: 100%|██████████| 199/199 [00:00<00:00, 389.76it/s]

Processing language: ko

Creating revisions dictionary: 100%|██████████| 35510/35510 [00:00<00:00, 562185.24it/s]
Checking revisions: 100%|██████████| 10771/10771 [00:39<00:00, 271.72it/s]

Processing language: ku

Creating revisions dictionary: 100%|██████████| 868/868 [00:00<00:00, 706374.83it/s]
Checking revisions: 100%|██████████| 378/378 [00:01<00:00, 296.32it/s]

Processing language: la

Creating revisions dictionary: 100%|██████████| 1388/1388 [00:00<00:00, 729809.95it/s]
Checking revisions: 100%|██████████| 572/572 [00:01<00:00, 318.37it/s]

Processing language: lb

Creating revisions dictionary: 100%|██████████| 1021/1021 [00:00<00:00, 690150.59it/s]
Checking revisions: 100%|██████████| 472/472 [00:01<00:00, 325.77it/s]

Processing language: lmo

Creating revisions dictionary: 100%|██████████| 27/27 [00:00<00:00, 200791.15it/s]
Checking revisions: 100%|██████████| 15/15 [00:00<00:00, 380.66it/s]

Processing language: lo

Creating revisions dictionary: 100%|██████████| 35/35 [00:00<00:00, 308404.71it/s]
Checking revisions: 100%|██████████| 13/13 [00:00<00:00, 364.88it/s]

Processing language: lt

Creating revisions dictionary: 100%|██████████| 3797/3797 [00:00<00:00, 892150.15it/s]
Checking revisions: 100%|██████████| 1677/1677 [00:05<00:00, 308.66it/s]

Processing language: lv

Creating revisions dictionary: 100%|██████████| 2808/2808 [00:00<00:00, 1012082.64it/s]
Checking revisions: 100%|██████████| 953/953 [00:03<00:00, 281.82it/s]

Processing language: mg

Creating revisions dictionary: 100%|██████████| 2008/2008 [00:00<00:00, 736782.65it/s]
Checking revisions: 100%|██████████| 301/301 [00:00<00:00, 371.87it/s]

Processing language: min

Creating revisions dictionary: 100%|██████████| 47/47 [00:00<00:00, 403959.61it/s]
Checking revisions: 100%|██████████| 12/12 [00:00<00:00, 350.59it/s]

Processing language: mk

Creating revisions dictionary: 100%|██████████| 1292/1292 [00:00<00:00, 667040.96it/s]
Checking revisions: 100%|██████████| 588/588 [00:01<00:00, 315.45it/s]

Processing language: mn

Creating revisions dictionary: 100%|██████████| 592/592 [00:00<00:00, 641112.31it/s]
Checking revisions: 100%|██████████| 168/168 [00:00<00:00, 358.87it/s]

Processing language: mr

Creating revisions dictionary: 100%|██████████| 110/110 [00:00<00:00, 534615.81it/s]
Checking revisions: 100%|██████████| 45/45 [00:00<00:00, 352.89it/s]

Processing language: ms

Creating revisions dictionary: 100%|██████████| 3777/3777 [00:00<00:00, 825485.19it/s]
Checking revisions: 100%|██████████| 1526/1526 [00:04<00:00, 345.33it/s]

Processing language: ne

Creating revisions dictionary: 100%|██████████| 394/394 [00:00<00:00, 578423.44it/s]
Checking revisions: 100%|██████████| 168/168 [00:00<00:00, 348.77it/s]

Processing language: nl

Creating revisions dictionary: 100%|██████████| 33226/33226 [00:00<00:00, 532206.79it/s]
Checking revisions: 100%|██████████| 12413/12413 [00:36<00:00, 341.91it/s]

Processing language: no

Creating revisions dictionary: 100%|██████████| 10176/10176 [00:00<00:00, 995387.89it/s]
Checking revisions: 100%|██████████| 3265/3265 [00:09<00:00, 334.08it/s]

Processing language: oc

Creating revisions dictionary: 100%|██████████| 1836/1836 [00:00<00:00, 759891.67it/s]
Checking revisions: 100%|██████████| 625/625 [00:02<00:00, 281.66it/s]

Processing language: om

Creating revisions dictionary: 100%|██████████| 36/36 [00:00<00:00, 311329.78it/s]
Checking revisions: 100%|██████████| 11/11 [00:00<00:00, 323.68it/s]

Processing language: pa

Creating revisions dictionary: 100%|██████████| 305/305 [00:00<00:00, 818990.22it/s]
Checking revisions: 100%|██████████| 106/106 [00:00<00:00, 335.36it/s]

Processing language: pl

Creating revisions dictionary: 100%|██████████| 40921/40921 [00:00<00:00, 640594.46it/s]
Checking revisions: 100%|██████████| 13581/13581 [00:39<00:00, 341.29it/s]

Processing language: pms

Creating revisions dictionary: 100%|██████████| 2/2 [00:00<00:00, 12520.31it/s]
Checking revisions: 100%|██████████| 2/2 [00:00<00:00, 318.00it/s]

Processing language: ps

Creating revisions dictionary: 100%|██████████| 13/13 [00:00<00:00, 77341.78it/s]
Checking revisions: 100%|██████████| 9/9 [00:00<00:00, 226.59it/s]

Processing language: pt

Creating revisions dictionary: 100%|██████████| 36665/36665 [00:00<00:00, 579987.09it/s]
Checking revisions: 100%|██████████| 8520/8520 [00:28<00:00, 299.16it/s]

Processing language: ro

Creating revisions dictionary: 100%|██████████| 6990/6990 [00:00<00:00, 965684.62it/s]
Checking revisions: 100%|██████████| 2354/2354 [00:07<00:00, 321.61it/s]

Processing language: ru

Creating revisions dictionary: 100%|██████████| 51195/51195 [00:00<00:00, 785192.56it/s]
Checking revisions: 100%|██████████| 20743/20743 [01:04<00:00, 319.81it/s]

Processing language: sa

Creating revisions dictionary: 100%|██████████| 28/28 [00:00<00:00, 276330.62it/s]
Checking revisions: 100%|██████████| 6/6 [00:00<00:00, 478.21it/s]

Processing language: scn

Creating revisions dictionary: 100%|██████████| 20/20 [00:00<00:00, 213450.59it/s]
Checking revisions: 100%|██████████| 13/13 [00:00<00:00, 323.12it/s]

Processing language: sco

Creating revisions dictionary: 100%|██████████| 45/45 [00:00<00:00, 378243.85it/s]
Checking revisions: 100%|██████████| 17/17 [00:00<00:00, 416.61it/s]

Processing language: sd

Creating revisions dictionary: 100%|██████████| 12/12 [00:00<00:00, 68665.28it/s]
Checking revisions: 100%|██████████| 7/7 [00:00<00:00, 359.81it/s]

Processing language: sh

Creating revisions dictionary: 100%|██████████| 1357/1357 [00:00<00:00, 968300.53it/s]
Checking revisions: 100%|██████████| 314/314 [00:00<00:00, 424.07it/s]

Processing language: si

Creating revisions dictionary: 100%|██████████| 72/72 [00:00<00:00, 442152.11it/s]
Checking revisions: 100%|██████████| 35/35 [00:00<00:00, 332.57it/s]

Processing language: simple

Creating revisions dictionary: 100%|██████████| 5175/5175 [00:00<00:00, 751082.16it/s]
Checking revisions: 100%|██████████| 1841/1841 [00:04<00:00, 439.31it/s]

Processing language: sk

Creating revisions dictionary: 100%|██████████| 5180/5180 [00:00<00:00, 787962.67it/s]
Checking revisions: 100%|██████████| 1286/1286 [00:03<00:00, 332.86it/s]

Processing language: sl

Creating revisions dictionary: 100%|██████████| 2427/2427 [00:00<00:00, 798085.13it/s]
Checking revisions: 100%|██████████| 775/775 [00:01<00:00, 387.98it/s]

Processing language: so

Creating revisions dictionary: 100%|██████████| 71/71 [00:00<00:00, 449842.27it/s]
Checking revisions: 100%|██████████| 30/30 [00:00<00:00, 434.41it/s]

Processing language: sq

Creating revisions dictionary: 100%|██████████| 992/992 [00:00<00:00, 892673.15it/s]
Checking revisions: 100%|██████████| 357/357 [00:00<00:00, 417.85it/s]

Processing language: sr

Creating revisions dictionary: 100%|██████████| 8745/8745 [00:00<00:00, 1072773.20it/s]
Checking revisions: 100%|██████████| 2188/2188 [00:05<00:00, 384.68it/s]

Processing language: su

Creating revisions dictionary: 100%|██████████| 8/8 [00:00<00:00, 46154.65it/s]
Checking revisions: 100%|██████████| 7/7 [00:00<00:00, 380.28it/s]

Processing language: sv

Creating revisions dictionary: 100%|██████████| 13640/13640 [00:00<00:00, 901872.89it/s]
Checking revisions: 100%|██████████| 5054/5054 [00:13<00:00, 373.83it/s]

Processing language: sw

Creating revisions dictionary: 100%|██████████| 596/596 [00:00<00:00, 718954.61it/s]
Checking revisions: 100%|██████████| 170/170 [00:00<00:00, 363.49it/s]

Processing language: ta

Creating revisions dictionary: 100%|██████████| 2293/2293 [00:00<00:00, 977491.52it/s]
Checking revisions: 100%|██████████| 762/762 [00:01<00:00, 392.08it/s]

Processing language: te

Creating revisions dictionary: 100%|██████████| 2576/2576 [00:00<00:00, 924411.97it/s]
Checking revisions: 100%|██████████| 964/964 [00:02<00:00, 379.88it/s]

Processing language: tg

Creating revisions dictionary: 100%|██████████| 187/187 [00:00<00:00, 702809.00it/s]
Checking revisions: 100%|██████████| 107/107 [00:00<00:00, 412.84it/s]

Processing language: tl

Creating revisions dictionary: 100%|██████████| 889/889 [00:00<00:00, 916151.41it/s]
Checking revisions: 100%|██████████| 216/216 [00:01<00:00, 152.20it/s]

Processing language: tr

Creating revisions dictionary: 100%|██████████| 25000/25000 [00:00<00:00, 559652.44it/s]
Checking revisions: 100%|██████████| 6811/6811 [00:26<00:00, 259.33it/s]

Processing language: tt

Creating revisions dictionary: 100%|██████████| 107/107 [00:00<00:00, 556122.09it/s]
Checking revisions: 100%|██████████| 54/54 [00:00<00:00, 463.01it/s]

Processing language: ug

Creating revisions dictionary: 100%|██████████| 1/1 [00:00<00:00, 6584.46it/s]
Checking revisions: 100%|██████████| 1/1 [00:00<00:00, 292.73it/s]

Processing language: uk

Creating revisions dictionary: 100%|██████████| 2/2 [00:00<00:00, 12965.39it/s]
Checking revisions: 100%|██████████| 2/2 [00:00<00:00, 150.52it/s]

Processing language: ur

Creating revisions dictionary: 100%|██████████| 5717/5717 [00:00<00:00, 841067.55it/s]
Checking revisions: 100%|██████████| 3287/3287 [00:14<00:00, 221.06it/s]

Processing language: uz

Creating revisions dictionary: 100%|██████████| 6490/6490 [00:00<00:00, 1080414.09it/s]
Checking revisions: 100%|██████████| 1343/1343 [00:03<00:00, 355.63it/s]

Processing language: vi

Creating revisions dictionary: 100%|██████████| 17236/17236 [00:00<00:00, 1077568.96it/s]
Checking revisions: 100%|██████████| 3716/3716 [00:12<00:00, 304.31it/s]

Processing language: vo

Creating revisions dictionary: 100%|██████████| 11/11 [00:00<00:00, 84655.68it/s]
Checking revisions: 100%|██████████| 4/4 [00:00<00:00, 379.54it/s]

Processing language: xh

Creating revisions dictionary: 100%|██████████| 1/1 [00:00<00:00, 6061.13it/s]
Checking revisions: 100%|██████████| 1/1 [00:00<00:00, 262.13it/s]

Processing language: yi

Creating revisions dictionary: 100%|██████████| 25/25 [00:00<00:00, 257635.38it/s]
Checking revisions: 100%|██████████| 19/19 [00:00<00:00, 415.08it/s]

Processing language: zh

Creating revisions dictionary: 100%|██████████| 49579/49579 [00:00<00:00, 890293.43it/s]
Checking revisions: 100%|██████████| 18087/18087 [00:51<00:00, 352.35it/s]

**Crawling first versions only**

In [6]:
for lang in langs:
    print(f"Processing language: {lang}")
    subprocess.run([
        "python", "crawl.py",
        "--revisions_path", f"{rev_files_dir}/revisions_{lang}.parquet",
        "--output_dir", f"{crawling_output_dir}/{lang}",
        "--n_processes", str(processes),
        "--lang", lang,
        #"--crawl_second_versions", "False" (false by default)
    ])

Processing language: af
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess

Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 66.51it/s]

Processing language: am
Total number of pages to crawl: 18
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 18/18 [00:00<00:00, 185.10it/s]

Processing language: an
Total number of pages to crawl: 12
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 12/12 [00:00<00:00, 16.18it/s]

Processing language: ar
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 127.70it/s]

Processing language: ary
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 174.66it/s]

Processing language: as
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 167.64it/s]

Processing language: ast
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 156.80it/s]

Processing language: az
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 112.91it/s]

Processing language: azb
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 147.02it/s]

Processing language: ba
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 131.76it/s]

Processing language: bar
Total number of pages to crawl: 16
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 16/16 [00:00<00:00, 163.63it/s]

Processing language: be
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 140.65it/s]

Processing language: bg
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 108.10it/s]

Processing language: br
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 63.48it/s]

Processing language: bs
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 167.69it/s]

Processing language: ca
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 141.16it/s]

Processing language: ce
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 178.95it/s]

Processing language: cs
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 188.46it/s]

Processing language: cv
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 155.44it/s]

Processing language: cy
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 159.68it/s]

Processing language: da
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 69.93it/s]

Processing language: de
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 167.19it/s]

Processing language: el
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 159.75it/s]

Processing language: en
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 171.43it/s]

Processing language: eo
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 129.59it/s]

Processing language: es
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 114.15it/s]

Processing language: et
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 191.18it/s]

Processing language: eu
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 171.40it/s]

Processing language: fa
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 158.36it/s]

Processing language: fi
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 205.46it/s]

Processing language: fr
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 133.99it/s]

Processing language: fy
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 184.04it/s]

Processing language: ga
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 174.62it/s]

Processing language: gd
Total number of pages to crawl: 13
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: gl

Moving files: 100%|██████████| 13/13 [00:00<00:00, 167.26it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 151.88it/s]

Processing language: gu
Total number of pages to crawl: 16
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: ha

Moving files: 100%|██████████| 16/16 [00:00<00:00, 194.88it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 198.10it/s]

Processing language: he
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 153.29it/s]

Processing language: hi
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 168.91it/s]

Processing language: hr
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 151.64it/s]

Processing language: hu
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 125.82it/s]

Processing language: hy
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 159.63it/s]

Processing language: id
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 158.82it/s]

Processing language: io
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 184.80it/s]

Processing language: is
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 191.80it/s]

Processing language: it
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 196.32it/s]

Processing language: ja
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 156.72it/s]

Processing language: jv
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 184.39it/s]

Processing language: ka
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 168.50it/s]

Processing language: kk
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 197.36it/s]

Processing language: km
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 187.70it/s]

Processing language: kn
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 197.61it/s]

Processing language: ko
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 176.74it/s]

Processing language: ku
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 70.92it/s]

Processing language: la
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 185.02it/s]

Processing language: lb
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 182.25it/s]

Processing language: lmo
Total number of pages to crawl: 15
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 15/15 [00:00<00:00, 155.01it/s]

Processing language: lo
Total number of pages to crawl: 13
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 13/13 [00:00<00:00, 165.83it/s]

Processing language: lt
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 174.17it/s]

Processing language: lv
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 145.72it/s]

Processing language: mg
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 171.71it/s]

Processing language: min
Total number of pages to crawl: 12
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: mk

Moving files: 100%|██████████| 12/12 [00:00<00:00, 193.90it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 176.85it/s]

Processing language: mn
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 178.64it/s]

Processing language: mr
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 172.84it/s]

Processing language: ms
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 149.46it/s]

Processing language: ne
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 170.46it/s]

Processing language: nl
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 161.12it/s]

Processing language: no
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 167.47it/s]

Processing language: oc
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 114.88it/s]

Processing language: om
Total number of pages to crawl: 11
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 11/11 [00:00<00:00, 41.41it/s]

Processing language: pa
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 176.75it/s]

Processing language: pl
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 151.44it/s]

Processing language: pms
Total number of pages to crawl: 2
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: ps

Moving files: 100%|██████████| 2/2 [00:00<00:00, 193.24it/s]

Total number of pages to crawl: 9
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: pt

Moving files: 100%|██████████| 9/9 [00:00<00:00, 121.61it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 143.87it/s]

Processing language: ro
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 101.66it/s]

Processing language: ru
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 192.68it/s]

Processing language: sa
Total number of pages to crawl: 6
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: scn

Moving files: 100%|██████████| 6/6 [00:00<00:00, 169.18it/s]

Total number of pages to crawl: 13
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 13/13 [00:00<00:00, 170.50it/s]

Processing language: sco
Total number of pages to crawl: 17
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 17/17 [00:00<00:00, 55.67it/s]

Processing language: sd
Total number of pages to crawl: 7
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: sh

Moving files: 100%|██████████| 7/7 [00:00<00:00, 191.86it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 174.10it/s]

Processing language: si
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 158.33it/s]

Processing language: simple
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 160.29it/s]

Processing language: sk
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 158.53it/s]

Processing language: sl
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 176.84it/s]

Processing language: so
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 110.19it/s]

Processing language: sq
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 168.94it/s]

Processing language: sr
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 145.61it/s]

Processing language: su
Total number of pages to crawl: 7
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: sv

Moving files: 100%|██████████| 7/7 [00:00<00:00, 136.86it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 165.08it/s]

Processing language: sw
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 159.89it/s]

Processing language: ta
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 174.97it/s]

Processing language: te
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 154.99it/s]

Processing language: tg
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 166.75it/s]

Processing language: tl
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 66.50it/s]

Processing language: tr
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 112.99it/s]

Processing language: tt
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 139.00it/s]

Processing language: ug
Total number of pages to crawl: 1
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: uk

Moving files: 100%|██████████| 1/1 [00:00<00:00, 117.19it/s]

Total number of pages to crawl: 2
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: ur

Moving files: 100%|██████████| 2/2 [00:00<00:00, 143.62it/s]

Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 60.35it/s]

Processing language: uz
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 63.50it/s]

Processing language: vi
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 41.84it/s]

Processing language: vo
Total number of pages to crawl: 4
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 4/4 [00:00<00:00, 169.43it/s]

Processing language: xh
Total number of pages to crawl: 1
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: yi

Moving files: 100%|██████████| 1/1 [00:00<00:00, 105.59it/s]

Total number of pages to crawl: 19
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 19/19 [00:00<00:00, 51.64it/s]

Processing language: zh
Total number of pages to crawl: 25
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 25/25 [00:00<00:00, 118.91it/s]

**Parsing of the htmls**

In [7]:
for lang in langs:
    print(f"Processing language: {lang}")
    second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
    first_version_specific_html_dir = f"{crawling_output_dir}/{lang}"
    save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
    output_dir = f"{parsed_htmls_dir}/{lang}_v2"
    first_version_specific_output_dir = f"{parsed_htmls_dir}/{lang}_v1"
        
    subprocess.run([
        "python", "parsing.py",
        "--revisions_path", save_path,        
        "--html_dir", f"{second_month_path}/eval/pages",
        "--first_versions_specific_html_dir", first_version_specific_html_dir,
        "--output_dir", output_dir,
        "--first_versions_specific_output_dir", first_version_specific_output_dir,
        "--n_processes", str(processes)
    ])

    parsed_htmls_paths = os.listdir(first_version_specific_output_dir)
    sentences_path = list(filter(lambda x: x.endswith("sentences.jsonl"), parsed_htmls_paths))[0]
    links_path = list(filter(lambda x: x.endswith("links.jsonl"), parsed_htmls_paths))[0]
    sentences_df = pd.read_json(f"{first_version_specific_output_dir}/{sentences_path}")
    links_df = pd.read_json(f"{first_version_specific_output_dir}/{links_path}")

    display(sentences_df.head(5))
    display(links_df.head(5))

Processing language: af
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/af
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Time taken for v1: 8.357717752456665
Writing sentences and links v2
Time taken for v2: 7.778958082199097

,md5,id,text,startIdx,endIdx,section,locList
0,da8d4baf43f51ce16b55db9d6fb353d2,0,Die 2023 Formule Een Katarse Grand Prix sal op...,47168,47521,Lead,"[{'start': 47167, 'end': 47168}, {'start': 471..."
1,319b9bcab48566285b2714c508c36e6d,1,Dit is die tweede uitgawe van die Grand Prix ​...,47522,47667,Lead,"[{'start': 47520, 'end': 47666}]"
2,00866195324af1f75ca8070f22ece80c,2,"Die Losail-baan, wat sedert 2004 in gebruik is...",47668,47933,Lead,"[{'start': 47666, 'end': 47667}, {'start': 476..."
3,33856bd55387ae00c51754cc632b107d,3,Pirelli sal die volgende bande in Katar verskaf:,48031,48127,Bande,"[{'start': 48030, 'end': 48031}, {'start': 480..."
4,21626bafc0afc15d1f8a294d8ab03db2,4,Die uitslag bepaal die roosteropstelling vir d...,55090,55165,Snelkwalifisering,"[{'start': 55089, 'end': 55090}, {'start': 550..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Engels,50865,Engels,50913,Lead,0
1,file:///wiki/Verenigde_State_van_Amerika,50987,Verenigde State,51086,Lead,0
2,file:///wiki/Wes-Indi%C3%AB,51090,Wes-Indië,51152,Lead,0
3,file:///wiki/T20I-w%C3%AAreldbeker,51261,T20I-wêreldbeker,51344,Lead,0
4,file:///wiki/Twintig20,51348,T20I,51400,Lead,0

Processing language: am
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/am
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.9595239162445068
Writing sentences and links v2
Time taken for v2: 2.4656906127929688

,md5,id,text,startIdx,endIdx,section,locList
0,cc7819055cde3194bb3b136bad5cf58d,0,&nbsp;,36258,36264,Lead,"[{'start': 36258, 'end': 36264}]"
1,1605c42e5b877c76dc8fa8988f8665dc,1,ፋይዳ የዲጂታል መታወቂያ ሲሆን ቴክኖሎጂን በመጠቀም የነዋሪዎችን የተመጠነ...,36265,36813,Lead,"[{'start': 36264, 'end': 36265}, {'start': 362..."
2,6b5f45e65e54e9984cc2e39253153e56,2,አላማው በሀገር አቀፍ ደረጃ የባዮሜትሪክ ዲጂታል መታወቂያ ስርዓትን በመተ...,36825,36990,Lead,"[{'start': 36824, 'end': 36914}, {'start': 369..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E1%8B%A8%E1%8B%8B%E1%89%85%E1%88...,70554,የዋቅላሚ ወገኖች,70686,ስርዓተ ምደባ,6
1,file:///wiki/%E1%8A%A0%E1%88%A8%E1%8A%95%E1%8C...,71671,አረንጓዴ ዋቅላሚዎች,71825,ስርዓተ ምደባ,11
2,file:///wiki/%E1%8B%B1%E1%8A%93%E1%88%8C%E1%88%8B,74630,ዱናሌላ,74704,ጥቅም,31
3,file:///wiki/%E1%88%B5%E1%8D%93%E1%8B%AD%E1%88...,76039,ስፓይሩሊና,76135,ጥቅም,36
4,https://en.wikipedia.org/wiki/Algae,80759,http://en.wikipedia.org/wiki/Algae,80865,ዋቢ ምንጭ,58

Processing language: an
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/an
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.5535945892333984
Writing sentences and links v2
Time taken for v2: 2.6049883365631104

,md5,id,text,startIdx,endIdx,section,locList
0,781e47f5f4f4186121aae7e1a7dd9de2,0,"Marcelino Iglesias Ricou (Bonansa, Uesca, 16 d...",49906,50566,Lead,"[{'start': 49905, 'end': 49906}, {'start': 499..."
1,d82012a7b5431e10bb4951c1e42496f8,1,"Ye treballador autonomo, ye casato y tien dos ...",50567,50620,Lead,"[{'start': 50565, 'end': 50619}]"
2,3c5725339a3c4da9ad15d4f46d3b05af,2,"Empecipió estando alcalde de Bonansa, en Ribag...",50621,50821,Lead,"[{'start': 50619, 'end': 50620}, {'start': 506..."
3,1ea28a7d79e486f5ce9ab42a04d22583,3,"Dimpués, estió president d'a Deputación Provin...",50822,51547,Lead,"[{'start': 50820, 'end': 50850}, {'start': 509..."
4,65c656300f5c5d92011d7734030eb1da,4,Marcelino Iglesias ocupó a Secretaría d'o PSOE...,51548,51761,Lead,"[{'start': 51546, 'end': 51547}, {'start': 515..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Bonansa,49240,Bonansa,49291,Lead,0
1,file:///wiki/Provincia_de_Uesca,49293,Uesca,49364,Lead,0
2,file:///wiki/16_d%27abril,49366,16 d'abril,49428,Lead,0
3,file:///wiki/1951,49432,1951,49474,Lead,0
4,file:///wiki/Politico,49482,politico,49536,Lead,0

Processing language: ar
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ar
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 22.95382285118103
Writing sentences and links v2
Time taken for v2: 23.37787961959839

,md5,id,text,startIdx,endIdx,section,locList
0,4bce01acde302a4b480e76679711c8bc,0,اليهودية هي ديانة الشعب اليهودي، وهي ديانة توح...,141477,142011,Lead,"[{'start': 141476, 'end': 141477}, {'start': 1..."
1,4b893c6e563f0f28bd510faff308e320,1,وتستند في تعاليمها على التوراة كنصها التأسيسي ...,142012,145621,Lead,"[{'start': 142010, 'end': 142034}, {'start': 1..."
2,b3bb3415d119e33b82fc5806cbba8111,2,تطورت اليهودية الحديثة من اليهودية، ديانة مملك...,145622,146099,Lead,"[{'start': 145620, 'end': 145663}, {'start': 1..."
3,4e4d2dc00e6deec9e51888e86805ae8e,3,يري كثير من المؤرخين أن أصول الديانة اليهودية ...,146100,148093,Lead,"[{'start': 146098, 'end': 146123}, {'start': 1..."
4,a9bf37133d743d62099d3a849decf28a,4,التوراة هي جزء من النص الأكبر المعروف باسم الت...,148094,148689,Lead,"[{'start': 148092, 'end': 148093}, {'start': 1..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A7%D9%84%D9%85%D8%A4%D8%B3%D8...,88205,المؤسس عثمان,88367,Lead,0
1,file:///wiki/%D9%85%D8%AD%D9%85%D8%AF_%D8%A8%D...,88518,محمد بوزداغ,88631,Lead,0
2,file:///wiki/%D8%A7%D9%84%D9%85%D8%A4%D8%B3%D8...,88647,المؤسس عثمان,88809,Lead,0
3,file:///wiki/%D9%85%D8%B9%D8%B1%D9%83%D8%A9_%D...,89010,معركة بافيوس,89131,القصة,1
4,file:///wiki/%D8%A8%D9%88%D8%B1%D8%A7%D9%83_%D...,89968,بوراك أوزجيفيت,90125,الممثلون والشخصيات,7

Processing language: ary
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ary
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.5149784088134766
Writing sentences and links v2
Time taken for v2: 4.106189489364624

,md5,id,text,startIdx,endIdx,section,locList
0,45af954d4639deab6182a41186023228,0,بن حمد جماعة ترابية حضرية كاينة ف إقليم/عمالة ...,43022,43475,Lead,"[{'start': 43021, 'end': 43022}, {'start': 430..."
1,cf4f0bb1f87fd095c5356028f139b687,1,نسبة لأمية (نّاس لّي ما كايعرفوش يقراو ولا يكت...,43588,43664,تعليم,"[{'start': 43587, 'end': 43588}, {'start': 435..."
2,b297d0c0417bee989e23ea3e5bec3496,2,نسبة سّكان لّي قاريين فوق تّانوي (تانوي و جامع...,43665,43734,تعليم,"[{'start': 43663, 'end': 43664}, {'start': 436..."
3,3c8eaffdcc1eb6902e8618083c5e324e,3,"نسبة نّاس نّشيطين (لّي يقدرو يخدمو): 45,9%",43850,43906,اقتصاد,"[{'start': 43849, 'end': 43850}, {'start': 438..."
4,f382f36d7d12adc2a8ef58b5c640f30f,4,نسبة لبطالة (نّاس لّي ما خدامينش و تايقلبو على...,43907,43975,اقتصاد,"[{'start': 43905, 'end': 43906}, {'start': 439..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A8%D9%8A%D8%B2%D9%86%D9%8A%D8...,98895,بيزنيسمان,98997,Lead,0
1,file:///wiki/%D8%AC%D9%86%D9%88%D8%A8_%D8%A5%D...,99052,جنوب إفريقيا,99173,Lead,1
2,file:///wiki/%D9%83%D8%A7%D9%86%D8%A7%D8%AF%D8%A7,99176,كانادا,99254,Lead,1
3,file:///wiki/%D8%A7%D9%84%D9%88%D9%84%D8%A7%D9...,99257,لميريكان,99469,Lead,1
4,file:///wiki/%D8%B3%D9%BE%D9%8A%D8%B3_%D8%A5%D...,99535,سپيس إيكس,99632,Lead,1

Processing language: as
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/as
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.273221492767334
Writing sentences and links v2
Time taken for v2: 3.220827579498291

,md5,id,text,startIdx,endIdx,section,locList
0,ce69361961521182850f73e724f41850,0,Blue light is scattered more than other wavele...,82978,84329,Lead,"[{'start': 82977, 'end': 82978}, {'start': 834..."
1,45316d388ff63453f4e12bb819f0ed40,1,পৃথিৱীৰ বায়ুমণ্ডল হৈছে পৃথিৱীৰ মাধ্যাকৰ্ষণ শক...,84330,85945,Lead,"[{'start': 84328, 'end': 84329}, {'start': 843..."
2,d004ed58dd244f1dd5b406e30a277ee3,2,২০২৩ চনৰ হিচাপত মোল ভগ্নাংশ অনুসৰি (অৰ্থাৎ অণু...,85947,88112,Lead,"[{'start': 85944, 'end': 85946}, {'start': 859..."
3,39246f82d08e5ec6ce9724d6a7065b3b,3,পৃথিৱীৰ প্ৰাৰম্ভিক বায়ুমণ্ডল সৌৰ নীহাৰিকাত থক...,88113,88464,Lead,"[{'start': 88110, 'end': 88111}, {'start': 881..."
4,796b47bcb655d4ff6ff2c7a29febd0b8,4,The atmosphere has a mass of about 5.15×1018&n...,88466,88912,Lead,"[{'start': 88463, 'end': 88465}, {'start': 884..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A6%B2%E0%A6%BF%E0%A6%85%27%E0...,70571,লিঅ'নাৰ্ড' দা ভিন্সি,70793,Lead,0
1,file:///wiki/%E0%A7%B1%E0%A6%BF%E0%A6%95%E0%A6...,71209,ˌ,71465,Lead,1
2,file:///wiki/%E0%A7%B1%E0%A6%BF%E0%A6%95%E0%A6...,71490,f,71735,Lead,1
3,file:///wiki/%E0%A7%B1%E0%A6%BF%E0%A6%95%E0%A6...,71760,ɪ,72010,Lead,1
4,file:///wiki/%E0%A7%B1%E0%A6%BF%E0%A6%95%E0%A6...,72035,z,72280,Lead,1

Processing language: ast
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ast
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.2276763916015625
Writing sentences and links v2
Time taken for v2: 6.8418214321136475

,md5,id,text,startIdx,endIdx,section,locList
0,d221fa254d939926671987c5fec95ddc,0,Llan de Cubel ye ún de los más veteranos (dend...,42075,42356,Lead,"[{'start': 42074, 'end': 42075}, {'start': 420..."
1,71e36eb1a772bca8f4ab6e9c311a07c2,1,El so nome ta sacáu del Picu Llan de Cubel ent...,42357,42735,Lead,"[{'start': 42355, 'end': 42380}, {'start': 425..."
2,6133e657b3fd5a5503b05a07113a125b,2,La so música ta basada nel repertoriu tradicio...,42736,42955,Lead,"[{'start': 42734, 'end': 42735}, {'start': 427..."
3,e5bf34c81628ff4cbf580dded5757a91,3,El so soníu ye acústicu y apoyen les sos melod...,42956,43920,Lead,"[{'start': 42954, 'end': 42955}, {'start': 429..."
4,725e0294f0ea132567ae034982807df1,4,Tamién usen dalgún mediu llétricu pa pasaxes m...,43921,44100,Lead,"[{'start': 43919, 'end': 44099}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Conceyos_d%27Asturies,59204,conceyu,59301,Lead,0
1,file:///wiki/Asturies,59304,Asturies,59378,Lead,0
2,file:///wiki/Xix%C3%B3n,59398,Xixón,59448,Lead,1
3,file:///wiki/Corvera,59451,Corvera,59502,Lead,1
4,file:///wiki/Uvi%C3%A9u,59515,Uviéu,59565,Lead,1

Processing language: az
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/az
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 8.024033069610596
Writing sentences and links v2
Time taken for v2: 7.962450981140137

,md5,id,text,startIdx,endIdx,section,locList
0,9af56a2eb2b10d0188387693ef7151e9,0,Yura Poqosyan (erm. Մհեր Ջուլհաճյան) - Birinc...,13880,14221,Lead,"[{'start': 13879, 'end': 13880}, {'start': 138..."
1,9bc0cffa08c5e460a9677813a5c74879,1,1996-cı ildə Ermənistanın Milli Qəhrəmanı adın...,14222,14398,Lead,"[{'start': 14220, 'end': 14234}, {'start': 143..."
2,037561f00c8a21cdf669b7387a1de3ff,2,1992-ci ilin 12 iyun tarixində Azərbaycan Resp...,14399,14985,Lead,"[{'start': 14397, 'end': 14398}, {'start': 144..."
3,86105b4e7b6c6f473b2b7d641ee334fb,3,Yura Poqosyan 1961-ci ilin 8 aprel tarixində R...,15086,15517,Həyatı,"[{'start': 15085, 'end': 15086}, {'start': 150..."
4,6c4168dd7b40e7b90275543ad3d99b0d,4,Uşaqlıq və gənclik illərini Dağlıq Qarabağ Mux...,15518,15730,Həyatı,"[{'start': 15516, 'end': 15545}, {'start': 156..."

                   link  startIdx     text  endIdx section  sentid
0  file:///wiki/13_iyun     16772  13 iyun   16823    Lead       0
1     file:///wiki/1959     16824     1959   16866    Lead       0
2    file:///wiki/Semey     17070    Semey   17115    Lead       0

Processing language: azb
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/azb
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.086843490600586
Writing sentences and links v2
Time taken for v2: 6.32117486000061

,md5,id,text,startIdx,endIdx,section,locList
0,0703378262233d60034da325a758b379,0,Autonomous region of عراقشابلون:SHORTDESC:Auto...,66085,91010,Lead,"[{'start': 66085, 'end': 66110}, {'start': 663..."
1,b953968e82942dff8a014ccc130e7ef6,1,عراق کوردوستانی‌نین بؤلگه‌سل موختار حؤکومتی (ک...,91011,91699,Lead,"[{'start': 91010, 'end': 91011}, {'start': 910..."
2,81d0c37e0070e7d26d0c85c62af018c0,2,عراق,91979,92060,بیرده باخ,"[{'start': 91978, 'end': 91979}, {'start': 920..."
3,f5dcf6cfd36c0a71c0e070ffaa6cadc1,3,قایناق خطاسی برچسب &lt;ref&gt; برای گروهی به ن...,137485,137728,قایناقلار,"[{'start': 137484, 'end': 137485}, {'start': 1..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D9%81%D8%A7%D8%B1%D8%B3_%D8%AF%D...,38474,فارسجا,38568,Lead,0
1,file:///wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86,38608,ایران,38678,Lead,0
2,file:///wiki/%D8%B3%DB%8C%D8%B3%D8%AA%D8%A7%D9...,38681,سیستان و بلوچیستان اوستانیندا,38907,Lead,0

Processing language: ba
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ba
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 11.25321364402771
Writing sentences and links v2
Time taken for v2: 10.824209451675415

,md5,id,text,startIdx,endIdx,section,locList
0,2e7452d111f69fe2aa86b79f26ba4724,0,"Люцернала шахмат олимпиадаһы , 1982",64968,65577,Lead,"[{'start': 64967, 'end': 64968}, {'start': 655..."
1,9b9068d55c355cbdbabbebb5123bc20a,1,Бөтә донъя шахмат олимпиадаһы (рус.&nbsp;Всеми...,65578,66098,Lead,"[{'start': 65576, 'end': 65577}, {'start': 655..."
2,0d8462dd3f296778bc6054b460798833,2,"Был ярыштар 1927 йылдан алып үткәрелә, 1940 йы...",66099,66191,Lead,"[{'start': 66097, 'end': 66190}]"
3,2aae9910e1f191032fb3eac3557f2e27,3,Төп приз сифатында күсмә Гамильтон-Рассел алты...,66192,66302,Lead,"[{'start': 66190, 'end': 66301}]"
4,0bdf2aafe9a88af061267ed679932335,4,Һәр матч 4 таҡтала үтә.,66303,66326,Lead,"[{'start': 66301, 'end': 66325}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%A0%D1%83%D1%81_%D1%82%D0%B5%D...,64415,рус.,64520,Lead,1
1,file:///wiki/%D0%A5%D0%B0%D0%BB%D1%8B%D2%A1-%D...,64594,ФИДЕ,64809,Lead,1
2,https://ru.wikipedia.org/wiki/%D0%9A%D0%BD%D0%...,65239,ru:Книга:Шахматный словарь,65487,Әҙәбиәт,2
3,https://ru.wikipedia.org/wiki/%D0%9A%D0%BD%D0%...,65514,ru:Книга:Шахматы. Энциклопедический словарь,65888,Әҙәбиәт,4
4,https://ru.wikipedia.org/wiki/%D0%90%D1%80%D1%...,67187,Wayback Machine,67381,Һылтанмалар,9

Processing language: bar
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/bar
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.8872385025024414
Writing sentences and links v2
Time taken for v2: 2.033029079437256

,md5,id,text,startIdx,endIdx,section,locList
0,3c8f4c313ec9be93388897460eb0ed95,0,Glasofen is a Stadttei vo Marktheidenfeld im u...,44888,45241,Lead,"[{'start': 44887, 'end': 44888}, {'start': 448..."
1,5a37c849b84a548dd9eb92c88116513c,1,Da topographisch hechsde Punkt vom Oatsteil be...,45402,46332,Geografie,"[{'start': 45401, 'end': 45402}, {'start': 454..."
2,1f0301cd5a16639db40e92e962d2dcc6,2,Nebn am Oat Glasofen bestäd da Stodtei no aus ...,46333,46448,Geografie,"[{'start': 46331, 'end': 46378}, {'start': 464..."
3,043f41d023fd180c223e4d2b6a26a9e0,3,Nochbargemarkunga im Uahzeigrsinn im Noadn ofa...,46536,47093,Geografie,"[{'start': 46535, 'end': 46536}, {'start': 465..."
4,5f5135cec7c04af5489980cdd5ffc0b0,4,Im Westn vo da Gemarkung entspringt da nerdlic...,47192,47415,Geografie,"[{'start': 47191, 'end': 47192}, {'start': 471..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/New_York,42655,New York,42729,Lead,2
1,file:///wiki/Vereinigte_Staaten,42737,amerikanischa,42836,Lead,2
2,file:///wiki/Internet_Movie_Database,43617,Internet Movie Database,43716,Im Netz,4
3,file:///wiki/Vorlog:Normdaten#Kopiervorlage,44342,Typ fehlt,44427,Im Netz,6

Processing language: be
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/be
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 10.222092151641846
Writing sentences and links v2
Time taken for v2: 10.350221157073975

,md5,id,text,startIdx,endIdx,section,locList
0,acdd79a6ec25153850c11da29a73ced7,0,"Дагледжаная версія гэтай старонкі, зацверджана...",41037,42623,Lead,"[{'start': 41037, 'end': 41055}, {'start': 410..."
1,0998855488752f31474e07f967fb6158,1,"Czapska, M. Europa w rodzinie.",42772,42934,Літаратура,"[{'start': 42771, 'end': 42772}, {'start': 428..."
2,97b73ae5547cc9cce22d29b2bf1d7813,2,Czas odmieniony / M. Czapska.,42935,42964,Літаратура,"[{'start': 42933, 'end': 42963}]"
3,63720de98471a8c6b94dab65ceee33a4,3,"— Kraków&nbsp;: Znak, 2014.",42965,42992,Літаратура,"[{'start': 42963, 'end': 42991}]"
4,a16a4d81ed3327e0aa3721fe05f61f6c,4,— 384 s.,42993,43011,Літаратура,"[{'start': 42991, 'end': 43000}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%86%D0%BB%D1%8C%D1%8F_%D0%A0%D...,40874,Ілья Раманавіч Прыгожын,41078,Вядомыя носьбіты,1
1,file:///wiki/%D0%9D%D0%BE%D0%B1%D0%B5%D0%BB%D0...,41168,Нобелеўскай прэміі па хіміі,41399,Вядомыя носьбіты,1
2,file:///wiki/%D0%AF%D1%9E%D0%B3%D0%B5%D0%BD_%D...,41417,Яўген Віктаравіч Прыгожын,41637,Вядомыя носьбіты,2
3,file:///wiki/%D0%9F%D0%92%D0%9A_%C2%AB%D0%92%D...,41717,ПВК «Вагнер»,41838,Вядомыя носьбіты,2
4,file:///wiki/%D0%93%D0%B5%D1%80%D0%BE%D0%B9_%D...,41840,Герой Расійскай Федэрацыі,42060,Вядомыя носьбіты,2

Processing language: bg
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/bg
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 9.416420698165894
Writing sentences and links v2
Time taken for v2: 10.20378589630127

,md5,id,text,startIdx,endIdx,section,locList
0,c1d01f0c6b5baca1d4da297a3a05de8d,0,Ocean surface currents,70255,70699,Lead,"[{'start': 70254, 'end': 70255}, {'start': 706..."
1,511dd992a2923f21508524373d682ef9,1,Всичките течения в света на океанска карта.,70700,71127,Lead,"[{'start': 70698, 'end': 70699}, {'start': 710..."
2,c3dfe8065c58455f86ae4396ca6494a4,2,Визуализация на световните океански течения от...,71128,74346,Lead,"[{'start': 71126, 'end': 71127}, {'start': 741..."
3,ab7e8066d44bf3743be2acb9030b78a7,3,Океански течения (или морски течения) се нарич...,74347,74608,Lead,"[{'start': 74345, 'end': 74346}, {'start': 743..."
4,dddcec7c50915c033c60b48ff4d60c4d,4,"Предизвикват се от гравитационни, приливообраз...",74609,74741,Lead,"[{'start': 74607, 'end': 74740}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%9E%D0%BA%D0%B5%D0%B0%D0%BD,74462,океан,74532,Lead,3
1,file:///wiki/%D0%A1%D0%BA%D0%BE%D1%80%D0%BE%D1...,74820,скоростта,74908,Lead,5
2,file:///wiki/%D0%97%D0%B5%D0%BC%D1%8F,75056,Земята,75120,Lead,5
3,file:///wiki/%D0%9A%D0%BE%D1%80%D0%B8%D0%BE%D0...,75213,Кориолисова сила,75366,Lead,6
4,file:///wiki/%D0%93%D1%8A%D0%BB%D1%84%D1%81%D1...,75574,Гълфстрийм,75684,Lead,8

Processing language: br
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/br
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.1785247325897217
Writing sentences and links v2
Time taken for v2: 2.4297523498535156

,md5,id,text,startIdx,endIdx,section,locList
0,44d5f03806075798927e616a16f58081,0,Camino zo un anv-lec'h italianek ha spagnolek.,38741,38934,Lead,"[{'start': 38740, 'end': 38741}, {'start': 387..."
1,11623613233dc1906bf40d2bc3807dbd,1,&nbsp;Italia,38935,39343,Lead,"[{'start': 38933, 'end': 38934}, {'start': 392..."
2,7f932bff0a52b249c13fa19cd8e3d8ee,2,Kumunioù,39348,39375,Lead,"[{'start': 39347, 'end': 39348}, {'start': 393..."
3,341ff3e8d76fc2acdda94172be0130ec,3,"Camino (Italia), e Proviñs Alessandria",39376,39560,Lead,"[{'start': 39374, 'end': 39375}, {'start': 394..."
4,19275f8528cf2be9861a0206c4370356,4,"Camino al Tagliamento, e Proviñs Udine",39561,39746,Lead,"[{'start': 39559, 'end': 39560}, {'start': 396..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Deiziadur_gregorian,81153,deiziadur gregorian,81240,Lead,0
1,file:///wiki/Roazhon,81611,Roazhon,81662,Darvoudoù,1
2,file:///wiki/Skol-veur_Roazhon,81973,skol-veur Roazhon II,82057,Darvoudoù,2
3,file:///wiki/Unvaniezh_ar_Gelennerien_Brezhoneg,82106,UGB,82207,Darvoudoù,2
4,file:///wiki/Douarnenez,82577,Douarnenez,82637,Darvoudoù,5

Processing language: bs
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/bs
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.769282102584839
Writing sentences and links v2
Time taken for v2: 4.2182700634002686

,md5,id,text,startIdx,endIdx,section,locList
0,501494dcef8c62e13e950941702bb26b,0,"Pregledana verzija ove stranice, odobrena dana...",82747,85155,Lead,"[{'start': 82747, 'end': 82765}, {'start': 827..."
1,25419da0c8dabdf8e3437f3cbbd94fd6,1,8.,85348,85403,Događaji,"[{'start': 85347, 'end': 85348}, {'start': 854..."
2,53b96a9d1731e515a91d9faff8dc62f2,2,januar – Pristalice bivšeg predsjednika Brazil...,85404,86840,Događaji,"[{'start': 85402, 'end': 85409}, {'start': 854..."
3,4363b12ae39947f045a4fb5fad740dc8,3,6.,86903,86960,Događaji,"[{'start': 86902, 'end': 86903}, {'start': 869..."
4,a9e655d852e269d9f8ffd44460c3b6d0,4,februar,86961,86972,Događaji,"[{'start': 86959, 'end': 86967}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Avion,58985,aviona,59031,Lead,3
1,file:///wiki/Prototip,59142,prototip,59196,Lead,5
2,file:///wiki/Radar,59635,radarskih talasa,59691,Lead,10
3,file:///wiki/Panama,60038,Panami,60086,Lead,13
4,file:///wiki/Northrop-Grumman_B-2,61678,Northrop-Grumman B-2,61788,Također pogledajte,18

Processing language: ca
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ca
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 31.94068670272827
Writing sentences and links v2
Time taken for v2: 23.62640690803528

,md5,id,text,startIdx,endIdx,section,locList
0,73587c571d1d902c5fddcec5f3f97891,0,La medalla d'Egipte (1882–1889) (anglès: Egypt...,40004,40648,Lead,"[{'start': 40003, 'end': 40004}, {'start': 400..."
1,3270ecffd5c1d52f9c6f51545f6dbce2,1,El ressentiment per l'augment de la participac...,40649,41048,Lead,"[{'start': 40647, 'end': 40648}, {'start': 406..."
2,a479b23a42d1b9b68afdab049aa0afd9,2,La intervenció militar britànica va ser com a ...,41049,41143,Lead,"[{'start': 41047, 'end': 41142}]"
3,1cb872ecc120392ad59ed1a273b0b8ca,3,"Un cop a Egipte, els britànics es van implicar...",41144,41344,Lead,"[{'start': 41142, 'end': 41268}, {'start': 413..."
4,ca995b344901ee0c9b85c7fc9c48d3c0,4,Tots els destinataris de la Medalla d'Egipte t...,41345,41617,Lead,"[{'start': 41343, 'end': 41344}, {'start': 413..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/FCB,124838,FCB,124897,Lead,0
1,file:///wiki/Catalunya,196676,Catalunya,196733,Lead,3
2,file:///wiki/Barcelona,197007,Barcelona,197064,Lead,4
3,file:///wiki/29_de_novembre,197068,29 de novembre,197140,Lead,4
4,file:///wiki/1899,197144,1899,197186,Lead,4

Processing language: ce
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ce
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 4.111337900161743
Writing sentences and links v2
Time taken for v2: 4.16874885559082

,md5,id,text,startIdx,endIdx,section,locList
0,0a91278a87624a549244b52a365b050f,0,"Хьаьжжина хӀокху агӀон верси, бакъйинарг 2023...",53022,53730,Lead,"[{'start': 53022, 'end': 53032}, {'start': 530..."
1,c545b3e321c59c8eefe214605fe0b726,1,Пестово (оьрс. Пестово) — Российн Федерацин Но...,61987,62587,Lead,"[{'start': 61986, 'end': 61987}, {'start': 619..."
2,e388395c2fd0bc46e3199f14306b1ab6,2,"Кхузахь климат барамера континенталан, хӀордан...",63521,63698,Климат,"[{'start': 63520, 'end': 63521}, {'start': 635..."
3,4cb28e282d0b594671fb647b972a8492,3,"Ӏай кхуьлина хенан хӀоттам хуьлу, йукъа-кара (...",63699,63779,Климат,"[{'start': 63697, 'end': 63778}]"
4,0b7adff9cf20beb2ff55496c44bf343a,4,Ӏа дохделча ша хьокху.,63780,63802,Климат,"[{'start': 63778, 'end': 63801}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%9F%D0%B5%D1%81%D1%82%D0%BE%D0...,40547,Пестово,40633,Lead,0
1,file:///wiki/%D0%9F%D0%B5%D1%81%D1%82%D0%BE%D0...,40643,Пестово (Боровенковскан йуьртан меттиг),40960,Lead,1
2,file:///wiki/%D0%9F%D0%B5%D1%81%D1%82%D0%BE%D0...,40970,Пестово (Домшинскан йуьртан меттиг),41255,Lead,2
3,file:///wiki/%D0%9F%D0%B5%D1%81%D1%82%D0%BE%D0...,41265,Пестово (Кулотинскан йуьртан меттиг),41558,Lead,3
4,file:///wiki/%D0%9F%D0%B5%D1%81%D1%82%D0%BE%D0...,41568,Пестово (Наговскан йуьртан меттиг),41845,Lead,4

Processing language: cs
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/cs
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 9.417100429534912
Writing sentences and links v2
Time taken for v2: 10.170560121536255

,md5,id,text,startIdx,endIdx,section,locList
0,455b3365b64829fb7df806390955f662,0,Filmová výchova (v českém vzdělávacím systému ...,38290,38534,Lead,"[{'start': 38290, 'end': 38305}, {'start': 383..."
1,7a527be5635f909e449947912a626b8a,1,Podle Asociace pro filmovou a audiovizuální vý...,38535,38728,Lead,"[{'start': 38534, 'end': 38598}, {'start': 386..."
2,0e4dacdccb3572c02bfb39ca38f2ee6b,2,Film není tedy pouhým prostředkem výuky nebo o...,38729,38882,Lead,"[{'start': 38727, 'end': 38802}, {'start': 388..."
3,e30ee415f061b7c5f4217683c40c8ed2,3,Pojem filmová výchova se používá nejčastěji sa...,38994,39175,Terminologie,"[{'start': 38993, 'end': 38994}, {'start': 389..."
4,fb5aec15c29738480cc34c566e278c10,4,"počítačových her, videomappingu nebo VJ-ingu).",39176,39394,Terminologie,"[{'start': 39174, 'end': 39175}, {'start': 392..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/N%C3%A1pov%C4%9Bda:Edita%C4%8Dn%C...,36990,editačním konfliktům,37112,Lead,1
1,file:///wiki/Latina,38066,latinského,38118,Lead,6
2,file:///wiki/Venkov,38187,venkovský,38238,Lead,6
3,file:///wiki/%C4%8Ce%C5%A1tina,38243,český,38302,Lead,6
4,file:///wiki/Literatura,38303,literární,38362,Lead,6

Processing language: cv
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/cv
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 8.743923425674438
Writing sentences and links v2
Time taken for v2: 4.457268953323364

,md5,id,text,startIdx,endIdx,section,locList
0,04de41cf0ff9f43b9cc826cf107ff8b3,0,Касакстан (каз. Qazaqstan) — Азире вырнаçнă па...,116025,116292,Lead,"[{'start': 116024, 'end': 116025}, {'start': 1..."
1,531f01038e6f1ceb152473e39e72c13a,1,"Раççейпе, Китайпа, Кăркăсстанпе, Туркменистанп...",116293,116874,Lead,"[{'start': 116291, 'end': 116292}, {'start': 1..."
2,c1a95245abf4221caffe94252cca9aea,2,"Касакстанăн чылай пайĕ тӳремлĕ вырăн, мальенпе...",117172,117269,Тавралăх,"[{'start': 117171, 'end': 117172}, {'start': 1..."
3,df8a3bf6ab9b6e594f0aae4aa797b358,3,Кăркăсстанпе чикеленнĕ вырăнти сăртсен çӳллĕшĕ...,117270,117350,Тавралăх,"[{'start': 117268, 'end': 117349}]"
4,68c7c719fda13c51ebea92885fe38b67,4,Касакстанăн çурçĕр пайĕ Анăçри Çĕпĕр тӳремне й...,117351,117638,Тавралăх,"[{'start': 117349, 'end': 117374}, {'start': 1..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%9A%D0%B0%D0%B7%D0%B0%D1%85_%D...,116046,каз.,116152,Lead,0
1,file:///wiki/%D0%90%D0%B7%D0%B8,116216,Азире,116272,Lead,0
2,file:///wiki/%D0%A0%D0%B0%C3%A7%C3%A7%D0%B5%D0%B9,116292,Раççейпе,116392,Lead,1
3,file:///wiki/%D0%9A%D0%B8%D1%82%D0%B0%D0%B9,116394,Китайпа,116486,Lead,1
4,file:///wiki/%D0%9A%C4%83%D1%80%D0%BA%C4%83%D1...,116488,Кăркăсстанпе,116600,Lead,1

Processing language: cy
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/cy
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.4244492053985596
Writing sentences and links v2
Time taken for v2: 3.5117318630218506

,md5,id,text,startIdx,endIdx,section,locList
0,f193db12b0112a2d84f00c5dc69830c6,0,Ffilm ddrama rhamantus gan y cyfarwyddwr Georg...,51965,52264,Lead,"[{'start': 51964, 'end': 51965}, {'start': 519..."
1,54167110a46ab7a3d7218264b1950811,1,Teitl gwreiddiol y ffilm oedd Camille ac fe'i ...,52265,52691,Lead,"[{'start': 52263, 'end': 52294}, {'start': 523..."
2,fcf700eb3da1ae7175be64056ee60ce9,2,Sgwennwyd y sgript yn wreiddiol yn Saesneg a h...,52692,52856,Lead,"[{'start': 52690, 'end': 52726}, {'start': 527..."
3,03ab30b2d08df3f09dd9d3d20935ff62,3,Mae'n ffilm a ddosbarthwyd drwy fideo ar alw.,52857,52956,Lead,"[{'start': 52855, 'end': 52888}, {'start': 529..."
4,c1f65ea46f39c3536ea55bf7915c72dc,4,"Y prif actorion yn y ffilm hon yw Greta Garbo,...",52957,53293,Lead,"[{'start': 52955, 'end': 52956}, {'start': 529..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Crys-T,48501,Crys-T,48549,Lead,0
1,file:///wiki/Is-Arlywydd_yr_Unol_Daleithiau,49016,Is-Arlywydd yr Unol Daleithiau,49136,Lead,1
2,file:///wiki/Mike_Pence,49138,Mike Pence,49198,Lead,1
3,file:///wiki/Damcaniaeth_gydgynllwyniol,49581,ddamcaniaethau cynllwynio,49688,Lead,3
4,file:///wiki/Asgell_dde,49689,asgell dde,49769,Lead,3

Processing language: da
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/da
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.500870704650879
Writing sentences and links v2
Time taken for v2: 7.534380197525024

,md5,id,text,startIdx,endIdx,section,locList
0,31e0e7a11bb5315661c448a3785efb07,0,Stormfloden 2023 ramte i det sydlige Danmark o...,40873,41047,Lead,"[{'start': 40872, 'end': 40873}, {'start': 408..."
1,9f5a3c516348d36fdefac95fac395b4d,1,oktober 2023.[1][2] Den ramte kysterne langs Ø...,41048,41950,Lead,"[{'start': 41046, 'end': 41060}, {'start': 411..."
2,ce791dc71858935646657b5e400b76e1,2,Stormfloden forventedes især at ramme Hadersle...,42052,42797,Danmark,"[{'start': 42051, 'end': 42052}, {'start': 420..."
3,1a1031304d3cded06c2340094a91ba6e,3,Naturskaderådet afgjorde 21.,42798,42898,Danmark,"[{'start': 42796, 'end': 42797}, {'start': 428..."
4,d30c10530c1e5c12e8c6d0f25ac44271,4,"oktober 2023, at der var stormflod i flere del...",42899,43032,Danmark,"[{'start': 42897, 'end': 42956}, {'start': 430..."

                             link  startIdx       text  endIdx section  sentid
0              file:///wiki/Latin     48975      latin   49020    Lead       0
1  file:///wiki/Italiensk_(sprog)     49037  italiensk   49110    Lead       0
2       file:///wiki/Tysk_(sprog)     49125       tysk   49183    Lead       0
3          file:///wiki/Dalmatien     49223  Dalmatien   49280    Lead       0
4           file:///wiki/Kroatien     49283   Kroatien   49337    Lead       0

Processing language: de
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/de
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 37.98034167289734
Writing sentences and links v2
Time taken for v2: 37.582563161849976

,md5,id,text,startIdx,endIdx,section,locList
0,718a519b7ed105dae98468cc8729badd,0,"Eine gesichtete Version dieser Seite, die am 28.",9603,9782,Lead,"[{'start': 9603, 'end': 9608}, {'start': 9732,..."
1,d848d35888d13effef3c255400ace663,1,"Dezember 2018 freigegeben wurde, basiert auf d...",9783,10478,Lead,"[{'start': 9782, 'end': 9796}, {'start': 9800,..."
2,67f0022914d3e26b7925f3e879337f65,2,Sa'd allah Abd al-Qadir Lutfi al-Dschabiri (ar...,10479,11133,Lead,"[{'start': 10477, 'end': 10478}, {'start': 104..."
3,de02c1f7320f289db5b6fd137b105ca6,3,Der Sunnit Dschabiri wurde im damals osmanisch...,11134,11251,Lead,"[{'start': 11132, 'end': 11133}, {'start': 111..."
4,829f96938fa93c8ce94b65d1fa664ba1,4,Er hatte fünf Geschwister und besuchte in Alep...,11252,11347,Lead,"[{'start': 11250, 'end': 11346}]"

                   link  startIdx     text  endIdx section  sentid
0  file:///wiki/5._Juni      9659  5. Juni    9710    Lead       2
1     file:///wiki/1905      9711     1905    9753    Lead       2
2   file:///wiki/London      9757   London    9805    Lead       2
3  file:///wiki/24._Mai      9809  24. Mai    9860    Lead       3
4     file:///wiki/1996      9861     1996    9903    Lead       3

Processing language: el
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/el
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 8.881654500961304
Writing sentences and links v2
Time taken for v2: 9.48942255973816

,md5,id,text,startIdx,endIdx,section,locList
0,9dafac0d948c97e43f0bcf5ba52f2e61,0,Θάνατοι το 2023&nbsp;: Ιανουάριος - Φεβρουάριο...,57635,59940,Lead,"[{'start': 57635, 'end': 57650}, {'start': 576..."
1,15437087f85144e940736a3246230529,1,Παρατίθενται παρακάτω θάνατοι σημαντικών προσώ...,59951,60163,Lead,"[{'start': 59950, 'end': 59951}, {'start': 599..."
2,0d077c3581ca6fb6dab2e9fc1ae5f5ea,2,"Των ονομάτων ακολουθούν η ηλικία, η ιδιότητα, ...",60164,60323,Lead,"[{'start': 60162, 'end': 60322}]"
3,31c32cc8978a15a76afeda59a61dc5ec,3,"Καντρί Αμπού Μπακρ, 70, Παλαιστίνιος πολιτικός...",60492,60954,1 Ιουλίου,"[{'start': 60491, 'end': 60492}, {'start': 607..."
4,37b87090a0fa7be0d4029c93d9449f0e,4,"Ρομπέρτο Αρτέμιο Γκραμάχο, 75, Αργεντίνος ποδο...",60955,61812,1 Ιουλίου,"[{'start': 60953, 'end': 60954}, {'start': 611..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%CE%97_%CE%95%CE%BB%CE%BB%CE%AC%C...,72643,Η Ελλάδα στον Α' Βαλκανικό πόλεμο,72909,Lead,0
1,file:///wiki/%CE%92%CE%B1%CE%BB%CE%BA%CE%B1%CE...,73078,Βαλκανικοί Πόλεμοι,73247,Lead,1
2,file:///wiki/%CE%A4%CE%BF%CF%85%CF%81%CE%BA%CE...,102594,τουρκικά,102732,Lead,2
3,file:///wiki/%CE%A3%CE%B5%CF%81%CE%B2%CE%B9%CE...,102792,σερβικά,102922,Lead,2
4,file:///wiki/%CE%92%CE%BF%CF%85%CE%BB%CE%B3%CE...,102979,βουλγαρικά,103133,Lead,2

Processing language: en
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/en
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 15.414081573486328
Writing sentences and links v2
Time taken for v2: 15.253468751907349

,md5,id,text,startIdx,endIdx,section,locList
0,b618f386f2310c33ab1aff5b8fa03aea,0,Drone attacks on bases in Iraq,46226,46262,Lead,"[{'start': 46226, 'end': 46256}]"
1,7d9ca2c7ba20284ff33e2ab26b876b86,1,"On 18 October 2023, American military bases in...",151295,151610,Lead,"[{'start': 151294, 'end': 151295}, {'start': 1..."
2,6952d1ff6bdf29aa162ddb6cc1e459bb,2,Pentagon officials insisted that there are few...,151611,152515,Lead,"[{'start': 151609, 'end': 151610}, {'start': 1..."
3,d9e733c03098f8e1d9f669c6b3e7d345,3,"On 18 October 2023, amid the 2023 Israel–Hamas...",152659,153303,2023 Al-Asad air base attack,"[{'start': 152658, 'end': 152659}, {'start': 1..."
4,bf85f1d05fb54f50983693b5108c747a,4,"The next day, a false alarm in the airbase cau...",153304,153826,2023 Al-Asad air base attack,"[{'start': 153302, 'end': 153303}, {'start': 1..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Diary_of_a_Wimpy_Kid:_Rodrick_Rul...,49460,Diary of a Wimpy Kid: Rodrick Rules,49619,Lead,2
1,file:///wiki/Diary_of_a_Wimpy_Kid:_Dog_Days_(f...,49638,Diary of a Wimpy Kid: Dog Days,49772,Lead,2
2,file:///wiki/Supernatural_(American_TV_series),49788,Supernatural,49896,Lead,2
3,file:///wiki/The_Marine_4:_Moving_Target,49912,The Marine 4: Moving Target,50023,Lead,2
4,file:///wiki/Star_Trek_Beyond,50039,Star Trek Beyond,50117,Lead,2

Processing language: eo
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/eo
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.396453142166138
Writing sentences and links v2
Time taken for v2: 5.630243539810181

,md5,id,text,startIdx,endIdx,section,locList
0,fade66f5b1163dd730ab9034bc7b1d89,0,"Reviziita versio de ĉi tiu paĝo, aprobita je 2...",41774,41965,Lead,"[{'start': 41774, 'end': 41790}, {'start': 417..."
1,c003640e76beb954b44d63f2c60aea1a,1,"2023, estis bazita sur ĉi tiu versio.ISO",41966,51766,Lead,"[{'start': 41965, 'end': 41970}, {'start': 419..."
2,fd03b1abae5a644da303cbd2a39cfa74,2,Belsito estas komunumo de Italio.,51767,51918,Lead,"[{'start': 51765, 'end': 51766}, {'start': 517..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Gregoria_kalendaro,91824,Gregoria kalendaro,91908,Lead,0
1,file:///wiki/Romio,92085,Romio,92130,Eventoj,3
2,file:///wiki/-42,92139,-42,92178,Eventoj,4
3,file:///wiki/Dua_triumviraro,92180,Dua triumviraro,92255,Eventoj,4
4,file:///wiki/Marko_Antonio,92257,Marko Antonio,92326,Eventoj,4

Processing language: es
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/es
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 28.39527440071106
Writing sentences and links v2
Time taken for v2: 28.775866746902466

,md5,id,text,startIdx,endIdx,section,locList
0,8f1828f27f18f1e7bd5b63aa67107a60,0,Ilustres ignorantes es un programa de televisi...,55309,55730,Lead,"[{'start': 55308, 'end': 55309}, {'start': 553..."
1,b9422d02d369529d8349e8a095d87d96,1,El programa empezó a emitirse el 1 de noviembr...,55731,55965,Lead,"[{'start': 55729, 'end': 55822}, {'start': 559..."
2,b5b56838921ec75e6d3b52867a88da09,2,Desde el 29 de abril de 2016 se emite en la pl...,55966,56235,Lead,"[{'start': 55964, 'end': 56020}, {'start': 560..."
3,c857327731c26eee41d24e2367652acb,3,Las dos primeras temporadas se grabaron en Vil...,56236,56732,Lead,"[{'start': 56234, 'end': 56390}, {'start': 564..."
4,344755ee8ceef18b9062dd1e599667bc,4,"En cada programa, se presenta a dos invitados ...",56733,56986,Lead,"[{'start': 56731, 'end': 56732}, {'start': 567..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Anexo:Expediciones_a_la_Estaci%C3...,51048,misión,51199,Lead,1
1,file:///wiki/Estaci%C3%B3n_Espacial_Internacional,51223,Estación Espacial Internacional,51351,Lead,1
2,file:///wiki/Soyuz_MS-23,51434,Soyuz MS-23,51497,Lead,2
3,file:///wiki/SpaceX_Crew-7,51561,SpaceX Crew-7,51630,Lead,2
4,file:///wiki/Soyuz_MS-24,51636,Soyuz MS-24,51699,Lead,2

Processing language: et
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/et
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 26.134008407592773
Writing sentences and links v2
Time taken for v2: 27.091001510620117

,md5,id,text,startIdx,endIdx,section,locList
0,832a0624485bd2a644fdfb8d8a0c831b,0,Siin on loetletud sõjanduse mõisteid.,32879,32971,Lead,"[{'start': 32879, 'end': 32897}, {'start': 329..."
1,814cce1f53ddc53a9e2de175831fdcab,1,"Sõdu on loetletud sõdade loendis, lahinguid la...",32972,33572,Lead,"[{'start': 32971, 'end': 32972}, {'start': 329..."
2,7a2cf72c89bf30a9461e1a832fe0588e,2,# A B C D E F G H I J K L M N O P Q R S Š Z Ž ...,33645,34282,Lead,"[{'start': 33644, 'end': 33645}, {'start': 336..."
3,1d41e6f55521cdba4fc73febd09d2eb4,3,1.,34416,34488,Lead,"[{'start': 34415, 'end': 34416}, {'start': 344..."
4,ccf312db591ecd655b6afc04794f9347,4,järgu kapten,34489,34510,Lead,"[{'start': 34487, 'end': 34500}]"

                       link  startIdx  text  endIdx section  sentid
0         file:///wiki/2023     47087  2023   47129    Lead       0
1  file:///wiki/Surnud_2013     47310    ◄◄   47364    Lead       2
2  file:///wiki/Surnud_2018     47372     ◄   47425    Lead       2
3  file:///wiki/Surnud_2019     47433  2019   47489    Lead       2
4  file:///wiki/Surnud_2020     47497  2020   47553    Lead       2

Processing language: eu
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/eu
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.250663757324219
Writing sentences and links v2
Time taken for v2: 6.351395130157471

,md5,id,text,startIdx,endIdx,section,locList
0,75fe827e2a656fe62ebc0c3084f3ae16,0,Bigarren Mundu Gerraren aurreko gertaeren kron...,49310,49734,Lead,"[{'start': 49310, 'end': 49362}, {'start': 493..."
1,8b621c62e1a2fd15c1ec8bcf65bdb7b8,1,Urriaren 8: Japoniar agenteek Koreako Min erre...,50674,51470,1895,"[{'start': 50673, 'end': 50674}, {'start': 506..."
2,8ed1c521a23b91cd21a2d1a18af6e4b3,2,Irailaren 5: Portsmoutheko itunak Errusia-Japo...,51527,51767,1905,"[{'start': 51526, 'end': 51527}, {'start': 515..."
3,a120adeb11fed22955b1fa160cb39b2b,3,Japoniako Inperioari Hego Mantxuriako Trenbide...,51768,52142,1905,"[{'start': 51766, 'end': 51788}, {'start': 519..."
4,d9ff926790cbceaa51dd5bde5b1a38f6,4,Abuztuaren 22-29: Japoniak Korea anexionatu zu...,52199,52637,1910,"[{'start': 52198, 'end': 52199}, {'start': 522..."

Empty DataFrame
Columns: []
Index: []

Processing language: fa
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/fa
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.074055910110474
Writing sentences and links v2
Time taken for v2: 6.803395986557007

,md5,id,text,startIdx,endIdx,section,locList
0,7461c3b1d2e7c9ce994b27f40c4c4263,0,خیانت تصاویر (به فرانسوی: La Trahison des imag...,50126,51504,Lead,"[{'start': 50125, 'end': 50126}, {'start': 501..."
1,94d40ce4423dc76964242613c7f12161,1,این نگاره یک پیپ را نشان می‌دهد که در نگاه اول...,51505,51668,Lead,"[{'start': 51503, 'end': 51504}, {'start': 515..."
2,9f6490b1d2e1d4f6120122628d007aec,2,ماگریت در پایین تصویر متنی (به فرانسوی: Ceci n...,51669,52030,Lead,"[{'start': 51667, 'end': 51699}, {'start': 518..."
3,472601abaf220e3a398de9797c6699d2,3,این نقاشی، یک «پیپ» (واقعی) نیست بلکه «تصویری ...,52031,52103,Lead,"[{'start': 52029, 'end': 52102}]"
4,e71491755da025dc054d85ef1f2ff1c8,4,این اثر آغازی بود بر تأثیر زنجیره‌وار آثار و ا...,52104,52372,Lead,"[{'start': 52102, 'end': 52161}, {'start': 522..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D9%86%D8%A7%D8%B5%D8%B1%D8%A7%D9...,38554,ناصرالدین شاه قاجار,38697,Lead,0
1,file:///wiki/%D8%A8%D9%84%D9%88%DA%86%D8%B3%D8...,38735,بلوچستان,38829,Lead,0
2,file:///wiki/%D8%A7%DB%8C%D8%A7%D9%84%D8%AA_%D...,38834,ایالت خیبر پختونخوا,39006,Lead,0
3,file:///wiki/%D8%A7%DB%8C%D8%A7%D9%84%D8%AA_%D...,39009,ایالت بلوچستان,39146,Lead,0
4,file:///wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86,39153,ایران,39223,Lead,0

Processing language: fi
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/fi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.044910430908203
Writing sentences and links v2
Time taken for v2: 7.276557445526123

,md5,id,text,startIdx,endIdx,section,locList
0,d8f29e314e2b2183b696df52ada9739c,0,"Katsottu versio tästä sivusta, joka hyväksytti...",9770,9969,Lead,"[{'start': 9770, 'end': 9785}, {'start': 9789,..."
1,0cf2d38b0c8886d1f4cea4ecd2e7f709,1,"syyskuuta 2023, perustui tähän versioon.Linkki...",9970,10565,Lead,"[{'start': 9969, 'end': 9984}, {'start': 9988,..."
2,72c7caac2758aa0542bd2dcda551829e,2,Termillä voidaan viitata myös päivittämättömii...,10566,10711,Lead,"[{'start': 10564, 'end': 10638}, {'start': 106..."
3,8538dcd53900835f82ba7132a2b54225,3,Toimimatonta linkkiä kutsutaan kuolleeksi link...,10712,10805,Lead,"[{'start': 10710, 'end': 10742}, {'start': 107..."
4,aaa83b1f34c1486cce84ce0afcaa13ec,4,Vuonna 2013 valmistuneessa tutkimuksessa havai...,12149,12407,Yleisyys,"[{'start': 12148, 'end': 12149}, {'start': 121..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/7._joulukuuta,15053,7. joulukuuta,15122,Lead,3
1,file:///wiki/1956,15123,1956,15165,Lead,3
2,file:///wiki/Michoac%C3%A1n,15312,Michoacán,15374,Lead,3
3,file:///wiki/14._joulukuuta,15377,14. joulukuuta,15449,Lead,4
4,file:///wiki/2019,15450,2019,15492,Lead,4

Processing language: fr
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/fr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 8.98384952545166
Writing sentences and links v2
Time taken for v2: 9.031708240509033

,md5,id,text,startIdx,endIdx,section,locList
0,90e48feb63da12435b5c6edd8965a9f9,0,«&nbsp;Hand&nbsp;» redirige ici.,78396,78432,Lead,"[{'start': 78395, 'end': 78396}, {'start': 783..."
1,f02e2abcee18ac8b72718e45dc81e7bc,1,"Pour les autres significations, voir Hand (hom...",78433,78683,Lead,"[{'start': 78431, 'end': 78469}, {'start': 785..."
2,b49b2084a9c5afc52a3ec9567d7aaae2,2,Handball,79085,79105,Lead,"[{'start': 79084, 'end': 79085}, {'start': 790..."
3,810df7d92da52edd5d7fb5dd7dbce023,3,Tir en extension à 6 mètres du parisien Nikola...,85372,85878,Lead,"[{'start': 85371, 'end': 85372}, {'start': 853..."
4,36b5c3fc04095544e67941f71544cac2,4,modifier,85879,86512,Lead,"[{'start': 85877, 'end': 85878}, {'start': 860..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Aide:Homonymie,36408,page d’homonymie,36482,Lead,0
1,file:///wiki/INS_Shishumar_(S44),38716,INS Shishumar (S44),38823,Domaine militaire,2
2,file:///wiki/Marine_indienne,38845,Marine indienne,38920,Domaine militaire,2
3,file:///wiki/Marine_sovi%C3%A9tique,39075,Marine soviétique,39161,Domaine militaire,3
4,file:///wiki/S44_(870),39178,S44 (870),39242,Domaine militaire,4

Processing language: fy
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/fy
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.166595935821533
Writing sentences and links v2
Time taken for v2: 4.868143320083618

,md5,id,text,startIdx,endIdx,section,locList
0,e74777afa10674e072d095a336dbd9b5,0,"Hippopotamus, meast Hippo, wie in jongereinsin...",32106,32294,Lead,"[{'start': 32106, 'end': 32118}, {'start': 321..."
1,282b52e96dcfb61fa7f10612bcffae64,1,By de iepening yn 1974 wiene optredens fan kab...,32295,32486,Lead,"[{'start': 32294, 'end': 32313}, {'start': 323..."
2,344785dff195c28800c5e832cca379b2,2,Foar dy tiid wie der al in groep jongeren dwaa...,32487,32559,Lead,"[{'start': 32485, 'end': 32558}]"
3,de3989877af51dc40403fa8e19320ee6,3,De aktiviteiten begûnen al yn 1968 op it Fuqfe...,32560,32633,Lead,"[{'start': 32558, 'end': 32632}]"
4,8cc5c9d2582ed017b0e5b3fbd9b95a3d,4,Letter wienen yn it JOK-gebou (letter troch br...,32634,32739,Lead,"[{'start': 32632, 'end': 32738}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Gewoan_jier_fan_snein_%C3%B4f,82483,Gregoriaanske kalinder foar 2023,82598,Lead,1
1,file:///wiki/1_jannewaris,82750,1,82805,Foarfallen,3
2,file:///wiki/Kroaasje,82808,Kroaasje,82862,Foarfallen,3
3,file:///wiki/Euro,82872,euro,82914,Foarfallen,3
4,file:///wiki/Muntienheid,82921,muntienheid,82984,Foarfallen,3

Processing language: ga
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ga
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.074666976928711
Writing sentences and links v2
Time taken for v2: 3.1645216941833496

,md5,id,text,startIdx,endIdx,section,locList
0,c638421e334e0053b9145633fdaf8c32,0,"Ba shagart, urscéalaí, drámadóir, aistritheoir...",42140,42963,Lead,"[{'start': 42138, 'end': 42140}, {'start': 421..."
1,4e1152a18a3fe66f0f93fae759c9121c,1,Bhí sé ina Ollamh le Fraincis i Maigh Nuad agu...,42965,43253,Lead,"[{'start': 42961, 'end': 42963}, {'start': 429..."
2,20d3e09db4c99afc58c9c564a66eedaf,2,Néal Maidine agus Tine Oíche (1964) agus An Br...,43254,43442,Lead,"[{'start': 43251, 'end': 43252}, {'start': 432..."
3,0e386a5075fd844fb4bd2b2be054534d,3,Ba cheannródaí i gcritic na Gaeilge é Breandán...,43444,43908,Lead,"[{'start': 43441, 'end': 43443}, {'start': 434..."
4,280ea8ac6604441600e3e0e0175d7427,4,Bhí an Doibhlineach ina Uachtarán ar Choláiste...,44003,44733,Saol,"[{'start': 44002, 'end': 44003}, {'start': 445..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Put%C3%B3g_mh%C3%B3r,66772,putóg,66837,Lead,8
1,file:///wiki/Faecas,66944,fhaecas,66993,Lead,9
2,file:///wiki/Cac,67005,cac,67044,Lead,9
3,file:///wiki/Gn%C3%ADomhaireacht_um_Chaomhn%C3...,67428,Gníomhaireacht um Chaomhnú Comhshaoil,67598,Lead,11
4,file:///wiki/Escherichia,68075,Escherichia,68139,Féach freisin,14

Processing language: gd
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/gd
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.807814121246338
Writing sentences and links v2
Time taken for v2: 1.8605008125305176

,md5,id,text,startIdx,endIdx,section,locList
0,7f65dbf77862ca69981b4672a51329b3,0,Teamplaid:Bliadhna-sèol,77840,77867,Lead,"[{'start': 77840, 'end': 77863}]"
1,701a4915b22720c03b396a7cc6634263,1,'S e bliadhna anns a' mhìosachan Griogarach a ...,77868,78006,Lead,"[{'start': 77867, 'end': 77890}, {'start': 779..."
2,4d253c2da4536b5457cb8f90e9d4769d,2,24 an Gearran: Ghabh feachdan na Ruis a-steach...,78083,78311,Tachartasan,"[{'start': 78082, 'end': 78083}, {'start': 781..."
3,dfc81b0fb10e0941d2a22b47bba651be,3,An Rìoghachd Aonaichte: Bliadhna nan triùir ph...,78312,78407,Tachartasan,"[{'start': 78310, 'end': 78311}, {'start': 783..."
4,e59bc9a9bbd8cef61ff133942d7fa57c,4,Chaidh [[Liz Truss] na prìomhaire agus ann an ...,78408,78569,Tachartasan,"[{'start': 78406, 'end': 78474}, {'start': 785..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Sg%C3%ACrean_ph%C3%A0rlamaid_West...,43776,sgìre Phàrlamaid Westminster,43924,Lead,0
1,file:///wiki/Cille_Bhr%C3%ACghde_an_Ear,44170,Cille Bhrìghde an Ear,44268,Lead,2
2,file:///wiki/Srath_Abhainn,44270,Srath Abhainn,44359,Lead,2
3,file:///wiki/Lios_Mo_Fh%C3%A8ige,44365,Lios Mo Fhèige,44462,Lead,2
4,file:///wiki/An_Ruadh-Ghleann_agus_Hamilton_an...,44581,An Ruadh-Ghleann agus Hamilton an Iar,44794,Lead,4

Processing language: gl
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/gl
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 10.765607357025146
Writing sentences and links v2
Time taken for v2: 11.174020051956177

,md5,id,text,startIdx,endIdx,section,locList
0,936ee847b0b0e805e41b07eb12f76964,0,A ecoloxía humana é unha ciencia que trata da ...,64183,64417,Lead,"[{'start': 64183, 'end': 64185}, {'start': 641..."
1,d4cba99d3c6784bf58e1041ee57a1c8a,1,"Aínda non é un campo da ciencia independente, ...",64418,64661,Lead,"[{'start': 64417, 'end': 64494}, {'start': 645..."
2,b7ff4c4e8437949bc08d345d8fdab707,2,A ecoloxía humana examina as causas dos proble...,64662,64905,Lead,"[{'start': 64660, 'end': 64775}, {'start': 648..."
3,e475e056a95c6d10d5556bf9d57fb848,3,Robert Park e Ernest Burgess utilizaron o term...,65008,65816,Historia,"[{'start': 65007, 'end': 65008}, {'start': 651..."
4,334adbae313fd6cf3f4ff7880b97d578,4,A ecoloxía humana examina cinco cuestións bási...,65817,65881,Historia,"[{'start': 65815, 'end': 65816}, {'start': 658..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Ciencia,64215,ciencia,64266,Lead,0
1,file:///wiki/Natureza,64301,a natureza,64357,Lead,0
2,file:///wiki/Ser_humano,64360,o home,64416,Lead,0
3,file:///wiki/Ciencias_naturais,64494,ciencias naturais,64575,Lead,1
4,file:///wiki/Ciencias_sociais,64581,ciencias sociais,64659,Lead,1

Processing language: gu
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/gu
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.475314140319824
Writing sentences and links v2
Time taken for v2: 2.8853371143341064

,md5,id,text,startIdx,endIdx,section,locList
0,43c8fc14e5c1b2f11c03ac57d51965ea,0,ઇમામશાહ બાવા દરગાહ (ઉર્દૂ امام شاہ باوا درگاہ)...,40472,40699,Lead,"[{'start': 40472, 'end': 40490}, {'start': 404..."
1,a4875fbf62407c72cc2a65775ed7a730,1,પીર ઇમામ શાહ બાવાએ લગભગ ૬૦૦ વર્ષ પહેલાં સતપંથ ...,40700,40784,Lead,"[{'start': 40699, 'end': 40783}]"
2,6f458d9e03955739b444fcfed1d4423e,2,તેમણે ધર્મોની સાર્વત્રિકતા પર સહિષ્ણુતા શીખવી ...,40785,41196,Lead,"[{'start': 40783, 'end': 40834}, {'start': 408..."
3,b56052d9be3ef23023ec87fc6c7f0751,3,ઇમામશાહ બાવા દરગાહે ઇસ્લામ અને હિન્દુ ધર્મ સિવ...,41470,41562,આંતરધર્મીય સંવાદિતા,"[{'start': 41469, 'end': 41470}, {'start': 414..."
4,a9900a68fa14885797bfa77c3e012889,4,"પીરાણા ગામમાં રહેતા તમામ ૧૮ સમુદાયો, જે જુદી જ...",41563,41811,આંતરધર્મીય સંવાદિતા,"[{'start': 41561, 'end': 41660}, {'start': 417..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%AA%87%E0%AA%A8%E0%AB%8D%E0%AA...,52333,IMDb,52561,બાહ્ય કડીઓ,35
1,file:///wiki/%E0%AA%97%E0%AB%81%E0%AA%9C%E0%AA...,52574,ગુજરાતી વિશ્વકોશમાં,52775,બાહ્ય કડીઓ,36

Processing language: ha
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ha
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.65069580078125
Writing sentences and links v2
Time taken for v2: 2.4322564601898193

,md5,id,text,startIdx,endIdx,section,locList
0,6bf6a33e7cd8e61e3bb30fda10d1be36,0,"Hon. Hajiya Halima Kyari Joda (Alkaman Gudi), ...",36413,36854,Lead,"[{'start': 36413, 'end': 36425}, {'start': 364..."
1,cf63ad97646a9165423308c323b41da8,1,"Mutuniyar karkara ce, a can aka haife ta.",36855,36897,Lead,"[{'start': 36854, 'end': 36896}]"
2,e8b6c97d0dc3384935576d47315c1c50,2,Baban ta hedimasta (Headmaster) ne wato shugab...,36898,37039,Lead,"[{'start': 36896, 'end': 36963}, {'start': 370..."
3,6c7aa09c9e3ed1956162406c98f24131,3,Hajiya Halima Kyari Joda (Shugabar Ƙaramar Huk...,37044,37535,Lead,"[{'start': 37043, 'end': 37044}, {'start': 374..."
4,c7507397071dad0dae98a7afa0cce331,4,Tayi makarantar Firamare ta Central da ke gari...,37630,37691,Karatu,"[{'start': 37629, 'end': 37630}, {'start': 376..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Kaduna_(jiha),35500,jihohin Kaduna,35570,Lead,0
1,file:///wiki/Kano_(jiha),35574,Kano da,35633,Lead,0
2,file:///wiki/Najeriya,35689,Nijeriya,35743,Lead,0
3,file:///wiki/Kiristanci,36298,addinin kirista ne,36366,Addini,2
4,file:///wiki/Musulunci,36525,Musulunci,36582,Addini,3

Processing language: he
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/he
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 9.372252225875854
Writing sentences and links v2
Time taken for v2: 10.058228254318237

,md5,id,text,startIdx,endIdx,section,locList
0,ec6a8f3b4778a0fdf245280676968f54,0,"אין לבלבל ערך זה עם הערך ""רבי יהודה נשיאה"".",55003,55510,Lead,"[{'start': 55002, 'end': 55003}, {'start': 553..."
1,57ce085ac6ce2fd970478fe715b8368a,1,"רבי יהודה הנשיא (ידוע גם בכינוי המקוצר ""רבי"") ...",63089,63582,Lead,"[{'start': 63088, 'end': 63089}, {'start': 630..."
2,0b5c9787355a7052f4bb321e7024927d,2,"לפי מסורת חז""ל, נולד רבי יהודה הנשיא בתקופת גז...",63584,64092,Lead,"[{'start': 63581, 'end': 63583}, {'start': 635..."
3,ea673cb8e87b466441b1db6302ab5768,3,"מנערותו למד מפי רבי שמעון בר יוחאי, רבי יהודה ...",64093,64759,Lead,"[{'start': 64090, 'end': 64107}, {'start': 642..."
4,5b3e2285428e64d8303a23654ec02b98,4,"רבי יהודה חי בטבריה[1], בציפורי[2] (בה נפטר כנ...",64761,65472,Lead,"[{'start': 64758, 'end': 64774}, {'start': 648..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/1947,43770,1947,43812,Lead,0
1,file:///wiki/%D7%A6%D7%99%D7%99%D7%A8,43818,ציירת,43881,Lead,0
2,file:///wiki/%D7%A4%D7%A1%D7%9C_(%D7%9E%D7%A7%...,43883,פסלת,43979,Lead,0
3,file:///wiki/%D7%99%D7%A9%D7%A8%D7%90%D7%9C%D7%99,43980,ישראלית,44079,Lead,0
4,file:///wiki/%D7%92%D7%A8%D7%9E%D7%A0%D7%99%D7%94,44222,גרמניה,44300,Lead,3

Processing language: hi
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/hi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 4.517849683761597
Writing sentences and links v2
Time taken for v2: 4.4464521408081055

,md5,id,text,startIdx,endIdx,section,locList
0,7e423c445efe7d7b9d141b7a415dc8fc,0,आदिकाल हिन्दी साहित्य के इतिहास का प्रारम्भिक ...,49163,50546,Lead,"[{'start': 49163, 'end': 49169}, {'start': 491..."
1,b5db97a0453a863cd42f293f2ba93aba,1,इस समय का साहित्य मुख्यतः चार रूपों में मिलता ...,50547,50610,Lead,"[{'start': 50546, 'end': 50547}, {'start': 505..."
2,732a91c6b3d47b2ff884468c7611744f,2,"चारण-साहित्य,",50615,50642,Lead,"[{'start': 50614, 'end': 50615}, {'start': 506..."
3,dc902f71261aae4c283ba105c5d16623,3,"सिद्ध-साहित्य तथा नाथ-साहित्य,",50643,50966,Lead,"[{'start': 50641, 'end': 50642}, {'start': 507..."
4,7cb057ffd6ac92dc3ac94e08037ecead,4,"जैन साहित्य,",50967,50988,Lead,"[{'start': 50965, 'end': 50966}, {'start': 509..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4...,48165,महाराष्ट्र सरकार,48363,Lead,0
1,file:///wiki/%E0%A4%B8%E0%A4%BE%E0%A4%AE%E0%A4...,48384,सामाजिक न्याय मंत्रालय,48746,Lead,0
2,file:///wiki/%E0%A4%95%E0%A5%88%E0%A4%AC%E0%A4...,48816,कैबिनेट स्तर,48984,Lead,1
3,file:///wiki/%E0%A4%8F%E0%A4%95%E0%A4%A8%E0%A4...,49016,एकनाथ शिंदे,49159,Lead,1
4,file:///wiki/%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4...,49182,मुख्यमंत्री,49551,Lead,1

Processing language: hr
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/hr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 12.948563814163208
Writing sentences and links v2
Time taken for v2: 12.809772968292236

,md5,id,text,startIdx,endIdx,section,locList
0,67d93d015ff64ddbe497bc34ecf2476e,0,Istraživačka stanica Alfreda Faurea,52077,52591,Lead,"[{'start': 52076, 'end': 52077}, {'start': 525..."
1,c2a0dfc6abc4532d46378de963088502,1,Eaton's Pintails nastanjuju otok,52592,53091,Lead,"[{'start': 52590, 'end': 52591}, {'start': 530..."
2,433c004cb85c46ac598e7eb0c4611d36,2,"Rezultati promatranja u Ship Bayu, Île de la P...",53092,53666,Lead,"[{'start': 53090, 'end': 53091}, {'start': 535..."
3,92cd64aba660b9a958ef1a39c7af4438,3,"Île de la Possession ili otok Possession, bivš...",53667,54001,Lead,"[{'start': 53665, 'end': 53666}, {'start': 536..."
4,2c9f138cfb88b0fa2048c8fe0965802f,4,Administrativno je dio francuskih južnih i ant...,54002,54186,Lead,"[{'start': 54000, 'end': 54024}, {'start': 541..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Oto%C4%8Dje_Crozet,53925,otočja Crozet,53999,Lead,3
1,file:///wiki/Francuski_ju%C5%BEni_i_antarkti%C...,54024,francuskih južnih i antarktičkih zemalja,54184,Lead,4
2,file:///wiki/%C3%8Ele_de_l%27Est,54545,Île de l'Est,54618,Opis,6
3,file:///wiki/Zeljaste_biljke,54828,zeljastom,54897,Opis,9
4,file:///wiki/Prosjek,55659,Prosječna,55732,Istraživačka stanica Alfreda Faurea,14

Processing language: hu
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/hu
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 41.006675720214844
Writing sentences and links v2
Time taken for v2: 44.278958320617676

,md5,id,text,startIdx,endIdx,section,locList
0,215726bae9bbdb2ed4ea261ba140e1fe,0,A lap ellenőrzött változata (ellenőrizve: 2023.,46282,46680,Lead,"[{'start': 46282, 'end': 46288}, {'start': 464..."
1,7aba4fb4641cd02cb80df251c1cbbddd,1,szeptember 6.) ezen a változaton alapul.,46681,47633,Lead,"[{'start': 46680, 'end': 46694}, {'start': 466..."
2,ccf37cf2374aa9ed1a8884b8ea3c278c,2,A 80 nap alatt a Föld körül Willy Foggal (ered...,60909,61527,Lead,"[{'start': 60908, 'end': 60909}, {'start': 609..."
3,0b4aac5b7996642b5b3930d5e89302f7,3,A szereplőket mind különböző állatok formálják...,61528,61830,Lead,"[{'start': 61526, 'end': 61556}, {'start': 616..."
4,cb2a86607c8c8c977ec0b6c8efffcda9,4,Először a Spanyol Televízióban vetítették.,61831,61961,Lead,"[{'start': 61829, 'end': 61840}, {'start': 619..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Holland_Kelet-indiai_T%C3%A1rsas%...,72587,Holland Kelet-indiai Társaság,72714,Lead,2
1,file:///wiki/Tibeti_nyelv,72770,tibeti,72830,Lead,3
2,file:///wiki/Wylie-f%C3%A9le_transzliter%C3%A1...,72845,wylie,72947,Lead,3
3,file:///wiki/Tibet,72964,Tibet,73009,Lead,3
4,file:///wiki/K%C3%ADna,73105,Kínához,73155,Lead,4

Processing language: hy
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/hy
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 11.01180362701416
Writing sentences and links v2
Time taken for v2: 12.423645973205566

,md5,id,text,startIdx,endIdx,section,locList
0,b606ce81ad795cad2eb22cf61465043c,0,Հերկուլես և Աթենաս .,56875,56975,Lead,"[{'start': 56875, 'end': 56884}, {'start': 568..."
1,b0e1c643d4b02a78e75a114221d553e0,1,"մ.թ.ա. մոտ 480 - 470 թվականներ, Պետական անտիկ ...",56976,57332,Lead,"[{'start': 56975, 'end': 57008}, {'start': 571..."
2,9c01a2f679b08bcd9d26586769e77433,2,"Կարմրապատկեր սկահակագրություն, կամ կարմրապատկե...",57333,57510,Lead,"[{'start': 57331, 'end': 57332}, {'start': 573..."
3,7057e59d1dca0148779bbce9090ca584,3,530 թվականին Աթենքում և գոյություն է ունեցել մ...,57511,59158,Lead,"[{'start': 57509, 'end': 57523}, {'start': 575..."
4,5d11b074fc144b461bd7511f7963a0c9,4,Կարմիր պատկերով ծաղկամանները Ատտիկայից տարածվե...,59159,60784,Lead,"[{'start': 59157, 'end': 59158}, {'start': 591..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D4%B1%D5%B6%D5%A3%D5%AC%D5%A5%D6...,141968,անգլ.,142059,Lead,0
1,file:///wiki/%D5%95%D5%A3%D5%B6%D5%B8%D6%82%D5...,142172,/ˈbaɪdən/,142583,Lead,0
2,file:///wiki/%D5%86%D5%B8%D5%B5%D5%A5%D5%B4%D5...,143679,նոյեմբերի 20,143790,Lead,0
3,file:///wiki/1942,143792,1942,143834,Lead,0
4,https://www.wikidata.org/wiki/Q6279#P569,144264,[…],144352,Lead,0

Processing language: id
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/id
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 8.575869798660278
Writing sentences and links v2
Time taken for v2: 8.567813396453857

,md5,id,text,startIdx,endIdx,section,locList
0,4672ff8592dacd6f59c4091eecd4b89f,0,"Friedrich Wilhelm Nietzsche (/ˈniːtʃə, ˈniːtʃi...",106051,110400,Lead,"[{'start': 106050, 'end': 106051}, {'start': 1..."
1,3a55b54484e974bd72f58f1c894464f9,1,Ia memulai karirnya sebagai seorang filolog kl...,110401,110531,Lead,"[{'start': 110399, 'end': 110436}, {'start': 1..."
2,4144d6238a4fef7e6173b24efc1c52eb,2,Ia menjadi orang termuda yang menjabat sebagai...,110532,110723,Lead,"[{'start': 110530, 'end': 110607}, {'start': 1..."
3,dd241125463e312d42302e7712dfe82c,3,"Namun, ia mengundurkan diri pada tahun 1879 ka...",110724,110824,Lead,"[{'start': 110722, 'end': 110823}]"
4,217550c9f2406115cf84736fb6d3f100,4,"Pada tahun 1889, di usia 44 tahun, ia terjatuh...",110825,111080,Lead,"[{'start': 110823, 'end': 110920}, {'start': 1..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Bayi_Ajaib_(film_1982),32132,Bayi Ajaib (film 1982),32228,Lead,0

Processing language: io
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/io
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.037274360656738
Writing sentences and links v2
Time taken for v2: 5.175623655319214

,md5,id,text,startIdx,endIdx,section,locList
0,4a2f4a425bd18a53c5050dcd92e4aa59,0,"Clay esas urbo en la komtio Webster, Kentucky,...",41874,42011,Lead,"[{'start': 41874, 'end': 41878}, {'start': 418..."
1,d01eb469fe3a18e56ff0dbdbc7c4c91b,1,"Segun la demografiala kontado di 2000, ol havi...",42012,42147,Lead,"[{'start': 42011, 'end': 42021}, {'start': 420..."
2,f21481fc5f2d0b3b6830133ba2801a73,2,"Loko di Clay, Kentucky",42219,42620,Geografio,"[{'start': 42218, 'end': 42219}, {'start': 425..."
3,56948c84ef0c5e0a7f5d3bc6452a7a4c,3,Clay jacas a 37.48°&nbsp;N 87.82°&nbsp;W.,42621,42793,Geografio,"[{'start': 42619, 'end': 42620}, {'start': 426..."
4,fa274246b74065a9d9d51b4dd8881388,4,"Segun l'Usana Kontado Ministerio, l'urbo havas...",42794,43170,Geografio,"[{'start': 42792, 'end': 42793}, {'start': 428..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Port-of-Spain,45802,Port-of-Spain,45871,Lead,0
1,file:///wiki/Ekonomio,45900,ekonomio,45974,Lead,1
2,file:///wiki/Trinidad_e_Tobago,45978,Trinidad e Tobago,46059,Lead,1
3,file:///wiki/Petrolo,46091,petrolo,46142,Lead,1
4,file:///wiki/Turismo,46188,turismo,46239,Lead,1

Processing language: is
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/is
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.4170303344726562
Writing sentences and links v2
Time taken for v2: 3.492234468460083

,md5,id,text,startIdx,endIdx,section,locList
0,a85803f14639bef7f4539bad631d088c,0,5.,87613,87619,Lead,"[{'start': 87612, 'end': 87613}, {'start': 876..."
1,694537155d6fef96f49d26ec42831256,1,október er 278.,87620,87639,Lead,"[{'start': 87618, 'end': 87626}, {'start': 876..."
2,9c0ecd3b0cdf9b2e0cf29142d04cca64,2,dagur ársins (279.,87640,87756,Lead,"[{'start': 87638, 'end': 87639}, {'start': 876..."
3,541d3995e239b0ab2cf520b2d749cc5a,3,á hlaupári) samkvæmt gregoríska tímatalinu.,87757,87934,Lead,"[{'start': 87755, 'end': 87758}, {'start': 878..."
4,19a3d66ec27b6146a268e06bab2a9fd2,4,87 dagar eru eftir af árinu.,87935,87963,Lead,"[{'start': 87933, 'end': 87962}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Foxtrot_(a%C3%B0greining),42214,aðgreiningarsíðuna,42327,Lead,0
1,file:///wiki/Bandar%C3%ADkin,43478,bandarískum,43544,Lead,4
2,file:///wiki/Rokk_og_r%C3%B3l,44071,rokk og ról,44139,Lead,6

Processing language: it
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/it
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 10.625920534133911
Writing sentences and links v2
Time taken for v2: 10.368187427520752

,md5,id,text,startIdx,endIdx,section,locList
0,511c380f78479271cdc987d207d0ba2e,0,"Asti, il Palazzo del Podestà",12180,12321,Lead,"[{'start': 12180, 'end': 12184}, {'start': 121..."
1,3eea3c7636b1e92cdb1bade46b707392,1,La casaforte è un'antica residenza signorile f...,12322,12797,Lead,"[{'start': 12321, 'end': 12322}, {'start': 123..."
2,db2bf2f49b1ea57bdbbd8806319bfe45,2,"Era una ""costruzione protetta"", utilizzata sia...",12798,13509,Lead,"[{'start': 12796, 'end': 12848}, {'start': 129..."
3,047e718a19e97de0d2cbb0755fb57427,3,Il cuore della struttura fortificata era la to...,13510,13832,Lead,"[{'start': 13508, 'end': 13509}, {'start': 135..."
4,ce2f760f72e6090b1c86804b6b887222,4,"L'edificio, di solito a pianta rettangolare, p...",15239,15373,L'architettura,"[{'start': 15238, 'end': 15239}, {'start': 152..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Nucleo_atomico,12639,nucleo atomico,12711,Lead,1
1,file:///wiki/Protone,12730,protoni,12781,Lead,1
2,file:///wiki/Neutrone,12808,neutroni,12862,Lead,1
3,file:///wiki/Elettrone,12899,elettroni,12956,Lead,1
4,file:///wiki/Niels_Bohr,13142,Niels Bohr,13202,Lead,2

Processing language: ja
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ja
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.803573369979858
Writing sentences and links v2
Time taken for v2: 8.25142502784729

,md5,id,text,startIdx,endIdx,section,locList
0,2486efb33eee0be5525c36feb0dccc9b,0,『ハイエナ』は、2023年10月20日より、テレビ東京系「ドラマ8」枠で放送予定のテレビドラ...,53181,53898,Lead,"[{'start': 53180, 'end': 53181}, {'start': 531..."
1,7f41cf3ff83ecde9fe656b82c4879ccc,1,2020年に韓国で放送された弁護士ドラマ『ハイエナ －弁護士たちの生存ゲーム－』を日本版とし...,53899,54064,Lead,"[{'start': 53897, 'end': 53898}, {'start': 539..."
2,30225c22b6cb21c89b0119bc475facf0,2,勝つためなら手段を選ばないアウトローな女性弁護士と、法曹一家に生まれたエリートな男性弁護士の...,54065,54247,Lead,"[{'start': 54063, 'end': 54064}, {'start': 540..."
3,51aac14fcb122821249828e4e3cc0285,3,結希凛子,55796,55814,キャスト,"[{'start': 55795, 'end': 55796}, {'start': 558..."
4,4aa28df7638f08c84188d9e29cd098a7,4,演 - 篠原涼子,55815,55902,キャスト,"[{'start': 55813, 'end': 55814}, {'start': 558..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/1945%E5%B9%B4,49600,1945年,49653,Lead,0
1,file:///wiki/7%E6%9C%887%E6%97%A5,49653,7月7日,49711,Lead,0
2,file:///wiki/%E6%97%A5%E6%9C%AC,49717,日本,49769,Lead,0
3,file:///wiki/%E5%B0%8F%E8%AA%AC%E5%AE%B6,49770,小説家,49833,Lead,0
4,file:///wiki/%E8%A9%A9%E4%BA%BA,49834,詩人,49886,Lead,0

Processing language: jv
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/jv
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 15.60092544555664
Writing sentences and links v2
Time taken for v2: 36.379319190979004

,md5,id,text,startIdx,endIdx,section,locList
0,607137eac6fce6688e9010b07d6c103c,0,Musiyum Misi Muntilan Pusat Animasi Misionaris...,40382,41258,Lead,"[{'start': 40381, 'end': 40382}, {'start': 403..."
1,24495ac4fe6e44953353e643f009727a,1,Musiyum puniki dipunresmikake tanggal 14 Desem...,41259,41423,Lead,"[{'start': 41257, 'end': 41342}, {'start': 414..."
2,14f208fb063bfeeb8c1c50a1446cd97c,2,Keuskupan Agung Semarang ndarbeni musiyum puni...,41424,41636,Lead,"[{'start': 41422, 'end': 41423}, {'start': 414..."
3,98ffbba3a9211893a88116094bd600a4,3,Misi Muntilan Pusat Animasi Misioner puniki ng...,41715,42061,Lead,"[{'start': 41714, 'end': 41715}, {'start': 417..."
4,26d597540753d299d5722c1ab9cfe33c,4,Bangunan musiyum dumadi saking rong lantai.,42062,42105,Lead,"[{'start': 42060, 'end': 42104}]"

,link,startIdx,text,endIdx,section,sentid
0,"file:///wiki/Munthilan,_Magelang",40513,Muntilan,40589,Lead,0
1,file:///wiki/Kutha_Magelang,40591,Magelang,40657,Lead,0
2,file:///wiki/Jawa_Tengah,40659,Jawa Tengah,40722,Lead,0
3,file:///wiki/Musiyum,40808,Musiyum,40859,Lead,0
4,file:///wiki/Sajarah,40904,sejarah,40955,Lead,0

Processing language: ka
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ka
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 10.603310585021973
Writing sentences and links v2
Time taken for v2: 10.461524963378906

,md5,id,text,startIdx,endIdx,section,locList
0,9319298dd4cfd1b0de20bdb8fb551080,0,კვარცხანას ციხე — მდებარეობს ისტორიული კლარჯეთ...,46090,46307,Lead,"[{'start': 46090, 'end': 46105}, {'start': 461..."
1,20093bffe5f4b77db2cd95f4534f80a2,1,ჭოროხის მარჯვენა სანაპიროზე შეფენილ მაღალ მთებ...,46308,46453,Lead,"[{'start': 46307, 'end': 46308}, {'start': 463..."
2,6eaae1530b0dd482bdfd9212cf65ed6f,2,კვარცხანას ციხე ლიგანის ქვეყნის ციხეებს[1] შორ...,46454,46645,Lead,"[{'start': 46452, 'end': 46453}, {'start': 464..."
3,ae372e0be0a26310f6b5efe20b74f159,3,კვარცხანას ციხის შესახებ წყაროების სიმცირის მი...,46909,47066,შესწავლის ისტორია,"[{'start': 46908, 'end': 46909}, {'start': 469..."
4,c57520d699d1584e162bbc7c91da4085,4,დევი ბერძენიშვილი V ექსპედიციის დღიურში კვარცხ...,47068,47437,შესწავლის ისტორია,"[{'start': 47065, 'end': 47067}, {'start': 472..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E1%83%94%E1%83%A1%E1%83%9E%E1%83...,135940,ესპ.,136086,Lead,1
1,file:///wiki/%E1%83%90%E1%83%A0%E1%83%92%E1%83...,136156,არგენტინას,136286,Lead,1
2,file:///wiki/%E1%83%A4%E1%83%94%E1%83%AE%E1%83...,136326,ფეხბურთში,136445,Lead,1
3,file:///wiki/%E1%83%A4%E1%83%98%E1%83%A4%E1%83%90,136538,ფიფას,136613,Lead,3
4,file:///wiki/%E1%83%99%E1%83%9D%E1%83%9C%E1%83...,136634,კონმებოლის,136764,Lead,3

Processing language: kk
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/kk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 4.7855224609375
Writing sentences and links v2
Time taken for v2: 4.89973258972168

,md5,id,text,startIdx,endIdx,section,locList
0,499877beb80de8bc6ca2139fa38753c0,0,Сигоза — Ресейдегі өзен.,12969,13069,Lead,"[{'start': 12968, 'end': 12969}, {'start': 129..."
1,8f0383fbc4cc1dbab0dff16a4c401e50,1,Омбы облысы[1] жер аумақтарынан ағып өтеді.,13070,13197,Lead,"[{'start': 13068, 'end': 13080}, {'start': 131..."
2,01e8300295a3456a9e1d388450734191,2,Өзен сағасы Кыртовка өзенінің сол жағалауынан ...,13198,13358,Lead,"[{'start': 13196, 'end': 13209}, {'start': 132..."
3,b8990a36afabf5f60f399a1083a9da2a,3,Өзен ұзындығы 10 км-ді құрайды.,13360,13391,Lead,"[{'start': 13357, 'end': 13389}]"
4,5bbee7f9bad7f217d227811fefa4c9d2,4,Ресей мемлекеттік су тізілімінің мәліметі бойы...,13654,14668,Су реестрінің мәліметтері,"[{'start': 13653, 'end': 13654}, {'start': 138..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/1936,11461,1936,11523,Lead,1
1,file:///wiki/1939,11524,1939,11586,Lead,1
2,file:///wiki/1936,11706,1936,11768,Lead,4
3,file:///wiki/%D0%9A%D0%A1%D0%A0%D0%9E,11828,КСРО,11910,Lead,5
4,file:///wiki/%D0%9C%D0%B5%D0%BA%D1%81%D0%B8%D0...,11915,Мексика,12001,Lead,5

Processing language: km
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/km
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.286679744720459
Writing sentences and links v2
Time taken for v2: 5.502835988998413

,md5,id,text,startIdx,endIdx,section,locList
0,4d2f91b1749b17edf9c6c41fafd8f7bf,0,'សាកលវិទ្យាល័យវេជ្ជសាស្ត្រ និងឱសថសាស្រ្ត (Viet...,69342,70527,Lead,"[{'start': 69342, 'end': 69343}, {'start': 693..."
1,cf165cac689af1f5f159a969b66accc0,1,នៅថ្ងៃទី 20 ខែឧសភា ឆ្នាំ 2010 PR. Dr។ Mai Tron...,70800,72369,ប្រវត្តិសាស្ត្រ,"[{'start': 70799, 'end': 70800}, {'start': 708..."
2,28bce5065f111b54c9354e8d252617e4,2,មហាវិទ្យាល័យវេជ្ជសាស្ត្រ និងឱសថសាស្រ្ត គឺជាសាក...,72370,73057,ប្រវត្តិសាស្ត្រ,"[{'start': 72368, 'end': 72369}, {'start': 723..."
3,912bdf309f2f2edc26be9a7d3aaf16e1,3,Xuân Thủy'',73218,73255,ការដំឡើង,"[{'start': 73217, 'end': 73218}, {'start': 732..."
4,2b74931469371d952f4cd4000c1a1d4e,4,"Dịch Vọng Hậu, Cầu Giấy, Hà Nội, Việt Nam.",73256,73888,ការដំឡើង,"[{'start': 73254, 'end': 73255}, {'start': 734..."

Empty DataFrame
Columns: []
Index: []

Processing language: kn
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/kn
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.5180747509002686
Writing sentences and links v2
Time taken for v2: 3.5889151096343994

,md5,id,text,startIdx,endIdx,section,locList
0,67728724ce03902d7ef785dfb3129cac,0,ಕೃಷ್ಣ ರಾಜ್ (ಜನನ ೨೨ ಫೆಬ್ರವರಿ ೧೯೬೭) ಒಬ್ಬ ಭಾರತೀಯ ...,41765,42493,Lead,"[{'start': 41764, 'end': 41765}, {'start': 417..."
1,8f9cd5552d5e04336597722394482e2c,1,[೧] ಅವರು ೧೯೯೬ಮತ್ತು ೨೦೦೭ ರಲ್ಲಿ ಮೊಹಮ್ಮದಿ ಕ್ಷೇತ್ರ...,42494,42795,Lead,"[{'start': 42492, 'end': 42493}, {'start': 425..."
2,e6028d78d868db8d7909878369a2300d,2,[೨] ಅವರು ೨೦೧೪ ರ ಲೋಕಸಭಾ ಚುನಾವಣೆಯಲ್ಲಿ ಉತ್ತರ ಪ್ರದ...,42796,43499,Lead,"[{'start': 42794, 'end': 42795}, {'start': 428..."
3,f72f7945e6c7e71fb0fe79759931b22e,3,ಕೃಷ್ಣ ರಾಜ್ ಅವರು ಉತ್ತರ ಪ್ರದೇಶದ ಫೈಜಾಬಾದ್‌ನಲ್ಲಿ ಫ...,43812,44071,ಆರಂಭಿಕ ಜೀವನ ಮತ್ತು ಶಿಕ್ಷಣ,"[{'start': 43811, 'end': 43812}, {'start': 438..."
4,89c3be83bca5790b80cb14edc143c273,4,ಅವರು ಡಾ.,44072,44080,ಆರಂಭಿಕ ಜೀವನ ಮತ್ತು ಶಿಕ್ಷಣ,"[{'start': 44070, 'end': 44079}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%B2%B9%E0%B2%BF%E0%B2%82%E0%B2...,39471,ಹಿಂದೂ ಪುರಾಣ,39614,Lead,0
1,file:///wiki/%E0%B2%85%E0%B2%B8%E0%B3%81%E0%B2%B0,39620,ಅಸುರ,39694,Lead,0
2,file:///wiki/%E0%B2%AD%E0%B2%97%E0%B2%A6%E0%B2...,39705,ಭಗದತ್ತ,39801,Lead,1
3,file:///wiki/%E0%B2%B5%E0%B3%87%E0%B2%A6%E0%B2...,39936,ವೇದಗಳು,40052,Lead,2
4,file:///wiki/%E0%B2%AC%E0%B3%83%E0%B2%B9%E0%B2...,40054,ಬೃಹಸ್ಪತಿ,40172,Lead,2

Processing language: ko
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ko
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 14.007972955703735
Writing sentences and links v2
Time taken for v2: 14.261559009552002

,md5,id,text,startIdx,endIdx,section,locList
0,c6fb681f6372a1b4f1d0036740d106ce,0,신암뉴타운은 대구광역시 동구 신암동 일대에 개발 중인 뉴타운이다.,34375,34767,Lead,"[{'start': 34374, 'end': 34375}, {'start': 343..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%EC%88%98%EC%9A%94%EC%9D%BC%EB%A1...,89975,수요일로 시작하는 윤년,90121,Lead,0
1,file:///wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5...,90262,대한민국 임시정부,90383,연호,1
2,file:///wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5...,90395,대한민국,90495,연호,1
3,file:///wiki/%EC%A4%91%ED%99%94%EB%AF%BC%EA%B5%AD,90515,중화민국,90589,연호,2
4,file:///wiki/%EB%AF%BC%EA%B5%AD%EA%B8%B0%EC%9B%90,90596,민국,90668,연호,2

Processing language: ku
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ku
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.959409713745117
Writing sentences and links v2
Time taken for v2: 4.028789281845093

,md5,id,text,startIdx,endIdx,section,locList
0,6bcb742bdca8020bd52134528093c600,0,Hadîşehr bajarek li bakurê Îranê ser bi parêzg...,38682,38871,Lead,"[{'start': 38682, 'end': 38690}, {'start': 386..."
1,5e9fc753d85b671400836688967cfdea,1,Pirranya xelkê li wir dijîn gelê Mazenderanî n...,38872,39119,Lead,"[{'start': 38871, 'end': 38900}, {'start': 389..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/D%C3%AErokzan,60713,dîrokzanan,60794,Lead,1
1,file:///wiki/Ewropa,61080,Ewropa,61128,Lead,2
2,file:///wiki/Serdema_Kevnare,61129,Serdema Kevnare,61224,Lead,2
3,file:///wiki/%C3%87axa_Nav%C3%AEn,61243,serdema navîn,61336,Lead,2
4,file:///wiki/Got,61369,Got,61408,Lead,3

Processing language: la
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/la
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.265954256057739
Writing sentences and links v2
Time taken for v2: 6.625593185424805

,md5,id,text,startIdx,endIdx,section,locList
0,7533ef76476c8e391cbd2dc4c8fd09ed,0,-3 (maximum dubium) Latinitas huius rei maxim...,61837,62021,Lead,"[{'start': 61836, 'end': 61840}, {'start': 618..."
1,8b27e1cda891852f051bd121455b4c6b,1,Vide {{latinitas}}.,62022,62115,Lead,"[{'start': 62020, 'end': 62028}, {'start': 620..."
2,1e8bdff4fc701f73a3768f3d5186e3f1,2,Doctor Who (Anglice Doctor Hú enuntiatus; Lati...,62116,62638,Lead,"[{'start': 62114, 'end': 62115}, {'start': 621..."
3,becc70489d7db7203d48be3a523d5e5e,3,"Doctor est peregrinator extraterrestris, qui i...",62639,63141,Lead,"[{'start': 62637, 'end': 62649}, {'start': 627..."
4,c66b5c7a463ce30e8ea2c023ad74c2d5,4,Nomen TARDIS est acronymum locutionis 'Tempus ...,63142,63286,Lead,"[{'start': 63140, 'end': 63141}, {'start': 631..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Calendarium_Gregorianum,95642,Calendario Gregoriano,95739,Lead,0
1,file:///wiki/Calendarium_Romanum,95774,Calendarium Romanum,95861,Lead,1
2,file:///wiki/Idus,95888,Idus,95930,Lead,1
3,file:///wiki/Abbreviatio,95975,abbreviatur,96038,Lead,3
4,file:///wiki/654,96215,654,96254,Eventa,4

Processing language: lb
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/lb
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.620378017425537
Writing sentences and links v2
Time taken for v2: 3.8068573474884033

,md5,id,text,startIdx,endIdx,section,locList
0,89d8052592f9b06289b14a90286e80c0,0,"D'Martine Kemp, gebuer ëm 1993, ass eng lëtzeb...",40185,40331,Lead,"[{'start': 40184, 'end': 40185}, {'start': 401..."
1,6d2fbb325b96590d362861e5f5528610,1,D'Martine Kemp schafft fir d'Stad Lëtzebuerg.,41141,41275,Liewen a Carrière,"[{'start': 41140, 'end': 41141}, {'start': 411..."
2,d75612530725e30a3e94aaf86fb89fbd,2,Als Drëttgewielt op der Lëscht vun der CSV a F...,41276,41395,Liewen a Carrière,"[{'start': 41274, 'end': 41275}, {'start': 412..."
3,226365d471635426bdfed84c3561c18d,3,Oktober 2023 fir de Christophe Hansen als eng ...,41396,41992,Liewen a Carrière,"[{'start': 41394, 'end': 41415}, {'start': 414..."
4,6a51454e300d606946d3d340491b378f,4,Oktober 2023 am Bezierk Norden an d'Chamber ge...,41993,42239,Liewen a Carrière,"[{'start': 41991, 'end': 42004}, {'start': 420..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Galerie_(Biergbau),38489,Galerien,38563,Lead,1
1,file:///wiki/Gemeng_Schengen,38588,Gemeng Schengen,38663,Lead,1
2,file:///wiki/20._Joerhonnert,38700,20. Joerhonnert,38775,Lead,2
3,file:///wiki/Mini%C3%A8re#%C3%8Bnner_Dag,38776,ënner Dag,38844,Lead,2
4,file:///wiki/1920,39384,1920er,39428,Geschicht,4

Processing language: lmo
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/lmo
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.566047191619873
Writing sentences and links v2
Time taken for v2: 2.550469398498535

,md5,id,text,startIdx,endIdx,section,locList
0,4f8ea611f0ecd644d107331922b55907,0,El 2023 a l'è un ann del secol quell de XXI.,82289,82491,Lead,"[{'start': 82288, 'end': 82289}, {'start': 822..."
1,7fb32e6f28985170ec375198917a18f4,1,1 de sginer: la Svezzia la ciapa la presidenza...,82720,82928,Cossa gh'è capitad,"[{'start': 82719, 'end': 82720}, {'start': 827..."
2,8760f5c345f4a0e3e9ebe1ea3e0f75b3,2,1 de sginer: la Croazzia la taca a doperà l'Eu...,82929,83258,Cossa gh'è capitad,"[{'start': 82927, 'end': 82928}, {'start': 829..."
3,78ccb866007fc5d24bb9a39e498da596,3,1 de sginer: el Luiz Inácio Lula da Silva el g...,83259,83428,Cossa gh'è capitad,"[{'start': 83257, 'end': 83258}, {'start': 832..."
4,04058ab8c93e5c637e132d1920623529,4,5 de sginer: obet del Papa Emerit Benet XVI,83429,83601,Cossa gh'è capitad,"[{'start': 83427, 'end': 83428}, {'start': 834..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Svezzia,82748,Svezzia,82819,Cossa gh'è capitad,1
1,file:///wiki/Union_Europea,82857,Union Europea,82926,Cossa gh'è capitad,1
2,file:///wiki/Croazzia,82952,Croazzia,83026,Cossa gh'è capitad,2
3,file:///wiki/Euro,83046,Euro,83088,Cossa gh'è capitad,2
4,file:///wiki/Luiz_In%C3%A1cio_Lula_da_Silva,83282,Luiz Inácio Lula da Silva,83392,Cossa gh'è capitad,3

Processing language: lo
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/lo
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.876570224761963
Writing sentences and links v2
Time taken for v2: 3.2342896461486816

,md5,id,text,startIdx,endIdx,section,locList
0,67617ba9f0150d17b991b6c7643fbe5c,0,ເກັນຊິນອິມແພກ (ອັງກິດ: Genshin Impact) ແມ່ນເກມ...,51633,53479,Lead,"[{'start': 51633, 'end': 51646}, {'start': 516..."
1,333aa37f3cd6c28105c123ab042cc96b,1,ເກັນຊິນອິມແພກ ເປັນເກມແອັກຊັນສວມບົດບາດ ທີ່ພັດທະ...,53704,54875,ພາບລວມ[1],"[{'start': 53703, 'end': 53704}, {'start': 537..."
2,8dcb93d5e654792c7dfa226dd3aa557b,2,"ສຳລັບລະບົບປະຕິບັດການ ແອນດຣອຍດ໌, IOS, ເພລສະເຕຊັ...",54876,55765,ພາບລວມ[1],"[{'start': 54874, 'end': 54896}, {'start': 550..."
3,3c4b60ddf3a959304aa33d6ba63278c0,3,ຕົວເກມມີສະພາບແວດລ້ອມແບບ ໂອເພັນເວີ (ໂລກກວ້າງ) ແ...,55766,56100,ພາບລວມ[1],"[{'start': 55764, 'end': 55789}, {'start': 560..."
4,fc17c65bc79386d77bcdaf18d78f4124,4,ເປັນເກມຫຼິ້ນຟຣີທີ່ສ້າງລາຍໄດ້ຜ່ານ ລະບົບສຸ່ມກາຊາ...,56101,57074,ພາບລວມ[1],"[{'start': 56099, 'end': 56104}, {'start': 563..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%BA%9E%E0%BA%B2%E0%BA%AA%E0%BA...,121624,ພາສາເຕຕຸມ,121753,ທີ່ມາຂອງຊື່,3
1,https://en.wikipedia.org/wiki/Maritime_Southea...,127153,[6],127252,ອ້າງອິງ,19

Processing language: lt
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/lt
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.846193313598633
Writing sentences and links v2
Time taken for v2: 5.9573469161987305

,md5,id,text,startIdx,endIdx,section,locList
0,a6443bd1a37b8a45a49a06be8d625654,0,Geopozicionavimo principai naudojant GPS,42704,42766,Lead,"[{'start': 42704, 'end': 42744}]"
1,7b9545f54573ee5b24df84d64cddd88a,1,Geopozicionavimas&nbsp;– objekto geografinės p...,42767,43031,Lead,"[{'start': 42766, 'end': 42767}, {'start': 427..."
2,2086364ff7bf21b04e53c7c15534031e,2,Geopozicionavimas pateikia geografinių koordin...,43032,43238,Lead,"[{'start': 43030, 'end': 43031}, {'start': 430..."
3,5297d6da73b862e19f81bdca78ddaef3,3,Geografinė padėtis taip pat gali būti išreikšt...,43239,43433,Lead,"[{'start': 43237, 'end': 43291}, {'start': 433..."
4,2fd1cc8cdb2285e46b8ada90dc1a5c9d,4,Geopozicionavimo konkretūs pavyzdžiai gali būt...,43434,44454,Lead,"[{'start': 43432, 'end': 43433}, {'start': 434..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Ispan%C5%B3_kalba,51401,isp.,51464,Lead,0
1,file:///wiki/%C4%8Cil%C4%97,51518,Čilės,51571,Lead,0
2,file:///wiki/Valparaisas,51847,Valparaise,51909,Lead,2
3,file:///wiki/Kokimbas,51911,Kokimbe,51964,Lead,2
4,file:///wiki/Antofagasta,51966,Antofagastije,52031,Lead,2

Processing language: lv
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/lv
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.8539879322052
Writing sentences and links v2
Time taken for v2: 7.96874475479126

,md5,id,text,startIdx,endIdx,section,locList
0,064393314641f9a6e94aa43a7250d13e,0,Šajā lapā ir apkopoti 2023.,59092,59193,Lead,"[{'start': 59091, 'end': 59092}, {'start': 590..."
1,8a356537aa7951f9f649b410d6abdd0b,1,gada laikapstākļi Latvijā.,59194,59272,Lead,"[{'start': 59192, 'end': 59197}, {'start': 592..."
2,683760ddc8b90f9399736f1961201405,2,2022./2023.,59424,59442,Gada raksturojums pa gadalaikiem,"[{'start': 59423, 'end': 59424}, {'start': 594..."
3,74db985499d6b9238a37a71b3be5b5d6,3,"gada ziema, vidējā gaisa temperatūra Latvijā b...",59443,59552,Gada raksturojums pa gadalaikiem,"[{'start': 59441, 'end': 59452}, {'start': 594..."
4,c66c392c1a7b8da73fc372c667362d97,4,"Vissiltākā ziema bija valsts dienvidos, Daugav...",59553,59708,Gada raksturojums pa gadalaikiem,"[{'start': 59551, 'end': 59707}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Jaunais_R%C4%ABgas_te%C4%81tris,46093,Jaunajā Rīgas teātrī,46195,Lead,0
1,file:///wiki/Alvis_Hermanis,46523,Alvis Hermanis,46595,1993. gadā,4
2,file:///wiki/Aleksandrs_%C4%8Caks,46618,Aleksandrs Čaks,46698,1993. gadā,6
3,file:///wiki/Juris_Rijnieks,46729,Juris Rijnieks,46801,1993. gadā,8
4,file:///wiki/P%C4%93teris_P%C4%93tersons,46866,Pēteris Pētersons,46957,1993. gadā,12

Processing language: mg
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/mg
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.571687936782837
Writing sentences and links v2
Time taken for v2: 2.4313719272613525

,md5,id,text,startIdx,endIdx,section,locList
0,7a744e894c49d350ec2226b0c8ee161f,0,I Mosesy sy i Aarona miaraka amin' ny Didy Fol...,71987,72202,Lead,"[{'start': 71987, 'end': 71989}, {'start': 720..."
1,a5588eef5dd4f6309dcef050a8485197,1,Ny Didy Folo dia fitambaran-tsoratra mirakitra...,72203,72862,Lead,"[{'start': 72202, 'end': 72203}, {'start': 722..."
2,76da63d3ae1b96668ba44bd3b6c5372a,2,Amin' ny teny hebreo dia atao hoe עֲשֶׂרֶת הַד...,72863,73245,Lead,"[{'start': 72861, 'end': 72871}, {'start': 729..."
3,9893a5fb76c969b7680d83b06818f850,3,Takelaka hoditra tamin' ny taona 1768 nataon' ...,73450,74591,Lahatsoratra ao amin' ny Baiboly,"[{'start': 73449, 'end': 73450}, {'start': 739..."
4,ce30440b2e72c07364228f12ec0cb577,4,Hitantsika etsy ambany ny lahatsoratra nalaina...,74592,74816,Lahatsoratra ao amin' ny Baiboly,"[{'start': 74590, 'end': 74651}, {'start': 747..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Afrika_Atsinanana,85361,Afrika Atsinanana,85442,Lead,1
1,file:///wiki/Afrika_Afovoany,85661,Afrika Afovoany,85736,Lead,3
2,file:///wiki/Oganda,85796,Oganda,85844,Lead,3
3,file:///wiki/Sodana,85853,Sodàna,85921,Lead,3
4,file:///wiki/Ejipta,85930,Egipta,85978,Lead,3

Processing language: min
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/min
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.4494669437408447
Writing sentences and links v2
Time taken for v2: 3.6877248287200928

,md5,id,text,startIdx,endIdx,section,locList
0,ab6ec3222a63c926915870b7c1cb7c21,0,Logika adolah studi tentang penalaran nan masu...,74461,74525,Lead,"[{'start': 74460, 'end': 74461}, {'start': 744..."
1,7580f97639aeefa1de5e0c146f4a70d4,1,Iko tamasuak logika formal dan informal.,74526,74566,Lead,"[{'start': 74524, 'end': 74565}]"
2,fcbc0649b323a1c3cfe7c2776c23f6b1,2,Logika formal adolah ilmu tentang kesimpulan l...,74567,74658,Lead,"[{'start': 74565, 'end': 74657}]"
3,742dce1997f2582f9a5e2bc5b17e8f23,3,Inyo mandapekan caronyo kesimpulan di ambiak d...,74659,74789,Lead,"[{'start': 74657, 'end': 74788}]"
4,2c6da14b3111e6fcf7c0907511d2f413,4,Logika informal dikaitkan jo kasalahan informa...,74790,74879,Lead,"[{'start': 74788, 'end': 74878}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Bahaso_Arab,53894,bahaso Arab,53957,Lead,0
1,file:///wiki/Bangso_Arab,54260,bangso Arab,54343,Lead,0
2,file:///wiki/Bahaso_Arab,54459,babahaso Arab,54524,Lead,1
3,file:///wiki/Bahaso_Yunani,54703,bahaso Yunani,54772,Etimologi,2

Processing language: mk
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/mk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.063108444213867
Writing sentences and links v2
Time taken for v2: 3.3059654235839844

,md5,id,text,startIdx,endIdx,section,locList
0,c705cd3cd8c86f63f32dca70d36b35a5,0,"Проверена верзија на оваа страница, одобрена н...",61265,66461,Lead,"[{'start': 61265, 'end': 61282}, {'start': 612..."
1,4d15db475b6dcf716b2a01b14aa9faf4,1,Менорка (каталонски и шпански: Menorca; од лат...,66470,67293,Lead,"[{'start': 66469, 'end': 66470}, {'start': 664..."
2,b59392bf792b0bf2160ca6af9c7a7ed3,2,Името го доби бидејќи е помал од соседниот ост...,67294,67517,Lead,"[{'start': 67292, 'end': 67343}, {'start': 675..."
3,bd977bc8de19282f887e26dd7f76b6d8,3,"Има околу 88.000 жители, а највисоката точка и...",67518,67582,Lead,"[{'start': 67516, 'end': 67581}]"
4,079e2a1c4dc7a65fa849c432598bceba,4,Главен град е Маон.,67583,67738,Lead,"[{'start': 67581, 'end': 67596}, {'start': 677..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%9B%D0%B0%D1%82%D0%B8%D0%BD%D1...,85147,латински,85278,Lead,1
1,file:///wiki/%D0%93%D0%BB%D0%BE%D0%B4%D0%B0%D1...,85585,глодачите,85673,Lead,1
2,file:///wiki/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0...,85807,анатомската,85911,Lead,2
3,file:///wiki/%D0%9C%D1%80%D0%B0%D0%BC%D0%BE%D1...,86460,мраморец,86554,Надворешен изглед,3
4,file:///wiki/%D0%9E%D0%B1%D0%B8%D1%87%D0%BD%D0...,86867,обичната верверица,87042,Надворешен изглед,5

Processing language: mn
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/mn
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.4131274223327637
Writing sentences and links v2
Time taken for v2: 3.78304386138916

,md5,id,text,startIdx,endIdx,section,locList
0,e66e4d4348469c117717e0f7f122f2db,0,Хориотой хот (англи.,67389,67420,Lead,"[{'start': 67388, 'end': 67389}, {'start': 673..."
1,f0fb0cba880a5f527adc40ee21a0750b,1,"Forbidden city), монголчуудын уламжлалт нэршлэ...",67421,67764,Lead,"[{'start': 67419, 'end': 67469}, {'start': 674..."
2,f16afd3600ed8bd6b3442789989ab205,2,Хятад улс 1949 онд социалист дэглэмтэй улс бол...,67765,67927,Lead,"[{'start': 67763, 'end': 67843}, {'start': 679..."
3,afea798570fa105284687f23bc3c0999,3,"Хориотой хотод Юань, Мин, Чин улсын хаад амьда...",67928,68007,Lead,"[{'start': 67926, 'end': 68006}]"
4,e563fe80e69c5e052466f488a03b8780,4,Хориотой хот нь Мин гүрний хаанчлалын үеэс эхл...,68347,68468,Lead,"[{'start': 68346, 'end': 68347}, {'start': 683..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%90%D0%BB%D1%82%D0%B0%D0%BD_%D...,42744,Алтан ордны улсын,42849,Lead,0
1,file:///wiki/%D0%91%D0%B0%D1%82_%D1%85%D0%B0%D...,43016,Бат хан,43104,Хөх орд,1
2,file:///wiki/%D0%A1%D0%B0%D1%80%D1%82%D0%B0%D0%B3,43126,Сартаг,43204,Хөх орд,2
3,file:///wiki/%D0%A3%D0%BB%D0%B0%D0%B3%D1%87%D0%B8,43221,Улагчи,43299,Хөх орд,3
4,file:///wiki/%D0%91%D1%8D%D1%80%D1%85,43316,Бэрх,43378,Хөх орд,4

Processing language: mr
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/mr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 4.956322193145752
Writing sentences and links v2
Time taken for v2: 5.1545045375823975

,md5,id,text,startIdx,endIdx,section,locList
0,385359ee41b88161018ac53bcd7caad1,0,विकिपीडियातील इतिहासविषयक लेखात पाळावयाचे लेख...,56162,56370,Lead,"[{'start': 56161, 'end': 56162}, {'start': 563..."
1,c1b75defe6919cb881a81736435e632d,1,विकिपीडियात संदर्भ कसे जोडावेत लेखाकडे चला,58455,58890,Lead,"[{'start': 58454, 'end': 58455}, {'start': 588..."
2,0bb0c9c1bcc9df8867134be736249056,2,मूळ एतिहासिक दस्तएवज कुठे चढवावेत ते,59125,59317,Lead,"[{'start': 59124, 'end': 59125}, {'start': 592..."
3,5ace5684708b458f5be6828711526b2c,3,आपल्याला १००% कॉपीराइटमुक्त पब्लीक डॉमेन इतिहा...,59411,60010,Lead,"[{'start': 59410, 'end': 59452}, {'start': 597..."
4,d39c32e0e7c337b22532f6737e8ff135,4,विकिस्रोतावर काय चालेल&nbsp;?,60012,60113,Lead,"[{'start': 60009, 'end': 60011}, {'start': 600..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4...,64264,महाराष्ट्राचा,64407,Lead,3
1,file:///wiki/%E0%A4%97%E0%A5%8B%E0%A4%A6%E0%A4...,64408,गोदावरी,64535,Lead,3
2,file:///wiki/%E0%A4%9B%E0%A4%A4%E0%A5%8D%E0%A4...,64618,छत्रपती संभाजीनगर शहर,64831,Lead,4
3,file:///wiki/%E0%A4%AA%E0%A5%88%E0%A4%A0%E0%A4%A3,65327,पैठणचे,65403,Lead,10
4,file:///wiki/%E0%A4%A6%E0%A5%87%E0%A4%B5%E0%A4...,65415,देवगिरीचे यादव,65591,Lead,10

Processing language: ms
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ms
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.627564907073975
Writing sentences and links v2
Time taken for v2: 6.849717378616333

,md5,id,text,startIdx,endIdx,section,locList
0,4cce54ea6c796cf2f4d4c3b9995bb1d7,0,Maidin Ibrahim (1938 – 13 Ogos 2014) adalah pe...,38442,38573,Lead,"[{'start': 38441, 'end': 38442}, {'start': 384..."
1,31ea0ff7a174a436f4c35660a797ba25,1,Maidin Ibrahim juga dikenali sebagai Pak Tam a...,38574,38645,Lead,"[{'start': 38572, 'end': 38644}]"
2,394ba0d0e58532dda2be99dd69df213e,2,Maidin yang dilahirkan pada tahun 1938 di Poko...,38646,38928,Lead,"[{'start': 38644, 'end': 38645}, {'start': 386..."
3,1a984c71843bf89ca3c5d00d60e12fa5,3,Beliau mula menceburi bidang seni sejak tahun ...,38929,39054,Lead,"[{'start': 38927, 'end': 38996}, {'start': 390..."
4,2c585fc2074c85e35c8d015e1b742dba,4,Beliau juga pernah berkhidmat sebagai tentera ...,39055,39188,Lead,"[{'start': 39053, 'end': 39187}]"

                        link  startIdx          text  endIdx section  sentid
0      file:///wiki/Malaysia     38517      Malaysia   38571    Lead       0
1  file:///wiki/Bagan_Lalang     38707  Bagan Lalang   38773    Lead       2
2   file:///wiki/Butterworth     38775   Butterworth   38858    Lead       2
3  file:///wiki/Pulau_Pinang     38860  Pulau Pinang   38926    Lead       2
4         file:///wiki/Boria     38996         boria   39041    Lead       3

Processing language: ne
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ne
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.544567584991455
Writing sentences and links v2
Time taken for v2: 2.6261987686157227

,md5,id,text,startIdx,endIdx,section,locList
0,b888251d841dc9e8c5a53e54768cab1b,0,साधारण गुलेली,57522,57557,Lead,"[{'start': 57522, 'end': 57535}]"
1,ff4665c577719e8afe6aad4d2222bf22,1,गुलेली सामान्यतया सानो हातले सञ्चालित प्रक्षेप...,57558,57739,Lead,"[{'start': 57557, 'end': 57558}, {'start': 575..."
2,30f88506259e8feaa221a89daafdb25b,2,सामन्यतय यसमा अङ्ग्रेजी अक्षर वाई-आकारको फ्रेम...,57741,58150,Lead,"[{'start': 57738, 'end': 57740}, {'start': 577..."
3,be6be0e969759e0e6b37533b8ef64d74,3,"गुलेली बलियो ईलास्टिक सामाग्री, प्राय भल्कनाईज...",58405,58867,प्रयोग र ईतिहास,"[{'start': 58404, 'end': 58405}, {'start': 584..."
4,674f486461d7a7fa1aaf6466df7adb76,4,प्रारम्भिक गुलेलीहरू सबैभन्दा धेरै युवा बदमासस...,58870,59442,प्रयोग र ईतिहास,"[{'start': 58866, 'end': 58869}, {'start': 588..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A4%96%E0%A4%B0%E0%A4%BE%E0%A4...,59133,खरायो,59218,प्रयोग र ईतिहास,4
1,file:///wiki/%E0%A4%A2%E0%A5%81%E0%A4%95%E0%A5...,59220,ढुकुर,59305,प्रयोग र ईतिहास,4
2,file:///wiki/%E0%A4%B2%E0%A5%8B%E0%A4%96%E0%A4...,59309,लोखर्के,59416,प्रयोग र ईतिहास,4
3,file:///wiki/%E0%A4%A6%E0%A5%8B%E0%A4%B8%E0%A5...,60237,दोस्रो विश्वयुद्धपश्चात,60454,प्रयोग र ईतिहास,6
4,file:///wiki/%E0%A4%85%E0%A4%99%E0%A5%8D%E0%A4...,61196,अङ्ग्रेजी,61367,प्रयोग र ईतिहास,9

Processing language: nl
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/nl
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 4.811286449432373
Writing sentences and links v2
Time taken for v2: 5.065502405166626

,md5,id,text,startIdx,endIdx,section,locList
0,6ce394e139f4a3fa1f01c47f9220ace5,0,Widows kan verwijzen naar:,33314,33344,Lead,"[{'start': 33314, 'end': 33320}, {'start': 333..."
1,0f634a4705430cf090dd64951892c4db,1,"Widows (televisieserie), een miniserie uit 198...",33350,33516,Lead,"[{'start': 33349, 'end': 33350}, {'start': 334..."
2,26eb5f6d5171aec20da10eb37584cc58,2,"Widows (film), een film uit 2018 van regisseur...",33517,33647,Lead,"[{'start': 33515, 'end': 33516}, {'start': 335..."
3,439e49e76ab1f0e75ba77ea887d9f1c3,3,Bekijk alle artikelen waarvan de titel begint ...,34126,34462,Lead,"[{'start': 34125, 'end': 34126}, {'start': 341..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Schimmels,45624,schimmel,45680,Lead,0
1,file:///wiki/Stephanosporaceae,45705,Stephanosporaceae,45786,Lead,0
2,file:///wiki/Saprotroof,45798,saprotroof,45878,Lead,1
3,file:///wiki/Loofhout,45882,loofhout,45936,Lead,1
4,file:///wiki/Hymenium,46611,hymenium,46665,Kenmerken,4

Processing language: no
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/no
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 9.731147050857544
Writing sentences and links v2
Time taken for v2: 10.196878671646118

,md5,id,text,startIdx,endIdx,section,locList
0,00052a491ccb6da5eae25e484d54f99f,0,Havnespy Didemnum vexillum tidligere kalt japa...,44426,44911,Lead,"[{'start': 44425, 'end': 44426}, {'start': 444..."
1,0690ce20bbce3dbe48fe41a45fa78f62,1,^ &nbsp;,45042,46214,Referanser,"[{'start': 45041, 'end': 45042}, {'start': 451..."
2,0690ce20bbce3dbe48fe41a45fa78f62,2,^ &nbsp;,46220,47677,Referanser,"[{'start': 46219, 'end': 46220}, {'start': 462..."
3,0690ce20bbce3dbe48fe41a45fa78f62,3,^ &nbsp;,47683,49208,Referanser,"[{'start': 47682, 'end': 47683}, {'start': 477..."
4,0690ce20bbce3dbe48fe41a45fa78f62,4,^ &nbsp;,49214,50053,Referanser,"[{'start': 49213, 'end': 49214}, {'start': 492..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/1959,80990,1959,81032,Lead,2
1,file:///wiki/Norge,81040,norsk,81085,Lead,2
2,file:///wiki/Forfatter,81086,forfatter,81143,Lead,2
3,file:///wiki/Dramatiker,81145,dramatiker,81205,Lead,2
4,file:///wiki/Litteraturvitenskap,81221,litteraturviter,81304,Lead,2

Processing language: oc
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/oc
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.8072474002838135
Writing sentences and links v2
Time taken for v2: 3.970442771911621

,md5,id,text,startIdx,endIdx,section,locList
0,2a2b29c1ebc431abbbdc7e0d63b2dd0b,0,Thierry Amiel es un cantaire francés de Proven...,38814,39120,Lead,"[{'start': 38814, 'end': 38827}, {'start': 388..."
1,39bdb44639505fbf0541b73daa93f821,1,Revelat per l'emission À la recherche de la No...,39121,39661,Lead,"[{'start': 39120, 'end': 39144}, {'start': 392..."
2,03824c0a9e53047e49892cd80997eddd,2,2003: Paradoxes,39739,39775,Discografia,"[{'start': 39738, 'end': 39739}, {'start': 397..."
3,4e83ee1a124887997bd8a24f3de709cb,3,2006: Thierry Amiel,39776,39811,Discografia,"[{'start': 39774, 'end': 39775}, {'start': 397..."
4,0e5477081d4a00b4981be2398650c75c,4,2010: Où vont les histoires&nbsp;?,39812,39862,Discografia,"[{'start': 39810, 'end': 39811}, {'start': 398..."

                        link  startIdx         text  endIdx section  sentid
0          file:///wiki/1000     56662         1000   56724    Lead       0
1    file:///wiki/P%C3%B2ble     56873        pòble   56923    Lead       1
2   file:///wiki/Est%C3%A8pa     57071       estèpa   57124    Lead       1
3       file:///wiki/Eurasia     57125  eurasiatica   57180    Lead       1
4  file:///wiki/S%C3%A8gle_X     57202      sègle X   57258    Lead       2

Processing language: om
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/om
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.7227470874786377
Writing sentences and links v2
Time taken for v2: 1.8741614818572998

,md5,id,text,startIdx,endIdx,section,locList
0,8b2cc36ed88c4be4055e48b953af5ae0,0,SALADINABDURAMANMAHEMMADSuuraa beekamaa lafaa ...,119417,119959,Lead,"[{'start': 119417, 'end': 119441}, {'start': 1..."
1,f1db6dec0be9ae07839d29cebac36c6e,1,Lafa (mallattoo: ),120415,120846,Lead,"[{'start': 120414, 'end': 120415}, {'start': 1..."
2,f88df9f18b9440be0619fdee5181005c,2,Lafti Lafjoo sadarkaa sadaffaa Biiftuu irraa f...,120994,121163,Lafti maalii?,"[{'start': 120993, 'end': 120994}, {'start': 1..."
3,ac6235b36e826bad96ad4ea5719a7a39,3,Lafti Sirna Biiftuu keessatti bishaan baay'ee ...,121164,121408,Lafti maalii?,"[{'start': 121162, 'end': 121407}]"
4,000923d6b432ddd154e0c7235936e4fc,4,Naannoowwan bantii lafaa yeroo ammaa bishaan k...,121409,121560,Lafti maalii?,"[{'start': 121407, 'end': 121559}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Sadhata_waliigalaa,77619,sadhata waliigalaa,77703,Lead,5
1,file:///wiki/Holqa_gurraacha,77794,holqa gurraachaatti,77873,Lead,6
2,file:///wiki/Harkisoo,77881,harkisaan,77936,Lead,6
3,file:///wiki/Fiiziksii,78483,Fiiziksii,78540,Hiika,10
4,file:///wiki/Sirna_Argama_Addunyaa,79078,Sirna Argama Addunyaa (GPS),79177,Hiika,14

Processing language: pa
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/pa
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.3402862548828125
Writing sentences and links v2
Time taken for v2: 2.3896682262420654

,md5,id,text,startIdx,endIdx,section,locList
0,06f52454023be7e86d8c3bb3731b3549,0,The president of the World Bank Group is the h...,51323,51542,Lead,"[{'start': 51322, 'end': 51323}, {'start': 513..."
1,8143470d5232d797c4efd752134c0a93,1,The president is responsible for chairing the ...,51543,51676,Lead,"[{'start': 51541, 'end': 51675}]"
2,152932b8c912afccd85d54a4c24a0461,2,The nominee is subject to confirmation by the ...,51678,51803,Lead,"[{'start': 51675, 'end': 51677}, {'start': 516..."
3,cc087ea625cf3eaab9d1e5055e9b9a29,3,"Traditionally, the World Bank Group president ...",51804,52703,Lead,"[{'start': 51801, 'end': 51867}, {'start': 520..."
4,708ec09a86cad19ad6ec410f2839f60e,4,The fourteenth and current World Bank Group pr...,52704,53047,Lead,"[{'start': 52702, 'end': 52703}, {'start': 527..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A8%AD%E0%A8%BE%E0%A8%B0%E0%A8...,56678,ਭਾਰਤੀ ਰਾਸ਼ਟਰੀ ਕਾਂਗਰਸ,56912,ਕੁੰਜੀਆਂ,0
1,file:///wiki/%E0%A8%B8%E0%A8%BC%E0%A9%8D%E0%A8...,57107,ਸ਼੍ਰੋਮਣੀ ਅਕਾਲੀ ਦਲ,57308,ਕੁੰਜੀਆਂ,1
2,file:///wiki/%E0%A8%86%E0%A8%AE_%E0%A8%86%E0%A...,58239,ਆਮ ਆਦਮੀ ਪਾਰਟੀ,58396,ਕੁੰਜੀਆਂ,5

Processing language: pl
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/pl
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 8.650115251541138
Writing sentences and links v2
Time taken for v2: 11.12503433227539

,md5,id,text,startIdx,endIdx,section,locList
0,4b5c47a2482eb378b2b6b3eef4baf865,0,"Następująca wersja przejrzana tej strony, któr...",40764,41835,Lead,"[{'start': 40764, 'end': 40776}, {'start': 408..."
1,4c9f52ee94a99e8077eb494fd1e34803,1,"Leonid, imię świeckie Leonid Eduardowicz Gorba...",48280,48353,Lead,"[{'start': 48279, 'end': 48280}, {'start': 482..."
2,2ebc75f3458104264a5391c69a5dad12,2,26 października 1968 w Stawropolu) – rosyjski ...,48354,48667,Lead,"[{'start': 48352, 'end': 48353}, {'start': 484..."
3,bf3eef6aea857f90e7154ab3abb1b4fd,3,"Urodzony w Stawropolu, dzieciństwo i młodość s...",48769,48954,Życiorys,"[{'start': 48768, 'end': 48769}, {'start': 487..."
4,156d825f8cb55eaa6504bd2df6ae66d4,4,Po ukończeniu szkoły średniej od 1985 do 1986 ...,48955,49066,Życiorys,"[{'start': 48953, 'end': 49065}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Warszawa,38231,Warszawie,38286,Lead,2
1,file:///wiki/%C5%81%C3%B3d%C5%BA,38311,Łodzi,38369,Lead,2
2,file:///wiki/Lw%C3%B3w,38699,Lwowie,38748,Lead,5
3,file:///wiki/Grodno,38850,Grodnie,38899,Lead,5
4,file:///wiki/Qui_Pro_Quo,38914,Qui Pro quo,38977,Lead,5

Processing language: pms
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/pms
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.04150390625
Writing sentences and links v2
Time taken for v2: 1.1096835136413574

,md5,id,text,startIdx,endIdx,section,locList
0,d6587fd10dae96b4d8ee473d2692a7da,0,Gabian a l'é 'l nòm ëd,33075,33108,Lead,"[{'start': 33074, 'end': 33075}, {'start': 330..."
1,53e99b7afbcb4cb8d9e39d90168ffd2c,1,"Gabian (AL), l'è un comun dla provincia ëd Lis...",33114,33241,Lead,"[{'start': 33113, 'end': 33114}, {'start': 331..."
2,9f8d487023971b63329d67dfd6c9312b,2,"Gabian (vin), vin prodov ant le comun-e ëd Gab...",33242,33406,Lead,"[{'start': 33240, 'end': 33241}, {'start': 332..."
3,19a4c9092f62e91180953c74e67d479e,3,Categorìa:Gestion dij sinònim,33407,33615,Lead,"[{'start': 33405, 'end': 33406}, {'start': 335..."

                       link  startIdx         text  endIdx section  sentid
0  file:///wiki/Gabian_(AL)     31891  Gabian (AL)   31954    Lead       0

Processing language: ps
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ps
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.7849810123443604
Writing sentences and links v2
Time taken for v2: 4.033746242523193

,md5,id,text,startIdx,endIdx,section,locList
0,24179aec7c46136830916bee825f35ec,0,افغانستان، (د افغانستان اسلامي امارت) په غرونو...,148787,149089,Lead,"[{'start': 148786, 'end': 148787}, {'start': 1..."
1,b9d7a8d45f371aacbe4317c8501a4c9b,1,په ټولیزه توګه دا هېواد د منځنۍ اسيا يوه برخه ...,149090,149869,Lead,"[{'start': 149088, 'end': 149115}, {'start': 1..."
2,d70cd11c92b84cba2e0b3aef787c1549,2,دا هېواد په لوېديځ کې په سوېل او ختيځ کې له پا...,149870,150599,Lead,"[{'start': 149868, 'end': 149913}, {'start': 1..."
3,2c9a2ebaec6f76a0e324d26b2711b474,3,په ۱۷۴۷ زېږدیز كال كې افغانستان د لومړي ځل له ...,150600,150858,Lead,"[{'start': 150598, 'end': 150599}, {'start': 1..."
4,d27f1049775ad2b88f8e92f665b94608,4,دغه پولي چي تر انګریزي استعمار مخکي دافغانستان...,150859,151019,Lead,"[{'start': 150857, 'end': 151018}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D9%BE%D8%A7%DA%A9%D8%B3%D8%AA%D8...,37367,د پاکستان,37455,Lead,0
1,file:///wiki/%D9%BE%DA%9A%D8%AA%D8%A7%D9%86%D9%87,37475,پښتون,37552,Lead,0
2,file:///wiki/%D9%BE%DA%9A%D8%AA%D8%A7%D9%86%D9%87,37557,پښتون,37634,Lead,0
3,file:///wiki/%D9%BE%DA%9A%D8%AA%D8%A7%D9%86%D9%87,37637,پټان,37713,Lead,0
4,file:///wiki/%D8%AA%D9%88%D8%B1_%D8%BA%D8%B1_%...,39851,د تور غر,39977,جغرافيه,9

Processing language: pt
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/pt
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 9.661529064178467
Writing sentences and links v2
Time taken for v2: 9.332345008850098

,md5,id,text,startIdx,endIdx,section,locList
0,0e664ec37c4b4fb1d1f4030a1a6202b6,0,"Lucas Santiago de Melo Barbosa, mais conhecido...",52330,53123,Lead,"[{'start': 52329, 'end': 52330}, {'start': 523..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Portugal,47319,Portugal,47373,Lead,0
1,file:///wiki/Bandeira_de_Portugal,47417,bandeira nacional,47504,Lead,0
2,file:///wiki/Unidade_militar,47519,unidades,47587,Lead,0
3,file:///wiki/For%C3%A7as_Armadas_de_Portugal,47619,Forças Armadas,47720,Lead,0
4,file:///wiki/For%C3%A7as_de_seguran%C3%A7a#Por...,47722,forças de seguranças,47829,Lead,0

Processing language: ro
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ro
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 18.46437954902649
Writing sentences and links v2
Time taken for v2: 19.31350564956665

,md5,id,text,startIdx,endIdx,section,locList
0,11285062bdbe19f0b29aa0fc5f45a2c2,0,Timișoara (în latină Timisvaria; în maghiară T...,122820,123837,Lead,"[{'start': 122819, 'end': 122820}, {'start': 1..."
1,16b2983f288aca84132255d89bd9e772,1,"Se află în vestul României, aproape de frontie...",123838,124120,Lead,"[{'start': 123836, 'end': 123855}, {'start': 1..."
2,30af1a8629242fbf9b5ebc7200f87eb3,2,Numele localității provine de la cel al râului...,124121,124362,Lead,"[{'start': 124119, 'end': 124120}, {'start': 1..."
3,48d8cfad088d2983c174fe5ef4950f74,3,"Situat pe râul Bega, Timișoara este cel mai ma...",124363,124642,Lead,"[{'start': 124361, 'end': 124372}, {'start': 1..."
4,82b84e1d8040ecafe975ec2b42422456,4,Din 1848 și până în 1860 a fost capitala Voivo...,124643,124851,Lead,"[{'start': 124641, 'end': 124683}, {'start': 1..."

                             link  startIdx       text  endIdx section  sentid
0          file:///wiki/17_august     42230  17 august   42287    Lead       0
1               file:///wiki/1967     42288       1967   42330    Lead       0
2  file:///wiki/Actri%C8%9B%C4%83     42339    actriță   42420    Lead       0
3               file:///wiki/Film     42424       film   42466    Lead       0
4               file:///wiki/Voce     42478       voce   42540    Lead       0

Processing language: ru
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ru
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 9.397190809249878
Writing sentences and links v2
Time taken for v2: 9.637239933013916

,md5,id,text,startIdx,endIdx,section,locList
0,6398d1410ecc8c6f91d9e36e8429395a,0,"Отпатрулированная версия этой страницы, провер...",14205,14793,Lead,"[{'start': 14205, 'end': 14229}, {'start': 142..."
1,3facac8d86f8da619005a88b20a9f774,1,Бутина.,14794,14900,Lead,"[{'start': 14793, 'end': 14794}, {'start': 148..."
2,7965b15f8ff68a803968386a70d448d3,2,Мари́я Вале́рьевна Бу́тина (род.,29002,29119,Lead,"[{'start': 29001, 'end': 29002}, {'start': 290..."
3,80ceacea741c4aab60fadc7e1a07810f,3,"10 ноября 1988&nbsp;года, Барнаул, РСФСР, СССР...",29120,29628,Lead,"[{'start': 29118, 'end': 29128}, {'start': 291..."
4,bffb70573b7dfb31f0f3650ee18a7538,4,Депутат Государственной Думы Федерального собр...,29629,30650,Lead,"[{'start': 29627, 'end': 29636}, {'start': 298..."

,link,startIdx,text,endIdx,section,sentid
0,https://en.wikipedia.org/wiki/Fred_Roos,16145,[англ.],16320,Lead,1
1,"file:///wiki/%D0%A4%D0%B8%D1%88%D0%B5%D1%80,_%...",16445,Кэрри Фишер,16560,Lead,3
2,"file:///wiki/%D0%9E%D1%80%D0%B0,_%D0%A0%D0%B8%...",16562,Рита Ора,16653,Lead,3
3,file:///wiki/%D0%9D%D0%B5%D0%BB%D0%BB_%D0%A2%D...,16857,Нелл Тайгер Фри,17017,Lead,3
4,"file:///wiki/%D0%9E%D1%83%D1%8D%D0%BD,_%D0%9B%...",18355,Ллойд Оуэн,18462,Синопсис,4

Processing language: sa
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sa
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.3440821170806885
Writing sentences and links v2
Time taken for v2: 1.3748252391815186

,md5,id,text,startIdx,endIdx,section,locList
0,5dbaa944a8fecf9f51f882c7d4614ba0,0,तेय्यम् इति उत्तरकेरलदेशे कर्नाटकस्य केषुचित् ...,45273,46057,Lead,"[{'start': 45273, 'end': 45285}, {'start': 454..."
1,971d54bbe2d2e2a41d71da0842f33878,1,कासरगोड् तथा कन्नूरमण्डलेषु एषा संस्कारकला मुख...,46058,46516,Lead,"[{'start': 46057, 'end': 46058}, {'start': 460..."
2,8f9c6cc51b6835231be03ff166826a0b,2,"तेय्यम् सामान्यतया पुलयार्, वन्नान्, मलयन, अन्...",46517,46853,Lead,"[{'start': 46515, 'end': 46516}, {'start': 465..."
3,ebbead81c5ec00c9a18648fccb39e733,3,तत्र प्रायः ४५६ प्रकाराः तेय्यम् इति दस्तावेजि...,46855,47254,Lead,"[{'start': 46852, 'end': 46854}, {'start': 468..."
4,947ed970cc5c0275381ab894c460f46a,4,"तेय्यम् इत्यस्य ४५० तः अधिकाः विविधताः सन्ति, ...",47265,47453,Lead,"[{'start': 47264, 'end': 47452}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A4%95%E0%A5%87%E0%A4%B0%E0%A4...,45285,उत्तरकेरलदेशे,45438,Lead,0
1,file:///wiki/%E0%A4%95%E0%A4%B0%E0%A5%8D%E0%A4...,45439,कर्नाटकस्य,45619,Lead,0
2,file:///wiki/%E0%A4%88%E0%A4%B6%E0%A5%8D%E0%A4...,45900,देवस्य,45996,Lead,0
3,file:///wiki/%E0%A4%95%E0%A4%A3%E0%A5%8D%E0%A4...,46078,कन्नूरमण्डलेषु,46252,Lead,1
4,file:///wiki/%E0%A4%95%E0%A4%BE%E0%A4%B8%E0%A4...,47911,कासरगोड्,48099,Lead,8

Processing language: scn
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/scn
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.127440929412842
Writing sentences and links v2
Time taken for v2: 2.4527082443237305

,md5,id,text,startIdx,endIdx,section,locList
0,cf195f859ddfee30b6aa48df490572ae,0,Lista p'òrdini alfabbèticu di cantanti e autur...,31770,32144,Lead,"[{'start': 31770, 'end': 31778}, {'start': 318..."
1,42d74aaba89d0d1c9abeca37aa4e8e66,1,"Mario Abbate, cantanti e Atturi",32929,33224,A,"[{'start': 32928, 'end': 32929}, {'start': 330..."
2,142ebad2d50bb1164b16402859e8727e,2,Alessandro Aleotti,33225,33395,A,"[{'start': 33223, 'end': 33224}, {'start': 333..."
3,42dbac47a4a74633195ad10e807f80d0,3,Alexia,33396,33530,A,"[{'start': 33394, 'end': 33395}, {'start': 335..."
4,64489c85dc2fe0787b85cd87214b3810,4,Alice,33531,33684,A,"[{'start': 33529, 'end': 33530}, {'start': 336..."

                   link  startIdx     text  endIdx      section  sentid
0  file:///wiki/Palluni     35481  palluni   35552  Abbinimenti       1
1    file:///wiki/Qatar     35555    Qatar   35600  Abbinimenti       1

Processing language: sco
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sco
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.033949375152588
Writing sentences and links v2
Time taken for v2: 1.9689805507659912

,md5,id,text,startIdx,endIdx,section,locList
0,69afd3766c5f80d4d38fcc03169e7d67,0,The Raijū as depictit in Ban Kōkē's Kanda-Jihitsu,34197,34282,Lead,"[{'start': 34197, 'end': 34201}, {'start': 342..."
1,4e9d8dfdecc1f538c75c755aa0d105cc,1,"Raijū (雷獣, ""thunner ainimal"" or ""thunner beast...",34283,34776,Lead,"[{'start': 34282, 'end': 34283}, {'start': 342..."
2,9e6743dc250a62f7ee176e9818d92c40,2,Its bouk is componed o lichtnin an mey be in t...,34777,35384,Lead,"[{'start': 34775, 'end': 34799}, {'start': 348..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Multinaitional_corporation,64809,multinational,64904,Lead,0

Processing language: sd
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sd
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.558152675628662
Writing sentences and links v2
Time taken for v2: 1.5128161907196045

,md5,id,text,startIdx,endIdx,section,locList
0,3c67b23277ebe1b5e6069f6026203eb8,0,سنڌ جا مايه ناز اديب، محقق، فتوي جا امام، لاجو...,46974,47407,Lead,"[{'start': 46973, 'end': 46974}, {'start': 469..."
1,cb0cdabed7453e43ee7094dbc8dad78a,1,پاڻ بلند پائي جا فقيه۽ اسلام جا عالم دين آهي.[...,47408,47612,Lead,"[{'start': 47406, 'end': 47453}, {'start': 475..."
2,a57a2856e7a96ab38760b25c2f73d84f,2,حضرت پنجن سالن جا هئا ته والد مربي وفات ڪري ويا.,47759,47811,تعليم,"[{'start': 47758, 'end': 47759}, {'start': 477..."
3,93ade75649adea37acbf6093d5a6a304,3,پنهنجي چاچي مولوي محمد يوسف جي سرپرستيءَ ۾ تعل...,47812,47870,تعليم,"[{'start': 47810, 'end': 47869}]"
4,5aec7750cd2d5270f2a682d5cbaed286,4,1956ع ڌاري هن کيس گهوٽڪيءَ جي مدرسه قاسم العلو...,47871,47977,تعليم,"[{'start': 47869, 'end': 47870}, {'start': 479..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%DA%86%D8%A7%DA%86%DA%99,47225,چاچڙ,47287,Lead,0
1,file:///wiki/%D9%85%D8%A7%D8%B1%DA%86,47291,مارچ,47353,Lead,0
2,file:///wiki/1942%D8%B9,47354,1942ع,47404,Lead,0
3,file:///wiki/%DA%AF%D9%87%D9%88%D9%BD%DA%AA%D9%8A,47429,گهوٽڪيءَ,47509,Lead,0
4,file:///wiki/1956%D8%B9,47985,1956ع,48035,تعليم,4

Processing language: sh
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sh
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.291321754455566
Writing sentences and links v2
Time taken for v2: 7.2957117557525635

,md5,id,text,startIdx,endIdx,section,locList
0,2a4d75e2ed2efe0a97e5d862e9ffd21b,0,Vargtimmen (sh. Vučje doba) je švedski crno-be...,19266,19485,Lead,"[{'start': 19265, 'end': 19266}, {'start': 192..."
1,f0ec721f5b77806b1bf61fd057599d35,1,godine u režiji Ingmara Bergmana.,19486,19577,Lead,"[{'start': 19484, 'end': 19501}, {'start': 195..."
2,7955058cc391ca99936f6b1e61d78f98,2,Žanr je mešavina psihološke drame i horora.,19578,19815,Lead,"[{'start': 19576, 'end': 19594}, {'start': 197..."
3,3d21d32e6e343ed628cf731c20af4f45,3,"Glavni junak, slikar (Max von Sydow) se zajedn...",19816,20083,Lead,"[{'start': 19814, 'end': 19837}, {'start': 198..."
4,a398e9ebd2b553d37a3b9955512e7b0d,4,Vargtimmen se za Bergmana isticao neobičnom up...,20085,20483,Lead,"[{'start': 20082, 'end': 20084}, {'start': 200..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%A1%D1%80%D0%B1%D0%B8%D1%98%D0%B0,21815,Србији,21913,Lead,1
1,file:///wiki/%D0%9E%D0%BF%D1%88%D1%82%D0%B8%D0...,21916,општини Житиште,22081,Lead,1
2,file:///wiki/%D0%A1%D1%80%D0%B5%D0%B4%D1%9A%D0...,22084,Средњобанатском управном округу,22351,Lead,1
3,file:///wiki/%D0%9F%D0%BE%D0%BF%D0%B8%D1%81_%D...,22369,2011.,22610,Lead,2
4,file:///wiki/%D0%9A%D1%80%D0%B0%D1%98%D0%B8%D1...,23855,Крајишник,23957,Географске одлике,3

Processing language: si
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/si
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 4.96796989440918
Writing sentences and links v2
Time taken for v2: 8.16559386253357

,md5,id,text,startIdx,endIdx,section,locList
0,b4477fa2afdb068b04e5bfbe0177ef9f,0,කොග්ගල දුම්රිය ස්ථානය යනු ශ්‍රී ලංකාවේ බස්නාහි...,49674,50475,Lead,"[{'start': 49673, 'end': 49674}, {'start': 496..."
1,dfc55105e924b9fea05f43cca2fafacc,1,එය කතළුව සහ හබරාදූව දුම්රිය ස්ථාන අතර පිහිටා ත...,50476,51046,Lead,"[{'start': 50474, 'end': 50478}, {'start': 507..."
2,bcbfc59881b4593b9f3435475de9b37b,2,"කොග්ගල දුම්රිය ස්ථානය, කොළඹ කොටුව දුම්රිය ස්ථා...",51047,51354,Lead,"[{'start': 51045, 'end': 51069}, {'start': 512..."

,link,startIdx,text,endIdx,section,sentid
0,https://en.wikipedia.org/wiki/Clinical_psychology,57617,Clinical psychology,57722,ආශ්‍රිත,20

Processing language: simple
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/simple
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.343518972396851
Writing sentences and links v2
Time taken for v2: 6.307406425476074

,md5,id,text,startIdx,endIdx,section,locList
0,3708960666435ae91a11b1dbf591cb88,0,"2023 (MMXXIII) is the current year, and is a c...",82114,82978,Lead,"[{'start': 82113, 'end': 82114}, {'start': 821..."
1,d6b46c236c793ad4da37283c529b1169,1,The year started with the continuation of the ...,82979,83200,Lead,"[{'start': 82977, 'end': 82978}, {'start': 829..."
2,f2533812ab62b194ea5b5093fdd7a784,2,"In January, an Islamist suicide bomber killed ...",83201,83518,Lead,"[{'start': 83199, 'end': 83215}, {'start': 832..."
3,b78ea47367a1ab3348306e5409ea5272,3,"In February, a major earthquake struck Turkey ...",83519,83985,Lead,"[{'start': 83517, 'end': 83531}, {'start': 836..."
4,3f5b19bc2db88e4761da76190c9df4f2,4,"Former King of Greece Constantine II, former P...",83986,84602,Lead,"[{'start': 83984, 'end': 83985}, {'start': 839..."

                             link  startIdx       text  endIdx section  sentid
0     file:///wiki/English_people     44388    English   44453    Lead       0
1           file:///wiki/Composer     44454   composer   44508    Lead       0
2  file:///wiki/Conductor_(music)     44510  conductor   44603    Lead       0
3     file:///wiki/Music_producer     44608   producer   44694    Lead       0
4        file:///wiki/Movie_score     44725      music   44782    Lead       1

Processing language: sk
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.603713750839233
Writing sentences and links v2
Time taken for v2: 7.406721591949463

,md5,id,text,startIdx,endIdx,section,locList
0,a732a4dd31524228b8e731131e95e84a,0,"Tamara Stohlová, MSc (*&nbsp;10.&nbsp;jún 1989...",38933,39763,Lead,"[{'start': 38932, 'end': 38933}, {'start': 389..."
1,8e4313608d34b26c64f371718bed99ce,1,V parlamentných voľbách v septembri 2023 bola ...,39764,40094,Lead,"[{'start': 39762, 'end': 39765}, {'start': 399..."
2,bc50c2bcf293cfe45bebc2341a7e8149,2,Krátko študovala informatiku (2007&nbsp;– 2008...,40233,41256,Životopis,"[{'start': 40232, 'end': 40233}, {'start': 402..."
3,78e9eaa7555f115be18e8157e45bdda6,3,Pracovala v Transparency International Slovens...,41257,41983,Životopis,"[{'start': 41255, 'end': 41256}, {'start': 412..."
4,db8af4754c5531e8fc88b221c313ee60,4,Kandidovať ju presvedčil v roku 2020 ekológ Er...,42123,42613,Politické pôsobenie,"[{'start': 42122, 'end': 42123}, {'start': 421..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Futbal,49979,futbalový,50030,Lead,0
1,file:///wiki/2._liga,50051,2. lige,50122,Lead,1
2,file:///wiki/1925,50184,1925,50226,Lead,2
3,file:///wiki/Ra%C4%8Da_(miestna_%C4%8Das%C5%A5),51172,Rači,51259,Vznik futbalu v Rači,7
4,file:///wiki/%C5%A0port,51491,športu,51542,Vznik futbalu v Rači,9

Processing language: sl
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sl
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.0584397315979
Writing sentences and links v2
Time taken for v2: 7.464532136917114

,md5,id,text,startIdx,endIdx,section,locList
0,419025a1c60babb75922e828c61ff63e,0,"Cemal Gürsel, turški vojaški častnik in politi...",65414,65700,Lead,"[{'start': 65413, 'end': 65414}, {'start': 654..."
1,d12d7f91684c5a5cdeec0d56dcf76877,1,"oktober 1895, Erzurum, Osmansko cesarstvo, † 14.",65701,65953,Lead,"[{'start': 65699, 'end': 65707}, {'start': 657..."
2,5be0bfcfdd88a6929cc13e27dc6ad4b4,2,"september 1966, Ankara, Turčija.",65954,66119,Lead,"[{'start': 65952, 'end': 65962}, {'start': 659..."
3,e7a679a10379f95592eace8a965ebb86,3,Bil je četrti predsednik Turške Republike.,66120,66268,Lead,"[{'start': 66118, 'end': 66119}, {'start': 661..."
4,7e3f9eb79ab0f4f6c05601cc5dd4cea0,4,Leta 1958 je bil imenovan za poveljnika turške...,66383,66603,Življenjepis,"[{'start': 66382, 'end': 66383}, {'start': 663..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Kitaj%C5%A1%C4%8Dina,45067,kitajsko,45135,Lead,0
1,file:///wiki/Dinastija_%C5%A0ang,45231,dinastija Šang,45308,Lead,0
2,file:///wiki/Zapisi_velikega_zgodovinarja,45321,Zapisi velikega zgodovinarja,45435,Lead,1
3,file:///wiki/D%C5%BEong_Ding,45518,Džong Dinga,45584,Lead,1
4,file:///wiki/Bambusni_letopisi,45763,Bambusnih letopisih,45846,Lead,4

Processing language: so
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/so
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.953672409057617
Writing sentences and links v2
Time taken for v2: 2.914523124694824

,md5,id,text,startIdx,endIdx,section,locList
0,7e747be34c2fbdc727cf753a19839dde,0,Deegaanka (MUKEYLE)/Degmada MUKEYLE waxaa uu d...,33418,33879,Lead,"[{'start': 33418, 'end': 33446}, {'start': 334..."
1,6f90939c5246c69665a94cbf86c613d5,1,Degmada 💖MUKEYLE💖 waxey dadkeedu kor udhaafaya...,33880,34037,Lead,"[{'start': 33879, 'end': 33880}, {'start': 338..."
2,8c2249ee2aafa7d162ca5fbb32ee3886,2,Siyaasiyiinta kasoo jeedo degaankan waxaa kami...,34038,34098,Lead,"[{'start': 34036, 'end': 34037}, {'start': 340..."
3,ee63f6dafcd71566e4494a4bffc95c77,3,1-Saalax cali faarax[waziirkii shaqada iyo sha...,34099,34183,Lead,"[{'start': 34097, 'end': 34182}]"
4,6e271633a8db1678b61bef4ea5c9a2e6,4,2-Xasan Geelleey[Gudoomiye kuxigeenkii degmada...,34184,34266,Lead,"[{'start': 34182, 'end': 34265}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Badweynta_Atlaantik,137834,Badweynta Atlaantik,137921,Lead,1
1,file:///wiki/Fanansuwela,138013,Fanansuwela,138076,Lead,2
2,file:///wiki/Guyana,138078,Guyana,138126,Lead,2
3,file:///wiki/Surinam,138128,Surinam,138179,Lead,2
4,file:///wiki/Kolombiya,138275,Kolombiya,138332,Lead,3

Processing language: sq
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sq
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.589149475097656
Writing sentences and links v2
Time taken for v2: 6.921171426773071

,md5,id,text,startIdx,endIdx,section,locList
0,ec92bb490c61cf37f3f37a56429381e0,0,"A checked version of this page, approved on 18...",85597,86065,Lead,"[{'start': 85597, 'end': 85599}, {'start': 857..."
1,227421bf7a759ef7923bca25402643d1,1,Vizatim i gjetur në shpellën Chauvet.,86224,86645,Parahistoria,"[{'start': 86223, 'end': 86224}, {'start': 865..."
2,1eb11d5398b284a49903a3a44efa95d2,2,Ndër format më të hershme të komunikimit dhe t...,86646,86934,Parahistoria,"[{'start': 86644, 'end': 86645}, {'start': 866..."
3,26dab8793af4b0e790ddf1eb18bc7b89,3,Piktogramet janë format e para të shkrimit dhe...,86935,87256,Parahistoria,"[{'start': 86933, 'end': 87021}, {'start': 871..."
4,49ffc7ded177dffaf804871431f23fca,4,Këto piktograme më pas u shëndrruan në petrogl...,87257,87752,Parahistoria,"[{'start': 87255, 'end': 87295}, {'start': 874..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Gjuha_angleze,42713,Anglisht,42777,Lead,0
1,file:///wiki/Gjuha_arabe,42831,Arabisht,42891,Lead,0
2,file:///wiki/Libri_komik,42947,librat komikë,43012,Lead,0
3,file:///wiki/Shtetet_e_Bashkuara_t%C3%AB_Ameri...,43013,amerikanë,43124,Lead,0
4,file:///wiki/DC_Comics,43139,DC Comics,43196,Lead,0

Processing language: sr
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 11.211602687835693
Writing sentences and links v2
Time taken for v2: 11.046433210372925

,md5,id,text,startIdx,endIdx,section,locList
0,a5ede879a223a290af9098f863832cff,0,"Милица Чађевић (Београд, 7. децембар 1890 — Бе...",51462,51608,Lead,"[{'start': 51461, 'end': 51462}, {'start': 514..."
1,a4dbd61f775bf396afa1a8b0b3710901,1,новембар 1947) је била српска сликарка.[1],51609,51731,Lead,"[{'start': 51607, 'end': 51647}, {'start': 517..."
2,025ac958ae7a7c703cc519844014a5c6,2,Рођена је 7. децембра 1890.,51884,51915,Биографија,"[{'start': 51883, 'end': 51884}, {'start': 518..."
3,b329168330d96a753e37f2d42c4202e8,3,у Београду.[1] Студирала је сликарство код Рис...,51916,52531,Биографија,"[{'start': 51914, 'end': 51917}, {'start': 519..."
4,1e6204d7244482ebce12b0ee3008a174,4,године.[1] Студије је наставила у Женској акад...,52532,53185,Биографија,"[{'start': 52530, 'end': 52538}, {'start': 526..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%9D%D0%B5%D1%83%D1%80%D0%BE%D0%BD,56629,Неурона,56708,Архитектура неурона,6
1,file:///wiki/%D0%93%D0%BB%D0%B8%D1%98%D0%B0%D0...,56943,Глије,57078,Архитектура неурона,9
2,file:///wiki/%D0%90%D1%81%D1%82%D1%80%D0%BE%D1...,57170,астроцита,57265,Архитектура неурона,10
3,file:///wiki/%D0%93%D0%BB%D0%B8%D1%98%D0%B0%D0...,57395,глијалних ћелија,57541,Архитектура неурона,11
4,file:///wiki/%D0%A3%D0%BD%D0%B8%D0%BF%D0%BE%D0...,61469,Униполарни неурон,61630,Архитектура неурона,17

Processing language: su
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/su
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.9275155067443848
Writing sentences and links v2
Time taken for v2: 1.9908421039581299

,md5,id,text,startIdx,endIdx,section,locList
0,6acce115ac87b95f03b0fc187ede8470,0,Cihampelas nyaéta hiji kacamatan di Kabupatén ...,38211,38579,Lead,"[{'start': 38210, 'end': 38211}, {'start': 382..."
1,6e74fce2bc862d79a51f583797158fa3,1,Asal usul ngaran ngaran Cihampelas mangrupakeu...,38651,38790,Etimologi,"[{'start': 38650, 'end': 38651}, {'start': 386..."
2,6deb2caa57f107675e612f3167986e60,2,"Kecap ""Hampelas"" dicokot tina ngaran tangkal h...",38791,38956,Etimologi,"[{'start': 38789, 'end': 38955}]"
3,786cfc8368f74a5d241fd24bef65ba87,3,Disébut Cihampelas kulantaran tina akar-akar t...,38957,39135,Etimologi,"[{'start': 38955, 'end': 39134}]"
4,2f1aebd906605bfc004738da5da82044,4,Lokasi anu dimaksud ayeuna téh nyaéta Kampung ...,39136,39339,Etimologi,"[{'start': 39134, 'end': 39263}, {'start': 393..."

                      link  startIdx        text  endIdx section  sentid
0  file:///wiki/Sansakerta     40736  Sansakerta   40816    Lead       0
1  file:///wiki/Wiracarita     40889  wiracarita   40949    Lead       0
2  file:///wiki/Mahabarata     40950  Mahabarata   41010    Lead       0
3     file:///wiki/Drupadi     41034     Drupadi   41085    Lead       1
4    file:///wiki/Srikandi     41092    Srikandi   41146    Lead       1

Processing language: sv
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sv
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 14.547573566436768
Writing sentences and links v2
Time taken for v2: 14.287479400634766

,md5,id,text,startIdx,endIdx,section,locList
0,dc9298c1ee6d587d4c6eff025e3a9c3b,0,Praděd (tyska Altvater) är ett bergsområde i S...,39582,39813,Lead,"[{'start': 39582, 'end': 39588}, {'start': 395..."
1,bd60d546c8b0fdb31c5183c861389830,1,Områdets högsta bergstopp är Hrubý Jeseník (Gr...,39814,39922,Lead,"[{'start': 39813, 'end': 39814}, {'start': 398..."
2,598ab37fc1389df5c0ffde4e522b2792,2,I området finns flera gamla järngruvor.,39923,39962,Lead,"[{'start': 39921, 'end': 39961}]"
3,cf0cbb27c92fbc15d77218ca6e8bb461,3,"Kända turistorter är Šumperk, Jeseník och Karl...",39963,40231,Lead,"[{'start': 39961, 'end': 39983}, {'start': 400..."
4,8bee38739ce9adae88d472c2393a5330,4,"Nationalencyklopedin multimedia plus, 2000",40327,40395,Källor,"[{'start': 40326, 'end': 40327}, {'start': 403..."

,link,startIdx,text,endIdx,section,sentid
0,https://sv.wiktionary.org/wiki/sax,39953,Ordbok,40039,Lead,0
1,file:///wiki/Sax,40104,Sax,40143,Lead,2
2,file:///wiki/Sax_(f%C3%A4lla),40181,Sax (fälla),40249,Lead,3
3,file:///wiki/Sax_(lyftanordning),40336,Sax (lyftanordning),40423,Lead,4
4,file:///wiki/Sax_(personnamn),40487,Sax (personnamn),40585,Lead,5

Processing language: sw
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/sw
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.051175117492676
Writing sentences and links v2
Time taken for v2: 1.8242933750152588

,md5,id,text,startIdx,endIdx,section,locList
0,7ba2c141eaa55b3657fe5d253fb5f4a2,0,David Dennis (amezaliwa Mei 17 1960) ni muigiz...,34968,35206,Lead,"[{'start': 34967, 'end': 34968}, {'start': 349..."
1,0529192e6df90e54798732e9fae3c800,1,Anajulikana sana kwa uigizaji wake kama Sol ka...,35207,35301,Lead,"[{'start': 35205, 'end': 35300}]"
2,9196c1d4a950282f47fe67cb15af894e,2,Dennis pia alicheza jukumu muhimu katika safu ...,35302,35520,Lead,"[{'start': 35300, 'end': 35350}, {'start': 354..."
3,9d9138b691c8faabc54ac3b2d3a4fad8,3,"Kwa jumla, Dennis ameigiza katika safu kumi na...",35521,35675,Lead,"[{'start': 35519, 'end': 35591}, {'start': 356..."
4,6d124a9b4bee76463b68dbdc70cb095f,4,Ameshinda tuzo nyingi za michezo ya ukumbini n...,35676,35834,Lead,"[{'start': 35674, 'end': 35675}, {'start': 356..."

                      link  startIdx        text  endIdx section  sentid
0   file:///wiki/Wafiadini     35209   Wafiadini   35286    Lead       0
1  file:///wiki/Wakatoliki     35287  Wakatoliki   35367    Lead       0
2        file:///wiki/1849     35571        1849   35613    Lead       1
3     file:///wiki/28_Juni     35761     28 Juni   35812    Lead       1
4        file:///wiki/1900     35813        1900   35855    Lead       1

Processing language: ta
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ta
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.405385971069336
Writing sentences and links v2
Time taken for v2: 5.277664661407471

,md5,id,text,startIdx,endIdx,section,locList
0,df87b53ec9d1c24e30119feabcdd10ba,0,"Village in Tamil Nadu, இந்தியாவார்ப்புரு:SHORT...",46367,49345,Lead,"[{'start': 46367, 'end': 46397}, {'start': 467..."
1,f9f47adac050ecec9d22370c378d6dcb,1,கீழக்குடியிருப்பு (Keelakudiyiruppu) என்பது இந...,49346,50162,Lead,"[{'start': 49345, 'end': 49346}, {'start': 493..."
2,29b20a75c2d400e1f52335d54b418167,2,"2001 மக்கள்தொகை கணக்கெடுப்பின்படி, கீழக்குடியி...",50345,50541,மக்கள்தொகை,"[{'start': 50344, 'end': 50345}, {'start': 503..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%AE%87%E0%AE%A8%E0%AF%8D%E0%AE...,49407,இந்தியாவின்,49518,Lead,1
1,file:///wiki/%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE...,49519,தமிழ்நாடு,49648,Lead,1
2,file:///wiki/%E0%AE%85%E0%AE%B0%E0%AE%BF%E0%AE...,49649,மாநிலத்தில் அரியலூர் மாவட்டத்தில்,49874,Lead,1
3,file:///wiki/%E0%AE%89%E0%AE%9F%E0%AF%88%E0%AE...,49880,உடையார்பாளையம் வட்டத்தில்,50137,Lead,1

Processing language: te
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/te
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.500617504119873
Writing sentences and links v2
Time taken for v2: 6.684522390365601

,md5,id,text,startIdx,endIdx,section,locList
0,beb0f05af691aedebddd7bcba312fe1c,0,"2023 ఐసిసి పురుషుల క్రికెట్ ప్రపంచ కప్, క్రికె...",17635,17918,Lead,"[{'start': 17635, 'end': 17674}, {'start': 176..."
1,5ba99cb9fce6cea8744e0beb6f7eb6a6,1,"ఇది, నాలుగేళ్ళ కోసారి పురుషుల జాతీయ జట్లు పోటీ...",17919,18319,Lead,"[{'start': 17918, 'end': 17970}, {'start': 181..."
2,bf0147db805c9f8df720bf5ea5f06d7d,2,దీన్ని అంతర్జాతీయ క్రికెట్ కౌన్సిల్ (ఐసిసి) ని...,18320,18379,Lead,"[{'start': 18318, 'end': 18378}]"
3,c75e89495fb867ad4b46d225e6db6c96,3,2023 అక్టోబరు 5 నుండి 2023 నవంబరు 19 వరకు జరిగ...,18380,18469,Lead,"[{'start': 18378, 'end': 18468}]"
4,300862a2ce787aacb5b6b0bfefed7eb3,4,ఈ టోర్నమెంటులో 10 జట్లు పోటీపడతాయి.,18470,18512,Lead,"[{'start': 18468, 'end': 18469}, {'start': 184..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%B0%95%E0%B1%8D%E0%B0%B0%E0%B0...,12075,క్రికెట్ క్రీడాకారిణి,12206,Lead,0
1,file:///wiki/%E0%B0%AB%E0%B0%BE%E0%B0%B8%E0%B1...,12217,మీడియం,12385,Lead,1
2,file:///wiki/%E0%B0%AC%E0%B1%8C%E0%B0%B2%E0%B0...,12386,బౌలర్‌గా,12580,Lead,1
3,file:///wiki/%E0%B0%A8%E0%B1%8D%E0%B0%AF%E0%B1...,12600,న్యూజీలాండ్,12957,Lead,2
4,file:///wiki/%E0%B0%AE%E0%B0%B9%E0%B0%BF%E0%B0...,12966,టెస్ట్ మ్యాచ్,13203,Lead,2

Processing language: tg
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/tg
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 2.7717819213867188
Writing sentences and links v2
Time taken for v2: 2.662747383117676

,md5,id,text,startIdx,endIdx,section,locList
0,75ae5a96325a7309197b0ae6a382645e,0,"Абулҳасан Наср ибни Аҳмад ибни Исмоил, Насри I...",46396,47548,Lead,"[{'start': 46395, 'end': 46396}, {'start': 464..."
1,18aaf78b6531ce35ae0aaa14818f9303,1,Дар замони ҳукумати ӯ китобҳои зиёде аз арабӣ ...,47549,47804,Lead,"[{'start': 47547, 'end': 47646}, {'start': 477..."
2,9505478e9109da3d47e07180c93ff3f1,2,Насри II наздик ба 30 сол амири давлати Сомони...,47975,48172,Ҳукмронӣ,"[{'start': 47974, 'end': 47975}, {'start': 479..."
3,f9ad2d52482c337bd21796c2e44370b8,3,Дар айёми ҳукумронии ӯ вазири донишманд ва оли...,48173,48485,Ҳукмронӣ,"[{'start': 48171, 'end': 48233}, {'start': 484..."
4,cfa97fe3234dc916a61b1024d7cd1834,4,Бо кушта шудани Аҳмад ба дарбори сомонӣ писари...,48716,48811,Ҳукмронӣ,"[{'start': 48715, 'end': 48716}, {'start': 487..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/915,41174,915,41233,Lead,1
1,file:///wiki/%D0%A1%D0%B0%D1%80%D1%80%D0%B5%D0...,42339,СИЭМТ,42669,Сарчашма,5
2,file:///wiki/%D0%AD%D0%BD%D1%81%D0%B8%D0%BA%D0...,42704,Энсиклопедияи Миллии Тоҷик,42952,Сарчашма,5
3,file:///wiki/%D0%90%D0%BB%D0%B8%D0%B1%D0%BE%D0...,43400,А. Қурбонов,43541,Сарчашма,7
4,file:///wiki/%D0%92%D0%B8%D0%B6%D0%B0:%D0%9C%D...,43586,ISBN 978-99947-33-45-3,43788,Сарчашма,7

Processing language: tl
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/tl
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.83495831489563
Writing sentences and links v2
Time taken for v2: 5.860112428665161

,md5,id,text,startIdx,endIdx,section,locList
0,04cf4dd2ccf2cfdeaa54be95a0d4f926,0,Ang Villarboit ay isang comune sa lalawigan ng...,59001,59242,Lead,"[{'start': 59000, 'end': 59001}, {'start': 590..."
1,d98ef7b94bf650e7205b7f3aeb98fd2c,1,(sa Italyano)Punong Websayt,66041,66203,Ugnay Panlabas,"[{'start': 66040, 'end': 66041}, {'start': 660..."
2,eee3a1e3bde1911559a9b9c9c200198e,2,Institusyong Pampubliko,66204,66245,Ugnay Panlabas,"[{'start': 66202, 'end': 66203}, {'start': 662..."
3,8687c5b457e4b9829f9d25e7aeb8dbf2,3,Pambansang Tanggapan ng Estadistika Naka-arkib...,66246,66600,Ugnay Panlabas,"[{'start': 66244, 'end': 66245}, {'start': 663..."
4,3248ac509e97d58624ce9ccd4ffb8700,4,ENIT Italian State Tourism Board Naka-arkibo 2...,66601,66990,Ugnay Panlabas,"[{'start': 66599, 'end': 66600}, {'start': 667..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Bahay_sa_baybayin,32336,bahay sa baybayin,32417,Lead,1
1,file:///wiki/Beach_House_(pelikula),32462,Beach House,32567,Lead,2

Processing language: tr
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/tr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 6.872316360473633
Writing sentences and links v2
Time taken for v2: 6.876128196716309

,md5,id,text,startIdx,endIdx,section,locList
0,f3a0bc38203aa647d6d7840af23df29c,0,"TÜRŞAD (Türkiye Şehit Aileleri Derneği), Bitli...",47474,47678,Lead,"[{'start': 47473, 'end': 47474}, {'start': 474..."
1,ef9cdaabcf474109e1820b9e558166e5,1,"Oyuncuları gardiyan ,milli eğitimde çalışan me...",47679,47729,Lead,"[{'start': 47677, 'end': 47728}]"
2,fbf265e71a1c2e41371f06b50060b745,2,"emniyet personeli, Koruyucu, esnaf, eczacı, ma...",47730,47830,Lead,"[{'start': 47728, 'end': 47829}]"
3,a08ff970c020f97fbe1e4175d72127f1,3,2019-2020 yılında 2. ligde şampiyon oldu ve pl...,47830,47906,Lead,"[{'start': 47829, 'end': 47906}]"
4,70041a2bdf3fc39ea3b728abc26a0af4,4,Lige yükseldi.,47906,47921,Lead,"[{'start': 47906, 'end': 47921}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Avrupa_Voleybol_Konfederasyonu,49833,Avrupa Voleybol Konfederasyonu,49953,Lead,1
1,file:///wiki/L%C3%BCksemburg,50869,Lüksemburg,50934,Katılım,10
2,file:///wiki/Kategori:Ar%C5%9Fivlenmesi_gereke...,180448,link,180661,Kaynakça,13
3,file:///wiki/Kategori:Ar%C5%9Fivlenmesi_gereke...,181874,link,182087,Kaynakça,14

Processing language: tt
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/tt
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 13.315862655639648
Writing sentences and links v2
Time taken for v2: 13.726190567016602

,md5,id,text,startIdx,endIdx,section,locList
0,14420e0b06dd2b98ba94e68c150e25a0,0,Канада атналыгыCanadian WeekSemaine canadienne...,75357,76439,Lead,"[{'start': 75356, 'end': 75357}, {'start': 754..."
1,5bfcf83beca5d58cea5e1b9386323fbe,1,Шулай ук Канада турында булган мәкаләләрне яхш...,76440,76505,Lead,"[{'start': 76438, 'end': 76504}]"
2,8e0ac7ea85fc9736c9b708719878f450,2,Канада атналыгы бу төбәк турындагы мәкаләләр б...,76506,76592,Lead,"[{'start': 76504, 'end': 76505}, {'start': 765..."
3,cee9e0ab9d33f24d6fd6aa2e350af100,3,Атна кысаларында Канада һәм Канада мәдәнияте б...,76593,76690,Lead,"[{'start': 76591, 'end': 76689}]"
4,63a00b3447922e086f2f092a75a9a31b,4,Вакыт: 26 октябрь — 5 ноябрь 2023,76691,76738,Lead,"[{'start': 76689, 'end': 76690}, {'start': 767..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%91%D0%B5%D0%BB%D0%B0%D1%80%D1...,69264,белар.,69379,Lead,0
1,file:///wiki/%D0%91%D0%B5%D0%BB%D0%B0%D1%80%D1...,69516,Белоруссиянең,69622,Lead,0
2,file:///wiki/%D0%9C%D0%B8%D0%BD%D1%81%D0%BA_%D...,69623,Минск өлкәсе,69744,Lead,0

Processing language: ug
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ug
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.2827143669128418
Writing sentences and links v2
Time taken for v2: 1.2467963695526123

,md5,id,text,startIdx,endIdx,section,locList
0,5e6559fb2d73297c54db6804070d963b,0,شەرقىي تۈركىستان جۇمھۇرىيەتچىلەر پارتىيەسى 201...,44233,44730,Lead,"[{'start': 44233, 'end': 44730}]"
1,91941f1fb55fc672987eaeeabdff09a4,1,East Turkistan Republican Party,44738,44775,Lead,"[{'start': 44737, 'end': 44738}, {'start': 447..."
2,b1d23c856ddfc705d64ddd7f0e235708,2,قىسقارتىپ يېزىلىشى,44783,44805,Lead,"[{'start': 44782, 'end': 44783}, {'start': 447..."
3,21ae1b12ac57930757dd82d9e5c6d0f5,3,ETRP,44806,44817,Lead,"[{'start': 44804, 'end': 44805}, {'start': 448..."
4,35dba5d75538a9bbe0b4da4422759a0e,4,[1],44818,44893,Lead,"[{'start': 44816, 'end': 44817}, {'start': 448..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A8%D8%B1%D9%8A%DB%87%D8%B3%D8...,44986,بريۇسسېل,45100,Lead,9
1,file:///wiki/%D8%A8%DB%90%D9%84%DA%AF%D9%89%D9...,45109,بېلگىيە,45195,Lead,10
2,file:///wiki/%D8%A6%DB%87%D9%8A%D8%BA%DB%87%D8...,45235,ئۇيغۇرچە,45349,Lead,12
3,file:///wiki/%D8%B4%DB%95%D8%B1%D9%82%D9%89%D9...,46251,شەرقىي تۈركىستان ئىسلام جۇمھۇرىيىتى,46546,Lead,21
4,file:///wiki/%D8%B4%DB%95%D8%B1%D9%82%D9%89%D9...,46561,شەرقىي تۈركىستان جۇمھۇرىيىتى,46805,Lead,22

Processing language: uk
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/uk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.643645763397217
Writing sentences and links v2
Time taken for v2: 3.639770984649658

,md5,id,text,startIdx,endIdx,section,locList
0,19ec435b2441624d6669ef4ad996cb8f,0,"Перевірена версія цієї сторінки, затверджена 1...",9172,19389,Lead,"[{'start': 9172, 'end': 9189}, {'start': 9193,..."
1,f420e18cce9e8eef651dfe1b3cb2096a,1,U-925&nbsp;— німецький середній підводний чове...,20515,21299,Lead,"[{'start': 20514, 'end': 20515}, {'start': 205..."
2,09ebd58a0d217aaa5c5e727ac0bb14ec,2,Закладений 15 жовтня 1941 року на верфі №&nbsp...,21300,21697,Lead,"[{'start': 21298, 'end': 21310}, {'start': 213..."
3,8f0d1560c1058ee313959e0cc75dac3d,3,3 квітня 1943 року спущений на воду.,21698,22068,Lead,"[{'start': 21696, 'end': 21697}, {'start': 217..."
4,ad6762ee3d7c8e389f434573626fa0ea,4,30 грудня 1943 року корабель увійшов до складу...,22069,22676,Lead,"[{'start': 22067, 'end': 22068}, {'start': 221..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/U-Boot,20538,німецький середній підводний човен,20614,Lead,1
1,file:///wiki/%D0%9F%D1%96%D0%B4%D0%B2%D0%BE%D0...,20615,типу VIIC,20785,Lead,1
2,file:///wiki/%D0%92%D1%96%D0%B9%D1%81%D1%8C%D0...,20807,Військово-морських сил Третього Рейху,21113,Lead,1
3,file:///wiki/%D0%94%D1%80%D1%83%D0%B3%D0%B0_%D...,21123,Другої світової війни,21297,Lead,1
4,file:///wiki/15_%D0%B6%D0%BE%D0%B2%D1%82%D0%BD...,21310,15 жовтня,21397,Lead,2

Processing language: ur
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/ur
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 11.619165182113647
Writing sentences and links v2
Time taken for v2: 11.850847721099854

,md5,id,text,startIdx,endIdx,section,locList
0,f202836ff05c8e95fc002d03ee05d5df,0,صارف:Tahir697,74260,74361,Lead,"[{'start': 74259, 'end': 74260}, {'start': 743..."
1,66b9fcbd7ee77e12b6023b33bb43709f,1,ابو سلیمان خالد بن ولید ابن مغیرہ المخزومی عرب...,82773,83836,Lead,"[{'start': 82772, 'end': 82773}, {'start': 827..."
2,ad7da4c22550c131ad77a006b8fccb78,2,ابی طالب وحضرت عبداللہ بن رواحہ رضی اللہ تعالی...,83837,86141,Lead,"[{'start': 83835, 'end': 84740}, {'start': 848..."
3,b5e1ef26214e27d7a3cdc848d26fc51e,3,اس کے بعد خالد بن ولید نے عراق میں فرات کی واد...,86141,88508,Lead,"[{'start': 86140, 'end': 86142}, {'start': 861..."
4,8a02c530b76d59e9a2b446d59ff6511b,4,انہیں عام طور پر مورخین ابتدائی اسلامی دور کے ...,88509,89322,Lead,"[{'start': 88508, 'end': 88509}, {'start': 885..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A2%D8%A6%D8%B1_%D9%84%DB%8C%D...,54259,آئرلینڈ کی خواتین کرکٹ ٹیم,54463,Lead,0
1,file:///wiki/%D8%B3%DA%A9%D8%A7%D9%B9_%D9%84%D...,54468,اسکاٹ لینڈ کی خواتین کی کرکٹ ٹیم,54735,Lead,0
2,file:///wiki/%D8%A7%D9%84%D9%85%D8%B1%DB%8C%DB%81,54748,المریا,54826,Lead,0
3,file:///wiki/%DA%88%DB%8C%D8%B2%D8%B1%D9%B9_%D...,54831,ڈیزرٹ اسپرنگس کرکٹ گراؤنڈ,55046,Lead,0
4,file:///wiki/%D8%AE%D9%88%D8%A7%D8%AA%DB%8C%D9...,55055,خواتین کے ایک روزہ بین الاقوامی میچز,55297,Lead,0

Processing language: uz
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/uz
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 5.349730014801025
Writing sentences and links v2
Time taken for v2: 5.664031505584717

,md5,id,text,startIdx,endIdx,section,locList
0,18d7321edbdd1ae0b7996d0930581039,0,Qavola&nbsp;— Buxoro viloyati Buxoro tumanidag...,35566,35626,Lead,"[{'start': 35566, 'end': 35572}, {'start': 355..."
1,bd93d79d30909ed4ad66371cd2c01f0e,1,Qavola&nbsp;— xalq orasida „Qavola Mahmud“ nom...,35627,35690,Lead,"[{'start': 35626, 'end': 35689}]"
2,ddf360d90d4558b0fad244af5bd9ed0a,2,Toponim toʻgʻrisida bir-necha farazlar mavjud.,35691,35737,Lead,"[{'start': 35689, 'end': 35736}]"
3,7d082a6c526703130a13478fdcd4dc10,3,"Qavola soʻzi „notiq“, „hofiz“ maʼnolarini angl...",35738,35790,Lead,"[{'start': 35736, 'end': 35789}]"
4,8d2ef3d9426422187ef140c3dfe177c3,4,"Toponimga maʼno jihatdan qaraydigan boʻlsak, „...",35791,36051,Lead,"[{'start': 35789, 'end': 35956}, {'start': 360..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Nukus,40754,Nukus,40799,Lead,0
1,file:///wiki/Qoraqalpog%CA%BBiston,40801,Qoraqalpogʻiston,40884,Lead,0
2,file:///wiki/O%CA%BBzbekiston,40886,Oʻzbekiston,40954,Lead,0
3,file:///wiki/Amudaryo_bo%CA%BBlimi,41236,Amudaryo boʻlimi,41319,Biografiyasi,2
4,file:///wiki/Qoraqalpog%CA%BBiston,41328,Qoraqalpogʻiston,41411,Biografiyasi,2

Processing language: vi
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/vi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 14.526707649230957
Writing sentences and links v2
Time taken for v2: 14.947487354278564

,md5,id,text,startIdx,endIdx,section,locList
0,3e0a8be2c46a5be9d17daf4f444cae99,0,Nghi lễ thờ cúng thần nước hòa mình vào Mẹ thi...,44834,44910,Lead,"[{'start': 44834, 'end': 44888}]"
1,c50b04a54c526e2d307642784108a88d,1,Tín ngưỡng sùng bái tự nhiên (Nature worship/N...,44911,46071,Lead,"[{'start': 44910, 'end': 44911}, {'start': 449..."
2,c6a716f7f153a6d86669f85655cb2ecb,2,Một vị thần tự nhiên có thể là đấng cai quản v...,46072,46195,Lead,"[{'start': 46070, 'end': 46194}]"
3,04be0feccef199e7d35166fe052db0e8,3,Sự sùng bái tự nhiên thường được coi là nguồn ...,46196,47969,Lead,"[{'start': 46194, 'end': 46289}, {'start': 463..."
4,fd90d1dbbbdc703c8e94ac26bc39f878,4,Điểm chung của hầu hết các hình thức tôn thờ t...,47970,48247,Lead,"[{'start': 47968, 'end': 48170}, {'start': 482..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Nhi%E1%BB%87t_%C4%91%E1%BB%99ng_l...,109291,nhiệt động lực học,109412,Lead,1
1,file:///wiki/Entropy,109512,entropy,109563,Lead,2
2,file:///wiki/Nh%C3%A0_v%E1%BA%ADt_l%C3%BD_h%E1...,109567,nhà vật lý học,109685,Lead,2
3,file:///wiki/Ph%E1%BB%95_(qu%E1%BB%91c_gia),109692,Phổ,109769,Lead,2
4,file:///wiki/Rudolf_Clausius,109773,Rudolf Clausius,109848,Lead,2

Processing language: vo
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/vo
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.1514484882354736
Writing sentences and links v2
Time taken for v2: 1.3318183422088623

,md5,id,text,startIdx,endIdx,section,locList
0,a6cd0dc89d007aa73dc079e085c0e24a,0,Hiel Valentin Alekseyevic Golubenko (rusänapük...,34265,34695,Lead,"[{'start': 34264, 'end': 34265}, {'start': 342..."
1,f6d9f3dc6d043aaf73958d6155c84cfd,1,Valentin Golubenko in IMDb,34811,34944,Yüms plödik,"[{'start': 34810, 'end': 34811}, {'start': 349..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Rus%C3%A4nap%C3%BCk,35599,rusänapüko,35667,Lead,0
1,file:///wiki/1937,35704,1937,35746,Lead,0
2,file:///wiki/Mayul_11,35747,mayul 11,35801,Lead,0
3,file:///wiki/Rus%C3%A4n,35965,Rusänik,36017,Lead,0

Processing language: xh
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/xh
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 1.126711368560791
Writing sentences and links v2
Time taken for v2: 1.1836786270141602

,md5,id,text,startIdx,endIdx,section,locList
0,24677d3432cf0e1ee0c7062de195071f,0,"AS SONIDEP, esekelwe kwi-2014 ngumbutho webhol...",36481,36672,Lead,"[{'start': 36481, 'end': 36491}, {'start': 364..."
1,ee3ef28084b7d239d8476fabfe47aba6,1,Kwiqembu lokuqala kusukela ngomnyaka wokuqala ...,36673,36844,Lead,"[{'start': 36672, 'end': 36673}, {'start': 366..."
2,56f461d5c6aea527dd12d5ad27c7b42c,2,"Kwintsebenzo ngeli xesha lonyaka, iklabhu ibin...",36845,36953,Lead,"[{'start': 36843, 'end': 36952}]"
3,9b87ff6940353177e6b559ec3659549d,3,"Kolu khuphiswano lwendebe yesizwe, i-AS SONIDE...",36954,37040,Lead,"[{'start': 36952, 'end': 37039}]"
4,d5c05f7f484a79a75b6738be5a8a2bc2,4,"Ngexesha le-2017-2018, i-AS SONIDEP yachithwa ...",37041,37123,Lead,"[{'start': 37039, 'end': 37122}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Ibhola_ekhatywayo,36525,webhola yebhola,36604,Lead,0
1,file:///wiki/Niamey,36614,eNiamey,36663,Lead,0
2,file:///wiki/Super_Ligue_(eNiger),37799,I-Niger Premier League,37891,Impumelelo,10
3,file:///wiki/Indebe_yaseNiger,37974,Indebe yeNiger,38050,Impumelelo,12

Processing language: yi
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/yi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 3.248147964477539
Writing sentences and links v2
Time taken for v2: 2.9493465423583984

,md5,id,text,startIdx,endIdx,section,locList
0,19fa3662e0706914e7df05b0028f5c34,0,די מדינת ישראל-כאמאס קריג,64448,64480,Lead,"[{'start': 64448, 'end': 64451}, {'start': 644..."
1,f577c3a57ec4b2d825b8efebc6e741ef,1,איז אן אנגייענדער קאנפליקט צווישן מדינת ישראל ...,64481,65094,Lead,"[{'start': 64480, 'end': 64531}, {'start': 646..."
2,ce5cf027b1f88503577729294e9c96b9,2,די אטאקע האט זיך אנגעהויבן אין די פרי מארגן וו...,65095,65327,Lead,"[{'start': 65093, 'end': 65326}]"
3,987d8a5aeac3e7a18a4c2c7f447215da,3,פאלעסטינע מיליטאנטן האבן זיך אדורכגעבראכן די מ...,65328,65519,Lead,"[{'start': 65326, 'end': 65518}]"
4,053eb3a35d06eae44c747c9c933a98f7,4,די מדינת ישראל קאנטעראפענסיווע ווערט גערופן אפ...,65520,65692,Lead,"[{'start': 65518, 'end': 65563}, {'start': 655..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D7%93%D7%99%D7%99%D7%9F,40430,דיין,40492,Lead,0
1,file:///wiki/%D7%95%D7%95%D7%99%D7%9C%D7%99%D7...,40497,וויליאמסבורג,40643,Lead,0
2,file:///wiki/%D7%99%D7%A9%D7%99%D7%91%D7%94,40663,ישיבה,40733,Lead,0
3,file:///wiki/%D7%A7%D7%A8%D7%99%D7%AA_%D7%99%D...,40811,קרית יואל,40908,Lead,1
4,file:///wiki/%D7%A1%D7%90%D7%98%D7%9E%D7%90%D7...,41156,"הופער ביהמ""ד",41300,Lead,2

Processing language: zh
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/crawled_pages/zh
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 18.958969593048096
Writing sentences and links v2
Time taken for v2: 15.79861044883728

,md5,id,text,startIdx,endIdx,section,locList
0,cb0f9446e495d2827afc8e471534d661,0,2023年國家女子足球聯賽賽季是國家女子足球聯賽（NWSL）的第11個賽季，也是由國際足協與...,58324,59554,Lead,"[{'start': 58323, 'end': 58324}, {'start': 583..."
1,739d28fd832202f38139edb3e345c9e4,1,"^ 流明球場可容納68,740人，但OL君主僅限1萬人觀賽。[2]",72327,72561,參賽球隊,"[{'start': 72326, 'end': 72327}, {'start': 724..."
2,a130eeb995b132f361984cf7d9e38d8e,2,"^ 可擴展至15,304個座位數[3]。",72567,72788,參賽球隊,"[{'start': 72566, 'end': 72567}, {'start': 726..."
3,16bfacff0bab3bfc362a9e308f83d4ce,3,註：Nike是NWSL長期合作的球衣製造商[4]。,72963,73149,參賽球隊,"[{'start': 72962, 'end': 72963}, {'start': 729..."
4,25c9ba2a6fa1a4574bac6e5367e049cf,4,資料來源：NWSL排名規則：詳見(C) 冠軍,124310,139114,例行賽,"[{'start': 124309, 'end': 124310}, {'start': 1..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E5%93%88%E9%A6%AC%E6%96%AF,92102,哈馬斯,92185,Lead,0
1,file:///wiki/%E4%BB%A5%E8%89%B2%E5%88%97,92186,以色列,92249,Lead,0
2,file:///wiki/%E5%9F%BA%E5%B8%83%E5%85%B9,92613,基布兹,92676,Lead,0
3,file:///wiki/%E6%96%AF%E5%BE%B7%E6%B4%9B%E7%89%B9,92683,斯德洛特,92777,Lead,0
4,file:///wiki/%E6%9D%B0%E5%93%88%E5%BE%B7,93054,杰哈德,93137,Lead,0

**Preprocessing**

In [8]:
for lang in langs:
    for side_context_size in side_context_sizes:
        print(f"Processing language: {lang} with side context size {side_context_size}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
        output_dir = f"{contexts_splitted_data_dir}/{lang}/context_size_{side_context_size}"
        
        subprocess.run([
            "python", "modular_preprocessing.py",
            "--revisions_path", save_path,
            "--parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v2",
            "--first_versions_specific_parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v1",
            "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
            "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",
            "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",
            "--output_dir", output_dir,
            "--side_contexts_size", str(side_context_size),
            "--n_processes", "1" #str(processes)
        ])

        #preprocessed_data_path = os.path.join(output_dir, f'test_data.parquet')

        #preprocessed_data = pd.read_parquet(preprocessed_data_path)
        #display(preprocessed_data.head(5))

Processing language: af with side context size 5

Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 20.30it/s]
100%|██████████| 56/56 [00:00<00:00, 10471.27it/s]

The length of the output is 56
Processing language: am with side context size 5
Running on 1 processes

 61%|██████    | 11/18 [00:00<00:00, 32.43it/s]

No links found
32066_378260_links.jsonl

100%|██████████| 18/18 [00:00<00:00, 29.19it/s]
100%|██████████| 22/22 [00:00<00:00, 21902.37it/s]

The length of the output is 22
Processing language: an with side context size 5
Running on 1 processes

100%|██████████| 12/12 [00:00<00:00, 34.73it/s]
100%|██████████| 79/79 [00:00<00:00, 18624.59it/s]

The length of the output is 79
Processing language: ar with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 15.94it/s]
100%|██████████| 94/94 [00:00<00:00, 14458.87it/s]

The length of the output is 94
Processing language: ary with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 34.35it/s]
100%|██████████| 48/48 [00:00<00:00, 21281.88it/s]

The length of the output is 48
Processing language: as with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 26.93it/s]
100%|██████████| 68/68 [00:00<00:00, 9503.60it/s]

The length of the output is 68
Processing language: ast with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 16.66it/s]
100%|██████████| 45/45 [00:00<00:00, 15204.10it/s]

The length of the output is 45
Processing language: az with side context size 5
Running on 1 processes
No sentences found in 1
815798_7267641_sentences.jsonl

100%|██████████| 25/25 [00:01<00:00, 17.83it/s]
100%|██████████| 108/108 [00:00<00:00, 16984.17it/s]

The length of the output is 108
Processing language: azb with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 37.48it/s]
100%|██████████| 23/23 [00:00<00:00, 36918.86it/s]

The length of the output is 23
Processing language: ba with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 16.10it/s]
100%|██████████| 65/65 [00:00<00:00, 24881.79it/s]

The length of the output is 65
Processing language: bar with side context size 5
Running on 1 processes

100%|██████████| 16/16 [00:00<00:00, 31.23it/s]
100%|██████████| 33/33 [00:00<00:00, 36782.36it/s]

The length of the output is 33
Processing language: be with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 16.79it/s]
100%|██████████| 65/65 [00:00<00:00, 27241.18it/s]

The length of the output is 65
Processing language: bg with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 15.81it/s]
100%|██████████| 86/86 [00:00<00:00, 11360.59it/s]

The length of the output is 86
Processing language: br with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 28.09it/s]
100%|██████████| 122/122 [00:00<00:00, 71939.42it/s]

The length of the output is 122
Processing language: bs with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 21.45it/s]
100%|██████████| 87/87 [00:00<00:00, 11057.38it/s]

The length of the output is 87
Processing language: ca with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.62it/s]
100%|██████████| 323/323 [00:00<00:00, 4468.40it/s]

The length of the output is 323
Processing language: ce with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 23.48it/s]
100%|██████████| 575/575 [00:00<00:00, 61951.88it/s]

The length of the output is 575
Processing language: cs with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 18.54it/s]
100%|██████████| 178/178 [00:00<00:00, 38862.43it/s]

The length of the output is 178
Processing language: cv with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 20.51it/s]
100%|██████████| 241/241 [00:00<00:00, 43465.22it/s]

The length of the output is 241
Processing language: cy with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 28.10it/s]
100%|██████████| 82/82 [00:00<00:00, 11176.45it/s]

The length of the output is 82
Processing language: da with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 30.62it/s]
100%|██████████| 74/74 [00:00<00:00, 34303.55it/s]

The length of the output is 74
Processing language: de with side context size 5
Running on 1 processes

100%|██████████| 25/25 [01:14<00:00,  2.97s/it]
100%|██████████| 716/716 [00:00<00:00, 14603.99it/s]

The length of the output is 716
Processing language: el with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 14.92it/s]
100%|██████████| 104/104 [00:00<00:00, 16582.06it/s]

The length of the output is 104
Processing language: en with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 20.79it/s]
100%|██████████| 52/52 [00:00<00:00, 19449.24it/s]

The length of the output is 52
Processing language: eo with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 26.56it/s]
100%|██████████| 164/164 [00:00<00:00, 38149.07it/s]

The length of the output is 164
Processing language: es with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.04it/s]
100%|██████████| 85/85 [00:00<00:00, 12121.85it/s]

The length of the output is 85
Processing language: et with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  6.08it/s]
100%|██████████| 43/43 [00:00<00:00, 16660.98it/s]

The length of the output is 43
Processing language: eu with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:02<00:00,  9.75it/s]
100%|██████████| 88/88 [00:00<00:00, 52458.61it/s]

The length of the output is 88
Processing language: fa with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 20.25it/s]
100%|██████████| 63/63 [00:00<00:00, 19051.27it/s]

The length of the output is 63
Processing language: fi with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 17.91it/s]
100%|██████████| 57/57 [00:00<00:00, 21857.32it/s]

The length of the output is 57
Processing language: fr with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:02<00:00, 12.12it/s]
100%|██████████| 52/52 [00:00<00:00, 13713.77it/s]

The length of the output is 52
Processing language: fy with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 19.08it/s]
100%|██████████| 152/152 [00:00<00:00, 28902.63it/s]

The length of the output is 152
Processing language: ga with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 28.16it/s]
100%|██████████| 62/62 [00:00<00:00, 27738.33it/s]

The length of the output is 62
Processing language: gd with side context size 5
Running on 1 processes

100%|██████████| 13/13 [00:00<00:00, 36.07it/s]
100%|██████████| 28/28 [00:00<00:00, 31809.46it/s]

The length of the output is 28
Processing language: gl with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 17.45it/s]
100%|██████████| 74/74 [00:00<00:00, 23729.24it/s]

The length of the output is 74
Processing language: gu with side context size 5
Running on 1 processes

100%|██████████| 16/16 [00:00<00:00, 28.95it/s]
100%|██████████| 52/52 [00:00<00:00, 30112.36it/s]

The length of the output is 52
Processing language: ha with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 32.53it/s]
100%|██████████| 44/44 [00:00<00:00, 29742.04it/s]

The length of the output is 44
Processing language: he with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 17.83it/s]
100%|██████████| 85/85 [00:00<00:00, 18968.65it/s]

The length of the output is 85
Processing language: hi with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:00<00:00, 25.80it/s]
100%|██████████| 68/68 [00:00<00:00, 13445.82it/s]

The length of the output is 68
Processing language: hr with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 16.41it/s]
100%|██████████| 71/71 [00:00<00:00, 7795.29it/s]

The length of the output is 71
Processing language: hu with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:01<00:00, 13.94it/s]
100%|██████████| 62/62 [00:00<00:00, 16051.28it/s]

The length of the output is 62
Processing language: hy with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:02<00:00, 11.86it/s]
  0%|          | 0/527 [00:00<?, ?it/s]

The length of the output is 527

100%|██████████| 527/527 [00:00<00:00, 7488.69it/s]

Processing language: id with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  6.12it/s]
100%|██████████| 65/65 [00:00<00:00, 17773.63it/s]

The length of the output is 65
Processing language: io with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  8.13it/s]
100%|██████████| 69/69 [00:00<00:00, 17641.39it/s]

The length of the output is 69
Processing language: is with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.04it/s]
100%|██████████| 130/130 [00:00<00:00, 22091.38it/s]

The length of the output is 130
Processing language: it with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.02it/s]
100%|██████████| 80/80 [00:00<00:00, 15494.29it/s]

The length of the output is 80
Processing language: ja with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.27it/s]
100%|██████████| 44/44 [00:00<00:00, 51651.10it/s]

The length of the output is 44
Processing language: jv with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.77it/s]
100%|██████████| 106/106 [00:00<00:00, 11066.77it/s]

The length of the output is 106
Processing language: ka with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.08it/s]
100%|██████████| 70/70 [00:00<00:00, 13828.24it/s]

The length of the output is 70
Processing language: kk with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:07<00:00,  3.30it/s]
100%|██████████| 43/43 [00:00<00:00, 9724.74it/s]

The length of the output is 43
Processing language: km with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  8.06it/s]
100%|██████████| 45/45 [00:00<00:00, 15317.62it/s]

The length of the output is 45
Processing language: kn with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.96it/s]
100%|██████████| 246/246 [00:00<00:00, 10900.63it/s]

The length of the output is 246
Processing language: ko with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.49it/s]
100%|██████████| 62/62 [00:00<00:00, 48908.57it/s]

The length of the output is 62
Processing language: ku with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  8.14it/s]
100%|██████████| 68/68 [00:00<00:00, 8226.97it/s]

The length of the output is 68
Processing language: la with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.09it/s]
100%|██████████| 79/79 [00:00<00:00, 9622.20it/s]

The length of the output is 79
Processing language: lb with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.95it/s]
100%|██████████| 67/67 [00:00<00:00, 22743.47it/s]

The length of the output is 67
Processing language: lmo with side context size 5
Running on 1 processes

100%|██████████| 15/15 [00:01<00:00,  8.47it/s]
100%|██████████| 28/28 [00:00<00:00, 19734.58it/s]

The length of the output is 28
Processing language: lo with side context size 5
Running on 1 processes

100%|██████████| 13/13 [00:01<00:00,  8.94it/s]
100%|██████████| 45/45 [00:00<00:00, 21036.97it/s]

The length of the output is 45
Processing language: lt with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.87it/s]
100%|██████████| 35/35 [00:00<00:00, 24454.55it/s]

The length of the output is 35
Processing language: lv with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.67it/s]
100%|██████████| 84/84 [00:00<00:00, 16618.16it/s]

The length of the output is 84
Processing language: mg with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  8.22it/s]
100%|██████████| 155/155 [00:00<00:00, 16854.20it/s]

The length of the output is 155
Processing language: min with side context size 5
Running on 1 processes

100%|██████████| 12/12 [00:01<00:00,  6.58it/s]
100%|██████████| 51/51 [00:00<00:00, 8855.34it/s]

The length of the output is 51
Processing language: mk with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.52it/s]
100%|██████████| 72/72 [00:00<00:00, 18541.77it/s]

The length of the output is 72
Processing language: mn with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.78it/s]
100%|██████████| 111/111 [00:00<00:00, 15194.27it/s]

The length of the output is 111
Processing language: mr with side context size 5
Running on 1 processes

 52%|█████▏    | 13/25 [00:02<00:01,  7.23it/s]

No sentences found in 1
18525_1508230_sentences.jsonl
No sentences found in 1
15046_1494708_sentences.jsonl

100%|██████████| 25/25 [00:03<00:00,  6.47it/s]
100%|██████████| 49/49 [00:00<00:00, 9384.52it/s]

The length of the output is 49
Processing language: ms with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.93it/s]
100%|██████████| 47/47 [00:00<00:00, 13136.02it/s]

The length of the output is 47
Processing language: ne with side context size 5
Running on 1 processes
No sentences found in 1
47519_1029770_sentences.jsonl

100%|██████████| 25/25 [00:02<00:00,  9.48it/s]
  0%|          | 0/53 [00:00<?, ?it/s]

The length of the output is 53
Processing language: nl with side context size 5

100%|██████████| 53/53 [00:00<00:00, 11077.24it/s]

Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  6.20it/s]
100%|██████████| 73/73 [00:00<00:00, 25229.42it/s]

The length of the output is 73
Processing language: no with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:07<00:00,  3.33it/s]
100%|██████████| 456/456 [00:00<00:00, 12937.41it/s]

The length of the output is 456
Processing language: oc with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.53it/s]
100%|██████████| 77/77 [00:00<00:00, 16398.97it/s]

The length of the output is 77
Processing language: om with side context size 5
Running on 1 processes

100%|██████████| 11/11 [00:02<00:00,  4.79it/s]
100%|██████████| 35/35 [00:00<00:00, 7954.09it/s]

The length of the output is 35
Processing language: pa with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:02<00:00,  9.27it/s]
100%|██████████| 114/114 [00:00<00:00, 10038.01it/s]

The length of the output is 114
Processing language: pl with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.60it/s]
100%|██████████| 50/50 [00:00<00:00, 16398.09it/s]

The length of the output is 50
Processing language: pms with side context size 5
Running on 1 processes

100%|██████████| 2/2 [00:00<00:00,  8.35it/s]
100%|██████████| 2/2 [00:00<00:00, 4251.70it/s]

The length of the output is 2
Processing language: ps with side context size 5
Running on 1 processes

100%|██████████| 9/9 [00:01<00:00,  8.04it/s]
100%|██████████| 11/11 [00:00<00:00, 6919.22it/s]

The length of the output is 11
Processing language: pt with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.32it/s]
100%|██████████| 58/58 [00:00<00:00, 13897.15it/s]

The length of the output is 58
Processing language: ro with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.41it/s]
100%|██████████| 39/39 [00:00<00:00, 8788.84it/s]

The length of the output is 39
Processing language: ru with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  6.13it/s]
100%|██████████| 106/106 [00:00<00:00, 13024.26it/s]

The length of the output is 106
Processing language: sa with side context size 5
Running on 1 processes

100%|██████████| 6/6 [00:00<00:00,  8.60it/s]
100%|██████████| 34/34 [00:00<00:00, 4835.75it/s]

The length of the output is 34
Processing language: scn with side context size 5
Running on 1 processes

100%|██████████| 13/13 [00:01<00:00,  9.15it/s]
100%|██████████| 23/23 [00:00<00:00, 10963.63it/s]

The length of the output is 23
Processing language: sco with side context size 5
Running on 1 processes

100%|██████████| 17/17 [00:01<00:00,  9.57it/s]
100%|██████████| 44/44 [00:00<00:00, 16088.34it/s]

The length of the output is 44
Processing language: sd with side context size 5
Running on 1 processes

100%|██████████| 7/7 [00:00<00:00,  7.85it/s]
100%|██████████| 13/13 [00:00<00:00, 16175.01it/s]

The length of the output is 13
Processing language: sh with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.08it/s]
100%|██████████| 240/240 [00:00<00:00, 17037.03it/s]

The length of the output is 240
Processing language: si with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.44it/s]
  0%|          | 0/69 [00:00<?, ?it/s]

The length of the output is 69

100%|██████████| 69/69 [00:00<00:00, 7755.57it/s]

Processing language: simple with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  8.10it/s]
100%|██████████| 116/116 [00:00<00:00, 20868.97it/s]

The length of the output is 116
Processing language: sk with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.82it/s]
100%|██████████| 74/74 [00:00<00:00, 23410.66it/s]

The length of the output is 74
Processing language: sl with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.30it/s]
100%|██████████| 137/137 [00:00<00:00, 8814.54it/s]

The length of the output is 137
Processing language: so with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.63it/s]
100%|██████████| 58/58 [00:00<00:00, 9794.25it/s]

The length of the output is 58
Processing language: sq with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.54it/s]
100%|██████████| 116/116 [00:00<00:00, 7470.51it/s]

The length of the output is 116
Processing language: sr with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.43it/s]
100%|██████████| 91/91 [00:00<00:00, 9899.92it/s]

The length of the output is 91
Processing language: su with side context size 5
Running on 1 processes

100%|██████████| 7/7 [00:00<00:00,  7.77it/s]
100%|██████████| 8/8 [00:00<00:00, 6245.01it/s]

The length of the output is 8
Processing language: sv with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  6.04it/s]
100%|██████████| 66/66 [00:00<00:00, 22476.78it/s]

The length of the output is 66
Processing language: sw with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:02<00:00,  8.94it/s]
100%|██████████| 72/72 [00:00<00:00, 22211.67it/s]

The length of the output is 72
Processing language: ta with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.46it/s]
100%|██████████| 67/67 [00:00<00:00, 18429.85it/s]

The length of the output is 67
Processing language: te with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.97it/s]
100%|██████████| 36/36 [00:00<00:00, 27998.32it/s]

The length of the output is 36
Processing language: tg with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.73it/s]
100%|██████████| 42/42 [00:00<00:00, 29857.76it/s]

The length of the output is 42
Processing language: tl with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.82it/s]
100%|██████████| 106/106 [00:00<00:00, 14192.56it/s]

The length of the output is 106
Processing language: tr with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.44it/s]
100%|██████████| 109/109 [00:00<00:00, 21736.28it/s]

The length of the output is 109
Processing language: tt with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  5.58it/s]
100%|██████████| 77/77 [00:00<00:00, 35077.81it/s]

The length of the output is 77
Processing language: ug with side context size 5
Running on 1 processes
The length of the output is 1

100%|██████████| 1/1 [00:00<00:00,  7.53it/s]
100%|██████████| 1/1 [00:00<00:00, 2015.52it/s]

Processing language: uk with side context size 5
Running on 1 processes

100%|██████████| 2/2 [00:00<00:00,  7.55it/s]
100%|██████████| 2/2 [00:00<00:00, 3515.76it/s]

The length of the output is 2
Processing language: ur with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:06<00:00,  4.15it/s]
  0%|          | 0/42 [00:00<?, ?it/s]

The length of the output is 42

100%|██████████| 42/42 [00:00<00:00, 1569.70it/s]

Processing language: uz with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  7.61it/s]
100%|██████████| 94/94 [00:00<00:00, 17016.17it/s]

The length of the output is 94
Processing language: vi with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:04<00:00,  6.09it/s]
100%|██████████| 77/77 [00:00<00:00, 7893.09it/s]

The length of the output is 77
Processing language: vo with side context size 5
Running on 1 processes

100%|██████████| 4/4 [00:00<00:00, 10.23it/s]
100%|██████████| 11/11 [00:00<00:00, 17260.51it/s]

The length of the output is 11
Processing language: xh with side context size 5
Running on 1 processes
The length of the output is 1

100%|██████████| 1/1 [00:00<00:00,  6.54it/s]
100%|██████████| 1/1 [00:00<00:00, 1901.32it/s]

Processing language: yi with side context size 5
Running on 1 processes

100%|██████████| 19/19 [00:02<00:00,  8.00it/s]
100%|██████████| 37/37 [00:00<00:00, 4447.58it/s]

The length of the output is 37
Processing language: zh with side context size 5
Running on 1 processes

100%|██████████| 25/25 [00:03<00:00,  6.43it/s]
100%|██████████| 86/86 [00:00<00:00, 46114.82it/s]

The length of the output is 86

**Merging**

In [11]:
test_data_dir = contexts_splitted_data_dir
output_dir = ready_to_score_data_dir

subprocess.run([
    "python", "modular_merge_data.py",
    "--test_data_dir", test_data_dir,
    "--raw_data_dir", simple_render_raw_data_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--output_dir", output_dir,
    "--ignore_warnings"
])

first_lang = langs[0]
first_context_size = str(side_context_sizes[0])
scored_files_example = os.listdir(output_dir)
scored_files_example = list(filter(lambda x: (first_lang in x and first_context_size in x), scored_files_example))
final_input_data_path = os.path.join(output_dir, scored_files_example[0])

final_input_data_df = pd.read_parquet(final_input_data_path)
display(final_input_data_df.head(5))

Saving mention maps
Processing language af (1/108)
Finished processing language af
Processing language am (2/108)
Finished processing language am
Processing language an (3/108)
Finished processing language an
Processing language ar (4/108)
Finished processing language ar
Processing language ary (5/108)
Finished processing language ary
Processing language as (6/108)
Finished processing language as
Processing language ast (7/108)
Finished processing language ast
Processing language az (8/108)
Finished processing language az
Processing language azb (9/108)
Finished processing language azb
Processing language ba (10/108)
Finished processing language ba
Processing language bar (11/108)
Finished processing language bar
Processing language be (12/108)
Finished processing language be
Processing language bg (13/108)
Finished processing language bg
Processing language br (14/108)
Finished processing language br
Processing language bs (15/108)
Finished processing language bs
Processing language ca (16/108)
Finished processing language ca
Processing language ce (17/108)
Finished processing language ce
Processing language cs (18/108)
Finished processing language cs
Processing language cv (19/108)
Finished processing language cv
Processing language cy (20/108)
Finished processing language cy
Processing language da (21/108)
Finished processing language da
Processing language de (22/108)
Finished processing language de
Processing language el (23/108)
Finished processing language el
Processing language en (24/108)
Finished processing language en
Processing language eo (25/108)
Finished processing language eo
Processing language es (26/108)
Finished processing language es
Processing language et (27/108)
Finished processing language et
Processing language eu (28/108)
Finished processing language eu
Processing language fa (29/108)
Finished processing language fa
Processing language fi (30/108)
Finished processing language fi
Processing language fr (31/108)
Finished processing language fr
Processing language fy (32/108)
Finished processing language fy
Processing language ga (33/108)
Finished processing language ga
Processing language gd (34/108)
Finished processing language gd
Processing language gl (35/108)
Finished processing language gl
Processing language gu (36/108)
Finished processing language gu
Processing language ha (37/108)
Finished processing language ha
Processing language he (38/108)
Finished processing language he
Processing language hi (39/108)
Finished processing language hi
Processing language hr (40/108)
Finished processing language hr
Processing language hu (41/108)
Finished processing language hu
Processing language hy (42/108)
Finished processing language hy
Processing language id (43/108)
Finished processing language id
Processing language io (44/108)
Finished processing language io
Processing language is (45/108)
Finished processing language is
Processing language it (46/108)
Finished processing language it
Processing language ja (47/108)
Finished processing language ja
Processing language jv (48/108)
Finished processing language jv
Processing language ka (49/108)
Finished processing language ka
Processing language kk (50/108)
Finished processing language kk
Processing language km (51/108)
Finished processing language km
Processing language kn (52/108)
Finished processing language kn
Processing language ko (53/108)
Finished processing language ko
Processing language ku (54/108)
Finished processing language ku
Processing language la (55/108)
Finished processing language la
Processing language lb (56/108)
Finished processing language lb
Processing language lmo (57/108)
Finished processing language lmo
Processing language lo (58/108)
Finished processing language lo
Processing language lt (59/108)
Finished processing language lt
Processing language lv (60/108)
Finished processing language lv
Processing language mg (61/108)
Finished processing language mg
Processing language min (62/108)
Finished processing language min
Processing language mk (63/108)
Finished processing language mk
Processing language mn (64/108)
Finished processing language mn
Processing language mr (65/108)
Finished processing language mr
Processing language ms (66/108)
Finished processing language ms
Processing language ne (67/108)
Finished processing language ne
Processing language nl (68/108)
Finished processing language nl
Processing language no (69/108)
Finished processing language no
Processing language oc (70/108)
Finished processing language oc
Processing language om (71/108)
Finished processing language om
Processing language pa (72/108)
Finished processing language pa
Processing language pl (73/108)
Finished processing language pl
Processing language pms (74/108)
Finished processing language pms
Processing language ps (75/108)
Finished processing language ps
Processing language pt (76/108)
Finished processing language pt
Processing language ro (77/108)
Finished processing language ro
Processing language ru (78/108)
Finished processing language ru
Processing language sa (79/108)
Finished processing language sa
Processing language scn (80/108)
Finished processing language scn
Processing language sco (81/108)
Finished processing language sco
Processing language sd (82/108)
Finished processing language sd
Processing language sh (83/108)
Finished processing language sh
Processing language si (84/108)
Finished processing language si
Processing language simple (85/108)
Finished processing language simple
Processing language sk (86/108)
Finished processing language sk
Processing language sl (87/108)
Finished processing language sl
Processing language so (88/108)
Finished processing language so
Processing language sq (89/108)
Finished processing language sq
Processing language sr (90/108)
Finished processing language sr
Processing language su (91/108)
Finished processing language su
Processing language sv (92/108)
Finished processing language sv
Processing language sw (93/108)
Finished processing language sw
Processing language ta (94/108)
Finished processing language ta
Processing language te (95/108)
Finished processing language te
Processing language tg (96/108)
Finished processing language tg
Processing language tl (97/108)
Finished processing language tl
Processing language tr (98/108)
Finished processing language tr
Processing language tt (99/108)
Finished processing language tt
Processing language ug (100/108)
Finished processing language ug
Processing language uk (101/108)
Finished processing language uk
Processing language ur (102/108)
Finished processing language ur
Processing language uz (103/108)
Finished processing language uz
Processing language vi (104/108)
Finished processing language vi
Processing language vo (105/108)
Finished processing language vo
Processing language xh (106/108)
Finished processing language xh
Processing language yi (107/108)
Finished processing language yi
Processing language zh (108/108)
Finished processing language zh
Processing language af (1/108)
Loaded pages
Loaded redirects

100%|██████████| 110890/110890 [00:00<00:00, 846067.90it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 56 links for language af
Removed 0 links because of empty contexts
Removed 10 links because target title is not in source titles
Removed 14 links because of missing section
After cleaning, there are 32 links for language af
Finished processing language af
Processing language am (2/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 22 links for language am
Removed 0 links because of empty contexts
Removed 9 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 13 links for language am
Finished processing language am
Processing language an (3/108)

100%|██████████| 12954/12954 [00:00<00:00, 837232.09it/s]

Loaded pages
Loaded redirects

100%|██████████| 40772/40772 [00:00<00:00, 626447.57it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 79 links for language an
Removed 0 links because of empty contexts
Removed 26 links because target title is not in source titles
Removed 31 links because of missing section
After cleaning, there are 22 links for language an
Finished processing language an
Processing language ar (4/108)
Loaded pages
Loaded redirects

100%|██████████| 1209639/1209639 [00:01<00:00, 802469.30it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 94 links for language ar
Removed 0 links because of empty contexts
Removed 19 links because target title is not in source titles
Removed 14 links because of missing section
After cleaning, there are 61 links for language ar
Finished processing language ar
Processing language ary (5/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 48 links for language ary
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 40 links for language ary
Finished processing language ary
Processing language as (6/108)

100%|██████████| 7149/7149 [00:00<00:00, 696711.73it/s]

Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 68 links for language as
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 30 links because of missing section
After cleaning, there are 33 links for language as

100%|██████████| 11809/11809 [00:00<00:00, 638963.53it/s]

Finished processing language as
Processing language ast (7/108)
Loaded pages
Loaded redirects

100%|██████████| 128435/128435 [00:00<00:00, 675483.56it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 45 links for language ast
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 10 links because of missing section
After cleaning, there are 29 links for language ast
Finished processing language ast
Processing language az (8/108)
Loaded pages
Loaded redirects

100%|██████████| 187134/187134 [00:00<00:00, 734685.54it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 108 links for language az
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 15 links because of missing section
After cleaning, there are 81 links for language az
Finished processing language az
Processing language azb (9/108)
Loaded pages
Loaded redirects

100%|██████████| 242070/242070 [00:00<00:00, 681255.89it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 23 links for language azb
Removed 0 links because of empty contexts
Removed 0 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 23 links for language azb
Finished processing language azb
Processing language ba (10/108)
Loaded pages
Loaded redirects

100%|██████████| 62380/62380 [00:00<00:00, 677678.13it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 65 links for language ba
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 18 links because of missing section
After cleaning, there are 41 links for language ba
Finished processing language ba
Processing language bar (11/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 33 links for language bar
Removed 0 links because of empty contexts
Removed 10 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 22 links for language bar

100%|██████████| 26971/26971 [00:00<00:00, 821648.56it/s]

Finished processing language bar
Processing language be (12/108)
Loaded pages
Loaded redirects

100%|██████████| 231746/231746 [00:00<00:00, 854355.59it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 65 links for language be
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 34 links because of missing section
After cleaning, there are 20 links for language be
Finished processing language be
Processing language bg (13/108)
Loaded pages
Loaded redirects

100%|██████████| 287825/287825 [00:00<00:00, 902821.29it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 86 links for language bg
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 9 links because of missing section
After cleaning, there are 66 links for language bg
Finished processing language bg
Processing language br (14/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 44586/44586 [00:00<00:00, 862702.87it/s]

Loaded links for context_size_5
Originally, there are 122 links for language br
Removed 0 links because of empty contexts
Removed 68 links because target title is not in source titles
Removed 39 links because of missing section
After cleaning, there are 15 links for language br
Finished processing language br
Processing language bs (15/108)
Loaded pages
Loaded redirects

100%|██████████| 89499/89499 [00:00<00:00, 692120.36it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 87 links for language bs
Removed 0 links because of empty contexts
Removed 13 links because target title is not in source titles
Removed 21 links because of missing section
After cleaning, there are 53 links for language bs
Finished processing language bs
Processing language ca (16/108)
Loaded pages
Loaded redirects

100%|██████████| 730261/730261 [00:00<00:00, 861973.26it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 323 links for language ca
Removed 0 links because of empty contexts
Removed 117 links because target title is not in source titles
Removed 70 links because of missing section
After cleaning, there are 136 links for language ca
Finished processing language ca
Processing language ce (17/108)
Loaded pages
Loaded redirects

100%|██████████| 599478/599478 [00:00<00:00, 809337.20it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 575 links for language ce
Removed 0 links because of empty contexts
Removed 439 links because target title is not in source titles
Removed 129 links because of missing section
After cleaning, there are 7 links for language ce
Finished processing language ce
Processing language cs (18/108)
Loaded pages
Loaded redirects

100%|██████████| 529676/529676 [00:00<00:00, 844614.07it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 178 links for language cs
Removed 0 links because of empty contexts
Removed 22 links because target title is not in source titles
Removed 72 links because of missing section
After cleaning, there are 84 links for language cs
Finished processing language cs
Processing language cv (19/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 48283/48283 [00:00<00:00, 839699.06it/s]

Loaded links for context_size_5
Originally, there are 241 links for language cv
Removed 0 links because of empty contexts
Removed 92 links because target title is not in source titles
Removed 82 links because of missing section
After cleaning, there are 67 links for language cv
Finished processing language cv
Processing language cy (20/108)
Loaded pages
Loaded redirects

100%|██████████| 269727/269727 [00:00<00:00, 769087.04it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 82 links for language cy
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 74 links for language cy
Finished processing language cy
Processing language da (21/108)
Loaded pages
Loaded redirects

100%|██████████| 293819/293819 [00:00<00:00, 885976.12it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 74 links for language da
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 23 links because of missing section
After cleaning, there are 44 links for language da
Finished processing language da
Processing language de (22/108)
Loaded pages
Loaded redirects

100%|██████████| 2826417/2826417 [00:03<00:00, 790952.07it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 716 links for language de
Removed 0 links because of empty contexts
Removed 164 links because target title is not in source titles
Removed 456 links because of missing section
After cleaning, there are 96 links for language de
Finished processing language de
Processing language el (23/108)
Loaded pages
Loaded redirects

100%|██████████| 224166/224166 [00:00<00:00, 883415.00it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 104 links for language el
Removed 0 links because of empty contexts
Removed 20 links because target title is not in source titles
Removed 18 links because of missing section
After cleaning, there are 66 links for language el
Finished processing language el
Processing language en (24/108)
Loaded pages
Loaded redirects

100%|██████████| 6708565/6708565 [00:09<00:00, 683636.33it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 52 links for language en
Removed 0 links because of empty contexts
Removed 9 links because target title is not in source titles
Removed 2 links because of missing section
After cleaning, there are 41 links for language en
Finished processing language en
Processing language eo (25/108)
Loaded pages
Loaded redirects

100%|██████████| 339641/339641 [00:00<00:00, 868562.25it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 164 links for language eo
Removed 0 links because of empty contexts
Removed 13 links because target title is not in source titles
Removed 62 links because of missing section
After cleaning, there are 89 links for language eo
Finished processing language eo
Processing language es (26/108)
Loaded pages
Loaded redirects

100%|██████████| 1829995/1829995 [00:02<00:00, 786885.21it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 85 links for language es
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 17 links because of missing section
After cleaning, there are 56 links for language es
Finished processing language es
Processing language et (27/108)
Loaded pages
Loaded redirects

100%|██████████| 235263/235263 [00:00<00:00, 854598.34it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 43 links for language et
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 8 links because of missing section
After cleaning, there are 29 links for language et
Finished processing language et
Processing language eu (28/108)
Loaded pages
Loaded redirects

100%|██████████| 411531/411531 [00:00<00:00, 911297.16it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 88 links for language eu
Removed 0 links because of empty contexts
Removed 25 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 56 links for language eu
Finished processing language eu
Processing language fa (29/108)
Loaded pages
Loaded redirects

100%|██████████| 967157/967157 [00:01<00:00, 785582.12it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 63 links for language fa
Removed 0 links because of empty contexts
Removed 14 links because target title is not in source titles
Removed 2 links because of missing section
After cleaning, there are 47 links for language fa
Finished processing language fa
Processing language fi (30/108)
Loaded pages
Loaded redirects

100%|██████████| 552836/552836 [00:00<00:00, 858099.73it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 57 links for language fi
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 2 links because of missing section
After cleaning, there are 47 links for language fi
Finished processing language fi
Processing language fr (31/108)
Loaded pages
Loaded redirects

100%|██████████| 2515482/2515482 [00:03<00:00, 809085.41it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 52 links for language fr
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 37 links for language fr
Finished processing language fr
Processing language fy (32/108)
Loaded pages
Loaded redirects

100%|██████████| 50798/50798 [00:00<00:00, 834219.86it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 152 links for language fy
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 49 links because of missing section
After cleaning, there are 88 links for language fy
Finished processing language fy
Processing language ga (33/108)
Loaded pages
Loaded redirects

100%|██████████| 55867/55867 [00:00<00:00, 672073.65it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 62 links for language ga
Removed 0 links because of empty contexts
Removed 20 links because target title is not in source titles
Removed 20 links because of missing section
After cleaning, there are 22 links for language ga
Finished processing language ga
Processing language gd (34/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 28 links for language gd
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 8 links because of missing section
After cleaning, there are 17 links for language gd
Finished processing language gd
Processing language gl (35/108)

100%|██████████| 15854/15854 [00:00<00:00, 673259.51it/s]

Loaded pages
Loaded redirects

100%|██████████| 195281/195281 [00:00<00:00, 741846.15it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 74 links for language gl
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 16 links because of missing section
After cleaning, there are 53 links for language gl
Finished processing language gl
Processing language gu (36/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 52 links for language gu
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 16 links because of missing section
After cleaning, there are 35 links for language gu

100%|██████████| 30230/30230 [00:00<00:00, 836585.99it/s]

Finished processing language gu
Processing language ha (37/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 44 links for language ha
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 30 links for language ha
Finished processing language ha
Processing language he (38/108)

100%|██████████| 30053/30053 [00:00<00:00, 941680.12it/s]

Loaded pages
Loaded redirects

100%|██████████| 339595/339595 [00:00<00:00, 890254.62it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 85 links for language he
Removed 0 links because of empty contexts
Removed 16 links because target title is not in source titles
Removed 6 links because of missing section
After cleaning, there are 63 links for language he
Finished processing language he
Processing language hi (39/108)
Loaded pages
Loaded redirects

100%|██████████| 156710/156710 [00:00<00:00, 759127.03it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 68 links for language hi
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 16 links because of missing section
After cleaning, there are 44 links for language hi
Finished processing language hi
Processing language hr (40/108)
Loaded pages
Loaded redirects

100%|██████████| 193757/193757 [00:00<00:00, 783986.56it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 71 links for language hr
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 11 links because of missing section
After cleaning, there are 48 links for language hr
Finished processing language hr
Processing language hu (41/108)
Loaded pages
Loaded redirects

100%|██████████| 525500/525500 [00:00<00:00, 918958.67it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 62 links for language hu
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 52 links for language hu
Finished processing language hu
Processing language hy (42/108)
Loaded pages
Loaded redirects

100%|██████████| 295280/295280 [00:00<00:00, 826996.95it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 527 links for language hy
Removed 0 links because of empty contexts
Removed 77 links because target title is not in source titles
Removed 367 links because of missing section
After cleaning, there are 83 links for language hy
Finished processing language hy
Processing language id (43/108)
Loaded pages
Loaded redirects

100%|██████████| 645165/645165 [00:00<00:00, 837839.81it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 65 links for language id
Removed 0 links because of empty contexts
Removed 9 links because target title is not in source titles
Removed 4 links because of missing section
After cleaning, there are 52 links for language id
Finished processing language id
Processing language io (44/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 69 links for language io
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 11 links because of missing section
After cleaning, there are 56 links for language io

100%|██████████| 38573/38573 [00:00<00:00, 905694.29it/s]

Finished processing language io
Processing language is (45/108)
Loaded pages
Loaded redirects

100%|██████████| 56361/56361 [00:00<00:00, 638450.32it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 130 links for language is
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 43 links because of missing section
After cleaning, there are 80 links for language is
Finished processing language is
Processing language it (46/108)
Loaded pages
Loaded redirects

100%|██████████| 1775929/1775929 [00:02<00:00, 743417.72it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 80 links for language it
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 2 links because of missing section
After cleaning, there are 70 links for language it
Finished processing language it
Processing language ja (47/108)
Loaded pages
Loaded redirects

100%|██████████| 1369610/1369610 [00:01<00:00, 792141.23it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 44 links for language ja
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 13 links because of missing section
After cleaning, there are 27 links for language ja
Finished processing language ja
Processing language jv (48/108)
Loaded pages
Loaded redirects

100%|██████████| 70540/70540 [00:00<00:00, 810870.04it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 106 links for language jv
Removed 0 links because of empty contexts
Removed 27 links because target title is not in source titles
Removed 20 links because of missing section
After cleaning, there are 59 links for language jv
Finished processing language jv
Processing language ka (49/108)
Loaded pages
Loaded redirects

100%|██████████| 163136/163136 [00:00<00:00, 683715.52it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 70 links for language ka
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 65 links for language ka
Finished processing language ka
Processing language kk (50/108)
Loaded pages
Loaded redirects

100%|██████████| 233608/233608 [00:00<00:00, 720231.93it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 43 links for language kk
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 31 links for language kk
Finished processing language kk
Processing language km (51/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 9796/9796 [00:00<00:00, 724965.19it/s]

Loaded links for context_size_5
Originally, there are 45 links for language km
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 32 links for language km
Finished processing language km
Processing language kn (52/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 27889/27889 [00:00<00:00, 566245.25it/s]

Loaded links for context_size_5
Originally, there are 246 links for language kn
Removed 0 links because of empty contexts
Removed 81 links because target title is not in source titles
Removed 57 links because of missing section
After cleaning, there are 108 links for language kn
Finished processing language kn
Processing language ko (53/108)
Loaded pages
Loaded redirects

100%|██████████| 630490/630490 [00:00<00:00, 822946.93it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 62 links for language ko
Removed 0 links because of empty contexts
Removed 21 links because target title is not in source titles
Removed 6 links because of missing section
After cleaning, there are 35 links for language ko
Finished processing language ko
Processing language ku (54/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 53321/53321 [00:00<00:00, 863272.23it/s]

Loaded links for context_size_5
Originally, there are 68 links for language ku
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 60 links for language ku
Finished processing language ku
Processing language la (55/108)
Loaded pages
Loaded redirects

100%|██████████| 137977/137977 [00:00<00:00, 692257.39it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 79 links for language la
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 18 links because of missing section
After cleaning, there are 54 links for language la
Finished processing language la
Processing language lb (56/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 61539/61539 [00:00<00:00, 871236.09it/s]

Loaded links for context_size_5
Originally, there are 67 links for language lb
Removed 0 links because of empty contexts
Removed 24 links because target title is not in source titles
Removed 12 links because of missing section
After cleaning, there are 31 links for language lb
Finished processing language lb
Processing language lmo (57/108)
Loaded pages
Loaded redirects

100%|██████████| 71919/71919 [00:00<00:00, 657023.82it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 28 links for language lmo
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 18 links because of missing section
After cleaning, there are 6 links for language lmo
Finished processing language lmo
Processing language lo (58/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 45 links for language lo
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 14 links because of missing section
After cleaning, there are 27 links for language lo
Finished processing language lo
Processing language lt (59/108)

100%|██████████| 4750/4750 [00:00<00:00, 565109.74it/s]

Loaded pages
Loaded redirects

100%|██████████| 209809/209809 [00:00<00:00, 812991.87it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 35 links for language lt
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 6 links because of missing section
After cleaning, there are 25 links for language lt
Finished processing language lt
Processing language lv (60/108)
Loaded pages
Loaded redirects

100%|██████████| 120915/120915 [00:00<00:00, 786274.72it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 84 links for language lv
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 30 links because of missing section
After cleaning, there are 49 links for language lv
Finished processing language lv
Processing language mg (61/108)
Loaded pages
Loaded redirects

100%|██████████| 95653/95653 [00:00<00:00, 875910.71it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 155 links for language mg
Removed 0 links because of empty contexts
Removed 30 links because target title is not in source titles
Removed 24 links because of missing section
After cleaning, there are 101 links for language mg
Finished processing language mg
Processing language min (62/108)
Loaded pages
Loaded redirects

100%|██████████| 226012/226012 [00:00<00:00, 987969.89it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 51 links for language min
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 21 links because of missing section
After cleaning, there are 24 links for language min
Finished processing language min
Processing language mk (63/108)
Loaded pages
Loaded redirects

100%|██████████| 135573/135573 [00:00<00:00, 700179.99it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 72 links for language mk
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 10 links because of missing section
After cleaning, there are 47 links for language mk
Finished processing language mk
Processing language mn (64/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 22402/22402 [00:00<00:00, 775017.51it/s]

Loaded links for context_size_5
Originally, there are 111 links for language mn
Removed 0 links because of empty contexts
Removed 21 links because target title is not in source titles
Removed 20 links because of missing section
After cleaning, there are 70 links for language mn
Finished processing language mn
Processing language mr (65/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 60208/60208 [00:00<00:00, 608720.29it/s]

Loaded links for context_size_5
Originally, there are 49 links for language mr
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 6 links because of missing section
After cleaning, there are 32 links for language mr
Finished processing language mr
Processing language ms (66/108)
Loaded pages
Loaded redirects

100%|██████████| 362531/362531 [00:00<00:00, 782030.09it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 47 links for language ms
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 12 links because of missing section
After cleaning, there are 24 links for language ms
Finished processing language ms
Processing language ne (67/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 53 links for language ne
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 12 links because of missing section
After cleaning, there are 34 links for language ne

100%|██████████| 31846/31846 [00:00<00:00, 738418.62it/s]

Finished processing language ne
Processing language nl (68/108)
Loaded pages
Loaded redirects

100%|██████████| 2131550/2131550 [00:02<00:00, 866778.67it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 73 links for language nl
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 20 links because of missing section
After cleaning, there are 38 links for language nl
Finished processing language nl
Processing language no (69/108)
Loaded pages
Loaded redirects

100%|██████████| 610021/610021 [00:00<00:00, 841311.55it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 456 links for language no
Removed 0 links because of empty contexts
Removed 35 links because target title is not in source titles
Removed 342 links because of missing section
After cleaning, there are 79 links for language no
Finished processing language no
Processing language oc (70/108)
Loaded pages
Loaded redirects

100%|██████████| 88093/88093 [00:00<00:00, 824369.09it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 77 links for language oc
Removed 0 links because of empty contexts
Removed 21 links because target title is not in source titles
Removed 8 links because of missing section
After cleaning, there are 48 links for language oc
Finished processing language oc
Processing language om (71/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 35 links for language om
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 4 links because of missing section
After cleaning, there are 28 links for language om

100%|██████████| 1684/1684 [00:00<00:00, 603177.45it/s]

Finished processing language om
Processing language pa (72/108)
Loaded pages
Loaded redirects

100%|██████████| 49263/49263 [00:00<00:00, 579699.40it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 114 links for language pa
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 39 links because of missing section
After cleaning, there are 60 links for language pa
Finished processing language pa
Processing language pl (73/108)
Loaded pages
Loaded redirects

100%|██████████| 1561597/1561597 [00:01<00:00, 896494.68it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 50 links for language pl
Removed 0 links because of empty contexts
Removed 13 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 30 links for language pl
Finished processing language pl
Processing language pms (74/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 2 links for language pms
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 0 links for language pms
Finished processing language pms
Processing language ps (75/108)

100%|██████████| 2593/2593 [00:00<00:00, 677199.89it/s]

Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 11 links for language ps
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 2 links because of missing section
After cleaning, there are 8 links for language ps
Finished processing language ps
Processing language pt (76/108)

100%|██████████| 16165/16165 [00:00<00:00, 853496.70it/s]

Loaded pages
Loaded redirects

100%|██████████| 1103653/1103653 [00:01<00:00, 869514.85it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 58 links for language pt
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 10 links because of missing section
After cleaning, there are 37 links for language pt
Finished processing language pt
Processing language ro (77/108)
Loaded pages
Loaded redirects

100%|██████████| 439427/439427 [00:00<00:00, 840298.82it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 39 links for language ro
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 9 links because of missing section
After cleaning, there are 19 links for language ro
Finished processing language ro
Processing language ru (78/108)
Loaded pages
Loaded redirects

100%|██████████| 1920674/1920674 [00:02<00:00, 722296.76it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 106 links for language ru
Removed 0 links because of empty contexts
Removed 75 links because target title is not in source titles
Removed 9 links because of missing section
After cleaning, there are 22 links for language ru
Finished processing language ru
Processing language sa (79/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 34 links for language sa
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 9 links because of missing section
After cleaning, there are 19 links for language sa
Finished processing language sa
Processing language scn (80/108)

100%|██████████| 10559/10559 [00:00<00:00, 711734.13it/s]

Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 23 links for language scn
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 5 links because of missing section
After cleaning, there are 6 links for language scn
Finished processing language scn
Processing language sco (81/108)

100%|██████████| 23820/23820 [00:00<00:00, 876834.89it/s]

Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 44 links for language sco
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 43 links for language sco

100%|██████████| 35565/35565 [00:00<00:00, 866468.91it/s]

Finished processing language sco
Processing language sd (82/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 13 links for language sd
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 6 links for language sd
Finished processing language sd
Processing language sh (83/108)

100%|██████████| 13456/13456 [00:00<00:00, 846421.73it/s]

Loaded pages
Loaded redirects

100%|██████████| 456485/456485 [00:00<00:00, 749500.93it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 240 links for language sh
Removed 0 links because of empty contexts
Removed 54 links because target title is not in source titles
Removed 99 links because of missing section
After cleaning, there are 87 links for language sh
Finished processing language sh
Processing language si (84/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 20353/20353 [00:00<00:00, 782807.00it/s]

Loaded links for context_size_5
Originally, there are 69 links for language si
Removed 0 links because of empty contexts
Removed 18 links because target title is not in source titles
Removed 16 links because of missing section
After cleaning, there are 35 links for language si
Finished processing language si
Processing language simple (85/108)
Loaded pages
Loaded redirects

100%|██████████| 238680/238680 [00:00<00:00, 871572.14it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 116 links for language simple
Removed 0 links because of empty contexts
Removed 9 links because target title is not in source titles
Removed 58 links because of missing section
After cleaning, there are 49 links for language simple
Finished processing language simple
Processing language sk (86/108)
Loaded pages
Loaded redirects

100%|██████████| 242165/242165 [00:00<00:00, 936512.75it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 74 links for language sk
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 61 links for language sk
Finished processing language sk
Processing language sl (87/108)
Loaded pages
Loaded redirects

100%|██████████| 181970/181970 [00:00<00:00, 897830.35it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 137 links for language sl
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 54 links because of missing section
After cleaning, there are 71 links for language sl
Finished processing language sl
Processing language so (88/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 58 links for language so
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 27 links because of missing section
After cleaning, there are 30 links for language so
Finished processing language so
Processing language sq (89/108)

100%|██████████| 7472/7472 [00:00<00:00, 900078.68it/s]

Loaded pages
Loaded redirects

100%|██████████| 96859/96859 [00:00<00:00, 687674.50it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 116 links for language sq
Removed 0 links because of empty contexts
Removed 72 links because target title is not in source titles
Removed 10 links because of missing section
After cleaning, there are 34 links for language sq
Finished processing language sq
Processing language sr (90/108)
Loaded pages
Loaded redirects

100%|██████████| 665677/665677 [00:00<00:00, 686027.85it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 91 links for language sr
Removed 0 links because of empty contexts
Removed 37 links because target title is not in source titles
Removed 13 links because of missing section
After cleaning, there are 41 links for language sr
Finished processing language sr
Processing language su (91/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 8 links for language su
Removed 0 links because of empty contexts
Removed 0 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 7 links for language su

100%|██████████| 60184/60184 [00:00<00:00, 896738.14it/s]

Finished processing language su
Processing language sv (92/108)
Loaded pages
Loaded redirects

100%|██████████| 2568242/2568242 [00:03<00:00, 799653.33it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 66 links for language sv
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 32 links because of missing section
After cleaning, there are 32 links for language sv
Finished processing language sv
Processing language sw (93/108)
Loaded pages
Loaded redirects

100%|██████████| 74218/74218 [00:00<00:00, 858824.20it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 72 links for language sw
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 71 links for language sw
Finished processing language sw
Processing language ta (94/108)
Loaded pages
Loaded redirects

100%|██████████| 156364/156364 [00:00<00:00, 583631.29it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 67 links for language ta
Removed 0 links because of empty contexts
Removed 23 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 41 links for language ta
Finished processing language ta
Processing language te (95/108)
Loaded pages
Loaded redirects

100%|██████████| 81342/81342 [00:00<00:00, 578170.28it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 36 links for language te
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 20 links because of missing section
After cleaning, there are 12 links for language te
Finished processing language te
Processing language tg (96/108)
Loaded pages
Loaded redirects

100%|██████████| 108508/108508 [00:00<00:00, 600360.04it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 42 links for language tg
Removed 0 links because of empty contexts
Removed 9 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 30 links for language tg
Finished processing language tg
Processing language tl (97/108)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 43110/43110 [00:00<00:00, 819367.79it/s]

Loaded links for context_size_5
Originally, there are 106 links for language tl
Removed 0 links because of empty contexts
Removed 16 links because target title is not in source titles
Removed 36 links because of missing section
After cleaning, there are 54 links for language tl
Finished processing language tl
Processing language tr (98/108)
Loaded pages
Loaded redirects

100%|██████████| 528537/528537 [00:00<00:00, 886817.05it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 109 links for language tr
Removed 0 links because of empty contexts
Removed 45 links because target title is not in source titles
Removed 29 links because of missing section
After cleaning, there are 35 links for language tr
Finished processing language tr
Processing language tt (99/108)
Loaded pages
Loaded redirects

100%|██████████| 496485/496485 [00:00<00:00, 783242.73it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 77 links for language tt
Removed 0 links because of empty contexts
Removed 16 links because target title is not in source titles
Removed 23 links because of missing section
After cleaning, there are 38 links for language tt
Finished processing language tt
Processing language ug (100/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 1 links for language ug
Removed 0 links because of empty contexts
Removed 0 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 1 links for language ug
Finished processing language ug
Processing language uk (101/108)

100%|██████████| 5962/5962 [00:00<00:00, 607542.28it/s]

Loaded pages
Loaded redirects

100%|██████████| 358682/358682 [00:00<00:00, 775813.24it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 2 links for language uk
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 0 links for language uk
Finished processing language uk
Processing language ur (102/108)
Loaded pages
Loaded redirects

100%|██████████| 188553/188553 [00:00<00:00, 851222.40it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 42 links for language ur
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 39 links for language ur
Finished processing language ur
Processing language uz (103/108)
Loaded pages
Loaded redirects

100%|██████████| 229168/229168 [00:00<00:00, 855026.49it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 94 links for language uz
Removed 0 links because of empty contexts
Removed 5 links because target title is not in source titles
Removed 26 links because of missing section
After cleaning, there are 63 links for language uz
Finished processing language uz
Processing language vi (104/108)
Error reading file /dlabdata1/tsoares/wikidumps/viwiki-NS0-20231001/processed_data/good_pages/good_pages_55.parquet
Loaded pages
Loaded redirects

100%|██████████| 1273459/1273459 [00:01<00:00, 943141.30it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 77 links for language vi
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 37 links because of missing section
After cleaning, there are 38 links for language vi
Finished processing language vi
Processing language vo (105/108)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 11 links for language vo
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 7 links for language vo
Finished processing language vo
Processing language xh (106/108)

100%|██████████| 34315/34315 [00:00<00:00, 829529.65it/s]

Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 1 links for language xh
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 0 links for language xh
Finished processing language xh
Processing language yi (107/108)

100%|██████████| 1596/1596 [00:00<00:00, 506630.53it/s]

Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 37 links for language yi
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 33 links for language yi

100%|██████████| 15252/15252 [00:00<00:00, 781856.82it/s]

Finished processing language yi
Processing language zh (108/108)
Loaded pages
Loaded redirects

100%|██████████| 1344667/1344667 [00:01<00:00, 824684.73it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 86 links for language zh
Removed 0 links because of empty contexts
Removed 22 links because target title is not in source titles
Removed 12 links because of missing section
After cleaning, there are 52 links for language zh
Finished processing language zh

,source_title,source_ID,target_title,context,insert_indices,moved_insertion_marker,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts,target_lead
0,Flofneut_toebroodjie,406971,Engels,None,[0],None,"'n Flofneut toebroodjie (""Fluffernutter"") (ook...",Engels,Lead,None,"'n Flofneut toebroodjie (""Fluffernutter"") (ook...",2617713,2617768,None,missing_mention_with_sentence_modifications,"[{'context': ''n Flofneut toebroodjie (""Fluffe...",Engels is 'n Wes-Germaanse taal wat vanuit Eng...
1,2023_Verenigde_State_Grand_Prix,407795,Alexander_Albon,None,[10],None,*1 Alexander Albon kry 'n tydstraf van vyftien...,Alexander Albon,Wedren,None,Die 2023 Formule Een Verenigde State Grand Pri...,2624374,2624722,None,missing_span,[{'context': 'Die 2023 Formule Een Verenigde S...,Alexander Albon is 'n Brits-Thaise professione...
2,2023_Verenigde_State_Grand_Prix,407795,Lewis_Hamilton,None,[10],None,*1 Alexander Albon kry 'n tydstraf van vyftien...,Lewis Hamilton,Wedren,None,Die 2023 Formule Een Verenigde State Grand Pri...,2624374,2624722,None,missing_span,[{'context': 'Die 2023 Formule Een Verenigde S...,Lewis Hamilton is 'n Britse Formule Een-renjae...
3,Nobelprys_vir_Fisiologie_of_Geneeskunde,49085,Covid-19-pandemie,None,[8],None,Die 2023-Nobelprys vir Fisiologie of Geneeskun...,COVID-19,Lead,None,Die Nobelprys vir Fisiologie of Geneeskunde (S...,2584760,2617050,None,missing_sentence,[{'context': 'Die Nobelprys vir Fisiologie of ...,Die Koronaviruspandemie van 2019-2020 verwys n...
4,Staat_Palestina,50015,W%C3%AAreldspektrum,None,[134],None,"Wêreldspektrum, 1982, ISBN 0-908409-63-X, volu...",Wêreldspektrum,Bronne,None,"Palestina (Arabies: فلسطين, Filasṭīn), ampteli...",2606816,2617755,None,missing_mention,"[{'context': 'Palestina (Arabies: فلسطين, Fila...",Wêreldspektrum is 'n Afrikaanse ensiklopedie m...

**Scoring the contexts**

In [19]:
data_dir = ready_to_score_data_dir
output_dir = scored_data_dir

subprocess.run([
    "python", "get_scores.py",
    "--data_dir", data_dir,
    "--output_dir", output_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--models_dir", "/dlabdata1/tsoares/models",
    "--models_prefix", "roberta_full",
    "--use_section_title",
    "--use_mentions",
    "--use_cuda",
    "--only_multilingual",
    "--multilingual_name", "multilingual-all"
])

scored_files_example = os.listdir(output_dir)[0]
scored_data = pd.read_parquet(f"{output_dir}/{scored_files_example}")

exemple = scored_data['all_contexts'][0][0]

for key in exemple.keys():
    print(f"{key}:\n{exemple[key]}\n")

Processing language af
af already done fro all conexts_sizes :['5'], passing
Processing language am
am already done fro all conexts_sizes :['5'], passing
Processing language an
an already done fro all conexts_sizes :['5'], passing
Processing language ar
ar already done fro all conexts_sizes :['5'], passing
Processing language ary
ary already done fro all conexts_sizes :['5'], passing
Processing language as
as already done fro all conexts_sizes :['5'], passing
Processing language ast
ast already done fro all conexts_sizes :['5'], passing
Processing language az
az already done fro all conexts_sizes :['5'], passing
Processing language azb
azb already done fro all conexts_sizes :['5'], passing
Processing language ba
ba already done fro all conexts_sizes :['5'], passing
Processing language bar
bar already done fro all conexts_sizes :['5'], passing
Processing language be
be already done fro all conexts_sizes :['5'], passing
Processing language bg
bg already done fro all conexts_sizes :['5'], passing
Processing language br
br already done fro all conexts_sizes :['5'], passing
Processing language bs
bs already done fro all conexts_sizes :['5'], passing
Processing language ca
ca already done fro all conexts_sizes :['5'], passing
Processing language ce
ce already done fro all conexts_sizes :['5'], passing
Processing language cs
cs already done fro all conexts_sizes :['5'], passing
Processing language cv
cv already done fro all conexts_sizes :['5'], passing
Processing language cy
cy already done fro all conexts_sizes :['5'], passing
Processing language da
da already done fro all conexts_sizes :['5'], passing
Processing language de
de already done fro all conexts_sizes :['5'], passing
Processing language el
el already done fro all conexts_sizes :['5'], passing
Processing language en
en already done fro all conexts_sizes :['5'], passing
Processing language eo
eo already done fro all conexts_sizes :['5'], passing
Processing language es
es already done fro all conexts_sizes :['5'], passing
Processing language et
et already done fro all conexts_sizes :['5'], passing
Processing language eu
eu already done fro all conexts_sizes :['5'], passing
Processing language fa
fa already done fro all conexts_sizes :['5'], passing
Processing language fi
fi already done fro all conexts_sizes :['5'], passing
Processing language fr
fr already done fro all conexts_sizes :['5'], passing
Processing language fy
fy already done fro all conexts_sizes :['5'], passing
Processing language ga
ga already done fro all conexts_sizes :['5'], passing
Processing language gd
gd already done fro all conexts_sizes :['5'], passing
Processing language gl
gl already done fro all conexts_sizes :['5'], passing
Processing language gu
gu already done fro all conexts_sizes :['5'], passing
Processing language ha
ha already done fro all conexts_sizes :['5'], passing
Processing language he
he already done fro all conexts_sizes :['5'], passing
Processing language hi
hi already done fro all conexts_sizes :['5'], passing
Processing language hr
hr already done fro all conexts_sizes :['5'], passing
Processing language hu
hu already done fro all conexts_sizes :['5'], passing
Processing language hy
hy already done fro all conexts_sizes :['5'], passing
Processing language id
id already done fro all conexts_sizes :['5'], passing
Processing language io
io already done fro all conexts_sizes :['5'], passing
Processing language is
is already done fro all conexts_sizes :['5'], passing
Processing language it
it already done fro all conexts_sizes :['5'], passing
Processing language ja
ja already done fro all conexts_sizes :['5'], passing
Processing language jv
jv already done fro all conexts_sizes :['5'], passing
Processing language ka
ka already done fro all conexts_sizes :['5'], passing
Processing language kk
kk already done fro all conexts_sizes :['5'], passing
Processing language km
km already done fro all conexts_sizes :['5'], passing
Processing language kn
kn already done fro all conexts_sizes :['5'], passing
Processing language ko
ko already done fro all conexts_sizes :['5'], passing
Processing language ku
ku already done fro all conexts_sizes :['5'], passing
Processing language la
la already done fro all conexts_sizes :['5'], passing
Processing language lb
lb already done fro all conexts_sizes :['5'], passing
Processing language lmo
lmo already done fro all conexts_sizes :['5'], passing
Processing language lo
lo already done fro all conexts_sizes :['5'], passing
Processing language lt
lt already done fro all conexts_sizes :['5'], passing
Processing language lv
lv already done fro all conexts_sizes :['5'], passing
Processing language mg
mg already done fro all conexts_sizes :['5'], passing
Processing language min
min already done fro all conexts_sizes :['5'], passing
Processing language mk
mk already done fro all conexts_sizes :['5'], passing
Processing language mn
mn already done fro all conexts_sizes :['5'], passing
Processing language mr
mr already done fro all conexts_sizes :['5'], passing
Processing language ms
ms already done fro all conexts_sizes :['5'], passing
Processing language ne
ne already done fro all conexts_sizes :['5'], passing
Processing language nl
nl already done fro all conexts_sizes :['5'], passing
Processing language no
no already done fro all conexts_sizes :['5'], passing
Processing language oc
oc already done fro all conexts_sizes :['5'], passing
Processing language om
om already done fro all conexts_sizes :['5'], passing
Processing language pa
pa already done fro all conexts_sizes :['5'], passing
Processing language pl
pl already done fro all conexts_sizes :['5'], passing
Processing language pms
pms already done fro all conexts_sizes :['5'], passing
Processing language ps
ps already done fro all conexts_sizes :['5'], passing
Processing language pt
pt already done fro all conexts_sizes :['5'], passing
Processing language ro
ro already done fro all conexts_sizes :['5'], passing
Processing language ru
ru already done fro all conexts_sizes :['5'], passing
Processing language sa
sa already done fro all conexts_sizes :['5'], passing
Processing language scn
scn already done fro all conexts_sizes :['5'], passing
Processing language sco
sco already done fro all conexts_sizes :['5'], passing
Processing language sd
sd already done fro all conexts_sizes :['5'], passing
Processing language sh
sh already done fro all conexts_sizes :['5'], passing
Processing language si
si already done fro all conexts_sizes :['5'], passing
Processing language simple
simple already done fro all conexts_sizes :['5'], passing
Processing language sk
sk already done fro all conexts_sizes :['5'], passing
Processing language sl
Processing context size 5

100%|██████████| 45/45 [03:11<00:00,  4.25s/it]

Processing language so
Processing context size 5

100%|██████████| 10/10 [00:42<00:00,  4.23s/it]

Processing language sq
Processing context size 5

100%|██████████| 8/8 [00:32<00:00,  4.01s/it]

Processing language sr
Processing context size 5

100%|██████████| 80/80 [05:43<00:00,  4.30s/it]

Processing language su
Processing context size 5

100%|██████████| 2/2 [00:07<00:00,  3.55s/it]

Processing language sv
Processing context size 5

100%|██████████| 28/28 [01:58<00:00,  4.22s/it]

Processing language sw
Processing context size 5

100%|██████████| 5/5 [00:18<00:00,  3.66s/it]

Processing language ta
Processing context size 5

100%|██████████| 12/12 [00:51<00:00,  4.33s/it]

Processing language te
Processing context size 5

100%|██████████| 2/2 [00:06<00:00,  3.05s/it]

Processing language tg
Processing context size 5

100%|██████████| 6/6 [00:24<00:00,  4.09s/it]

Processing language tl
Processing context size 5

100%|██████████| 28/28 [01:55<00:00,  4.11s/it]

Processing language tr
Processing context size 5

100%|██████████| 72/72 [05:07<00:00,  4.27s/it]

Processing language tt
Processing context size 5

100%|██████████| 23/23 [01:36<00:00,  4.18s/it]

Processing language ug
Processing context size 5

100%|██████████| 1/1 [00:01<00:00,  1.55s/it]

Processing language uk
Processing context size 5
Nothing to score for uk and 5
Processing language ur
Processing context size 5

100%|██████████| 21/21 [01:31<00:00,  4.34s/it]

Processing language uz
Processing context size 5

100%|██████████| 16/16 [01:10<00:00,  4.39s/it]

Processing language vi
Processing context size 5

100%|██████████| 23/23 [01:39<00:00,  4.31s/it]

Processing language vo
Processing context size 5

100%|██████████| 1/1 [00:00<00:00,  2.17it/s]

Processing language xh
Processing context size 5
Nothing to score for xh and 5
Processing language yi
Processing context size 5

100%|██████████| 9/9 [00:38<00:00,  4.30s/it]

Processing language zh
Processing context size 5

100%|██████████| 16/16 [01:09<00:00,  4.33s/it]

context:
Charles Dadi Umeha Onyeama (26 Afrilu 1916 - 5 Satumba 1999) ya kasance Alkalin Kotun Koli ta Najeriya,[1] Alkalin Najeriya na farko a Kotun Duniya,[2] kuma mahaifin Ministan Harkokin Waje na Najeriya, Geoffrey Onyeama, kuma marubuci. Dillib Onyeama.[3] Shi ne kuma kakan ƙwararren ɗan wasan rugby, Andrew Onyeama Christie.

middle_sentence:
{'clean_sentence': 'Charles Dadi Umeha Onyeama (26 Afrilu 1916 - 5 Satumba 1999) ya kasance Alkalin Kotun Koli ta Najeriya,[1] Alkalin Najeriya na farko a Kotun Duniya,[2] kuma mahaifin Ministan Harkokin Waje na Najeriya, Geoffrey Onyeama, kuma marubuci.', 'clean_sentence2': None, 'endIdx1': 37253, 'endIdx2': 39052.0, 'ids1': array([0]), 'ids2': array([0]), 'index': 0, 'locList1': array([{'end': 36666, 'start': 36640}, {'end': 36725, 'start': 36670},
       {'end': 36817, 'start': 36795}, {'end': 36822, 'start': 36821},
       {'end': 36887, 'start': 36884}, {'end': 36907, 'start': 36897},
       {'end': 36957, 'start': 36949}, {'end': 36986, 'start': 36961},
       {'end': 37051, 'start': 37048}, {'end': 37103, 'start': 37061},
       {'end': 37153, 'start': 37145}, {'end': 37159, 'start': 37157},
       {'end': 37233, 'start': 37217}, {'end': 37253, 'start': 37237}],
      dtype=object), 'locList2': array([{'end': 38449, 'start': 38423}, {'end': 38508, 'start': 38453},
       {'end': 38600, 'start': 38578}, {'end': 38605, 'start': 38604},
       {'end': 38678, 'start': 38667}, {'end': 38698, 'start': 38688},
       {'end': 38748, 'start': 38740}, {'end': 38777, 'start': 38752},
       {'end': 38850, 'start': 38839}, {'end': 38902, 'start': 38860},
       {'end': 38952, 'start': 38944}, {'end': 38958, 'start': 38956},
       {'end': 39032, 'start': 39016}, {'end': 39052, 'start': 39036}],
      dtype=object), 'modifications': None, 'section1': 'Lead', 'section2': 'Lead', 'startIdx1': 36640, 'startIdx2': 38423.0, 'status': 'neutral'}

score:
11.190138816833496

section:
Lead

**Colouring the pages**

In [25]:
output_dir = os.path.join(processed_data_dir, "colored_pages")

# Run the coloring script
subprocess.run([
    "python", "color_pages.py",
    "--scored_data_dir", scored_data_dir,
    "--html_dir", crawling_output_dir,
    "--files_link_output_dir", output_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--extra_crawled_files_dir", crawling_output_dir,
])

first_lang = langs[0]
first_context_size = str(side_context_sizes[0])
colored_files_paths = os.path.join(output_dir, first_lang, f"first_context_size.json")

print(f"Colored files path: {colored_files_paths}")

Processing language af with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 32/32 [00:00<00:00, 1066.05it/s]
100%|██████████| 32/32 [00:02<00:00, 12.65it/s]
100%|██████████| 13/13 [00:00<00:00, 1067.52it/s]
 23%|██▎       | 3/13 [00:00<00:00, 20.41it/s]

Processing language am with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 13/13 [00:00<00:00, 13.82it/s]
100%|██████████| 22/22 [00:00<00:00, 994.49it/s]
 14%|█▎        | 3/22 [00:00<00:00, 20.82it/s]

Processing language an with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 22/22 [00:01<00:00, 13.50it/s]
  0%|          | 0/61 [00:00<?, ?it/s]

Processing language ar with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 61/61 [00:00<00:00, 1146.87it/s]
100%|██████████| 61/61 [00:04<00:00, 12.45it/s]
  0%|          | 0/40 [00:00<?, ?it/s]

Processing language ary with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 40/40 [00:00<00:00, 1299.11it/s]
100%|██████████| 40/40 [00:02<00:00, 13.59it/s]
100%|██████████| 33/33 [00:00<00:00, 1160.70it/s]
  0%|          | 0/33 [00:00<?, ?it/s]

Processing language as with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 33/33 [00:02<00:00, 12.61it/s]
100%|██████████| 29/29 [00:00<00:00, 996.44it/s]
  0%|          | 0/29 [00:00<?, ?it/s]

Processing language ast with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 29/29 [00:02<00:00, 11.43it/s]

Processing language az with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 81/81 [00:00<00:00, 919.04it/s]
100%|██████████| 81/81 [00:07<00:00, 10.25it/s]
100%|██████████| 23/23 [00:00<00:00, 1334.42it/s]
  0%|          | 0/23 [00:00<?, ?it/s]

Processing language azb with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 23/23 [00:01<00:00, 13.64it/s]
  0%|          | 0/41 [00:00<?, ?it/s]

Processing language ba with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 41/41 [00:00<00:00, 944.25it/s]
100%|██████████| 41/41 [00:03<00:00, 12.38it/s]
100%|██████████| 22/22 [00:00<00:00, 1294.65it/s]
  0%|          | 0/22 [00:00<?, ?it/s]

Processing language bar with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 22/22 [00:01<00:00, 15.33it/s]

Processing language be with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 20/20 [00:00<00:00, 889.52it/s]
100%|██████████| 20/20 [00:01<00:00, 13.38it/s]

Processing language bg with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 66/66 [00:00<00:00, 742.46it/s]
100%|██████████| 66/66 [00:08<00:00,  8.02it/s]
100%|██████████| 15/15 [00:00<00:00, 1257.79it/s]
  0%|          | 0/15 [00:00<?, ?it/s]

Processing language br with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 15/15 [00:01<00:00, 13.17it/s]
  0%|          | 0/53 [00:00<?, ?it/s]

Processing language bs with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 53/53 [00:00<00:00, 1071.68it/s]
100%|██████████| 53/53 [00:04<00:00, 11.91it/s]

Processing language ca with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 136/136 [00:00<00:00, 603.56it/s]
  0%|          | 0/136 [00:00<?, ?it/s]

Style: highlight

100%|██████████| 136/136 [00:24<00:00,  5.64it/s]

Processing language ce with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 7/7 [00:00<00:00, 1129.15it/s]
100%|██████████| 7/7 [00:00<00:00, 11.98it/s]
  0%|          | 0/84 [00:00<?, ?it/s]

Processing language cs with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 84/84 [00:00<00:00, 1120.52it/s]
  4%|▎         | 3/84 [00:00<00:05, 15.30it/s]

Style: highlight

100%|██████████| 84/84 [00:07<00:00, 11.51it/s]
100%|██████████| 67/67 [00:00<00:00, 1222.99it/s]
  0%|          | 0/67 [00:00<?, ?it/s]

Processing language cv with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 67/67 [00:06<00:00, 11.00it/s]

Processing language cy with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 74/74 [00:00<00:00, 1308.48it/s]
100%|██████████| 74/74 [00:05<00:00, 12.48it/s]
100%|██████████| 44/44 [00:00<00:00, 1270.60it/s]
  0%|          | 0/44 [00:00<?, ?it/s]

Processing language da with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 44/44 [00:03<00:00, 12.23it/s]

Processing language de with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 96/96 [00:00<00:00, 809.80it/s]
100%|██████████| 96/96 [00:10<00:00,  8.85it/s]

Processing language el with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 66/66 [00:00<00:00, 1178.55it/s]
100%|██████████| 66/66 [00:07<00:00,  9.20it/s]

Processing language en with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 41/41 [00:00<00:00, 1103.95it/s]
100%|██████████| 41/41 [00:03<00:00, 10.37it/s]
100%|██████████| 89/89 [00:00<00:00, 1300.60it/s]

Processing language eo with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 89/89 [00:08<00:00, 10.73it/s]

Processing language es with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 56/56 [00:00<00:00, 232.77it/s]
  0%|          | 0/56 [00:00<?, ?it/s]

Style: highlight

100%|██████████| 56/56 [00:13<00:00,  4.14it/s]

Processing language et with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 29/29 [00:00<00:00, 910.92it/s]
100%|██████████| 29/29 [00:03<00:00,  7.90it/s]

Processing language eu with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 56/56 [00:00<00:00, 1037.17it/s]
  0%|          | 0/56 [00:00<?, ?it/s]

Style: highlight

100%|██████████| 56/56 [00:05<00:00,  9.69it/s]

Processing language fa with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 47/47 [00:00<00:00, 1231.65it/s]
100%|██████████| 47/47 [00:04<00:00, 10.05it/s]

Processing language fi with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 47/47 [00:00<00:00, 930.77it/s]
  0%|          | 0/47 [00:00<?, ?it/s]

Style: highlight

100%|██████████| 47/47 [00:05<00:00,  9.20it/s]

Processing language fr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 37/37 [00:00<00:00, 866.58it/s]
100%|██████████| 37/37 [00:04<00:00,  8.50it/s]
  0%|          | 0/88 [00:00<?, ?it/s]

Processing language fy with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 88/88 [00:00<00:00, 1240.24it/s]
  3%|▎         | 3/88 [00:00<00:05, 16.48it/s]

Style: highlight

100%|██████████| 88/88 [00:08<00:00, 10.67it/s]
100%|██████████| 22/22 [00:00<00:00, 1279.90it/s]
  0%|          | 0/22 [00:00<?, ?it/s]

Processing language ga with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 22/22 [00:02<00:00, 10.92it/s]
100%|██████████| 17/17 [00:00<00:00, 1028.33it/s]
  0%|          | 0/17 [00:00<?, ?it/s]

Processing language gd with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 17/17 [00:01<00:00, 11.25it/s]
100%|██████████| 53/53 [00:00<00:00, 1058.38it/s]
  0%|          | 0/53 [00:00<?, ?it/s]

Processing language gl with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 53/53 [00:05<00:00,  9.92it/s]

Processing language gu with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 35/35 [00:00<00:00, 1299.80it/s]
100%|██████████| 35/35 [00:03<00:00, 10.90it/s]
100%|██████████| 30/30 [00:00<00:00, 1196.46it/s]
  0%|          | 0/30 [00:00<?, ?it/s]

Processing language ha with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 30/30 [00:02<00:00, 11.18it/s]
  0%|          | 0/63 [00:00<?, ?it/s]

Processing language he with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 63/63 [00:00<00:00, 1056.97it/s]
  5%|▍         | 3/63 [00:00<00:03, 15.11it/s]

Style: highlight

100%|██████████| 63/63 [00:06<00:00,  9.31it/s]
100%|██████████| 44/44 [00:00<00:00, 1314.10it/s]
  0%|          | 0/44 [00:00<?, ?it/s]

Processing language hi with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 44/44 [00:04<00:00, 10.43it/s]

Processing language hr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 48/48 [00:00<00:00, 956.84it/s]
  4%|▍         | 2/48 [00:00<00:02, 17.49it/s]

Style: highlight

100%|██████████| 48/48 [00:05<00:00,  8.63it/s]

Processing language hu with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 52/52 [00:00<00:00, 912.11it/s]
100%|██████████| 52/52 [00:06<00:00,  8.20it/s]

Processing language hy with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 83/83 [00:00<00:00, 1233.57it/s]
100%|██████████| 83/83 [00:08<00:00,  9.60it/s]
100%|██████████| 52/52 [00:00<00:00, 1185.32it/s]
  0%|          | 0/52 [00:00<?, ?it/s]

Processing language id with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 52/52 [00:05<00:00,  9.28it/s]
100%|██████████| 56/56 [00:00<00:00, 1263.76it/s]
  0%|          | 0/56 [00:00<?, ?it/s]

Processing language io with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 56/56 [00:05<00:00, 10.34it/s]
100%|██████████| 80/80 [00:00<00:00, 1240.70it/s]
  0%|          | 0/80 [00:00<?, ?it/s]

Processing language is with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 80/80 [00:07<00:00, 10.36it/s]
100%|██████████| 70/70 [00:00<00:00, 1229.25it/s]
  0%|          | 0/70 [00:00<?, ?it/s]

Processing language it with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 70/70 [00:06<00:00, 10.28it/s]
100%|██████████| 27/27 [00:00<00:00, 1298.31it/s]
  0%|          | 0/27 [00:00<?, ?it/s]

Processing language ja with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 27/27 [00:02<00:00, 10.31it/s]

Processing language jv with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 59/59 [00:00<00:00, 1268.34it/s]
100%|██████████| 59/59 [00:05<00:00, 10.78it/s]
100%|██████████| 65/65 [00:00<00:00, 1292.41it/s]
  0%|          | 0/65 [00:00<?, ?it/s]

Processing language ka with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 65/65 [00:06<00:00, 10.52it/s]

Processing language kk with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 31/31 [00:00<00:00, 1193.41it/s]
100%|██████████| 31/31 [00:02<00:00, 10.40it/s]
  0%|          | 0/32 [00:00<?, ?it/s]

Processing language km with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 32/32 [00:00<00:00, 1252.59it/s]
100%|██████████| 32/32 [00:03<00:00, 10.29it/s]

Processing language kn with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 108/108 [00:00<00:00, 1045.43it/s]
100%|██████████| 108/108 [00:10<00:00, 10.02it/s]

Processing language ko with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 35/35 [00:00<00:00, 1212.00it/s]
100%|██████████| 35/35 [00:03<00:00, 10.07it/s]

Processing language ku with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 60/60 [00:00<00:00, 1249.90it/s]
100%|██████████| 60/60 [00:05<00:00, 10.37it/s]

Processing language la with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 54/54 [00:00<00:00, 1084.02it/s]
100%|██████████| 54/54 [00:05<00:00,  9.36it/s]

Processing language lb with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 31/31 [00:00<00:00, 1224.40it/s]
100%|██████████| 31/31 [00:02<00:00, 10.59it/s]
100%|██████████| 6/6 [00:00<00:00, 1095.83it/s]
  0%|          | 0/6 [00:00<?, ?it/s]

Processing language lmo with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 6/6 [00:00<00:00, 10.81it/s]
100%|██████████| 27/27 [00:00<00:00, 1220.08it/s]
  0%|          | 0/27 [00:00<?, ?it/s]

Processing language lo with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 27/27 [00:02<00:00, 10.75it/s]
  0%|          | 0/25 [00:00<?, ?it/s]

Processing language lt with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 25/25 [00:00<00:00, 907.06it/s]
100%|██████████| 25/25 [00:02<00:00,  9.69it/s]

Processing language lv with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 49/49 [00:00<00:00, 702.88it/s]
100%|██████████| 49/49 [00:06<00:00,  8.08it/s]

Processing language mg with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 101/101 [00:00<00:00, 1366.24it/s]
100%|██████████| 101/101 [00:09<00:00, 10.89it/s]
100%|██████████| 24/24 [00:00<00:00, 1265.41it/s]
  0%|          | 0/24 [00:00<?, ?it/s]

Processing language min with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 24/24 [00:02<00:00, 10.68it/s]

Processing language mk with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 47/47 [00:00<00:00, 1176.09it/s]
100%|██████████| 47/47 [00:04<00:00, 10.57it/s]

Processing language mn with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 70/70 [00:00<00:00, 1180.93it/s]
100%|██████████| 70/70 [00:06<00:00, 10.27it/s]

Processing language mr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 32/32 [00:00<00:00, 964.12it/s]
100%|██████████| 32/32 [00:03<00:00,  9.00it/s]
100%|██████████| 24/24 [00:00<00:00, 1014.96it/s]
  0%|          | 0/24 [00:00<?, ?it/s]

Processing language ms with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 24/24 [00:02<00:00,  9.58it/s]
  0%|          | 0/34 [00:00<?, ?it/s]

Processing language ne with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 34/34 [00:00<00:00, 1354.16it/s]
100%|██████████| 34/34 [00:03<00:00, 10.70it/s]

Processing language nl with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 38/38 [00:00<00:00, 990.88it/s]
100%|██████████| 38/38 [00:03<00:00,  9.59it/s]

Processing language no with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 79/79 [00:00<00:00, 1022.69it/s]
100%|██████████| 79/79 [00:08<00:00,  9.13it/s]
  0%|          | 0/48 [00:00<?, ?it/s]

Processing language oc with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 48/48 [00:00<00:00, 1073.90it/s]
  4%|▍         | 2/48 [00:00<00:02, 18.75it/s]

Style: highlight

100%|██████████| 48/48 [00:05<00:00,  9.41it/s]
  0%|          | 0/28 [00:00<?, ?it/s]

Processing language om with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 28/28 [00:00<00:00, 1250.36it/s]
100%|██████████| 28/28 [00:02<00:00, 10.73it/s]

Processing language pa with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 60/60 [00:00<00:00, 1324.54it/s]
100%|██████████| 60/60 [00:05<00:00, 11.02it/s]

Processing language pl with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 30/30 [00:00<00:00, 1031.78it/s]
100%|██████████| 30/30 [00:03<00:00,  8.49it/s]
100%|██████████| 8/8 [00:00<00:00, 1212.10it/s]
  0%|          | 0/8 [00:00<?, ?it/s]

Processing language pms with side contexts size 5
Processing language ps with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 8/8 [00:00<00:00,  8.02it/s]
  0%|          | 0/37 [00:00<?, ?it/s]

Processing language pt with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 37/37 [00:00<00:00, 1170.83it/s]
100%|██████████| 37/37 [00:08<00:00,  4.37it/s]

Processing language ro with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 19/19 [00:00<00:00, 840.89it/s]
100%|██████████| 19/19 [00:02<00:00,  6.54it/s]
100%|██████████| 22/22 [00:00<00:00, 1073.72it/s]
  0%|          | 0/22 [00:00<?, ?it/s]

Processing language ru with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 22/22 [00:02<00:00,  7.85it/s]
100%|██████████| 19/19 [00:00<00:00, 1377.42it/s]
 11%|█         | 2/19 [00:00<00:00, 18.97it/s]

Processing language sa with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 19/19 [00:01<00:00, 10.59it/s]
100%|██████████| 6/6 [00:00<00:00, 1215.86it/s]

Processing language scn with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 6/6 [00:00<00:00,  9.09it/s]
100%|██████████| 43/43 [00:00<00:00, 1107.59it/s]
  0%|          | 0/43 [00:00<?, ?it/s]

Processing language sco with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 43/43 [00:04<00:00, 10.43it/s]
100%|██████████| 6/6 [00:00<00:00, 674.42it/s]
 33%|███▎      | 2/6 [00:00<00:00, 18.50it/s]

Processing language sd with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 6/6 [00:00<00:00,  9.38it/s]

Processing language sh with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 87/87 [00:00<00:00, 1088.68it/s]
  2%|▏         | 2/87 [00:00<00:04, 19.66it/s]

Style: highlight

100%|██████████| 87/87 [00:08<00:00,  9.86it/s]
  0%|          | 0/35 [00:00<?, ?it/s]

Processing language si with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 35/35 [00:00<00:00, 1287.33it/s]
100%|██████████| 35/35 [00:03<00:00,  9.87it/s]
100%|██████████| 49/49 [00:00<00:00, 1216.94it/s]
  0%|          | 0/49 [00:00<?, ?it/s]

Processing language simple with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 49/49 [00:05<00:00,  9.61it/s]

Processing language sk with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 61/61 [00:00<00:00, 1292.13it/s]
100%|██████████| 61/61 [00:06<00:00,  9.61it/s]
  0%|          | 0/71 [00:00<?, ?it/s]

Processing language sl with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 71/71 [00:00<00:00, 1165.46it/s]
  3%|▎         | 2/71 [00:00<00:03, 18.92it/s]

Style: highlight

100%|██████████| 71/71 [00:07<00:00,  9.24it/s]
100%|██████████| 30/30 [00:00<00:00, 1206.46it/s]
  0%|          | 0/30 [00:00<?, ?it/s]

Processing language so with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 30/30 [00:03<00:00,  8.81it/s]
100%|██████████| 34/34 [00:00<00:00, 1308.72it/s]
  0%|          | 0/34 [00:00<?, ?it/s]

Processing language sq with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 34/34 [00:03<00:00,  9.57it/s]

Processing language sr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 41/41 [00:00<00:00, 843.88it/s]
100%|██████████| 41/41 [00:05<00:00,  7.77it/s]
100%|██████████| 7/7 [00:00<00:00, 1154.68it/s]
  0%|          | 0/7 [00:00<?, ?it/s]

Processing language su with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 7/7 [00:00<00:00,  9.31it/s]

Processing language sv with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 32/32 [00:00<00:00, 946.41it/s]
100%|██████████| 32/32 [00:03<00:00,  8.60it/s]

Processing language sw with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 71/71 [00:00<00:00, 1387.06it/s]
100%|██████████| 71/71 [00:06<00:00, 10.53it/s]
100%|██████████| 41/41 [00:00<00:00, 1166.93it/s]
  0%|          | 0/41 [00:00<?, ?it/s]

Processing language ta with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 41/41 [00:04<00:00,  9.36it/s]

Processing language te with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 12/12 [00:00<00:00, 1119.25it/s]
100%|██████████| 12/12 [00:01<00:00,  9.19it/s]
  0%|          | 0/30 [00:00<?, ?it/s]

Processing language tg with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 30/30 [00:00<00:00, 1048.29it/s]
100%|██████████| 30/30 [00:03<00:00,  9.72it/s]
  0%|          | 0/54 [00:00<?, ?it/s]

Processing language tl with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 54/54 [00:00<00:00, 1132.58it/s]
100%|██████████| 54/54 [00:05<00:00,  9.42it/s]

Processing language tr with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1

100%|██████████| 35/35 [00:00<00:00, 839.27it/s]
  6%|▌         | 2/35 [00:00<00:01, 17.58it/s]

Style: highlight

100%|██████████| 35/35 [00:04<00:00,  8.29it/s]
100%|██████████| 38/38 [00:00<00:00, 1156.67it/s]
  0%|          | 0/38 [00:00<?, ?it/s]

Processing language tt with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 38/38 [00:04<00:00,  8.72it/s]
100%|██████████| 1/1 [00:00<00:00, 708.74it/s]
100%|██████████| 1/1 [00:00<00:00,  8.22it/s]

Processing language ug with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight
Processing language uk with side contexts size 5
Processing language ur with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 39/39 [00:00<00:00, 1015.89it/s]
100%|██████████| 39/39 [00:04<00:00,  8.12it/s]
100%|██████████| 63/63 [00:00<00:00, 1280.54it/s]
  0%|          | 0/63 [00:00<?, ?it/s]

Processing language uz with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 63/63 [00:06<00:00, 10.10it/s]
100%|██████████| 38/38 [00:00<00:00, 1145.63it/s]
  0%|          | 0/38 [00:00<?, ?it/s]

Processing language vi with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 38/38 [00:04<00:00,  8.85it/s]
100%|██████████| 7/7 [00:00<00:00, 1246.08it/s]
 29%|██▊       | 2/7 [00:00<00:00, 19.37it/s]

Processing language vo with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 7/7 [00:00<00:00, 10.28it/s]
100%|██████████| 33/33 [00:00<00:00, 1127.05it/s]
  0%|          | 0/33 [00:00<?, ?it/s]

Processing language xh with side contexts size 5
Processing language yi with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 33/33 [00:03<00:00,  9.77it/s]

Processing language zh with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 52/52 [00:00<00:00, 1269.06it/s]
100%|██████████| 52/52 [00:05<00:00,  8.70it/s]

Colored files path: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs_2/colored_pages/af/first_context_size.json

**Locally download the colored pages**

In [ ]:
user_cluster  = "boulenge@iccluster039"
local_path = "Desktop/htmls"

scp_command = f"scp -qr {user_cluster}:{output_dir} {local_path} > /dev/null"

#subprocess.run(scp_command, shell=True)

print(f"Run the following in the terminal to dowload the colored pages:\n{scp_command}")

Run the following in the terminal to dowload the colored pages:
scp -qr boulenge@iccluster039:/dlabdata1/boulenge/wikidumps_data/full_pages_experiement2/colored_pages Desktop/htmls > /dev/null