**Necessary imports**

In [41]:
import subprocess
import os
import pandas as pd

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

**Setting parameters**

In [42]:
simple_render_raw_data_dir = "/dlabdata1/tsoares/wikidumps/"
processed_data_dir = "/dlabdata1/boulenge/wikidumps_data/full_pages_experiment_all_langs"
processes = 48
max_samples_per_lang = 100
langs =  sorted(set([filename.split("wiki")[0] for filename in os.listdir(simple_render_raw_data_dir) if "wiki" in filename]))
side_context_sizes = [5]  # Example context sizes
second_month = "20231001"
third_month = "20231101"

langs_to_remove = ["war", "ky", "nds-nl"]

for lang in langs_to_remove:
    langs.remove(lang)

**Defining data paths**

In [43]:
# Define directories
rev_files_dir = os.path.join(processed_data_dir, "revisions_files")
parsed_htmls_dir = os.path.join(processed_data_dir, "parsed_htmls")
contexts_splitted_data_dir = os.path.join(processed_data_dir, "contexts_splitted_data")
ready_to_score_data_dir = os.path.join(processed_data_dir, "ready_to_score_data")
scored_data_dir = os.path.join(processed_data_dir, "scored_data")
crawling_output_dir = os.path.join(processed_data_dir, "crawled_pages")

# Create necessary directories if they don't exist
os.makedirs(rev_files_dir, exist_ok=True)
os.makedirs(parsed_htmls_dir, exist_ok=True)
os.makedirs(contexts_splitted_data_dir, exist_ok=True)
os.makedirs(ready_to_score_data_dir, exist_ok=True)
os.makedirs(scored_data_dir, exist_ok=True)
os.makedirs(crawling_output_dir, exist_ok=True)

**Prepare files to be crawled and parsed**

In [44]:
for lang in langs:
    try:
        print(f"Processing language: {lang}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
            
        subprocess.run([
            "python", "generate_revisions_file.py",
            "--versions_file", f"{second_month_path}/eval/link_versions",
            "--html_dir", f"{second_month_path}/eval/pages",
            "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
            "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",
            "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",
            "--max_samples", str(max_samples_per_lang),
            "--save_path", save_path
        ])

        #revisions = pd.read_parquet(save_path)
        #display(revisions.head(5))
    except Exception as e:
        print(f"Error processing language {lang}: {e}")
        continue

Processing language: af

Creating revisions dictionary: 100%|██████████| 2082/2082 [00:00<00:00, 817347.52it/s]
Checking revisions: 100%|██████████| 707/707 [00:01<00:00, 654.32it/s]

Processing language: am

Creating revisions dictionary: 100%|██████████| 24/24 [00:00<00:00, 280399.15it/s]
Checking revisions: 100%|██████████| 18/18 [00:00<00:00, 703.30it/s]

Processing language: an

Creating revisions dictionary: 100%|██████████| 93/93 [00:00<00:00, 642619.89it/s]
Checking revisions: 100%|██████████| 12/12 [00:00<00:00, 626.12it/s]

Processing language: ar

Creating revisions dictionary: 100%|██████████| 24525/24525 [00:00<00:00, 496394.28it/s]
Checking revisions: 100%|██████████| 6700/6700 [00:09<00:00, 685.09it/s]

Processing language: ary

Creating revisions dictionary: 100%|██████████| 152/152 [00:00<00:00, 570245.27it/s]
Checking revisions: 100%|██████████| 77/77 [00:00<00:00, 651.82it/s]

Processing language: as

Creating revisions dictionary: 100%|██████████| 496/496 [00:00<00:00, 693920.88it/s]
Checking revisions: 100%|██████████| 185/185 [00:00<00:00, 706.53it/s]

Processing language: ast

Creating revisions dictionary: 100%|██████████| 56/56 [00:00<00:00, 486296.12it/s]
Checking revisions: 100%|██████████| 39/39 [00:00<00:00, 589.39it/s]

Processing language: az

Creating revisions dictionary: 100%|██████████| 8019/8019 [00:00<00:00, 889297.58it/s]
Checking revisions: 100%|██████████| 2821/2821 [00:04<00:00, 699.21it/s]

Processing language: azb

Creating revisions dictionary: 100%|██████████| 42/42 [00:00<00:00, 487979.97it/s]
Checking revisions: 100%|██████████| 25/25 [00:00<00:00, 576.37it/s]

Processing language: ba

Creating revisions dictionary: 100%|██████████| 878/878 [00:00<00:00, 840968.01it/s]
Checking revisions: 100%|██████████| 250/250 [00:00<00:00, 763.85it/s]

Processing language: bar

Creating revisions dictionary: 100%|██████████| 24/24 [00:00<00:00, 337796.30it/s]
Checking revisions: 100%|██████████| 16/16 [00:00<00:00, 669.59it/s]

Processing language: be

Creating revisions dictionary: 100%|██████████| 4191/4191 [00:00<00:00, 862824.72it/s]
Checking revisions: 100%|██████████| 1609/1609 [00:02<00:00, 666.52it/s]

Processing language: bg

Creating revisions dictionary: 100%|██████████| 6108/6108 [00:00<00:00, 767788.80it/s]
Checking revisions: 100%|██████████| 1893/1893 [00:02<00:00, 639.99it/s]

Processing language: br

Creating revisions dictionary: 100%|██████████| 1494/1494 [00:00<00:00, 958881.43it/s]
Checking revisions: 100%|██████████| 489/489 [00:00<00:00, 623.33it/s]

Processing language: bs

Creating revisions dictionary: 100%|██████████| 1255/1255 [00:00<00:00, 788710.15it/s]
Checking revisions: 100%|██████████| 339/339 [00:05<00:00, 60.66it/s]

Processing language: ca

Creating revisions dictionary: 100%|██████████| 28516/28516 [00:00<00:00, 573176.66it/s]
Checking revisions: 100%|██████████| 7147/7147 [00:11<00:00, 647.29it/s]

Processing language: ce

Creating revisions dictionary: 100%|██████████| 1631/1631 [00:00<00:00, 941884.87it/s]
Checking revisions: 100%|██████████| 106/106 [00:00<00:00, 603.90it/s]

Processing language: cs

Creating revisions dictionary: 100%|██████████| 17059/17059 [00:00<00:00, 953919.39it/s]
Checking revisions: 100%|██████████| 4391/4391 [00:07<00:00, 615.06it/s]

Processing language: cv

Creating revisions dictionary: 100%|██████████| 603/603 [00:00<00:00, 741038.77it/s]
Checking revisions: 100%|██████████| 144/144 [00:00<00:00, 664.81it/s]

Processing language: cy

Creating revisions dictionary: 100%|██████████| 526/526 [00:00<00:00, 689654.24it/s]
Checking revisions: 100%|██████████| 238/238 [00:00<00:00, 607.20it/s]

Processing language: da

Creating revisions dictionary: 100%|██████████| 3377/3377 [00:00<00:00, 884652.09it/s]
Checking revisions: 100%|██████████| 1042/1042 [00:01<00:00, 632.96it/s]

Processing language: de

Creating revisions dictionary: 100%|██████████| 118669/118669 [00:00<00:00, 493541.23it/s]
Checking revisions: 100%|██████████| 49899/49899 [01:27<00:00, 570.74it/s]

Processing language: el

Creating revisions dictionary: 100%|██████████| 8960/8960 [00:00<00:00, 819543.00it/s]
Checking revisions: 100%|██████████| 2191/2191 [00:04<00:00, 538.57it/s]

Processing language: en

Creating revisions dictionary: 100%|██████████| 448605/448605 [00:01<00:00, 445026.48it/s]
Checking revisions: 100%|██████████| 194300/194300 [05:33<00:00, 582.17it/s]

Processing language: eo

Creating revisions dictionary: 100%|██████████| 8385/8385 [00:00<00:00, 959021.57it/s]
Checking revisions: 100%|██████████| 2340/2340 [00:03<00:00, 600.21it/s]

Processing language: es

Creating revisions dictionary: 100%|██████████| 86000/86000 [00:00<00:00, 672954.13it/s]
Checking revisions: 100%|██████████| 29970/29970 [00:55<00:00, 541.49it/s]

Processing language: et

Creating revisions dictionary: 100%|██████████| 6043/6043 [00:00<00:00, 882527.13it/s]
Checking revisions: 100%|██████████| 2026/2026 [00:03<00:00, 594.77it/s]

Processing language: eu

Creating revisions dictionary: 100%|██████████| 7960/7960 [00:00<00:00, 991202.09it/s]
Checking revisions: 100%|██████████| 2155/2155 [00:12<00:00, 176.31it/s]

Processing language: fa

Creating revisions dictionary: 100%|██████████| 25510/25510 [00:00<00:00, 360391.71it/s]
Checking revisions: 100%|██████████| 7967/7967 [00:12<00:00, 622.08it/s]

Processing language: fi

Creating revisions dictionary: 100%|██████████| 17062/17062 [00:00<00:00, 866298.84it/s]
Checking revisions: 100%|██████████| 6203/6203 [00:09<00:00, 646.62it/s]

Processing language: fr

Creating revisions dictionary: 100%|██████████| 112993/112993 [00:00<00:00, 779321.12it/s]
Checking revisions: 100%|██████████| 26847/26847 [00:43<00:00, 616.23it/s]

Processing language: fy

Creating revisions dictionary: 100%|██████████| 731/731 [00:00<00:00, 835432.21it/s]
Checking revisions: 100%|██████████| 149/149 [00:00<00:00, 734.32it/s]

Processing language: ga

Creating revisions dictionary: 100%|██████████| 259/259 [00:00<00:00, 674317.03it/s]
Checking revisions: 100%|██████████| 109/109 [00:00<00:00, 491.75it/s]

Processing language: gd

Creating revisions dictionary: 100%|██████████| 21/21 [00:00<00:00, 250228.36it/s]
Checking revisions: 100%|██████████| 13/13 [00:00<00:00, 606.61it/s]

Processing language: gl

Creating revisions dictionary: 100%|██████████| 6132/6132 [00:00<00:00, 927028.26it/s]
Checking revisions: 100%|██████████| 1749/1749 [00:02<00:00, 707.44it/s]

Processing language: gu

Creating revisions dictionary: 100%|██████████| 50/50 [00:00<00:00, 427118.53it/s]
Checking revisions: 100%|██████████| 16/16 [00:00<00:00, 463.67it/s]

Processing language: ha

Creating revisions dictionary: 100%|██████████| 382/382 [00:00<00:00, 654770.79it/s]
Checking revisions: 100%|██████████| 180/180 [00:00<00:00, 655.65it/s]

Processing language: he

Creating revisions dictionary: 100%|██████████| 45686/45686 [00:00<00:00, 685621.67it/s]
Checking revisions: 100%|██████████| 17938/17938 [00:29<00:00, 606.90it/s]

Processing language: hi

Creating revisions dictionary: 100%|██████████| 3193/3193 [00:00<00:00, 833276.05it/s]
Checking revisions: 100%|██████████| 745/745 [00:01<00:00, 586.11it/s]

Processing language: hr

Creating revisions dictionary: 100%|██████████| 5426/5426 [00:00<00:00, 920159.04it/s]
Checking revisions: 100%|██████████| 1469/1469 [00:02<00:00, 606.06it/s]

Processing language: hu

Creating revisions dictionary: 100%|██████████| 11973/11973 [00:00<00:00, 879990.22it/s]
Checking revisions: 100%|██████████| 4830/4830 [00:07<00:00, 612.70it/s]

Processing language: hy

Creating revisions dictionary: 100%|██████████| 4489/4489 [00:00<00:00, 907034.91it/s]
Checking revisions: 100%|██████████| 952/952 [00:01<00:00, 663.87it/s]

Processing language: id

Creating revisions dictionary: 100%|██████████| 21284/21284 [00:00<00:00, 929515.17it/s]
Checking revisions: 100%|██████████| 5934/5934 [00:08<00:00, 665.59it/s]

Processing language: io

Creating revisions dictionary: 100%|██████████| 269/269 [00:00<00:00, 778115.71it/s]
Checking revisions: 100%|██████████| 92/92 [00:00<00:00, 625.76it/s]

Processing language: is

Creating revisions dictionary: 100%|██████████| 1243/1243 [00:00<00:00, 921116.59it/s]
Checking revisions: 100%|██████████| 285/285 [00:00<00:00, 636.05it/s]

Processing language: it

Creating revisions dictionary: 100%|██████████| 62268/62268 [00:00<00:00, 820734.73it/s]
Checking revisions: 100%|██████████| 22827/22827 [00:37<00:00, 601.51it/s]

Processing language: ja

Creating revisions dictionary: 100%|██████████| 136125/136125 [00:00<00:00, 710628.67it/s]
Checking revisions: 100%|██████████| 36301/36301 [00:57<00:00, 629.40it/s]

Processing language: jv

Creating revisions dictionary: 100%|██████████| 5865/5865 [00:00<00:00, 994244.32it/s]
Checking revisions: 100%|██████████| 95/95 [00:00<00:00, 662.32it/s]

Processing language: ka

Creating revisions dictionary: 100%|██████████| 2517/2517 [00:00<00:00, 940160.58it/s]
Checking revisions: 100%|██████████| 600/600 [00:00<00:00, 674.82it/s]

Processing language: kk

Creating revisions dictionary: 100%|██████████| 2282/2282 [00:00<00:00, 882726.34it/s]
Checking revisions: 100%|██████████| 1019/1019 [00:01<00:00, 617.58it/s]

Processing language: km

Creating revisions dictionary: 100%|██████████| 162/162 [00:00<00:00, 721313.43it/s]
Checking revisions: 100%|██████████| 58/58 [00:00<00:00, 451.78it/s]

Processing language: kn

Creating revisions dictionary: 100%|██████████| 676/676 [00:00<00:00, 722382.04it/s]
Checking revisions: 100%|██████████| 199/199 [00:05<00:00, 38.23it/s]

Processing language: ko

Creating revisions dictionary: 100%|██████████| 35510/35510 [00:00<00:00, 537715.75it/s]
Checking revisions: 100%|██████████| 10771/10771 [00:17<00:00, 600.42it/s]

Processing language: ku

Creating revisions dictionary: 100%|██████████| 868/868 [00:00<00:00, 790931.10it/s]
Checking revisions: 100%|██████████| 378/378 [00:00<00:00, 620.27it/s]

Processing language: la

Creating revisions dictionary: 100%|██████████| 1388/1388 [00:00<00:00, 827415.29it/s]
Checking revisions: 100%|██████████| 572/572 [00:00<00:00, 610.55it/s]

Processing language: lb

Creating revisions dictionary: 100%|██████████| 1021/1021 [00:00<00:00, 720818.78it/s]
Checking revisions: 100%|██████████| 472/472 [00:00<00:00, 611.13it/s]

Processing language: lmo

Creating revisions dictionary: 100%|██████████| 27/27 [00:00<00:00, 347381.01it/s]
Checking revisions: 100%|██████████| 15/15 [00:00<00:00, 535.86it/s]

Processing language: lo

Creating revisions dictionary: 100%|██████████| 35/35 [00:00<00:00, 338250.32it/s]
Checking revisions: 100%|██████████| 13/13 [00:00<00:00, 609.86it/s]

Processing language: lt

Creating revisions dictionary: 100%|██████████| 3797/3797 [00:00<00:00, 820028.44it/s]
Checking revisions: 100%|██████████| 1677/1677 [00:02<00:00, 646.25it/s]

Processing language: lv

Creating revisions dictionary: 100%|██████████| 2808/2808 [00:00<00:00, 896521.70it/s]
Checking revisions: 100%|██████████| 953/953 [00:01<00:00, 605.28it/s]

Processing language: mg

Creating revisions dictionary: 100%|██████████| 2008/2008 [00:00<00:00, 943342.57it/s]
Checking revisions: 100%|██████████| 301/301 [00:00<00:00, 511.38it/s]

Processing language: min

Creating revisions dictionary: 100%|██████████| 47/47 [00:00<00:00, 518769.18it/s]
Checking revisions: 100%|██████████| 12/12 [00:00<00:00, 552.23it/s]

Processing language: mk

Creating revisions dictionary: 100%|██████████| 1292/1292 [00:00<00:00, 792141.61it/s]
Checking revisions: 100%|██████████| 588/588 [00:01<00:00, 530.79it/s]

Processing language: mn

Creating revisions dictionary: 100%|██████████| 592/592 [00:00<00:00, 709639.32it/s]
Checking revisions: 100%|██████████| 168/168 [00:00<00:00, 590.52it/s]

Processing language: mr

Creating revisions dictionary: 100%|██████████| 110/110 [00:00<00:00, 598409.13it/s]
Checking revisions: 100%|██████████| 45/45 [00:00<00:00, 522.45it/s]

Processing language: ms

Creating revisions dictionary: 100%|██████████| 3777/3777 [00:00<00:00, 822015.68it/s]
Checking revisions: 100%|██████████| 1526/1526 [00:02<00:00, 614.95it/s]

Processing language: ne

Creating revisions dictionary: 100%|██████████| 394/394 [00:00<00:00, 696106.06it/s]
Checking revisions: 100%|██████████| 168/168 [00:00<00:00, 601.59it/s]

Processing language: nl

Creating revisions dictionary: 100%|██████████| 33226/33226 [00:00<00:00, 339949.57it/s]
Checking revisions: 100%|██████████| 12413/12413 [00:21<00:00, 566.10it/s]

Processing language: no

Creating revisions dictionary: 100%|██████████| 10176/10176 [00:00<00:00, 802701.37it/s]
Checking revisions: 100%|██████████| 3265/3265 [00:06<00:00, 484.51it/s]

Processing language: oc

Creating revisions dictionary: 100%|██████████| 1836/1836 [00:00<00:00, 920150.81it/s]
Checking revisions: 100%|██████████| 625/625 [00:00<00:00, 650.20it/s]

Processing language: om

Creating revisions dictionary: 100%|██████████| 36/36 [00:00<00:00, 376546.00it/s]
Checking revisions: 100%|██████████| 11/11 [00:00<00:00, 598.04it/s]

Processing language: pa

Creating revisions dictionary: 100%|██████████| 305/305 [00:00<00:00, 770640.19it/s]
Checking revisions: 100%|██████████| 106/106 [00:00<00:00, 571.75it/s]

Processing language: pl

Creating revisions dictionary: 100%|██████████| 40921/40921 [00:00<00:00, 598653.35it/s]
Checking revisions: 100%|██████████| 13581/13581 [00:24<00:00, 555.95it/s]

Processing language: pms

Creating revisions dictionary: 100%|██████████| 2/2 [00:00<00:00, 18315.74it/s]
Checking revisions: 100%|██████████| 2/2 [00:00<00:00, 413.17it/s]

Processing language: ps

Creating revisions dictionary: 100%|██████████| 13/13 [00:00<00:00, 94172.63it/s]
Checking revisions: 100%|██████████| 9/9 [00:00<00:00, 389.17it/s]

Processing language: pt

Creating revisions dictionary: 100%|██████████| 36665/36665 [00:00<00:00, 571208.41it/s]
Checking revisions: 100%|██████████| 8520/8520 [00:15<00:00, 535.61it/s]

Processing language: ro

Creating revisions dictionary: 100%|██████████| 6990/6990 [00:00<00:00, 932423.27it/s]
Checking revisions: 100%|██████████| 2354/2354 [00:04<00:00, 532.65it/s]

Processing language: ru

Creating revisions dictionary: 100%|██████████| 51195/51195 [00:00<00:00, 725175.59it/s]
Checking revisions: 100%|██████████| 20743/20743 [00:36<00:00, 570.45it/s]

Processing language: sa

Creating revisions dictionary: 100%|██████████| 28/28 [00:00<00:00, 323527.58it/s]
Checking revisions: 100%|██████████| 6/6 [00:00<00:00, 655.24it/s]

Processing language: scn

Creating revisions dictionary: 100%|██████████| 20/20 [00:00<00:00, 313007.76it/s]
Checking revisions: 100%|██████████| 13/13 [00:00<00:00, 647.87it/s]

Processing language: sco

Creating revisions dictionary: 100%|██████████| 45/45 [00:00<00:00, 419430.40it/s]
Checking revisions: 100%|██████████| 17/17 [00:00<00:00, 540.68it/s]

Processing language: sd

Creating revisions dictionary: 100%|██████████| 12/12 [00:00<00:00, 84307.62it/s]
Checking revisions: 100%|██████████| 7/7 [00:00<00:00, 569.34it/s]

Processing language: sh

Creating revisions dictionary: 100%|██████████| 1357/1357 [00:00<00:00, 679034.90it/s]
Checking revisions: 100%|██████████| 314/314 [00:00<00:00, 651.24it/s]

Processing language: si

Creating revisions dictionary: 100%|██████████| 72/72 [00:00<00:00, 507546.03it/s]
Checking revisions: 100%|██████████| 35/35 [00:00<00:00, 587.65it/s]

Processing language: simple

Creating revisions dictionary: 100%|██████████| 5175/5175 [00:00<00:00, 874235.67it/s]
Checking revisions: 100%|██████████| 1841/1841 [00:03<00:00, 600.90it/s]

Processing language: sk

Creating revisions dictionary: 100%|██████████| 5180/5180 [00:00<00:00, 743065.59it/s]
Checking revisions: 100%|██████████| 1286/1286 [00:02<00:00, 602.55it/s]

Processing language: sl

Creating revisions dictionary: 100%|██████████| 2427/2427 [00:00<00:00, 864434.09it/s]
Checking revisions: 100%|██████████| 775/775 [00:01<00:00, 639.74it/s]

Processing language: so

Creating revisions dictionary: 100%|██████████| 71/71 [00:00<00:00, 531777.83it/s]
Checking revisions: 100%|██████████| 30/30 [00:00<00:00, 616.17it/s]

Processing language: sq

Creating revisions dictionary: 100%|██████████| 992/992 [00:00<00:00, 744320.14it/s]
Checking revisions: 100%|██████████| 357/357 [00:00<00:00, 650.81it/s]

Processing language: sr

Creating revisions dictionary: 100%|██████████| 8745/8745 [00:00<00:00, 961194.67it/s]
Checking revisions: 100%|██████████| 2188/2188 [00:03<00:00, 645.53it/s]

Processing language: su

Creating revisions dictionary: 100%|██████████| 8/8 [00:00<00:00, 68478.43it/s]
Checking revisions: 100%|██████████| 7/7 [00:00<00:00, 515.21it/s]

Processing language: sv

Creating revisions dictionary: 100%|██████████| 13640/13640 [00:00<00:00, 751787.89it/s]
Checking revisions: 100%|██████████| 5054/5054 [00:08<00:00, 630.89it/s]

Processing language: sw

Creating revisions dictionary: 100%|██████████| 596/596 [00:00<00:00, 735020.64it/s]
Checking revisions: 100%|██████████| 170/170 [00:00<00:00, 576.43it/s]

Processing language: ta

Creating revisions dictionary: 100%|██████████| 2293/2293 [00:00<00:00, 772059.01it/s]
Checking revisions: 100%|██████████| 762/762 [00:01<00:00, 645.11it/s]

Processing language: te

Creating revisions dictionary: 100%|██████████| 2576/2576 [00:00<00:00, 885544.39it/s]
Checking revisions: 100%|██████████| 964/964 [00:01<00:00, 668.05it/s]

Processing language: tg

Creating revisions dictionary: 100%|██████████| 187/187 [00:00<00:00, 584017.01it/s]
Checking revisions: 100%|██████████| 107/107 [00:00<00:00, 626.94it/s]

Processing language: tl

Creating revisions dictionary: 100%|██████████| 889/889 [00:00<00:00, 790153.90it/s]
Checking revisions: 100%|██████████| 216/216 [00:00<00:00, 525.33it/s]

Processing language: tr

Creating revisions dictionary: 100%|██████████| 25000/25000 [00:00<00:00, 486120.27it/s]
Checking revisions: 100%|██████████| 6811/6811 [00:15<00:00, 453.86it/s]

Processing language: tt

Creating revisions dictionary: 100%|██████████| 107/107 [00:00<00:00, 633884.93it/s]
Checking revisions: 100%|██████████| 54/54 [00:02<00:00, 22.07it/s]

Processing language: ug

Creating revisions dictionary: 100%|██████████| 1/1 [00:00<00:00, 8144.28it/s]
Checking revisions: 100%|██████████| 1/1 [00:00<00:00, 609.99it/s]

Processing language: uk

Creating revisions dictionary: 100%|██████████| 2/2 [00:00<00:00, 14290.64it/s]
Checking revisions: 100%|██████████| 2/2 [00:00<00:00, 440.97it/s]

Processing language: ur

Creating revisions dictionary: 100%|██████████| 5717/5717 [00:00<00:00, 755120.01it/s]
Checking revisions: 100%|██████████| 3287/3287 [00:04<00:00, 789.30it/s]

Processing language: uz

Creating revisions dictionary: 100%|██████████| 6490/6490 [00:00<00:00, 967721.32it/s]
Checking revisions: 100%|██████████| 1343/1343 [00:02<00:00, 655.15it/s]

Processing language: vi

Creating revisions dictionary: 100%|██████████| 17236/17236 [00:00<00:00, 963264.81it/s]
Checking revisions: 100%|██████████| 3716/3716 [00:06<00:00, 584.75it/s]

Processing language: vo

Creating revisions dictionary: 100%|██████████| 11/11 [00:00<00:00, 74415.07it/s]
Checking revisions: 100%|██████████| 4/4 [00:00<00:00, 570.48it/s]

Processing language: xh

Creating revisions dictionary: 100%|██████████| 1/1 [00:00<00:00, 6842.26it/s]
Checking revisions: 100%|██████████| 1/1 [00:00<00:00, 522.78it/s]

Processing language: yi

Creating revisions dictionary: 100%|██████████| 25/25 [00:00<00:00, 235106.73it/s]
Checking revisions: 100%|██████████| 19/19 [00:00<00:00, 532.63it/s]

Processing language: zh

Creating revisions dictionary: 100%|██████████| 49579/49579 [00:00<00:00, 792937.32it/s]
Checking revisions: 100%|██████████| 18087/18087 [00:30<00:00, 602.31it/s]

**Crawling first versions only**

In [45]:
for lang in langs:
    print(f"Processing language: {lang}")
    subprocess.run([
        "python", "crawl.py",
        "--revisions_path", f"{rev_files_dir}/revisions_{lang}.parquet",
        "--output_dir", f"{crawling_output_dir}/{lang}",
        "--n_processes", str(processes),
        "--lang", lang,
        #"--crawl_second_versions", "False" (false by default)
    ])

Processing language: af
Total number of pages to crawl: 100
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 100/100 [00:00<00:00, 191.85it/s]

Processing language: am
Total number of pages to crawl: 18
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 18/18 [00:00<00:00, 232.06it/s]

Processing language: an
Total number of pages to crawl: 12
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...
Processing language: ar

Moving files: 100%|██████████| 12/12 [00:00<00:00, 158.94it/s]

Total number of pages to crawl: 100
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 100/100 [00:00<00:00, 164.09it/s]

Processing language: ary
Total number of pages to crawl: 77
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 77/77 [00:00<00:00, 197.22it/s]

Processing language: as
Total number of pages to crawl: 100
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 100/100 [00:00<00:00, 221.26it/s]

Processing language: ast
Total number of pages to crawl: 39
Running crawling on 48 processes
Parallel multiprocess
Crawling finished, post processing...

Moving files: 100%|██████████| 39/39 [00:00<00:00, 187.47it/s]

Processing language: az
Total number of pages to crawl: 100
Running crawling on 48 processes
Parallel multiprocess

KeyboardInterrupt:

**Parsing of the htmls**

In [ ]:
for lang in langs:
    print(f"Processing language: {lang}")
    second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
    first_version_specific_html_dir = f"{crawling_output_dir}/{lang}"
    save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
    output_dir = f"{parsed_htmls_dir}/{lang}_v2"
    first_version_specific_output_dir = f"{parsed_htmls_dir}/{lang}_v1"
        
    subprocess.run([
        "python", "parsing.py",
        "--revisions_path", save_path,        
        "--html_dir", f"{second_month_path}/eval/pages",
        "--first_versions_specific_html_dir", first_version_specific_html_dir,
        "--output_dir", output_dir,
        "--first_versions_specific_output_dir", first_version_specific_output_dir,
        "--n_processes", str(processes)
    ])

    parsed_htmls_paths = os.listdir(first_version_specific_output_dir)
    sentences_path = list(filter(lambda x: x.endswith("sentences.jsonl"), parsed_htmls_paths))[0]
    links_path = list(filter(lambda x: x.endswith("links.jsonl"), parsed_htmls_paths))[0]
    sentences_df = pd.read_json(f"{first_version_specific_output_dir}/{sentences_path}")
    links_df = pd.read_json(f"{first_version_specific_output_dir}/{links_path}")

    display(sentences_df.head(5))
    display(links_df.head(5))

Processing language: simple
First version html dir: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment/crawled_pages/simple
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1
Time taken for v1: 7.27161979675293
Writing sentences and links v2
Time taken for v2: 6.874102592468262

,md5,id,text,startIdx,endIdx,section,locList
0,3708960666435ae91a11b1dbf591cb88,0,"2023 (MMXXIII) is the current year, and is a c...",82150,83014,Lead,"[{'start': 82149, 'end': 82150}, {'start': 821..."
1,d6b46c236c793ad4da37283c529b1169,1,The year started with the continuation of the ...,83015,83236,Lead,"[{'start': 83013, 'end': 83014}, {'start': 830..."
2,f2533812ab62b194ea5b5093fdd7a784,2,"In January, an Islamist suicide bomber killed ...",83237,83554,Lead,"[{'start': 83235, 'end': 83251}, {'start': 833..."
3,b78ea47367a1ab3348306e5409ea5272,3,"In February, a major earthquake struck Turkey ...",83555,84021,Lead,"[{'start': 83553, 'end': 83567}, {'start': 836..."
4,3f5b19bc2db88e4761da76190c9df4f2,4,"Former King of Greece Constantine II, former P...",84022,84638,Lead,"[{'start': 84020, 'end': 84021}, {'start': 840..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Professional_wrestling,39282,professional wrestling,39378,Lead,0
1,file:///wiki/Pay-per-view,39379,pay-per-view,39445,Lead,0
2,file:///wiki/All_Elite_Wrestling,39459,All Elite Wrestling,39546,Lead,0
3,file:///wiki/Wembley_Stadium,39588,Wembley Stadium,39663,Lead,1
4,file:///wiki/London,39667,London,39715,Lead,1

**Preprocessing**

In [ ]:
for lang in langs:
    for side_context_size in side_context_sizes:
        print(f"Processing language: {lang} with side context size {side_context_size}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
        output_dir = f"{contexts_splitted_data_dir}/{lang}/context_size_{side_context_size}"
        
        subprocess.run([
            "python", "modular_preprocessing.py",
            "--revisions_path", save_path,
            "--parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v2",
            "--first_versions_specific_parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v1",
            "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
            "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",
            "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",
            "--output_dir", output_dir,
            "--side_contexts_size", str(side_context_size),
            "--n_processes", str(processes)
        ])

        preprocessed_data_path = os.path.join(output_dir, f'test_data.parquet')

        preprocessed_data = pd.read_parquet(preprocessed_data_path)
        display(preprocessed_data.head(5))

Processing language: simple with side context size 5
Running on 48 processes
Parallel multiprocess

100%|██████████| 10/10 [00:05<00:00,  1.78it/s]

The length of the output is 31

100%|██████████| 31/31 [00:00<00:00, 7411.28it/s]

,source_title,source_ID,target_title,context,insert_indices,moved_insertion_marker,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts
0,List_of_mayors_in_Norway_2023%E2%80%932027,1052251,M%C3%B8re_og_Romsdal,None,[26],None,"Hustadvika. KrF, and Centre Party; Nils Christ...",Møre og Romsdal,Lead,None,"In September and October 2023, every municipal...",9114883,9114892,None,missing_span,"[{'context': 'In September and October 2023, e..."
1,Puffin_Rock,954730,Disney_XD,None,[1],None,It follows the adventures of two young puffins...,Disney XD,Lead,None,Puffin Rock is a Irish animated children's tel...,8673424,9134125,None,missing_mention_with_sentence_modifications,[{'context': 'Puffin Rock is a Irish animated ...
2,Kevin_Costner,73022,"Lynwood,_California",None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,"Lynwood, California",Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...
3,Kevin_Costner,73022,United_States,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,USA,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...
4,Kevin_Costner,73022,Eliot_Ness,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,Eliot Ness,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...

**Merging**

In [ ]:
test_data_dir = contexts_splitted_data_dir
output_dir = ready_to_score_data_dir

subprocess.run([
    "python", "modular_merge_data.py",
    "--test_data_dir", test_data_dir,
    "--raw_data_dir", simple_render_raw_data_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--output_dir", output_dir,
    "--ignore_warnings"
])

first_lang = langs[0]
first_context_size = str(side_context_sizes[0])
scored_files_example = os.listdir(output_dir)
scored_files_example = list(filter(lambda x: (first_lang in x and first_context_size in x), scored_files_example))
final_input_data_path = os.path.join(output_dir, scored_files_example[0])

final_input_data_df = pd.read_parquet(final_input_data_path)
display(final_input_data_df.head(5))

Saving mention maps
Processing language simple (1/1)
Finished processing language simple
Processing language simple (1/1)
Loaded pages
Loaded redirects

100%|██████████| 238680/238680 [00:00<00:00, 730679.36it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 31 links for language simple
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 5 links because of missing section
After cleaning, there are 24 links for language simple
Finished processing language simple

,source_title,source_ID,target_title,context,insert_indices,moved_insertion_marker,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts,target_lead
0,List_of_mayors_in_Norway_2023%E2%80%932027,1052251,M%C3%B8re_og_Romsdal,None,[26],None,"Hustadvika. KrF, and Centre Party; Nils Christ...",Møre og Romsdal,Lead,None,"In September and October 2023, every municipal...",9114883,9114892,None,missing_span,"[{'context': 'In September and October 2023, e...",Møre og Romsdal is a county in Norway. Norway ...
1,Puffin_Rock,954730,Disney_XD,None,[1],None,It follows the adventures of two young puffins...,Disney XD,Lead,None,Puffin Rock is a Irish animated children's tel...,8673424,9134125,None,missing_mention_with_sentence_modifications,[{'context': 'Puffin Rock is a Irish animated ...,Disney XD is an American digital cable and sat...
2,Kevin_Costner,73022,United_States,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,USA,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...,"The United States of America, commonly known a..."
3,Kevin_Costner,73022,Eliot_Ness,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,Eliot Ness,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...,Eliot Ness was an American Prohibition agent. ...
4,Kevin_Costner,73022,Academy_Award_for_Best_Director,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,Academy Award for Best Director,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...,"The Academy Award for Best Directing, usually ..."

**Scoring the contexts**

In [ ]:
data_dir = ready_to_score_data_dir
output_dir = scored_data_dir

subprocess.run([
    "python", "get_scores.py",
    "--data_dir", data_dir,
    "--output_dir", output_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--models_dir", "/dlabdata1/tsoares/models",
    "--models_prefix", "roberta_full",
    "--use_section_title",
    "--use_mentions",
    "--use_cuda",
    "--only_multilingual",
    "--multilingual_name", "multilingual-all"
])

scored_files_example = os.listdir(output_dir)[0]
scored_data = pd.read_parquet(f"{output_dir}/{scored_files_example}")

exemple = scored_data['all_contexts'][0][0]

for key in exemple.keys():
    print(f"{key}:\n{exemple[key]}\n")

Processing language simple
Processing context size 5

100%|██████████| 6/6 [00:52<00:00,  8.68s/it]

context:
In September and October 2023, every municipal council in Norway, is supposed to elect a mayor. Four years later, the municipal councils will. elect mayors, again. (Names were added to this page, as late as October 7.) In regard to Alstahaug municipality, media says that there is a written[1] agreement, that makes Peter Talseth the new mayor [when voting will be done at the next council meeting].[2] Furthermore, the municipality is in Nordland (county). No mayor has been elected (2023) in these municipalities: Alta, (municipality), Alvdal, Alver, Andøy, Aremark, Arendal, Asker, Askvoll, Askøy, Aukra, Aure, Aurland, Aurskog-Høland, Austevoll, Austrheim, Averøy, Balsfjord

middle_sentence:
{'clean_sentence': 'In September and October 2023, every municipal council in Norway,', 'clean_sentence2': None, 'endIdx1': 34656, 'endIdx2': 34966.0, 'ids1': array([0]), 'ids2': array([0]), 'index': 0, 'locList1': array([{'end': 34574, 'start': 34537}, {'end': 34641, 'start': 34624},
       {'end': 34656, 'start': 34645}], dtype=object), 'locList2': array([{'end': 34884, 'start': 34847}, {'end': 34951, 'start': 34934},
       {'end': 34966, 'start': 34955}], dtype=object), 'modifications': None, 'section1': 'Lead', 'section2': 'Lead', 'startIdx1': 34537, 'startIdx2': 34847.0, 'status': 'neutral'}

score:
16.439611434936523

section:
Lead

**Colouring the pages**

In [ ]:
output_dir = os.path.join(processed_data_dir, "colored_pages")

# Run the coloring script
subprocess.run([
    "python", "color_pages.py",
    "--scored_data_dir", scored_data_dir,
    "--html_dir", crawling_output_dir,
    "--files_link_output_dir", output_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--extra_crawled_files_dir", crawling_output_dir,
])

first_lang = langs[0]
first_context_size = str(side_context_sizes[0])
colored_files_paths = os.path.join(output_dir, first_lang, f"first_context_size.json")

print(f"Colored files path: {colored_files_paths}")

Processing language simple with side contexts size 5
Coloring with grey_to_red
Smoothing param: 1
Style: highlight

100%|██████████| 24/24 [00:00<00:00, 1025.92it/s]
100%|██████████| 24/24 [00:02<00:00, 11.38it/s]

Colored files path: /dlabdata1/boulenge/wikidumps_data/full_pages_experiment/colored_pages/simple/first_context_size.json

**Locally download the colored pages**

In [ ]:
user_cluster  = "boulenge@iccluster039"
local_path = "Desktop/htmls"

scp_command = f"scp -qr {user_cluster}:{output_dir} {local_path} > /dev/null"

#subprocess.run(scp_command, shell=True)

print(f"Run the following in the terminal to dowload the colored pages:\n{scp_command}")

Run the following in the terminal to dowload the colored pages:
scp -qr boulenge@iccluster039:/dlabdata1/boulenge/wikidumps_data/full_pages_experiement2/colored_pages Desktop/htmls > /dev/null