**Necessary imports**

In [1]:
import subprocess
import os
import pandas as pd
import json

%load_ext autoreload
%autoreload 2

**Setting parameters**

In [2]:
simple_render_raw_data_dir = "/dlabdata1/tsoares/wikidumps/"
root_processing_dir = "/dlabdata1/boulenge/wikidumps_data"
experiment_name = "selected_langs_small_sample"
processed_data_dir = os.path.join(root_processing_dir, experiment_name)
server_out_dir = os.path.join("/var/www/html/wikinsert", experiment_name)
processes = 48
min_nb_samples = 10
revisions_sampling_size = 0.0005 #10% of the revisions 

#For all possible languages
all_langs = sorted(set([filename.split("wiki")[0] for filename in os.listdir(simple_render_raw_data_dir) if "wiki" in filename]))

selected_langs_path = 'selected_languages.json'

with open(selected_langs_path, 'r') as f:
   langs = json.load(f)

side_context_sizes = [5]  #List of context size to try
second_month = "20231001"
third_month = "20231101"

langs_to_remove = ["war", "ky", "nds-nl"] #These languages do not work

for lang in langs_to_remove:
    if lang in all_langs:
        all_langs.remove(lang)

print("Will process languages:\n" + '\n'.join(langs))

Will process languages:
af
ar
cs
cy
de
en
es
fa
fr
ga
gu
he
hi
is
it
ja
jv
kk
kn
ms
pt
ru
simple
sk
sw
tr
ur
uz
vi
zh

**Defining data paths**

In [6]:
# Define directories
all_revisions_dir = os.path.join(root_processing_dir, "all_revisions")
rev_files_dir = os.path.join(processed_data_dir, "revisions_files")
parsed_htmls_dir = os.path.join(processed_data_dir, "parsed_htmls")
contexts_splitted_data_dir = os.path.join(processed_data_dir, "contexts_splitted_data")
ready_to_score_data_dir = os.path.join(processed_data_dir, "ready_to_score_data")
scored_data_dir = os.path.join(processed_data_dir, "scored_data")
crawling_output_dir = os.path.join(processed_data_dir, "crawled_pages")

# Create necessary directories if they don't exist
os.makedirs(all_revisions_dir, exist_ok=True)
os.makedirs(rev_files_dir, exist_ok=True)
os.makedirs(parsed_htmls_dir, exist_ok=True)
os.makedirs(contexts_splitted_data_dir, exist_ok=True)
os.makedirs(ready_to_score_data_dir, exist_ok=True)
os.makedirs(scored_data_dir, exist_ok=True)
os.makedirs(crawling_output_dir, exist_ok=True)
os.makedirs(server_out_dir, exist_ok=True)

**Prepare files to be crawled and parsed**

**Carefull, the following is only needed to be ran once for all (common for any experiment), so was probably ran before**

It generates the diffenret pages ids we will crawl, using data from the previous study

In [22]:
"""for lang in all_langs:
        print(f"Processing language: {lang}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{all_revisions_dir}/revisions_{lang}.parquet"
        if not os.path.exists(save_path):
            print("Generating revisions file")    
            subprocess.run([
                "python", "generate_revisions_file.py",
                "--versions_file", f"{second_month_path}/eval/link_versions",
                "--html_dir", f"{second_month_path}/eval/pages",
                "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
                "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",
                "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",
                "--save_path", save_path
            ])
        else:
            print("Revisions file already exists")"""

'for lang in all_langs:\n        print(f"Processing language: {lang}")\n        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"\n        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"\n        save_path = f"{all_revisions_dir}/revisions_{lang}.parquet"\n        if not os.path.exists(save_path):\n            print("Generating revisions file")    \n            subprocess.run([\n                "python", "generate_revisions_file.py",\n                "--versions_file", f"{second_month_path}/eval/link_versions",\n                "--html_dir", f"{second_month_path}/eval/pages",\n                "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",\n                "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet",\n                "--mention_map", f"{second_month_path}/processed_data/mention_map.parquet",\n                "--save_path", save_path\n            ])\n        else:\n            print("Revisions file already exists")'

**Sampling**

In [23]:
langs_stats = []

for lang in langs:
    full_revisions_path = f"{all_revisions_dir}/revisions_{lang}.parquet"
    full_revisions_df = pd.read_parquet(full_revisions_path)
    print(f"Sampling language: {lang}")
    nb_total = len(full_revisions_df)
    pre_min_to_sample = 2*min_nb_samples #we take twice the number to prevent future loss of data
    if nb_total > pre_min_to_sample:
        pre_nb_samples = max(pre_min_to_sample, int(revisions_sampling_size*2*nb_total))
    else:
        pre_nb_samples = nb_total

    if nb_total > min_nb_samples:
        nb_samples = max(min_nb_samples, int(revisions_sampling_size*nb_total))
    else:
        nb_samples = nb_total

    langs_stats.append({
        "lang": lang,
        "orig_nb_revisions": nb_total,
        "pre_nb_samples": pre_nb_samples,
        "nb_samples": nb_samples
    })

    sampled_revisions_path = f"{rev_files_dir}/revisions_{lang}.parquet"
    sampled_revisions = full_revisions_df.sample(n=pre_nb_samples, random_state=42)
    sampled_revisions.to_parquet(sampled_revisions_path)

display(pd.DataFrame(langs_stats))
display(pd.DataFrame(langs_stats).sum())

Sampling language: af
Sampling language: ar
Sampling language: cs
Sampling language: cy
Sampling language: de
Sampling language: en
Sampling language: es
Sampling language: fa
Sampling language: fr
Sampling language: ga
Sampling language: gu
Sampling language: he
Sampling language: hi
Sampling language: is
Sampling language: it
Sampling language: ja
Sampling language: jv
Sampling language: kk
Sampling language: kn
Sampling language: ms
Sampling language: pt
Sampling language: ru
Sampling language: simple
Sampling language: sk
Sampling language: sw
Sampling language: tr
Sampling language: ur
Sampling language: uz
Sampling language: vi
Sampling language: zh

      lang  orig_nb_revisions  pre_nb_samples  nb_samples
0       af                707              20          10
1       ar               6700              20          10
2       cs               4391              20          10
3       cy                238              20          10
4       de              49899              49          24
5       en             194300             194          97
6       es              29970              29          14
7       fa               7967              20          10
8       fr              26847              26          13
9       ga                109              20          10
10      gu                 16              16          10
11      he              17938              20          10
12      hi                745              20          10
13      is                285              20          10
14      it              22827              22          11
15      ja              36301              36          18
16      jv                 95              20          10
17      kk               1019              20          10
18      kn                199              20          10
19      ms               1526              20          10
20      pt               8520              20          10
21      ru              20743              20          10
22  simple               1841              20          10
23      sk               1286              20          10
24      sw                170              20          10
25      tr               6811              20          10
26      ur               3287              20          10
27      uz               1343              20          10
28      vi               3716              20          10
29      zh              18087              20          10

lang                 afarcscydeenesfafrgaguhehiisitjajvkkknmsptrusi...
orig_nb_revisions                                               467883
pre_nb_samples                                                     832
nb_samples                                                         417
dtype: object

**Crawling first versions only**

There is no need to re-crawl the second version with all its files as the index is sufficent for these.

In [7]:
for lang in langs:
    print(f"Processing language: {lang}")
    subprocess.run([
        "python", "crawl.py",
        "--revisions_path", f"{rev_files_dir}/revisions_{lang}.parquet",
        "--output_dir", f"{crawling_output_dir}/{lang}",
        "--n_processes", str(processes),
        "--lang", lang
    ])

Processing language: af
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.15749736626942953 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 135.38it/s]

Processing language: ar
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.3681405504544576 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 75.03it/s]

Processing language: cs
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.12054530779520671 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 177.35it/s]

Processing language: cy
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.10315655867258708 minutes, post processing...
Processing language: de

Moving files: 100%|██████████| 20/20 [00:00<00:00, 210.74it/s]

Total number of pages to crawl: 49
Running crawling on 48 processes
Crawling finished in 0.8132737954457601 minutes, post processing...

Moving files: 100%|██████████| 49/49 [00:00<00:00, 223.24it/s]

Processing language: en
Total number of pages to crawl: 194
Running crawling on 48 processes
Crawling finished in 1.0464308977127075 minutes, post processing...

Moving files: 100%|██████████| 194/194 [00:01<00:00, 181.42it/s]

Processing language: es
Total number of pages to crawl: 29
Running crawling on 48 processes
Crawling finished in 0.21906830072402955 minutes, post processing...

Moving files: 100%|██████████| 29/29 [00:00<00:00, 149.77it/s]

Processing language: fa
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.17080066601435342 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 139.67it/s]

Processing language: fr
Total number of pages to crawl: 26
Running crawling on 48 processes
Crawling finished in 0.27108974059422813 minutes, post processing...

Moving files: 100%|██████████| 26/26 [00:00<00:00, 139.29it/s]

Processing language: ga
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.17239914337793985 minutes, post processing...
Processing language: gu

Moving files: 100%|██████████| 20/20 [00:00<00:00, 194.08it/s]

Total number of pages to crawl: 16
Running crawling on 48 processes
Crawling finished in 0.1214573343594869 minutes, post processing...

Moving files: 100%|██████████| 16/16 [00:00<00:00, 122.06it/s]

Processing language: he
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.15044069290161133 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 156.26it/s]

Processing language: hi
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.14659740924835205 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 155.33it/s]

Processing language: is
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.12232841650644938 minutes, post processing...
Processing language: it

Moving files: 100%|██████████| 20/20 [00:00<00:00, 198.89it/s]

Total number of pages to crawl: 22
Running crawling on 48 processes
Crawling finished in 0.11940956910451253 minutes, post processing...

Moving files: 100%|██████████| 22/22 [00:00<00:00, 185.10it/s]

Processing language: ja
Total number of pages to crawl: 36
Running crawling on 48 processes
Crawling finished in 0.1571477969487508 minutes, post processing...

Moving files: 100%|██████████| 36/36 [00:00<00:00, 163.72it/s]

Processing language: jv
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.13249480724334717 minutes, post processing...
Processing language: kk

Moving files: 100%|██████████| 20/20 [00:00<00:00, 204.92it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.1435683528582255 minutes, post processing...
Processing language: kn

Moving files: 100%|██████████| 20/20 [00:00<00:00, 202.50it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.09522219896316528 minutes, post processing...
Processing language: ms

Moving files: 100%|██████████| 20/20 [00:00<00:00, 206.15it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.10506134827931722 minutes, post processing...
Processing language: pt

Moving files: 100%|██████████| 20/20 [00:00<00:00, 211.75it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.279763925075531 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 168.00it/s]

Processing language: ru
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.09749630292256674 minutes, post processing...
Processing language: simple

Moving files: 100%|██████████| 20/20 [00:00<00:00, 190.78it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.12528279622395833 minutes, post processing...
Processing language: sk

Moving files: 100%|██████████| 20/20 [00:00<00:00, 197.02it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.11226094166437785 minutes, post processing...
Processing language: sw

Moving files: 100%|██████████| 20/20 [00:00<00:00, 215.76it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.08635321458180746 minutes, post processing...
Processing language: tr

Moving files: 100%|██████████| 20/20 [00:00<00:00, 220.83it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.12791096766789753 minutes, post processing...
Processing language: ur

Moving files: 100%|██████████| 20/20 [00:00<00:00, 186.75it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.18968360821406047 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 120.15it/s]

Processing language: uz
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.102299698193868 minutes, post processing...
Processing language: vi

Moving files: 100%|██████████| 20/20 [00:00<00:00, 196.03it/s]

Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.13142793575922648 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 161.20it/s]

Processing language: zh
Total number of pages to crawl: 20
Running crawling on 48 processes
Crawling finished in 0.15469912687937418 minutes, post processing...

Moving files: 100%|██████████| 20/20 [00:00<00:00, 160.31it/s]

**Parsing of the htmls and sentence tokenizing**

In [9]:
for lang in langs:
    print(f"Processing language: {lang}")
    second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
    first_version_specific_html_dir = f"{crawling_output_dir}/{lang}"
    save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
    output_dir = f"{parsed_htmls_dir}/{lang}_v2"
    first_version_specific_output_dir = f"{parsed_htmls_dir}/{lang}_v1"
        
    subprocess.run([
        "python", "parsing.py",
        "--revisions_path", save_path,        
        "--html_dir", f"{second_month_path}/eval/pages",
        "--first_versions_specific_html_dir", first_version_specific_html_dir,
        "--output_dir", output_dir,
        "--first_versions_specific_output_dir", first_version_specific_output_dir,
        "--lang", lang,
        "--n_processes", str(processes)
    ])

    parsed_htmls_paths = os.listdir(first_version_specific_output_dir)
    sentences_path = list(
        filter(
            lambda x: (
                x.endswith("sentences.jsonl") and ("raw" not in x)
                ),
            parsed_htmls_paths
            )
        )[0]
    links_path = list(filter(lambda x: x.endswith("links.jsonl"), parsed_htmls_paths))[0]
    sentences_df = pd.read_json(f"{first_version_specific_output_dir}/{sentences_path}")
    links_df = pd.read_json(f"{first_version_specific_output_dir}/{links_path}")

    display(sentences_df.head(5))
    display(links_df.head(5))

Processing language: af
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/af
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 59.78it/s]

Time taken for v1: 15.523229360580444
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 61.54it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,1509afbe912fc0e70ec3d7a083f7e21b,0,Piket-Bo-Berg is 'n plaasgemeenskap geleë in d...,34755,34882,Lead,"[{'start': 34755, 'end': 34768}, {'start': 347..."
1,c771bb69375660fb63a2c352317aafc7,1,Die gemeenskap lê bo-op die Piketberge en is n...,34882,35033,Lead,"[{'start': 34882, 'end': 34950}, {'start': 349..."
2,47b40cd8340f99c7be3ce1ea8b867e63,2,Dit is oor tyd deur 'n verskeidenheid boere be...,35033,35145,Lead,"[{'start': 35033, 'end': 35145}]"
3,49a811f19c48f823bf7f53ecdee39c16,3,"Voorheen is die Bo-Berg bewoon deur Boesmanne,...",35145,35239,Lead,"[{'start': 35145, 'end': 35239}]"
4,166bf21d3b5aa648f209a64e799810a6,4,In 1810 was daar vyf plase wat daar op die Ber...,35239,35307,Lead,"[{'start': 35246, 'end': 35307}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Russies,55494,Russies,55545,Lead,0
1,file:///wiki/11_Maart,55878,11 Maart,55932,Lead,0
2,file:///wiki/1818,55933,1818,55975,Lead,0
3,file:///wiki/14_Julie,56068,14 Julie,56122,Lead,0
4,file:///wiki/Ou_Styl-_en_Nuwe_Styl-datums,56124,1 Julie,56217,Lead,0

Processing language: ar
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/ar
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 52.25it/s]

Time taken for v1: 29.342939376831055
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 50.86it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c27eb9685a5f1a1eb3ac0779e8acc780,0,هل تقصد:\n\nميدان الشهداء أكبر ميادين الإسكندر...,46026,46433,Lead,"[{'start': 46026, 'end': 46035}, {'start': 460..."
1,3221f2aca4efbf9cf967f7d8b35fd4f5,1,\nميدان الشهداء في العاصمة الليبية طرابلس.,46433,46784,Lead,"[{'start': 46438, 'end': 46439}, {'start': 466..."
2,e0c8e70c897fc102d57200ce83426f37,2,\nميدان الشهداء في العاصمة اللبنانية بيروت.,46784,47197,Lead,"[{'start': 46789, 'end': 46790}, {'start': 470..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9...,89458,,89819,Lead,0
1,file:///wiki/%D8%AD%D8%B2%D8%A8_%D8%A7%D9%84%D...,89856,حزب الله (توضيح),90014,Lead,0
2,file:///wiki/%D8%A5%D8%B3%D9%84%D8%A7%D9%85_%D...,137612,حزب سياسي إسلامي,137730,Lead,1
3,file:///wiki/%D8%A7%D9%84%D8%B4%D9%8A%D8%B9%D8%A9,137731,شيعي,137807,Lead,1
4,file:///wiki/%D9%85%D9%8A%D9%84%D9%8A%D8%B4%D9...,137808,مسلح,137891,Lead,1

Processing language: cs
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/cs
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 75.25it/s]

Time taken for v1: 14.56418490409851
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 79.11it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,7874d8bc19165cf9c403c03c0bfd6cc8,0,Toto je seznam památek světového dědictví UNES...,42156,42222,Lead,"[{'start': 42156, 'end': 42171}, {'start': 421..."
1,3a0c0f497024979ece49a52f8e126310,1,Pro obsáhlost je Seznam světového kulturního a...,42222,42405,Lead,"[{'start': 42229, 'end': 42405}]"
2,c050a296e1d68faf8a3ab45b8d4276d5,2,Tato část obsahuje státy od Německa po Rusko.,42405,42451,Lead,"[{'start': 42405, 'end': 42451}]"
3,582d52042fd9117baca3584e1de81749,3,Následující přehled památek je aktuální k datu...,42451,42528,Lead,"[{'start': 42451, 'end': 42498}, {'start': 425..."
4,363cab87d44298af9697e28d558f679f,4,"U každé položky je uveden český název, oficiál...",42528,42693,Lead,"[{'start': 42535, 'end': 42693}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Fyzika_%C4%8D%C3%A1stic,50231,částicové fyzice,50313,Lead,0
1,file:///wiki/Boson,50358,bosony,50404,Lead,0
2,file:///wiki/Spin,50429,spinem,50473,Lead,0
3,file:///wiki/Gluon,50511,gluon,50556,Lead,0
4,file:///wiki/Foton,50558,foton,50603,Lead,0

Processing language: cy
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/cy
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 40.90it/s]

Time taken for v1: 6.2638304233551025
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 82.31it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,43b631d45fd807f4731a5af7dcf19b96,0,"\nPentref yn Awstria yw Fucking, wedi'i leoli...",53273,53698,Lead,"[{'start': 53271, 'end': 53273}, {'start': 533..."
1,9214d4938983574d0126b53d165d7210,1,Mae'r pentref yn gorwedd 33&nbsp;km i'r gogled...,53698,53924,Lead,"[{'start': 53698, 'end': 53748}, {'start': 537..."
2,816f10f755f9aa794a9f4669afbcf3a6,2,Mae'r enw yn rhegair yn Saesneg.,53924,54008,Lead,"[{'start': 53931, 'end': 53955}, {'start': 539..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Sosialaeth,78002,sosialaidd,78062,Lead,2
1,file:///wiki/Ewrop,78140,Ewrop,78185,Lead,2
2,file:///wiki/Rwsia,78188,Rwsia,78233,Lead,2
3,file:///wiki/Hawliau_dynol,78401,hawliau dynol,78470,Lead,3
4,file:///wiki/Clara_Zetkin,79511,Clara Zetkin,79577,Hanes y diwrnod,6

Processing language: de
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/de
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 49/49 [00:01<00:00, 26.76it/s]

Time taken for v1: 182.00779581069946
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 49/49 [00:01<00:00, 28.75it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,3adc323b94f5bb2bc00fbc78b36133d3,0,Maria Louise Eleonore von Hessen-Rotenburg (* 18.,9631,9729,Lead,"[{'start': 9631, 'end': 9673}, {'start': 9677,..."
1,06bd0d2d3f7c228b86f5b0adfa7074da,1,April 1729 auf Schloss Rotenburg; † 6.,9729,9918,Lead,"[{'start': 9729, 'end': 9734}, {'start': 9738,..."
2,4b2b253ec49f8652656e6cbb14cc6986,2,Januar 1800 auf Schloss Anholt) war eine landg...,9918,10250,Lead,"[{'start': 9918, 'end': 9924}, {'start': 9928,..."
3,806055f5c9f9f0efec57cf246cdae867,3,\n\nMaria Louise wurde als Tochter des Erbprin...,10250,10796,Leben,"[{'start': 10254, 'end': 10255}, {'start': 103..."
4,983bc2984debb2edc4d71aa6bc08cee9,4,Am 16. März 1756 heiratete sie in Hoogstraten ...,10796,11260,Leben,"[{'start': 10803, 'end': 10837}, {'start': 109..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Besatzungszone,12077,Besatzungszonen,12150,Lead,0
1,file:///wiki/Deutschland_1945_bis_1949,12154,besetzten Deutschland,12255,Lead,0
2,file:///wiki/Territorium,12286,territorialen,12351,Lead,1
3,file:///wiki/Harz_(Mittelgebirge),12369,Harz,12443,Lead,1
4,file:///wiki/Vereinigtes_K%C3%B6nigreich,15049,Briten,15134,Geschichte,2

Processing language: en
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/en
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 194/194 [00:04<00:00, 47.18it/s]

Time taken for v1: 121.81329798698425
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 194/194 [00:03<00:00, 48.83it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,c6a44f55f7e71837145ce9f653763b34,0,\nThalapathy 68 is the working title of an upc...,42741,43139,Lead,"[{'start': 42740, 'end': 42741}, {'start': 427..."
1,f977de3d97c855a76fc4626032a05c6e,1,"The film stars Vijay, leading an ensemble cast...",43139,44227,Lead,"[{'start': 43139, 'end': 43154}, {'start': 432..."
2,a5be16b7c0ca211aaa61f485f84e5a72,2,"Initially, Atlee was reported to direct the pr...",44227,44396,Lead,"[{'start': 44234, 'end': 44245}, {'start': 443..."
3,727435c628daccbc79a242d2e2814892,3,The film was announced in May 2023 under the t...,44396,44525,Lead,"[{'start': 44396, 'end': 44457}, {'start': 444..."
4,02ff19da1c68b6dab91b58016facede6,4,Principal photography began in October 2023.,44525,44642,Lead,"[{'start': 44593, 'end': 44614}, {'start': 446..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Stock_car_racing,52430,stock car racing,52508,Lead,0
1,file:///wiki/NASCAR_Cup_Series,52535,NASCAR Cup Series,52616,Lead,0
2,file:///wiki/NASCAR_Xfinity_Series,52621,NASCAR Xfinity Series,52714,Lead,0
3,file:///wiki/Matt_Kaulig,52737,Matt Kaulig,52820,Lead,1
4,file:///wiki/Chevrolet_Camaro_(sixth_generatio...,53024,Chevrolet Camaro ZL1,53148,Lead,2

Processing language: es
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/es
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 29/29 [00:00<00:00, 47.36it/s]

Time taken for v1: 19.981465339660645
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 29/29 [00:00<00:00, 33.63it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,cbcfd33e992ebd1b250c43e5e71ffab1,0,\nLos ataques contra palestinos que evacuan la...,44680,45352,Lead,"[{'start': 44679, 'end': 44680}, {'start': 446..."
1,b3d089df616633a155288473e4f0ac8e,1,​ Estos ataques tuvieron lugar después de una ...,45352,45708,Lead,"[{'start': 45520, 'end': 45708}]"
2,4d6c0999d60cdfda3f49f0cdd55da1c5,2,​\n\n\n\nLas tensiones aumentaron cuando milic...,45708,46312,Antecedentes,"[{'start': 45876, 'end': 45878}, {'start': 458..."
3,7edb8084e65d6309021d301676963578,3,El país Hebreo respondió con una serie de ataq...,46312,46529,Antecedentes,"[{'start': 46312, 'end': 46354}, {'start': 464..."
4,611804985aa4dd462b172ff19dd23d56,4,Las Fuerzas de Defensa de Israel (FDI) emitier...,46529,46780,Antecedentes,"[{'start': 46529, 'end': 46533}, {'start': 466..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Bowling,40140,bowling,40191,Lead,1
1,file:///wiki/Kingstree_(Carolina_del_Sur),40546,"Kingstree, Carolina del Sur",40659,Biografía,3
2,file:///wiki/Pittsburgh,41089,Pittsburgh,41149,Biografía,6
3,file:///wiki/S%C3%B3ftbol,41247,sóftbol,41303,Biografía,7
4,file:///wiki/Baloncesto,41306,baloncesto,41366,Biografía,7

Processing language: fa
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/fa
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 35.69it/s]

Time taken for v1: 17.979573726654053
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 65.21it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,96c172268cb3122d937ce6ccbd23eb05,0,\nبِنیتو آنتونیو مارتینِز اُکاسیو ((به اسپانیا...,52934,53688,Lead,"[{'start': 52933, 'end': 52934}, {'start': 529..."
1,e92a13f2bdd2d6071baade2e560e2f85,1,او اهل پورتوریکو است.,53688,53803,Lead,"[{'start': 53688, 'end': 53695}, {'start': 537..."
2,2fd81f6beea20a00e924a2920d75fd93,2,هنگامی که در سوپر مارکتی به عنوان حسابدار و در...,53803,54042,Lead,"[{'start': 53803, 'end': 53887}, {'start': 539..."
3,2e6c114710158daa66248960fb9936c6,3,آهنگ soy peor (من بدترم) در سال ۲۰۱۷ تک آهنگی ...,54042,54418,Lead,"[{'start': 54042, 'end': 54047}, {'start': 540..."
4,f8c1607ac1dceef80b308a201c253681,4,این آهنگ در ۱۰۰ آهنگ داغ بیلبورد، آهنگ شماره ی...,54418,54866,Lead,"[{'start': 54418, 'end': 54430}, {'start': 546..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86_%D...,83924,ایران بزرگ,84029,Lead,0
1,file:///wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86,84040,ایران,84110,Lead,0
2,file:///wiki/%D8%B1%D8%AE%D8%AC,84151,رُخَج,84207,Lead,1
3,file:///wiki/%D9%82%D9%86%D8%AF%D9%87%D8%A7%D8%B1,84223,قندهار,84301,Lead,1
4,file:///wiki/%D8%B2%D8%A7%D8%A8%D9%84%D8%B3%D8...,84308,زابُلِستان,84404,Lead,1

Processing language: fr
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/fr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 26/26 [00:00<00:00, 43.55it/s]

Time taken for v1: 29.538939952850342
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 26/26 [00:00<00:00, 42.49it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,54b9f040c8ba7ad8e0dfa6fdaa37d709,0,\n\n\nLe gouffre Jean-Bernard est une cavité s...,44976,54214,Lead,"[{'start': 44975, 'end': 44976}, {'start': 457..."
1,7b9d5824238cc2c7934374e8b2382171,1,\n\n\nLe gouffre a été ainsi baptisé par les s...,54214,54732,Historique,"[{'start': 54218, 'end': 54219}, {'start': 542..."
2,c970acaf91137ff64724a613cd77b70f,2,Le gouffre (V4) est trouvé en 1963 et arrêté à...,54732,54841,Historique,"[{'start': 54739, 'end': 54841}]"
3,b881ef8a8fe8ed71418bbb38c833edfc,3,Le collecteur est atteint à −210&nbsp;mètres e...,54841,54895,Historique,"[{'start': 54841, 'end': 54895}]"
4,c36a8f933241cfb8c04f479fb60b23a5,4,"Toujours en été, en 1965 et 1966, l'arrêt est ...",54895,54989,Historique,"[{'start': 54895, 'end': 54989}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Rouergue,57068,Rouergue,57122,Lead,1
1,file:///wiki/Aveyron_(d%C3%A9partement),57156,Aveyron,57240,Lead,1
2,file:///wiki/Saint-Georges-de-Luzen%C3%A7on,57533,Saint-Georges-de-Luzençon,57643,Histoire,4
3,file:///wiki/Millau,57653,Millau,57701,Histoire,4
4,file:///wiki/Bourgeoisie,57802,bourgeoisie,57865,Histoire,6

Processing language: ga
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/ga
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 81.97it/s]

Time taken for v1: 5.065596103668213
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 80.27it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,44f0f855f113dda4a1d8ccffeb946682,0,"\nBa shagart, urscéalaí, drámadóir, aistrithe...",43980,44726,Lead,"[{'start': 43978, 'end': 43980}, {'start': 439..."
1,d52203052ca557f7d0986b4f636ba543,1,\nBhí sé ina Ollamh le Fraincis i Maigh Nuad ...,44726,45092,Lead,"[{'start': 44801, 'end': 44803}, {'start': 448..."
2,20d3e09db4c99afc58c9c564a66eedaf,2,Néal Maidine agus Tine Oíche (1964) agus An Br...,45092,45283,Lead,"[{'start': 45095, 'end': 45123}, {'start': 451..."
3,96ce206d343e396a6663b2f656157003,3,Ba cheannródaí i gcritic na Gaeilge é Breandán...,45283,45348,Lead,"[{'start': 45290, 'end': 45348}]"
4,c5104f865dfd4cf5ba22bb93a8fb0e92,4,"Bhunaigh sé Scoil Chritice Mhá Nuad, a chuir ...",45348,45671,Lead,"[{'start': 45423, 'end': 45487}, {'start': 455..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/R%C3%ADocht_Aontaithe,90678,Ríocht Aontaithe,90781,Féilte,2
1,file:///wiki/1739,90981,1739,91023,Daoine a rugadh ar an lá seo,2
2,file:///wiki/Luis_de_Alburquerque_de_Melo_Pere...,91026,Luis de Alburquerque de Melo Pereira y Cáceres,91199,Daoine a rugadh ar an lá seo,2
3,file:///wiki/1797,91266,1797,91308,Daoine a rugadh ar an lá seo,3
4,file:///wiki/1790,91319,1790,91361,Daoine a rugadh ar an lá seo,3

Processing language: gu
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/gu
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 16/16 [00:00<00:00, 81.61it/s]

Time taken for v1: 6.066070318222046
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 16/16 [00:00<00:00, 73.09it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,43c8fc14e5c1b2f11c03ac57d51965ea,0,ઇમામશાહ બાવા દરગાહ (ઉર્દૂ امام شاہ باوا درگاہ)...,42145,42373,Lead,"[{'start': 42145, 'end': 42163}, {'start': 421..."
1,a4875fbf62407c72cc2a65775ed7a730,1,પીર ઇમામ શાહ બાવાએ લગભગ ૬૦૦ વર્ષ પહેલાં સતપંથ ...,42373,42457,Lead,"[{'start': 42373, 'end': 42457}]"
2,c71bb1bed1f577479ceeabfc4e56430d,2,તેમણે ધર્મોની સાર્વત્રિકતા પર સહિષ્ણુતા શીખવી ...,42457,42507,Lead,"[{'start': 42457, 'end': 42507}]"
3,7542a3075d32077d115eb29070c45d2d,3,"૧૯૩૧ સુધી, આ સંકુલ એક ખાનગી સંપત્તિ હતી જે સૈ...",42507,42674,Lead,"[{'start': 42582, 'end': 42674}]"
4,6df19688d00a30f54cd2bbe0233401d5,4,સંકુલમાં એક જૂની મસ્જિદ પણ અસ્તિત્વમાં હતી.,42674,42793,Lead,"[{'start': 42749, 'end': 42793}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%AA%87%E0%AA%A8%E0%AB%8D%E0%AA...,54075,IMDb,54303,બાહ્ય કડીઓ,17
1,file:///wiki/%E0%AA%97%E0%AB%81%E0%AA%9C%E0%AA...,54316,ગુજરાતી વિશ્વકોશમાં,54517,બાહ્ય કડીઓ,17

Processing language: he
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/he
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 37.12it/s]

Time taken for v1: 17.96557378768921
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 51.58it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b70ab151c7eec68fc1ee5275beb9e6b6,0,\n\n\nלדאק היא טריטוריית איחוד השוכנת בצפון הו...,70287,71611,Lead,"[{'start': 70286, 'end': 70287}, {'start': 707..."
1,dac62cfc014ff66501c339773fe8c87f,1,"עד 2019 הייתה חלק ממדינת ג'אמו וקשמיר, והפחות ...",71611,71845,Lead,"[{'start': 71611, 'end': 71614}, {'start': 716..."
2,c1d808845931cc1c8eeaa87df315135b,2,"לדאק מחולקת לשני מחוזות, קרגיל ולה, ובירתו היא...",71845,72372,Lead,"[{'start': 71845, 'end': 71870}, {'start': 720..."
3,2a3f983bc2f8c3791402e184686566a0,3,ב-31 באוקטובר 2019 קיבלה לדאק מעמד של טריטוריי...,72372,72768,Lead,"[{'start': 72372, 'end': 72374}, {'start': 724..."
4,3fe39adf59e51373ee62053b5ffdb04b,4,"\n\n\nגובה החבל נע בין 3,000 מטר מעל פני הים ב...",72768,73024,גאוגרפיה,"[{'start': 72772, 'end': 72773}, {'start': 728..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D7%91%D7%95%D7%91_%D7%9E%D7%95%D...,82267,בוב מורלי,82364,Lead,0
1,file:///wiki/%D7%90%D7%A0%D7%92%D7%9C%D7%99%D7%AA,93018,אנגלית,93096,Lead,1
2,file:///wiki/6_%D7%91%D7%A4%D7%91%D7%A8%D7%95%...,93127,6 בפברואר,93219,Lead,1
3,file:///wiki/1945,93220,1945,93262,Lead,1
4,file:///wiki/11_%D7%91%D7%9E%D7%90%D7%99,93265,11 במאי,93336,Lead,1

Processing language: hi
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/hi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 71.72it/s]

Time taken for v1: 12.158806085586548
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 70.46it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b02d3da8b92b888d6938dca31514c97e,0,जोशी&nbsp;: जोशी जाति के ब्राह्मणों की पूर्व ज...,41081,41153,Lead,"[{'start': 41081, 'end': 41153}]"
1,6aecaac723c46ddea8a45effb7c61fae,1,ये जाति कुमाऊं से सम्वत 1700 में गढ़वाल आई और ...,41153,41223,Lead,"[{'start': 41153, 'end': 41223}]"
2,024cda9d20338af92739e860bcbd08a9,2,जोशी भारत और नेपाल में ब्राह्मण (जाति) द्वारा ...,41223,41314,Lead,"[{'start': 41230, 'end': 41314}]"
3,619bb15126fc2f59ac75c25291704c0e,3,जोशी को कभी-कभी ज्योशी भी कहा जाता है।,41314,41353,Lead,"[{'start': 41314, 'end': 41353}]"
4,a57eeb54ec2b540e592c9df0eb405228,4,यह नाम संस्कृत शब्द ज्योतिषी से लिया गया है जि...,41353,41467,Lead,"[{'start': 41353, 'end': 41467}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%A4%B0%E0%A5%89%E0%A4%AF%E0%A4...,75275,रॉयटर्स,75382,वार्ता,10
1,file:///wiki/%E0%A4%8F%E0%A4%B8%E0%A5%8B%E0%A4...,75854,एसोसिएटेड प्रेस,76041,वार्ता,10
2,file:///wiki/%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A4...,77180,स्काई न्यूज़,77324,वार्ता,10

Processing language: is
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/is
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 82.04it/s]

Time taken for v1: 7.306291103363037
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 79.91it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,3b0c678339a62c2c8948ada819aa1393,0,\n\n\n\nSeattle er borg í norðvesturhluta Band...,69937,71975,Lead,"[{'start': 69936, 'end': 69937}, {'start': 705..."
1,06d0a570cde3993d898c3d1a88df9b34,1,Áætlaður íbúafjöldi árið 2016 var um 704 þúsun...,71975,72085,Lead,"[{'start': 71975, 'end': 72085}]"
2,1cacd8cab64aa47d489ca3c76836b296,2,Seattle er þekkt sem fæðingarstaður gruggtónli...,72085,72335,Lead,"[{'start': 72085, 'end': 72121}, {'start': 721..."
3,2b70e608c07c6ca486e27316b97db7cf,3,Borgin heitir eftir Seattle höfðingja frumbygg...,72335,72467,Lead,"[{'start': 72335, 'end': 72355}, {'start': 724..."
4,40f01bfe1902d8097d7f5426fe4ee8b6,4,\n\n&nbsp;&nbsp;Þessi Bandaríkja-tengda grein ...,72467,75182,Lead,"[{'start': 72471, 'end': 72472}, {'start': 743..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/17._okt%C3%B3ber,61383,17. október,61451,Lead,1
1,file:///wiki/1466,61452,1466,61494,Lead,1
2,file:///wiki/12._j%C3%BAl%C3%AD,61502,12. júlí,61566,Lead,2
3,file:///wiki/1536,61567,1536,61609,Lead,2
4,file:///wiki/H%C3%BAmanismi,61626,húmanisti,61688,Lead,2

Processing language: it
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/it
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 22/22 [00:00<00:00, 40.54it/s]

Time taken for v1: 19.26735782623291
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 22/22 [00:00<00:00, 49.08it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,9cf1beba6ce018dec5956d013b2852e0,0,\nKhaled Khalifa (in&nbsp;arabo خالد خليفة‎; A...,12830,13758,Lead,"[{'start': 12829, 'end': 12830}, {'start': 128..."
1,7c82c239c5aa023de77f89dd745ae855,1,"\n\n\n\nNato ad Aleppo nel 1964, dopo la laure...",13758,15152,Biografia,"[{'start': 13762, 'end': 13763}, {'start': 148..."
2,2763a0e23f2b89459b41bedea5bf1e9a,2,"Sceneggiatore per il cinema e la televisione, ...",15152,15371,Biografia,"[{'start': 15159, 'end': 15294}, {'start': 153..."
3,84846a8e79236332f8b820a2bec752d8,3,Da sempre critico nei confronti del governo As...,15371,15645,Biografia,"[{'start': 15378, 'end': 15568}, {'start': 156..."
4,426f162b771929dd59842eafa32b3bf1,4,Autore di quattro romanzi e di alcune raccolte...,15645,16021,Biografia,"[{'start': 15652, 'end': 15733}, {'start': 158..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Aiuto:Voce,11739,voci,11793,Lead,0
1,file:///wiki/Aiuto:Disambiguazione,11875,pagina di disambiguazione,11972,Lead,1
2,file:///wiki/Aiuto:Wikilink,12005,collegamento,12075,Lead,1
3,file:///wiki/Speciale:Prefissi/Tempio_di_Minerva,12183,iniziano con,12295,Lead,2
4,file:///wiki/Speciale:Ricerca/intitle:%22Tempi...,12298,contengono,12440,Lead,2

Processing language: ja
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/ja
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 36/36 [00:00<00:00, 53.25it/s]

Time taken for v1: 34.774678230285645
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 36/36 [00:00<00:00, 50.32it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,a499cdce40e2985fc9f3ad47bcbb91d0,0,\n\nナガスクジラ（長須鯨、長鬚鯨、Balaenoptera physalus）は、哺乳綱...,65486,74786,Lead,"[{'start': 65485, 'end': 65486}, {'start': 742..."
1,babd634285b9a71ffc55ecd9af24bf35,1,\n\n\n日本では、シロナガスクジラにも「長須鯨」という呼称が使われる場合が散見されたため...,74786,75176,名称,"[{'start': 74790, 'end': 74791}, {'start': 748..."
2,394d651673d0d2340de0a1467242449f,2,英語では少なくとも5つの呼称が存在し、遊泳の速さから「海のグレイハウンド」という異名がある。,75176,75635,名称,"[{'start': 75229, 'end': 75231}, {'start': 752..."
3,e7571f084275c4eef5d59b1b9fbcd121,3,中国語では、「长须鲸」や「剃刀鲸」など英語や日本語に準拠した呼称になっている。,75635,75742,名称,"[{'start': 75698, 'end': 75701}, {'start': 757..."
4,6f9ae6324d7d86932a2c4f773f6611b8,4,韓国語ではセミクジラと呼称が混同される場合が非常に多かったが、2015年にセミクジラが41年...,75742,76584,名称,"[{'start': 75825, 'end': 75828}, {'start': 758..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E8%97%A4%E5%AD%90%E4%B8%8D%E4%BA...,52587,藤子不二雄,52672,Lead,0
1,file:///wiki/%E8%97%A4%E5%AD%90%E3%83%BBF%E3%8...,52680,藤子・F・不二雄,52790,Lead,0
2,file:///wiki/%E6%97%A5%E6%9C%AC,52794,日本,52846,Lead,0
3,file:///wiki/%E3%82%B5%E3%82%A4%E3%82%A8%E3%83...,52847,SF,52999,Lead,0
4,file:///wiki/%E6%BC%AB%E7%94%BB,52999,漫画,53051,Lead,0

Processing language: jv
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/jv
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 36.98it/s]

Time taken for v1: 65.55494165420532
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 27.48it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,d9948346e3399d4deb5e312a722d3522,0,"\nRichard Buckminster ""Bucky"" Fuller (12 Juli ...",201624,202571,Lead,"[{'start': 201623, 'end': 201624}, {'start': 2..."
1,67110cfa0f057a693b6e164a26cce96c,1,\n\n\nPratélan paten: http://www.bfi.org/paten...,202571,205772,None,"[{'start': 202575, 'end': 202576}, {'start': 2..."
2,9bb1dc2b674350dadb2d85c4606de721,2,\nYour Private Sky (ISBN 3-907044-88-6)\nIdeas...,205772,206912,None,"[{'start': 205777, 'end': 205778}, {'start': 2..."
3,7d4095353441cc76db6b441836e7f080,3,"Buckminster Fuller on Education (1979, ASIN 08...",206912,207791,None,"[{'start': 206912, 'end': 206943}, {'start': 2..."
4,531e7c33568075ec4ca8bc4d82bda936,4,Baldwin\nPierre Cabrol\nJoseph Clinton\nDavid ...,207791,209708,None,"[{'start': 207791, 'end': 207798}, {'start': 2..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Salya,38434,Prabu Salya,38485,Lead,0
1,file:///wiki/Mahabharata,38490,Mahabharata,38553,Lead,0
2,file:///wiki/Endang_Pujawati,38576,Endang Pujawati,38651,Lead,1
3,file:///wiki/Astina,38854,Astina,38922,Lead,2
4,file:///wiki/Banowati,39011,Déwi Banowati,39070,Lead,4

Processing language: kk
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/kk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 78.78it/s]

Sentid is null for link:
14853
Anchor node from html:  an typeof="mw:File"><a href="/wiki/%D0%A3%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%90%D0%B9%D1%80%D1%8B%D2%9B" title="Айрық бет"><img alt="Айрық бет" src="15px-Disambig.svg.png" decoding="async" width="15" height="12" class="mw-file-element" srcset="23px-Disambig.svg.png 1.5x, 30px-Disambig.svg.png 2x" data-file-width="230" data-file-height="183"></a></span></div>
<div c
Time taken for v1: 9.40884017944336
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 74.45it/s]

Sentid is null for link:
15060
Anchor node from html:  an typeof="mw:File"><a href="/wiki/%D0%A3%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%90%D0%B9%D1%80%D1%8B%D2%9B" title="Айрық бет"><img alt="Айрық бет" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Disambig.svg/15px-Disambig.svg.png" decoding="async" width="15" height="12" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Disambig.svg/23px-Disambig.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Disambig.svg/30px-Disambig.svg.png 2x" data-file-width="230" data-file-height="183" /></a></span></div>
<div c

,md5,id,text,startIdx,endIdx,section,locList
0,58585e795ed49bb843aa0788a2b75fda,0,"Вениамин Александрович Каверин (19.4.1902, Пск...",12378,12528,Lead,"[{'start': 12378, 'end': 12408}, {'start': 124..."
1,4c5fcb21fccebe1fcca34030ca444f8e,1,Алғашқы әңгімесі 1922 жылы жариаланды.,12528,12567,Lead,"[{'start': 12528, 'end': 12567}]"
2,f4ee042a94d572d2c9704b7dc3b5fcc9,2,"«Тілектің орындалуы»(1934-1936), «Екі капитан»...",12567,12711,Lead,"[{'start': 12567, 'end': 12711}]"
3,1e4a275a42de1dfe29a01ec2ab84284d,3,Шығармалардың негізгі идеялық арқауы – совет и...,12711,12839,Lead,"[{'start': 12711, 'end': 12839}]"
4,a2305fb027dab2141f810bbd1ace2c6c,4,Каверин кітаптары көптеген шетелдік және КСРО...,12839,12914,Lead,"[{'start': 12839, 'end': 12914}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%90%D2%93%D1%8B%D0%BB%D1%88%D1...,11361,ағылш.,11476,Lead,1
1,file:///wiki/25_%D0%BC%D0%B0%D0%BC%D1%8B%D1%80,11525,25 мамыр,11604,Lead,1
2,file:///wiki/1921_%D0%B6%D1%8B%D0%BB,11605,1921,11670,Lead,1
3,file:///wiki/%D0%91%D0%B0%D0%B4-%D0%9A%D0%B8%D...,11672,Бад Киссинген,11801,Lead,1
4,file:///wiki/%D0%93%D0%B5%D1%80%D0%BC%D0%B0%D0...,11803,Германия,11897,Lead,1

Processing language: kn
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/kn
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 77.34it/s]

Time taken for v1: 5.375196695327759
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 74.75it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,5ad4fd44ae40f449d4e0a29472904b67,0,\n\n\nಗೋಧಿ ಪ್ರಪಂಚ ಎಲ್ಲೆಡೆ ಬಳಕೆಯಲ್ಲಿರುವ ಒಂದು ಏಕ...,78880,87309,Lead,"[{'start': 78879, 'end': 78880}, {'start': 872..."
1,3a2c3ce3ab68876fc92b111b8523c61d,1,ಪ್ರಪಂಚ ಅತ್ಯಂತ ಹೆಚ್ಚು ಬೆಳೆಸುವ ಧಾನ್ಯಗಳಲ್ಲಿ ಮೂರನೆ...,87309,87362,Lead,"[{'start': 87309, 'end': 87362}]"
2,786fe316e480c6f190cabd8bff92f718,2,ವಾರ್ಷಿಕ ಉತ್ಪಾದನೆ ಸುಮಾರು ೬೫೧ ಮಿಲಿಯನ್ ಟನ್‍ಗಳು.(೨...,87362,87414,Lead,"[{'start': 87362, 'end': 87414}]"
3,1f5625d82aec1ef61e5ebedd9e2e1505,3,ಜೋಳ ಮತ್ತು ಅಕ್ಕಿ ಗಿಂತ ಹೆಚ್ಚು ಪ್ರೋಟೀನ್‍ನ್ನು ಹೊಂದ...,87414,87785,Lead,"[{'start': 87470, 'end': 87473}, {'start': 874..."
4,e45b55f65c047e669f39e68ab7233978,4,ಗೋಧಿಯು ಅದರ ಬೀಜಕ್ಕಾಗಿ ವ್ಯಾಪಕವಾಗಿ ಬೆಳೆಸಲಾಗುದ ಹುಲ...,87785,87843,Lead,"[{'start': 87792, 'end': 87843}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E0%B2%86%E0%B2%B0%E0%B3%8B%E0%B2...,43488,ಆರೋಗ್ಯ,43584,ಇನ್ನರ್ ಇಂಜಿನಿಯರಿಂಗ್ ದರ್ಶನ:,3
1,file:///wiki/%E0%B2%86%E0%B2%A4%E0%B3%8D%E0%B2%AE,43663,ಆತ್ಮ,43737,ಇನ್ನರ್ ಇಂಜಿನಿಯರಿಂಗ್ ದರ್ಶನ:,4
2,file:///wiki/%E0%B2%AE%E0%B2%A8%E0%B2%B8%E0%B3...,43739,ಮನಸ್ಸು,43835,ಇನ್ನರ್ ಇಂಜಿನಿಯರಿಂಗ್ ದರ್ಶನ:,4
3,file:///wiki/%E0%B2%AF%E0%B3%8B%E0%B2%97,44636,ಯೋಗ,44699,ಶಾಂಭವಿ ಮಹಾಮುದ್ರ:,10
4,file:///wiki/%E0%B2%B6%E0%B2%BF%E0%B2%B5,45018,ಶಿವ,45081,ಶಾಂಭವಿ ಮಹಾಮುದ್ರ:,14

Processing language: ms
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/ms
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 64.89it/s]

Time taken for v1: 21.17551612854004
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 36.21it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b1d0838f7e1f4fc9f6319aefb07ccc3b,0,\nDatuk Haji Pkharuddin bin Haji Ghazali (Jawi...,43357,65347,Lead,"[{'start': 43356, 'end': 43357}, {'start': 433..."
1,b6059ef471e7a3df8c3429fca17e5bcb,1,\n\n\n\nPkharuddin dilahirkan di Kampung Selis...,65347,65852,Kehidupan awal dan pendidikan,"[{'start': 65518, 'end': 65519}, {'start': 655..."
2,264de2b993a9ef330670b57e7a1efa20,2,Beliau mempunyai sembilan orang adik beradik d...,65852,65944,Kehidupan awal dan pendidikan,"[{'start': 65852, 'end': 65944}]"
3,06f1e582e70db5eeccb4ffacd9beb3ee,3,Pkharuddin memulakan pelajaran di Sekolah Keba...,65944,66211,Kehidupan awal dan pendidikan,"[{'start': 65951, 'end': 65985}, {'start': 660..."
4,55d0cb719167500776e029adcf591dc0,4,Beliau merupakan seorang ahli pengakap pada za...,66211,66615,Kehidupan awal dan pendidikan,"[{'start': 66211, 'end': 66325}, {'start': 664..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Kupu-kupu,42158,kupu-kupu,42215,Lead,0
1,file:///wiki/Papilionidae,42232,swallowtail,42317,Lead,0
2,file:///wiki/Benua_kecil_India,42545,Benua kecil India,42646,Lead,3
3,file:///wiki/Asia_Tenggara,42674,Asia Tenggara,42743,Lead,3
4,file:///wiki/Australasia,42748,Australasia,42811,Lead,3

Processing language: pt
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/pt
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 63.50it/s]

Time taken for v1: 15.903706312179565
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 73.62it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,e39566d2646206b6ffd741f08c4e80c8,0,\nIpuiuna é um município brasileiro localizado...,65262,65458,Lead,"[{'start': 65261, 'end': 65262}, {'start': 652..."
1,1efee6236d51cb07979ecb1fa3f2c527,1,Localizado na Mesorregião do Sul e Sudoeste de...,65458,65546,Lead,"[{'start': 65458, 'end': 65546}]"
2,cb39bfb7f0fe37b4d361d07098ff0c4d,2,\n\n\nPode se dizer que a história do municípi...,65546,66006,História,"[{'start': 65550, 'end': 65551}, {'start': 655..."
3,a3ffdb08891d20833c3ca09158a5e8c6,3,Teve início a partir da descoberta do planalto...,66006,66206,História,"[{'start': 66006, 'end': 66206}]"
4,f816615303344cdb3d194c69ca812347,4,"A abertura, iniciada em Ouro Fino, transpôs a ...",66206,66392,História,"[{'start': 66206, 'end': 66392}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Munic%C3%ADpio,65285,município,65347,Lead,0
1,file:///wiki/Minas_Gerais,65390,Minas Gerais,65456,Lead,0
2,file:///wiki/Caldas,65832,Caldas,65880,História,2
3,file:///wiki/Santa_Rita_de_Caldas,65914,Santa Rita de Caldas,66004,História,2
4,file:///wiki/Caldas,68594,Caldas,68642,História,19

Processing language: ru
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/ru
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 43.85it/s]

Time taken for v1: 14.663537979125977
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 42.01it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,b459cfa4e21d45eac24b08ee98036734,0,"У этого топонима есть и другие значения, см. П...",16600,16867,Lead,"[{'start': 16600, 'end': 16645}, {'start': 168..."
1,9fc7114432a074efd9c9f1ec4b5125a0,1,\n\nПреображе́нская площадь&nbsp;— площадь Сан...,16867,27003,Lead,"[{'start': 16873, 'end': 16874}, {'start': 268..."
2,66b8daaee0747ccd270845b3a4518b4e,2,"Расположена на пересечении улицы Рылеева, Коро...",27003,28285,Lead,"[{'start': 27003, 'end': 27030}, {'start': 272..."
3,d72014ba04f3da45e1f788f77ac40066,3,\n\n\n\nПервоначальное название с 1836 года пл...,28285,30528,Наименование,"[{'start': 28289, 'end': 28290}, {'start': 299..."
4,97f205253481f3ef312e899e9be411cc,4,Одновременно существовали названия с 1840-х го...,30528,30804,Наименование,"[{'start': 30528, 'end': 30585}, {'start': 305..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%D0%91%D0%B5%D0%BB%D0%B0%D1%8F_%D...,13384,Белая гвардия (значения),13606,Lead,0
1,file:///wiki/%D0%91%D1%83%D0%BB%D0%B3%D0%B0%D0...,19902,Михаила Булгакова,20130,Lead,1
2,file:///wiki/%D0%A0%D0%B5%D0%B2%D0%BE%D0%BB%D1...,20152,Гражданской войны на Украине,20465,Lead,1
3,file:///wiki/1918_%D0%B3%D0%BE%D0%B4,20474,1918 года,20544,Lead,1
4,file:///wiki/%D0%9A%D0%B8%D0%B5%D0%B2,20901,Киева,20964,Lead,4

Processing language: simple
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/simple
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 67.98it/s]

Time taken for v1: 16.788881301879883
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 60.29it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,d2e21f6460f9a8c6bcb58e0a98d6a93b,0,\nThe Murray-Darling Basin is an area in Austr...,42503,42712,Lead,"[{'start': 42502, 'end': 42503}, {'start': 425..."
1,8e04a300d69cf8de67e857dc7901f828,1,Three million Australians inside and outside t...,42712,42805,Lead,"[{'start': 42712, 'end': 42805}]"
2,2d4f2f1b7eb87ba7fbef61ad2deb344c,2,About 6 per cent of Australia's total rainwate...,42805,42896,Lead,"[{'start': 42812, 'end': 42896}]"
3,f9fb789b45575c022411caeefe8362a1,3,About 85 per cent of all irrigation in Austra...,42896,43203,Lead,"[{'start': 42999, 'end': 43025}, {'start': 430..."
4,f8a20df2afdb5c55f295e7444424b40a,4,"The Murray-Darling Basin covers 1,061,469 squa...",43203,43364,Lead,"[{'start': 43210, 'end': 43364}]"

                        link  startIdx          text  endIdx section  sentid
0  file:///wiki/Construction     42840  construction   42906    Lead       1
1        file:///wiki/Pulley     43721       pulleys   43770    Lead       7

Processing language: sk
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/sk
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 67.97it/s]

Time taken for v1: 8.084615468978882
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 64.54it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,12a28de35fd8ec20dc8c88a1f54fbc79,0,\n\nTento index bol automaticky vygenerovaný p...,37620,38418,Lead,"[{'start': 37619, 'end': 37620}, {'start': 382..."
1,79941c7cc3096a2c3639142867773fea,1,Obsahuje 193 článkov.,38418,38447,Lead,"[{'start': 38418, 'end': 38427}, {'start': 384..."
2,27d2bf2ed1ad2f0e4486f6bb5819dad7,2,"Aby sa nové články zobrazili v tomto indexe, m...",38447,38553,Lead,"[{'start': 38447, 'end': 38553}]"
3,268f2af31e24b28101aa440caca66abc,3,Nové a upravené kategórie sa zohľadnia pri nas...,38553,38621,Lead,"[{'start': 38553, 'end': 38621}]"
4,4124cd6f35b1913b26b929cfa59aaca5,4,\n\nĽadový potok (prítok Popradu)\n\n\nĽuba Le...,38621,57326,ľu,"[{'start': 38625, 'end': 38626}, {'start': 387..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/Profesor_(vedecko-pedagogick%C3%A...,54539,Prof.,54660,Lead,1
1,file:///wiki/Doktor_pr%C3%A1v,54661,JUDr.,54723,Lead,2
2,file:///wiki/Doktor_vied,54743,DrSc.,54800,Lead,3
3,file:///wiki/Doctor_honoris_causa,54802,mult. Dr. h. c.,54903,Lead,4
4,file:///wiki/2._janu%C3%A1r,54907,2. január,54969,Lead,5

Processing language: sw
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/sw
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 88.80it/s]

Time taken for v1: 4.055478096008301
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 85.44it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,8e4417fde47fd3d51b8c833e9ec7f771,0,\nGodefrid Duynen (1502 - 1572) alikuwa padri ...,36205,36913,Lead,"[{'start': 36204, 'end': 36205}, {'start': 362..."
1,43681e69a6efd2d1fbb311f86610a368,1,Anaheshimiwa na Kanisa Katoliki kama mtakatifu...,36913,37131,Lead,"[{'start': 36920, 'end': 36936}, {'start': 369..."
2,66741ab5efb0693e9b3939feab7eda58,2,Kwanza alitangazwa na Papa Klement X kuwa mwen...,37131,37617,Lead,"[{'start': 37131, 'end': 37153}, {'start': 372..."
3,ea71f97ae1009f3c6c1ff57058ed7149,3,\n\nWatakatifu wa Agano la Kale\nOrodha ya Wat...,37617,40909,Tanbihi,"[{'start': 37621, 'end': 37622}, {'start': 376..."

                       link  startIdx         text  endIdx section  sentid
0         file:///wiki/Jina     34751         jina   34793    Lead       0
1  file:///wiki/20_Februari     34816  20 Februari   34879    Lead       0
2         file:///wiki/1952     34880         1952   34922    Lead       0
3         file:///wiki/Lamu     34965         Lamu   35007    Lead       0

Processing language: tr
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/tr
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 58.14it/s]

Time taken for v1: 13.811473608016968
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 57.78it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,8a503f573fa1c2529a9f657a62a00ea3,0,\n650.,45472,45483,Lead,"[{'start': 45471, 'end': 45472}, {'start': 454..."
1,c67f2eaf65b4449654479857e37999c8,1,"Kırkpınar Yağlı Güreşleri, 2011 yılında Edirne...",45483,45592,Lead,"[{'start': 45483, 'end': 45508}, {'start': 455..."
2,3da7f2dd4a662662e2380eedc6f36e9c,2,Başpehlivanlığı Ali Gürbüz kazandı.,45592,45748,Lead,"[{'start': 45592, 'end': 45608}, {'start': 457..."
3,ec2917d0016972a1f5c9606514d62973,3,Diğer sonuçlar -boy sırasında- şu şekilde ger...,45748,79409,Kaynakça,"[{'start': 45857, 'end': 45912}, {'start': 460..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%C4%B0srail,49612,İsrail,49665,7 Ekim,3
1,file:///wiki/Hamas,49690,Hamas,49735,7 Ekim,3
2,file:///wiki/Muhammed_Deif,49911,Muhammed Deif,50000,7 Ekim,4
3,file:///wiki/Re%27im_m%C3%BCzik_festivali_katl...,50413,Re'im,50520,7 Ekim,6
4,file:///wiki/%C4%B0srail_Savunma_Kuvvetleri,50863,İsrail Savunma Kuvvetleri,50973,7 Ekim,8

Processing language: ur
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/ur
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 26.08it/s]

Time taken for v1: 28.073539972305298
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 28.01it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,a113375e6a95b8fa360df127effa914b,0,\nحفصہ بنت عمر رضی اللہ عنہا (15ق.ھ / 45ھ) محم...,72715,73958,Lead,"[{'start': 72714, 'end': 72715}, {'start': 727..."
1,6c85e31fc6801be8b927045f85ab859b,1,حضرت خنیس رَضِیَ اللّٰہُ تَعَالٰی عَنْہُ نے غز...,73958,74222,Lead,"[{'start': 73958, 'end': 73963}, {'start': 740..."
2,37920d07756766d7aa79ecd2dc57df15,2,غزوہ کے بعد ان ہی زخموں کی وجہ سے انتقال فرما ...,74222,74273,Lead,"[{'start': 74222, 'end': 74273}]"
3,1b93b918ff83b408c67e4a9f08eb94ce,3,حضرت خنیس رَضِیَ اللّٰہُ تَعَالٰی عَنْہُ کی شہ...,74273,75239,Lead,"[{'start': 74273, 'end': 74278}, {'start': 743..."
4,2d766844b38a752b1e7920e8abbb6306,4,انہوں نے جواب دیا کہ میں اس معاملہ میں غور کرو...,75239,75603,Lead,"[{'start': 75239, 'end': 75409}, {'start': 755..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%DA%A9%D8%B1%DA%A9%D9%B9_%D8%B9%D...,69980,کرکٹ عالمی کپ,70104,Lead,0
1,file:///wiki/%DA%A9%D8%B1%DA%A9%D9%B9,70114,کرکٹ,70176,Lead,0
2,file:///wiki/%D8%A7%DB%8C%DA%A9_%D8%B1%D9%88%D...,70181,ایک روزہ بین الاقوامی,70364,Lead,0
3,file:///wiki/%D8%A8%DB%8C%D9%86_%D8%A7%D9%84%D...,70376,انٹرنیشنل کرکٹ کونسل,70572,Lead,1
4,file:///wiki/%DA%A9%D8%B1%DA%A9%D9%B9_%D8%B9%D...,70785,2007ء کے ورلڈ کپ,70929,Lead,2

Processing language: uz
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/uz
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 70.85it/s]

Time taken for v1: 8.353715896606445
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 61.36it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,795fe22e527c65de1e9ab15e76ce3831,0,Poyanda maqbarasi&nbsp;(yoki Polvon poyaki maq...,36518,36760,Lead,"[{'start': 36518, 'end': 36535}, {'start': 365..."
1,066b68d05454fb84763eabb5054f7377,1,"Maqbara XVI asrga oid boʻlib, bugungi kunda Xi...",36760,37072,Lead,"[{'start': 36760, 'end': 36768}, {'start': 368..."
2,8ed493b1f23e2e73c2875a3a8d282347,2,Tarixiy obyekt „Ichan qalʼa“ davlat muzey-qoʻr...,37072,37265,Lead,"[{'start': 37072, 'end': 37187}, {'start': 372..."
3,4f40d42e02b55af51ff500060ef30295,3,\n\nPahlavon Mahmud maqbarasi va Juma masjidi ...,37265,37592,Joylashuv oʻrni va etimologiyasi,"[{'start': 37269, 'end': 37270}, {'start': 374..."
4,e78fff6f0c90c177d00f3926713c6fb1,4,Bu ikki oraliqda peshtoqi sharqqa tomon qaraga...,37592,37666,Joylashuv oʻrni va etimologiyasi,"[{'start': 37592, 'end': 37666}]"

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/1844,38335,1844,38377,Lead,0
1,file:///wiki/1899,38380,1899,38422,Lead,0
2,file:///wiki/General-leytenant,38427,general-leytenant,38508,Lead,0
3,file:///wiki/Kuopio,38585,Kuopio,38633,Lead,0
4,file:///wiki/Gubernator,38634,gubernatori,38695,Lead,0

Processing language: vi
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/vi
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 51.64it/s]

Time taken for v1: 29.934101819992065
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 21.31it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,55007705735f6172f30b532e08ffdd77,0,Núi Thị Vải là một ngọn núi tại tỉnh Bà Rịa – ...,43151,43370,Lead,"[{'start': 43151, 'end': 43162}, {'start': 431..."
1,3d037e0855515f5da3069b5f5bcf0210,1,Núi nằm về phía tây núi Dinh.,43370,43451,Lead,"[{'start': 43370, 'end': 43390}, {'start': 434..."
2,eda975718b0b35e2869de998c6bd700e,2,\n\n\nNúi nằm về phía đông nội ô thị xã Phú Mỹ...,43451,43770,Vị trí và tên gọi,"[{'start': 43455, 'end': 43456}, {'start': 434..."
3,8e00e90c98652f16991bd1d7c4199aab,3,Từ Tp.HCM theo Quốc lộ 51 đến thị xã Phú Mỹ rẽ...,43770,43827,Vị trí và tên gọi,"[{'start': 43770, 'end': 43827}]"
4,90401bff536d406e5eb33152deaf780f,4,\nTheo sách Gia Định Thành Thông Chí của Trịnh...,43827,44316,Vị trí và tên gọi,"[{'start': 43946, 'end': 43947}, {'start': 439..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/L%C3%A3nh_th%E1%BB%95_h%E1%BA%A3i...,88523,Lãnh thổ hải ngoại thuộc Anh,88674,Lead,1
1,file:///wiki/V%C3%B9ng_Caribe,88677,Vùng Caribe,88745,Lead,1
2,file:///wiki/Qu%E1%BA%A7n_%C4%91%E1%BA%A3o_Lee...,88766,Quần đảo Leeward,88865,Lead,2
3,file:///wiki/Ti%E1%BB%83u_Antilles,88891,Tiểu Antilles,88968,Lead,2
4,file:///wiki/T%C3%A2y_%E1%BA%A4n,88975,Tây Ấn,89036,Lead,2

Processing language: zh
First version html dir: /var/www/html/wikinsert/selected_langs_small_sample/crawled_pages/zh
Running on 48 processes
Parallel multiprocess
Writing sentences and links v1

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 55.18it/s]

Time taken for v1: 31.38294553756714
Writing sentences and links v2

Sentence tokenization: 100%|██████████| 20/20 [00:00<00:00, 56.32it/s]

,md5,id,text,startIdx,endIdx,section,locList
0,a87b7f9939b52e11c45b15832a61fbe3,0,"\n未入流是明、清兩代對於低於從九品的官吏的稱呼，在唐代則被稱為""流外""。",42371,42477,Lead,"[{'start': 42370, 'end': 42371}, {'start': 423..."
1,76db8e7fe8a7329105d1cc465748b043,1,\n\n\n清代:\n文官\n\n\n\n武官\n\n\n\n《明史．卷七二．職官志一》：「...,42477,54907,文獻提及,"[{'start': 42481, 'end': 42482}, {'start': 425..."
2,decd6e782d8676fe47b96b8b6eb645cf,2,不及九品曰未入流。,54907,54916,文獻提及,"[{'start': 54907, 'end': 54916}]"
3,15923bd3fe492768a389e727b2a3dd82,3,」。,54916,54918,文獻提及,"[{'start': 54916, 'end': 54918}]"
4,f0948063ed2bfddf09570c7c8df17e4c,4,\n《二十年目睹之怪現狀》第二四回：“我屈著指頭算道：「降級是降正不降從的，降一級便是八品，...,54918,55064,文獻提及,"[{'start': 54993, 'end': 54994}, {'start': 550..."

,link,startIdx,text,endIdx,section,sentid
0,file:///wiki/%E7%83%8F%E5%85%8B%E8%98%AD%E8%AA%9E,44844,烏克蘭語,44938,Lead,0
1,file:///wiki/%E7%83%8F%E5%85%8B%E8%98%AD,44972,烏克蘭,45055,Lead,0
2,file:///wiki/%E5%88%87%E7%88%BE%E5%B0%BC%E6%88...,45065,切爾尼戈夫州,45161,Lead,0
3,file:///wiki/%E4%BC%8A%E5%A5%87%E5%B0%BC%E4%BA...,45163,伊奇尼亞區,45248,Lead,0
4,file:///wiki/%E4%BA%92%E8%81%94%E7%BD%91%E6%A1...,45746,互联网档案馆,45842,參考資料,1

**Preprocessing**

It included all prperocessing parts but the merging

In [12]:
for lang in langs:
    for side_context_size in side_context_sizes:
        print(f"Processing language: {lang} with side context size {side_context_size}")
        second_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{second_month}"
        third_month_path = f"{simple_render_raw_data_dir}/{lang}wiki-NS0-{third_month}"
        save_path = f"{rev_files_dir}/revisions_{lang}.parquet"
        output_dir = f"{contexts_splitted_data_dir}/{lang}/context_size_{side_context_size}"
        
        subprocess.run([
            "python", "preprocessing.py",
            "--revisions_path", save_path,
            "--parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v2",
            "--first_versions_specific_parsed_html_dir", f"{parsed_htmls_dir}/{lang}_v1",
            "--n_processes", str(processes),
            "--output_dir", output_dir,
            "--side_contexts_size", str(side_context_size),
            "--redirect_1", f"{second_month_path}/processed_data/redirect_map.parquet",
            "--redirect_2", f"{third_month_path}/processed_data/redirect_map.parquet"
        ])

        #preprocessed_data_path = os.path.join(output_dir, f'test_data.parquet')

        #preprocessed_data = pd.read_parquet(preprocessed_data_path)
        #display(preprocessed_data.head(5))

Processing language: af with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 57.99it/s]
100%|██████████| 83/83 [00:00<00:00, 3274.92it/s]

The length of the output is 83
Processing language: ar with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:07<00:00,  2.56it/s]

The length of the output is 38

100%|██████████| 38/38 [00:00<00:00, 5967.41it/s]

Processing language: cs with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:02<00:00,  9.81it/s]

The length of the output is 61

100%|██████████| 61/61 [00:00<00:00, 17636.49it/s]

Processing language: cy with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 111.35it/s]

The length of the output is 34

100%|██████████| 34/34 [00:00<00:00, 6158.24it/s]

Processing language: de with side context size 5
Running on 48 processes

100%|██████████| 49/49 [00:20<00:00,  2.38it/s]

The length of the output is 233

100%|██████████| 233/233 [00:00<00:00, 19393.80it/s]

Processing language: en with side context size 5
Running on 48 processes

100%|██████████| 194/194 [01:22<00:00,  2.35it/s]

The length of the output is 695

100%|██████████| 695/695 [00:00<00:00, 22733.09it/s]

Processing language: es with side context size 5
Running on 48 processes

100%|██████████| 29/29 [00:12<00:00,  2.26it/s]

The length of the output is 75

100%|██████████| 75/75 [00:00<00:00, 9093.28it/s]

Processing language: fa with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:14<00:00,  1.36it/s]

The length of the output is 74

100%|██████████| 74/74 [00:00<00:00, 11018.83it/s]

Processing language: fr with side context size 5
Running on 48 processes

100%|██████████| 26/26 [00:12<00:00,  2.16it/s]

The length of the output is 50

100%|██████████| 50/50 [00:00<00:00, 6912.17it/s]

Processing language: ga with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 192.69it/s]
100%|██████████| 69/69 [00:00<00:00, 15810.27it/s]

The length of the output is 69
Processing language: gu with side context size 5
Running on 48 processes

100%|██████████| 16/16 [00:00<00:00, 161.05it/s]
100%|██████████| 51/51 [00:00<00:00, 22457.69it/s]

The length of the output is 51
Processing language: he with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:01<00:00, 13.85it/s]

The length of the output is 48

100%|██████████| 48/48 [00:00<00:00, 10735.13it/s]

Processing language: hi with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 53.45it/s]
100%|██████████| 82/82 [00:00<00:00, 15204.82it/s]

The length of the output is 82
Processing language: is with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 128.61it/s]

The length of the output is 201

100%|██████████| 201/201 [00:00<00:00, 47614.09it/s]

Processing language: it with side context size 5
Running on 48 processes

100%|██████████| 22/22 [00:06<00:00,  3.21it/s]

The length of the output is 34

100%|██████████| 34/34 [00:00<00:00, 12976.01it/s]

Processing language: ja with side context size 5
Running on 48 processes

100%|██████████| 36/36 [00:06<00:00,  5.47it/s]

The length of the output is 134

100%|██████████| 134/134 [00:00<00:00, 45929.29it/s]

Processing language: jv with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 32.01it/s]
100%|██████████| 64/64 [00:00<00:00, 12868.43it/s]

The length of the output is 64
Processing language: kk with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 91.68it/s]
100%|██████████| 39/39 [00:00<00:00, 12545.28it/s]

The length of the output is 39
Processing language: kn with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 156.68it/s]
100%|██████████| 43/43 [00:00<00:00, 12940.74it/s]

The length of the output is 43
Processing language: ms with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 87.95it/s]

The length of the output is 41

100%|██████████| 41/41 [00:00<00:00, 11630.36it/s]

Processing language: pt with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:04<00:00,  4.10it/s]

The length of the output is 70

100%|██████████| 70/70 [00:00<00:00, 8972.05it/s]

Processing language: ru with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:22<00:00,  1.13s/it]

The length of the output is 50

100%|██████████| 50/50 [00:00<00:00, 11937.34it/s]

Processing language: simple with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 42.84it/s]

The length of the output is 46

100%|██████████| 46/46 [00:00<00:00, 7366.58it/s]

Processing language: sk with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 47.76it/s]
100%|██████████| 122/122 [00:00<00:00, 14210.48it/s]

The length of the output is 122
Processing language: sw with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:00<00:00, 221.32it/s]
100%|██████████| 62/62 [00:00<00:00, 15464.25it/s]

The length of the output is 62
Processing language: tr with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:02<00:00,  9.96it/s]
100%|██████████| 64/64 [00:00<00:00, 16209.87it/s]

The length of the output is 64
Processing language: ur with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:01<00:00, 12.27it/s]

The length of the output is 19

100%|██████████| 19/19 [00:00<00:00, 3995.78it/s]

Processing language: uz with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:01<00:00, 12.22it/s]

The length of the output is 79

100%|██████████| 79/79 [00:00<00:00, 3902.41it/s]

Processing language: vi with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:01<00:00, 11.95it/s]

The length of the output is 66

100%|██████████| 66/66 [00:00<00:00, 7487.40it/s]

Processing language: zh with side context size 5
Running on 48 processes

100%|██████████| 20/20 [00:09<00:00,  2.17it/s]

The length of the output is 89

100%|██████████| 89/89 [00:00<00:00, 55033.62it/s]

**Merging**

In [13]:
test_data_dir = contexts_splitted_data_dir
output_dir = ready_to_score_data_dir

subprocess.run([
    "python", "merge_data.py",
    "--test_data_dir", test_data_dir,
    "--raw_data_dir", simple_render_raw_data_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--output_dir", output_dir,
    "--ignore_warnings"
])

first_lang = langs[0]
first_context_size = str(side_context_sizes[0])
scored_files_example = os.listdir(output_dir)
scored_files_example = list(filter(lambda x: (first_lang in x and first_context_size in x), scored_files_example))
final_input_data_path = os.path.join(output_dir, scored_files_example[0])

final_input_data_df = pd.read_parquet(final_input_data_path)
display(final_input_data_df.head(5))

Saving mention maps:
Processing language af (1/30)
Finished processing language af
Processing language ar (2/30)
Finished processing language ar
Processing language cs (3/30)
Finished processing language cs
Processing language cy (4/30)
Finished processing language cy
Processing language de (5/30)
Finished processing language de
Processing language en (6/30)
Finished processing language en
Processing language es (7/30)
Finished processing language es
Processing language fa (8/30)
Finished processing language fa
Processing language fr (9/30)
Finished processing language fr
Processing language ga (10/30)
Finished processing language ga
Processing language gu (11/30)
Finished processing language gu
Processing language he (12/30)
Finished processing language he
Processing language hi (13/30)
Finished processing language hi
Processing language is (14/30)
Finished processing language is
Processing language it (15/30)
Finished processing language it
Processing language ja (16/30)
Finished processing language ja
Processing language jv (17/30)
Finished processing language jv
Processing language kk (18/30)
Finished processing language kk
Processing language kn (19/30)
Finished processing language kn
Processing language ms (20/30)
Finished processing language ms
Processing language pt (21/30)
Finished processing language pt
Processing language ru (22/30)
Finished processing language ru
Processing language simple (23/30)
Finished processing language simple
Processing language sk (24/30)
Finished processing language sk
Processing language sw (25/30)
Finished processing language sw
Processing language tr (26/30)
Finished processing language tr
Processing language ur (27/30)
Finished processing language ur
Processing language uz (28/30)
Finished processing language uz
Processing language vi (29/30)
Finished processing language vi
Processing language zh (30/30)
Finished processing language zh
Done saving mention maps:
Processing language af (1/30)
Loaded pages
Loaded redirects

100%|██████████| 110890/110890 [00:00<00:00, 709658.10it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 83 links for language af
Removed 0 links because of empty contexts
Removed 23 links because target title is not in source titles
Removed 21 links because of missing section
After cleaning, there are 39 links for language af
Finished processing language af
Processing language ar (2/30)
Loaded pages
Loaded redirects

100%|██████████| 1209639/1209639 [00:01<00:00, 811869.17it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 38 links for language ar
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 25 links for language ar
Finished processing language ar
Processing language cs (3/30)
Loaded pages
Loaded redirects

100%|██████████| 529676/529676 [00:00<00:00, 896199.53it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 61 links for language cs
Removed 0 links because of empty contexts
Removed 8 links because target title is not in source titles
Removed 33 links because of missing section
After cleaning, there are 20 links for language cs
Finished processing language cs
Processing language cy (4/30)
Loaded pages
Loaded redirects

100%|██████████| 269727/269727 [00:00<00:00, 797313.04it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 34 links for language cy
Removed 0 links because of empty contexts
Removed 2 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 31 links for language cy
Finished processing language cy
Processing language de (5/30)
Loaded pages
Loaded redirects

100%|██████████| 2826417/2826417 [00:03<00:00, 795874.33it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 233 links for language de
Removed 0 links because of empty contexts
Removed 148 links because target title is not in source titles
Removed 20 links because of missing section
After cleaning, there are 65 links for language de
Finished processing language de
Processing language en (6/30)
Loaded pages
Loaded redirects

100%|██████████| 6708565/6708565 [00:09<00:00, 682995.15it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 695 links for language en
Removed 0 links because of empty contexts
Removed 83 links because target title is not in source titles
Removed 293 links because of missing section
After cleaning, there are 319 links for language en
Finished processing language en
Processing language es (7/30)
Loaded pages
Loaded redirects

100%|██████████| 1829995/1829995 [00:02<00:00, 773965.99it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 75 links for language es
Removed 0 links because of empty contexts
Removed 13 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 59 links for language es
Finished processing language es
Processing language fa (8/30)
Loaded pages
Loaded redirects

100%|██████████| 967157/967157 [00:01<00:00, 769029.47it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 74 links for language fa
Removed 0 links because of empty contexts
Removed 18 links because target title is not in source titles
Removed 5 links because of missing section
After cleaning, there are 51 links for language fa
Finished processing language fa
Processing language fr (9/30)
Loaded pages
Loaded redirects

100%|██████████| 2515482/2515482 [00:03<00:00, 762985.77it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 50 links for language fr
Removed 0 links because of empty contexts
Removed 15 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 32 links for language fr
Finished processing language fr
Processing language ga (10/30)
Loaded pages
Loaded redirects
Processing context size 5

100%|██████████| 55867/55867 [00:00<00:00, 767211.21it/s]

Loaded links for context_size_5
Originally, there are 69 links for language ga
Removed 0 links because of empty contexts
Removed 36 links because target title is not in source titles
Removed 21 links because of missing section
After cleaning, there are 12 links for language ga
Finished processing language ga
Processing language gu (11/30)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 51 links for language gu
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 18 links because of missing section
After cleaning, there are 32 links for language gu

100%|██████████| 30230/30230 [00:00<00:00, 665514.43it/s]

Finished processing language gu
Processing language he (12/30)
Loaded pages
Loaded redirects

100%|██████████| 339595/339595 [00:00<00:00, 856877.19it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 48 links for language he
Removed 0 links because of empty contexts
Removed 14 links because target title is not in source titles
Removed 1 links because of missing section
After cleaning, there are 33 links for language he
Finished processing language he
Processing language hi (13/30)
Loaded pages
Loaded redirects

100%|██████████| 156710/156710 [00:00<00:00, 719267.98it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 82 links for language hi
Removed 0 links because of empty contexts
Removed 6 links because target title is not in source titles
Removed 8 links because of missing section
After cleaning, there are 68 links for language hi
Finished processing language hi
Processing language is (14/30)
Loaded pages
Loaded redirects

100%|██████████| 56361/56361 [00:00<00:00, 672687.50it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 201 links for language is
Removed 0 links because of empty contexts
Removed 12 links because target title is not in source titles
Removed 82 links because of missing section
After cleaning, there are 107 links for language is
Finished processing language is
Processing language it (15/30)
Loaded pages
Loaded redirects

100%|██████████| 1775929/1775929 [00:02<00:00, 857117.55it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 34 links for language it
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 27 links for language it
Finished processing language it
Processing language ja (16/30)
Loaded pages
Loaded redirects

100%|██████████| 1369610/1369610 [00:01<00:00, 849840.39it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 134 links for language ja
Removed 0 links because of empty contexts
Removed 10 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 121 links for language ja
Finished processing language ja
Processing language jv (17/30)
Loaded pages
Loaded redirects

100%|██████████| 70540/70540 [00:00<00:00, 872254.78it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 64 links for language jv
Removed 0 links because of empty contexts
Removed 20 links because target title is not in source titles
Removed 12 links because of missing section
After cleaning, there are 32 links for language jv
Finished processing language jv
Processing language kk (18/30)
Loaded pages
Loaded redirects

100%|██████████| 233608/233608 [00:00<00:00, 745300.12it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 39 links for language kk
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 6 links because of missing section
After cleaning, there are 26 links for language kk
Finished processing language kk
Processing language kn (19/30)
Loaded pages
Loaded redirects
Processing context size 5
Loaded links for context_size_5
Originally, there are 43 links for language kn
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 14 links because of missing section
After cleaning, there are 26 links for language kn

100%|██████████| 27889/27889 [00:00<00:00, 813908.60it/s]

Finished processing language kn
Processing language ms (20/30)
Loaded pages
Loaded redirects

100%|██████████| 362531/362531 [00:00<00:00, 851980.89it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 41 links for language ms
Removed 0 links because of empty contexts
Removed 3 links because target title is not in source titles
Removed 8 links because of missing section
After cleaning, there are 30 links for language ms
Finished processing language ms
Processing language pt (21/30)
Loaded pages
Loaded redirects

100%|██████████| 1103653/1103653 [00:01<00:00, 846112.05it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 70 links for language pt
Removed 0 links because of empty contexts
Removed 25 links because target title is not in source titles
Removed 17 links because of missing section
After cleaning, there are 28 links for language pt
Finished processing language pt
Processing language ru (22/30)
Loaded pages
Loaded redirects

100%|██████████| 1920674/1920674 [00:03<00:00, 640085.95it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 50 links for language ru
Removed 0 links because of empty contexts
Removed 36 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 14 links for language ru
Finished processing language ru
Processing language simple (23/30)
Loaded pages
Loaded redirects

100%|██████████| 238680/238680 [00:00<00:00, 785802.35it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 46 links for language simple
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 15 links because of missing section
After cleaning, there are 27 links for language simple
Finished processing language simple
Processing language sk (24/30)
Loaded pages
Loaded redirects

100%|██████████| 242165/242165 [00:00<00:00, 752262.89it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 122 links for language sk
Removed 0 links because of empty contexts
Removed 22 links because target title is not in source titles
Removed 64 links because of missing section
After cleaning, there are 36 links for language sk
Finished processing language sk
Processing language sw (25/30)
Loaded pages
Loaded redirects

100%|██████████| 74218/74218 [00:00<00:00, 780836.22it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 62 links for language sw
Removed 0 links because of empty contexts
Removed 1 links because target title is not in source titles
Removed 0 links because of missing section
After cleaning, there are 61 links for language sw
Finished processing language sw
Processing language tr (26/30)
Loaded pages
Loaded redirects

100%|██████████| 528537/528537 [00:00<00:00, 820905.28it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 64 links for language tr
Removed 0 links because of empty contexts
Removed 13 links because target title is not in source titles
Removed 30 links because of missing section
After cleaning, there are 21 links for language tr
Finished processing language tr
Processing language ur (27/30)
Loaded pages
Loaded redirects

100%|██████████| 188553/188553 [00:00<00:00, 747033.59it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 19 links for language ur
Removed 0 links because of empty contexts
Removed 4 links because target title is not in source titles
Removed 7 links because of missing section
After cleaning, there are 8 links for language ur
Finished processing language ur
Processing language uz (28/30)
Loaded pages
Loaded redirects

100%|██████████| 229168/229168 [00:00<00:00, 746960.72it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 79 links for language uz
Removed 0 links because of empty contexts
Removed 7 links because target title is not in source titles
Removed 31 links because of missing section
After cleaning, there are 41 links for language uz
Finished processing language uz
Processing language vi (29/30)
Error reading file /dlabdata1/tsoares/wikidumps/viwiki-NS0-20231001/processed_data/good_pages/good_pages_55.parquet
Loaded pages
Loaded redirects

100%|██████████| 1273459/1273459 [00:01<00:00, 879209.50it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 66 links for language vi
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 23 links because of missing section
After cleaning, there are 32 links for language vi
Finished processing language vi
Processing language zh (30/30)
Loaded pages
Loaded redirects

100%|██████████| 1344667/1344667 [00:01<00:00, 800066.24it/s]

Processing context size 5
Loaded links for context_size_5
Originally, there are 89 links for language zh
Removed 0 links because of empty contexts
Removed 11 links because target title is not in source titles
Removed 3 links because of missing section
After cleaning, there are 75 links for language zh
Finished processing language zh

,source_title,source_ID,target_title,context,insert_indices,moved_insertion_marker,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts,target_lead
0,1942,486,9_Julie,None,[62],None,"9 Julie - Richard Roundtree, Amerikaanse akteu...",9 Julie,Geboortes,None,Die jaar 1942 was 'n gewone jaar wat volgens d...,2622176,2624839,None,missing_sentence,[{'context': 'Die jaar 1942 was 'n gewone jaar...,9 Julie is die 190ste dag van die jaar in die ...
1,Marius_Petipa,407068,Pjotr_Tsjaikofski,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Tsjaikofski,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,"Pjotr Iljitsj Tsjaikofski, Wotkinsk, 7 Mei 184..."
2,Marius_Petipa,407068,Groothertog_Aleksander_Michailowitsj_van_Rusland,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Groothertog Aleksander Michailowitsj van Rusland,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,Hierdie naam is volgens die Oos-Slawiese gebru...
3,Marius_Petipa,407068,Nikolaas_II_van_Rusland,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Keiser Nikolaas II,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,Nikolaas II Aleksandrowitsj was die laaste kei...
4,Marius_Petipa,407068,Giuseppe_Verdi,None,[167],None,Gedurende die goue era van die Russiese Ryk he...,Verdi,"Sint Petersburg, Rusland",None,Marius Ivanovich Petipa (Russies: Мариус Ивано...,2621414,2621682,None,missing_span,[{'context': 'Marius Ivanovich Petipa (Russies...,Giuseppe Fortunino Francesco Verdi was 'n Ital...

**Scoring the contexts**

In [4]:
data_dir = ready_to_score_data_dir
output_dir = scored_data_dir

for lang in langs:
    for side_context_size in side_context_sizes:
        print(f"Processing language: {lang} with side context size {side_context_size}")

        subprocess.run([
            "python", "get_llm_scores.py",
            "--data_dir", data_dir,
            "--output_dir", output_dir,
            "--lang", lang,
            "--side_contexts_size", str(side_context_size),
            "--model_dir", "/dlabdata1/tsoares/models",
            "--model_prefix", "roberta_full",
            "--use_section_title",
            "--batch_size", "32",
            "--use_mentions",
            "--use_cuda",
            "--multilingual",
            "--multilingual_name", "multilingual-all"
        ])

scored_files_example = os.listdir(output_dir)[0]
scored_data = pd.read_parquet(f"{output_dir}/{scored_files_example}")

exemple = scored_data['all_contexts'][0][0]

for key in exemple.keys():
    print(f"{key}:\n{exemple[key]}\n")

Processing language: simple with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: simple already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: sk with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: sk already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: sw with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: sw already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: tr with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: tr already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: ur with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: ur already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: uz with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: uz already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: vi with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: vi already done for context_size 5 and model roberta_full_multilingual-all, passing

Processing language: zh with side context size 5

Traceback (most recent call last):
  File "/scratch/boulenge/wikinsert/get_llm_scores.py", line 112, in <module>
    raise ValueError(f'{lang} already done for context_size {side_contexts_size} and model {full_model_name}, passing')
ValueError: zh already done for context_size 5 and model roberta_full_multilingual-all, passing

context:
Vòng bảng UEFA Europa Conference League 2023–24 bắt đầu vào ngày 21 tháng 9 năm 2023 và kết thúc vào ngày 14 tháng 12 năm 2023. Có tổng cộng 32 đội thi đấu ở vòng bảng để xác định 16 trong số 24 suất vào vòng đấu loại trực tiếp của UEFA Europa Conference League 2023–24. Tất cả các đội bóng ngoài AZ, Ballkani, Bodø/Glimt, Fiorentina, Gent, HJK, Maccabi Tel Aviv, PAOK, Slovan Bratislava và Zorya Luhansk có lần đầu tiên ra mắt ở vòng bảng. Breiðablik, Čukarički, KÍ, Olimpija Ljubljana và Zrinjski Mostar có lần đầu tiên ra mắt ở vòng bảng một giải đấu UEFA. Breiðablik, KÍ và Zrinjski Mostar là những đội bóng đầu tiên lần lượt từ Iceland, Quần đảo Faroe và Bosnia và Herzegovina thi đấu ở vòng bảng một giải đấu UEFA. Có tổng cộng 28 hiệp hội quốc gia được đại diện ở vòng bảng.

middle_sentence:
{'clean_sentence': 'Vòng bảng UEFA Europa Conference League 2023–24 bắt đầu vào ngày 21 tháng 9 năm 2023 và kết thúc vào ngày 14 tháng 12 năm 2023.', 'clean_sentence2': None, 'endIdx1': 49121, 'endIdx2': 48255.0, 'ids1': array([0]), 'ids2': array([0]), 'index': 0, 'locList1': array([{'end': 49037, 'start': 48990}, {'end': 49121, 'start': 49041}],
      dtype=object), 'locList2': array([{'end': 48171, 'start': 48124}, {'end': 48255, 'start': 48175}],
      dtype=object), 'modifications': None, 'moved_to': None, 'section1': 'Lead', 'section2': 'Lead', 'startIdx1': 48990, 'startIdx2': 48124.0, 'status': 'neutral'}

score:
8.85589599609375

section:
Lead

**Colouring the pages**

In [24]:
sorted_link_output_dir = os.path.join(server_out_dir, "colored_pages")
soft_links_dir = os.path.join(server_out_dir, "soft_links")
print()
# Run the coloring script
subprocess.run([
    "python", "color_pages.py",
    "--scored_data_dir", scored_data_dir,
    "--html_dir", crawling_output_dir,
    "--sorted_links_output_dir", sorted_link_output_dir,
    "--soft_links_dir", soft_links_dir,
    "--langs", ",".join(langs),
    "--side_contexts_sizes", ",".join(map(str, side_context_sizes)),
    "--extra_crawled_files_dir", crawling_output_dir,
    "--full_model_name", "roberta_full_multilingual-all"
])