In [1]:
import pandas as pd
from color_pages import *
from tqdm import tqdm

import json
tqdm.pandas()



%load_ext autoreload
%autoreload 2

In [2]:
scored_simple_5 =pd.read_parquet("/dlabdata1/boulenge/wikidumps_data/originals/scored_data/simple_5_scored.parquet")

In [3]:
display(scored_simple_5['missing_category'].value_counts())

missing_category
missing_mention_with_sentence_modification    10
missing_mention                                3
Name: count, dtype: int64

In [5]:
display(scored_simple_5)

,source_title,source_ID,target_title,context,insert_indices,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts,target_lead,idx
0,The_Tempest,7515,Wizard,None,[2],It tells the story of a wizard who drives a sh...,wizard,Lead,None,Prospero and Ariel from a painting by William ...,8947932,9146709,None,missing_mention,[{'context': 'Prospero and Ariel from a painti...,"A wizard, magician, sorceror or sorceress is a...",0
1,Outline_of_socialism,1003155,Scientific socialism,None,"[0, 1, 2]",Utopian socialism. Scientific socialism. Bourg...,Scientific socialism,Classical and historical,None,,8841989,9150894,None,missing_mention,[{'context': 'Utopian socialism. Scientific so...,Scientific socialism utilizes scientific metho...,1
2,Narges_Mohammadi,1052532,Bail,None,[14],"She was briefly released on a US$50,000 bail b...",bail,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,Bail is money given to the court to guarantee ...,2
3,Narges_Mohammadi,1052532,Epilepsy,None,[15],"Mohammadi's health declined while in custody, ...",epilepsy,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,Epilepsy is a chronic condition of the brain. ...,3
4,Narges_Mohammadi,1052532,Imprisonment,None,"[17, 18]","In July 2011, Mohammadi was prosecuted again[1...",imprisonment,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,Imprisonment or incarceration is the holding o...,4
5,Narges_Mohammadi,1052532,Lawyer,None,"[19, 20]",Mohammadi stated that she had learned of the v...,lawyers,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,A lawyer is someone who practices law. A lawye...,5
6,Narges_Mohammadi,1052532,United States Senate,None,"[21, 22, 23]","On 26 April, she was arrested to begin her sen...",US Senator,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,The United States Senate is the upper house of...,6
7,Narges_Mohammadi,1052532,Canada,None,"[21, 22, 23]","On 26 April, she was arrested to begin her sen...",Canadian,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,Canada is a country in North America. Its land...,7
8,Narges_Mohammadi,1052532,Member of parliament,None,"[21, 22, 23]","On 26 April, she was arrested to begin her sen...",MP,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,A member of parliament (MP) is the representat...,8
9,Narges_Mohammadi,1052532,Tehran,None,"[25, 26]","In May 2016, she was sentenced in Tehran to 16...",Tehran,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,"Tehran, is the capital of Iran and the center ...",9
10,Narges_Mohammadi,1052532,Prison,None,"[25, 26]","In May 2016, she was sentenced in Tehran to 16...",prison,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,A prison or jail is a building where people ar...,10
11,Narges_Mohammadi,1052532,Solitary confinement,None,"[25, 26]","In May 2016, she was sentenced in Tehran to 16...",solitary confinement,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention_with_sentence_modification,[{'context': 'Narges Mohammadi. Narges Mohamma...,Solitary confinement is a punishment or specia...,11
12,Narges_Mohammadi,1052532,Reporters Without Borders,None,[28],Reporters Without Borders issued an appeal on ...,Reporters Without Borders,Prison,None,Narges Mohammadi. Narges Mohammadi is an Irani...,9125279,9125281,None,missing_mention,[{'context': 'Narges Mohammadi. Narges Mohamma...,Reporters Without Borders (RWB) is an internat...,12

In [9]:
colouring_pipeline(
    scored_simple_5,
    'colored_html_originals',
    'originals',
    'simple',
)

Coloring with blue_to_red
Smoothing param: 1

100%|██████████| 13/13 [00:00<00:00, 969.99it/s]

Style: highlight

 23%|██▎       | 3/13 [00:00<00:00, 20.51it/s]

100%|██████████| 13/13 [00:00<00:00, 13.49it/s]

In [10]:
def get_url(source_title, version):
    return f"https://simple.wikipedia.org/w/index.php?title={source_title}&oldid={version}"

In [11]:
def get_file_name(source_ID, version):
    return f"{source_ID}_{version}.html"

In [12]:
url_df = pd.DataFrame()

url_df['title'] = scored_simple_5['source_title']
url_df['first_file_name'] = scored_simple_5[['source_ID', 'first_version']].apply(lambda x: get_file_name(x['source_ID'], x['first_version']), axis=1)
url_df['second_file_name'] = scored_simple_5[['source_ID', 'second_version']].apply(lambda x: get_file_name(x['source_ID'], x['second_version']), axis=1)
url_df['first_version_url'] = scored_simple_5[['source_title', 'first_version']].apply(lambda x: get_url(x['source_title'], x['first_version']), axis=1)
url_df['second_version_url'] = scored_simple_5[['source_title', 'second_version']].apply(lambda x: get_url(x['source_title'], x['second_version']), axis=1)

display(url_df)

,title,first_file_name,second_file_name,first_version_url,second_version_url
0,Rob_Paulsen,536485_9119653.html,536485_9121450.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
1,The_Tempest,7515_8947932.html,7515_9146709.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
2,Outline_of_socialism,1003155_8841989.html,1003155_9150894.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
3,Deng_Nan,1057082_9149782.html,1057082_9154089.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
4,Narges_Mohammadi,1052532_9125279.html,1052532_9125281.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
...,...,...,...,...,...
995,Schizophrenia,3581_9144844.html,3581_9144870.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
996,McMaster_University,582188_9136899.html,582188_9136902.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
997,Palestinian_people,182644_9121013.html,182644_9123297.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
998,Liver_%28food%29,828897_8837337.html,828897_9039872.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
999,Cata_Coll,1050638_9098099.html,1050638_9098102.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...

In [13]:
for i, first_verison_url in enumerate(url_df['first_version_url']):
    print(i)
    print(url_df['first_file_name'][i])
    print(first_verison_url)

0
536485_9119653.html
https://simple.wikipedia.org/w/index.php?title=Rob_Paulsen&oldid=9119653
1
7515_8947932.html
https://simple.wikipedia.org/w/index.php?title=The_Tempest&oldid=8947932
2
1003155_8841989.html
https://simple.wikipedia.org/w/index.php?title=Outline_of_socialism&oldid=8841989
3
1057082_9149782.html
https://simple.wikipedia.org/w/index.php?title=Deng_Nan&oldid=9149782
4
1052532_9125279.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9125279
5
1053256_9117927.html
https://simple.wikipedia.org/w/index.php?title=Justice_Documentary_Festival_Paris&oldid=9117927
6
1046542_9096361.html
https://simple.wikipedia.org/w/index.php?title=Websites_blocked_in_China&oldid=9096361
7
3581_9156525.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9156525
8
1048917_9100489.html
https://simple.wikipedia.org/w/index.php?title=Amie_Doherty&oldid=9100489
9
298515_7837709.html
https://simple.wikipedia.org/w/index.php?title=Bachelor%27s_degree&oldid=7837709
10
1046542_9097074.html
https://simple.wikipedia.org/w/index.php?title=Websites_blocked_in_China&oldid=9097074
11
899880_9053273.html
https://simple.wikipedia.org/w/index.php?title=Ghassan_Kanafani&oldid=9053273
12
17751_8749614.html
https://simple.wikipedia.org/w/index.php?title=Trinidad_and_Tobago&oldid=8749614
13
1022917_9137052.html
https://simple.wikipedia.org/w/index.php?title=Daniel_Noboa&oldid=9137052
14
965349_9099730.html
https://simple.wikipedia.org/w/index.php?title=Power_Rangers_Cosmic_Fury&oldid=9099730
15
623621_9044036.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9044036
16
690874_8838743.html
https://simple.wikipedia.org/w/index.php?title=Bilal_Hassani&oldid=8838743
17
899880_9053273.html
https://simple.wikipedia.org/w/index.php?title=Ghassan_Kanafani&oldid=9053273
18
646739_9094979.html
https://simple.wikipedia.org/w/index.php?title=2026_FIFA_World_Cup&oldid=9094979
19
1040668_9021765.html
https://simple.wikipedia.org/w/index.php?title=Electrical_wiring_in_the_United_Kingdom&oldid=9021765
20
14264_9092240.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9092240
21
623621_9114111.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9114111
22
1052532_9125279.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9125279
23
9686_8987025.html
https://simple.wikipedia.org/w/index.php?title=Paragraph&oldid=8987025
24
93590_9138050.html
https://simple.wikipedia.org/w/index.php?title=SK_Rapid_Wien&oldid=9138050
25
50777_9131752.html
https://simple.wikipedia.org/w/index.php?title=Steve_Jobs&oldid=9131752
26
623621_9098434.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9098434
27
986335_9138326.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9138326
28
480662_6830963.html
https://simple.wikipedia.org/w/index.php?title=Hammenh%C3%B6gs_IF&oldid=6830963
29
623621_9144815.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9144815
30
847733_9093444.html
https://simple.wikipedia.org/w/index.php?title=Madongan_dam&oldid=9093444
31
910046_9098350.html
https://simple.wikipedia.org/w/index.php?title=Hazbin_Hotel&oldid=9098350
32
787689_8990401.html
https://simple.wikipedia.org/w/index.php?title=Aur%C3%A9lie_Groizeleau&oldid=8990401
33
770659_9064690.html
https://simple.wikipedia.org/w/index.php?title=Merano&oldid=9064690
34
1049714_9091172.html
https://simple.wikipedia.org/w/index.php?title=Susan_Graham&oldid=9091172
35
623621_9076157.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9076157
36
97945_9103204.html
https://simple.wikipedia.org/w/index.php?title=Arthur_%28TV_series%29&oldid=9103204
37
917970_9010046.html
https://simple.wikipedia.org/w/index.php?title=Eugene_Melnyk&oldid=9010046
38
182644_8960954.html
https://simple.wikipedia.org/w/index.php?title=Palestinian_people&oldid=8960954
39
1052180_9110774.html
https://simple.wikipedia.org/w/index.php?title=Ulm_Minster&oldid=9110774
40
623621_9114111.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9114111
41
562855_8550966.html
https://simple.wikipedia.org/w/index.php?title=Gautam&oldid=8550966
42
14264_9092240.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9092240
43
47138_6758076.html
https://simple.wikipedia.org/w/index.php?title=Real-time_strategy&oldid=6758076
44
10119_9054161.html
https://simple.wikipedia.org/w/index.php?title=2010s&oldid=9054161
45
929124_8967097.html
https://simple.wikipedia.org/w/index.php?title=Chanel_Terrero&oldid=8967097
46
319665_9116778.html
https://simple.wikipedia.org/w/index.php?title=Toys_%22R%22_Us&oldid=9116778
47
1052390_9111950.html
https://simple.wikipedia.org/w/index.php?title=Jon_Fosse&oldid=9111950
48
1052824_9115829.html
https://simple.wikipedia.org/w/index.php?title=List_of_law_enforcement_agencies_in_Florida&oldid=9115829
49
139165_9081463.html
https://simple.wikipedia.org/w/index.php?title=The_Jungle_Book_2&oldid=9081463
50
1055250_9133363.html
https://simple.wikipedia.org/w/index.php?title=List_of_United_States_representatives_from_Alabama&oldid=9133363
51
746617_7584288.html
https://simple.wikipedia.org/w/index.php?title=Warren_County%2C_Kentucky&oldid=7584288
52
962197_9100886.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100886
53
1041893_9030083.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9030083
54
912470_8269646.html
https://simple.wikipedia.org/w/index.php?title=Quaternion&oldid=8269646
55
1054556_9127447.html
https://simple.wikipedia.org/w/index.php?title=Pentag%C3%B3n_Jr.&oldid=9127447
56
4710_8764738.html
https://simple.wikipedia.org/w/index.php?title=Clothing&oldid=8764738
57
1052251_9123890.html
https://simple.wikipedia.org/w/index.php?title=List_of_mayors_in_Norway_2023%E2%80%932027&oldid=9123890
58
45104_9109924.html
https://simple.wikipedia.org/w/index.php?title=Western_Bloc&oldid=9109924
59
3581_9133439.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133439
60
3581_9143704.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9143704
61
182644_9112009.html
https://simple.wikipedia.org/w/index.php?title=Palestinian_people&oldid=9112009
62
932392_9128061.html
https://simple.wikipedia.org/w/index.php?title=Babar_Azam&oldid=9128061
63
984603_9123093.html
https://simple.wikipedia.org/w/index.php?title=Laurent_Mauvignier&oldid=9123093
64
1033557_9107832.html
https://simple.wikipedia.org/w/index.php?title=Henry_Jackman&oldid=9107832
65
922590_8540271.html
https://simple.wikipedia.org/w/index.php?title=French_language_in_Lebanon&oldid=8540271
66
716425_9091498.html
https://simple.wikipedia.org/w/index.php?title=Pietro_Ubaldi&oldid=9091498
67
34233_9127567.html
https://simple.wikipedia.org/w/index.php?title=Idi_Amin&oldid=9127567
68
962197_9100941.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100941
69
674156_9124350.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9124350
70
536485_9119653.html
https://simple.wikipedia.org/w/index.php?title=Rob_Paulsen&oldid=9119653
71
171483_7347482.html
https://simple.wikipedia.org/w/index.php?title=Ticket_of_leave&oldid=7347482
72
1016646_8922247.html
https://simple.wikipedia.org/w/index.php?title=Renaissance_%28Lionel_Richie_album%29&oldid=8922247
73
971606_9026418.html
https://simple.wikipedia.org/w/index.php?title=Max_Hamburgers&oldid=9026418
74
623621_9130499.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9130499
75
962197_9100886.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100886
76
537152_9129101.html
https://simple.wikipedia.org/w/index.php?title=Benedict_of_Nursia&oldid=9129101
77
962197_9100886.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100886
78
948805_9114752.html
https://simple.wikipedia.org/w/index.php?title=Philippine_Collective_Media_Corporation&oldid=9114752
79
986544_9030634.html
https://simple.wikipedia.org/w/index.php?title=Taylor_Louderman&oldid=9030634
80
984603_9123132.html
https://simple.wikipedia.org/w/index.php?title=Laurent_Mauvignier&oldid=9123132
81
1055054_9131769.html
https://simple.wikipedia.org/w/index.php?title=Fatah%E2%80%93Hamas_conflict&oldid=9131769
82
570951_9133194.html
https://simple.wikipedia.org/w/index.php?title=Guillermo_Lasso&oldid=9133194
83
122429_8390254.html
https://simple.wikipedia.org/w/index.php?title=Resident_Evil_5&oldid=8390254
84
198155_9105152.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105152
85
1052901_9138346.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9138346
86
473755_8758771.html
https://simple.wikipedia.org/w/index.php?title=Rooster_Teeth&oldid=8758771
87
454146_8932855.html
https://simple.wikipedia.org/w/index.php?title=Virat_Kohli&oldid=8932855
88
674156_9123796.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9123796
89
1052149_9114043.html
https://simple.wikipedia.org/w/index.php?title=Barnabas_Dejen_Mondal&oldid=9114043
90
179290_6973133.html
https://simple.wikipedia.org/w/index.php?title=Shoreditch&oldid=6973133
91
76039_9111071.html
https://simple.wikipedia.org/w/index.php?title=Taylor_Swift&oldid=9111071
92
477156_9125223.html
https://simple.wikipedia.org/w/index.php?title=Enver_Hoxha&oldid=9125223
93
818327_9126231.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126231
94
997047_8987616.html
https://simple.wikipedia.org/w/index.php?title=Shelly_Oberoi&oldid=8987616
95
1031676_8952489.html
https://simple.wikipedia.org/w/index.php?title=Oliver_Wood&oldid=8952489
96
1021939_9101673.html
https://simple.wikipedia.org/w/index.php?title=Ahir_Kingdom&oldid=9101673
97
788842_9046953.html
https://simple.wikipedia.org/w/index.php?title=Hydrostatic_paradox&oldid=9046953
98
536485_9119653.html
https://simple.wikipedia.org/w/index.php?title=Rob_Paulsen&oldid=9119653
99
1037087_9074232.html
https://simple.wikipedia.org/w/index.php?title=Student_World_Impact_Film_Festival&oldid=9074232
100
1056248_9143238.html
https://simple.wikipedia.org/w/index.php?title=Marek_Suski&oldid=9143238
101
1049978_9093277.html
https://simple.wikipedia.org/w/index.php?title=Gudetama&oldid=9093277
102
1054377_9127490.html
https://simple.wikipedia.org/w/index.php?title=List_of_fish_common_names&oldid=9127490
103
575437_9084992.html
https://simple.wikipedia.org/w/index.php?title=Richard_C._Clark&oldid=9084992
104
1051294_9104279.html
https://simple.wikipedia.org/w/index.php?title=Muhammad_Ibn_Muhammad_Al-Fulani_Al-Kishwani&oldid=9104279
105
1049713_9091161.html
https://simple.wikipedia.org/w/index.php?title=Joris_Schouten&oldid=9091161
106
1053243_9117872.html
https://simple.wikipedia.org/w/index.php?title=All_Star_Comics&oldid=9117872
107
447687_9114500.html
https://simple.wikipedia.org/w/index.php?title=Narendra_Modi&oldid=9114500
108
1049901_9092617.html
https://simple.wikipedia.org/w/index.php?title=Diergaarde_Blijdorp&oldid=9092617
109
1052901_9118635.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9118635
110
1037079_9015541.html
https://simple.wikipedia.org/w/index.php?title=William_Sealy_Gosset&oldid=9015541
111
937590_8680923.html
https://simple.wikipedia.org/w/index.php?title=Family_of_Kamala_Harris&oldid=8680923
112
623621_9053220.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9053220
113
1052901_9132123.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9132123
114
518246_7528381.html
https://simple.wikipedia.org/w/index.php?title=Typeface&oldid=7528381
115
674156_9122623.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9122623
116
623621_9114111.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9114111
117
424291_8681954.html
https://simple.wikipedia.org/w/index.php?title=Hiroshi_Tanahashi&oldid=8681954
118
920642_8175922.html
https://simple.wikipedia.org/w/index.php?title=Crytek&oldid=8175922
119
8608_8832931.html
https://simple.wikipedia.org/w/index.php?title=Wallet&oldid=8832931
120
725904_7926742.html
https://simple.wikipedia.org/w/index.php?title=101955_Bennu&oldid=7926742
121
623621_9076157.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9076157
122
623621_9144815.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9144815
123
283441_8324263.html
https://simple.wikipedia.org/w/index.php?title=Aaron_Sherritt&oldid=8324263
124
456929_8505940.html
https://simple.wikipedia.org/w/index.php?title=Sveio&oldid=8505940
125
245735_6439858.html
https://simple.wikipedia.org/w/index.php?title=Alexandre_Pato&oldid=6439858
126
1057086_9149806.html
https://simple.wikipedia.org/w/index.php?title=Alma_Reville&oldid=9149806
127
1041560_9110229.html
https://simple.wikipedia.org/w/index.php?title=Climate_change_and_marine_ecosystems&oldid=9110229
128
18508_9049119.html
https://simple.wikipedia.org/w/index.php?title=Nikola_Tesla&oldid=9049119
129
788842_9046953.html
https://simple.wikipedia.org/w/index.php?title=Hydrostatic_paradox&oldid=9046953
130
199337_7420050.html
https://simple.wikipedia.org/w/index.php?title=United_States_Environmental_Protection_Agency&oldid=7420050
131
1038520_9005267.html
https://simple.wikipedia.org/w/index.php?title=Kashtbhanjan_Dev_Sarangpur&oldid=9005267
132
727618_9102977.html
https://simple.wikipedia.org/w/index.php?title=Keir_Starmer&oldid=9102977
133
674156_9123788.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9123788
134
1052901_9145084.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9145084
135
1051934_9108106.html
https://simple.wikipedia.org/w/index.php?title=FTW_Championship&oldid=9108106
136
10317_9140849.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9140849
137
518246_7528381.html
https://simple.wikipedia.org/w/index.php?title=Typeface&oldid=7528381
138
623621_9144815.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9144815
139
4654_9107494.html
https://simple.wikipedia.org/w/index.php?title=Leonardo_da_Vinci&oldid=9107494
140
1042486_9034314.html
https://simple.wikipedia.org/w/index.php?title=Semionotiformes&oldid=9034314
141
423325_9046777.html
https://simple.wikipedia.org/w/index.php?title=Babar%3A_King_of_the_Elephants&oldid=9046777
142
846675_8756808.html
https://simple.wikipedia.org/w/index.php?title=Alfredo_%28name%29&oldid=8756808
143
50777_9131752.html
https://simple.wikipedia.org/w/index.php?title=Steve_Jobs&oldid=9131752
144
9569_9107264.html
https://simple.wikipedia.org/w/index.php?title=A_Clockwork_Orange&oldid=9107264
145
986335_9150410.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9150410
146
623621_9076157.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9076157
147
198155_9105152.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105152
148
25112_9055483.html
https://simple.wikipedia.org/w/index.php?title=Warner_Bros.&oldid=9055483
149
8608_8832931.html
https://simple.wikipedia.org/w/index.php?title=Wallet&oldid=8832931
150
1052901_9119447.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9119447
151
4077_9102213.html
https://simple.wikipedia.org/w/index.php?title=Fuel&oldid=9102213
152
170999_9019494.html
https://simple.wikipedia.org/w/index.php?title=Whopper&oldid=9019494
153
114299_9105207.html
https://simple.wikipedia.org/w/index.php?title=Sesame_Street&oldid=9105207
154
623621_9114111.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9114111
155
103150_8865218.html
https://simple.wikipedia.org/w/index.php?title=Salam&oldid=8865218
156
1052532_9112798.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9112798
157
182644_9111509.html
https://simple.wikipedia.org/w/index.php?title=Palestinian_people&oldid=9111509
158
807161_8640661.html
https://simple.wikipedia.org/w/index.php?title=Tony_Stark_%28Marvel_Cinematic_Universe%29&oldid=8640661
159
78545_9136736.html
https://simple.wikipedia.org/w/index.php?title=Airplane&oldid=9136736
160
1051448_9105454.html
https://simple.wikipedia.org/w/index.php?title=Angelo_Soliman&oldid=9105454
161
283017_8405723.html
https://simple.wikipedia.org/w/index.php?title=Murray%E2%80%93Darling_basin&oldid=8405723
162
1054083_9124263.html
https://simple.wikipedia.org/w/index.php?title=Vicente_Guerrero&oldid=9124263
163
623621_9152527.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9152527
164
623621_9111943.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9111943
165
832320_8981935.html
https://simple.wikipedia.org/w/index.php?title=Chris_Savino&oldid=8981935
166
674156_9123334.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9123334
167
423325_9046736.html
https://simple.wikipedia.org/w/index.php?title=Babar%3A_King_of_the_Elephants&oldid=9046736
168
475238_8709375.html
https://simple.wikipedia.org/w/index.php?title=%C3%89lisabeth_of_France&oldid=8709375
169
1000657_8749076.html
https://simple.wikipedia.org/w/index.php?title=Jadunath_Sarkar&oldid=8749076
170
1056157_9142301.html
https://simple.wikipedia.org/w/index.php?title=Hridaya_Shanker_Singh&oldid=9142301
171
986335_9127563.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9127563
172
9182_8961356.html
https://simple.wikipedia.org/w/index.php?title=Tiny_Tim&oldid=8961356
173
428338_9129719.html
https://simple.wikipedia.org/w/index.php?title=Bubba_Ray_Dudley&oldid=9129719
174
623621_9144815.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9144815
175
1051294_9104279.html
https://simple.wikipedia.org/w/index.php?title=Muhammad_Ibn_Muhammad_Al-Fulani_Al-Kishwani&oldid=9104279
176
938485_8532305.html
https://simple.wikipedia.org/w/index.php?title=Arabic_languages&oldid=8532305
177
114299_9113102.html
https://simple.wikipedia.org/w/index.php?title=Sesame_Street&oldid=9113102
178
1004212_8824952.html
https://simple.wikipedia.org/w/index.php?title=Short_U_%28Cyrillic%29&oldid=8824952
179
391393_8922222.html
https://simple.wikipedia.org/w/index.php?title=The_Weeknd&oldid=8922222
180
1052020_9108763.html
https://simple.wikipedia.org/w/index.php?title=Carson%2C_New_Mexico&oldid=9108763
181
623621_9104271.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9104271
182
1052532_9125279.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9125279
183
623621_9076157.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9076157
184
658023_8034307.html
https://simple.wikipedia.org/w/index.php?title=McGriddles&oldid=8034307
185
956790_9134331.html
https://simple.wikipedia.org/w/index.php?title=Matt_Walsh_%28political_commentator%29&oldid=9134331
186
1057082_9149782.html
https://simple.wikipedia.org/w/index.php?title=Deng_Nan&oldid=9149782
187
444830_9114051.html
https://simple.wikipedia.org/w/index.php?title=Erna_Solberg&oldid=9114051
188
1052532_9127971.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9127971
189
1051448_9105454.html
https://simple.wikipedia.org/w/index.php?title=Angelo_Soliman&oldid=9105454
190
674156_9126570.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9126570
191
20031_8988335.html
https://simple.wikipedia.org/w/index.php?title=AFI%27s_100_Years..._100_Stars&oldid=8988335
192
623621_9142067.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9142067
193
103644_8830718.html
https://simple.wikipedia.org/w/index.php?title=Indian_Premier_League&oldid=8830718
194
801079_9133427.html
https://simple.wikipedia.org/w/index.php?title=2024_United_States_presidential_election&oldid=9133427
195
623621_9099461.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9099461
196
221991_9099891.html
https://simple.wikipedia.org/w/index.php?title=3rd_millennium&oldid=9099891
197

In [14]:
for i, second_version_url in enumerate(url_df['second_version_url']):
    print(i)
    print(url_df['second_file_name'][i])
    print(second_version_url)

0
536485_9121450.html
https://simple.wikipedia.org/w/index.php?title=Rob_Paulsen&oldid=9121450
1
7515_9146709.html
https://simple.wikipedia.org/w/index.php?title=The_Tempest&oldid=9146709
2
1003155_9150894.html
https://simple.wikipedia.org/w/index.php?title=Outline_of_socialism&oldid=9150894
3
1057082_9154089.html
https://simple.wikipedia.org/w/index.php?title=Deng_Nan&oldid=9154089
4
1052532_9125281.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9125281
5
1053256_9117944.html
https://simple.wikipedia.org/w/index.php?title=Justice_Documentary_Festival_Paris&oldid=9117944
6
1046542_9097065.html
https://simple.wikipedia.org/w/index.php?title=Websites_blocked_in_China&oldid=9097065
7
3581_9156569.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9156569
8
1048917_9100542.html
https://simple.wikipedia.org/w/index.php?title=Amie_Doherty&oldid=9100542
9
298515_9118990.html
https://simple.wikipedia.org/w/index.php?title=Bachelor%27s_degree&oldid=9118990
10
1046542_9097079.html
https://simple.wikipedia.org/w/index.php?title=Websites_blocked_in_China&oldid=9097079
11
899880_9065156.html
https://simple.wikipedia.org/w/index.php?title=Ghassan_Kanafani&oldid=9065156
12
17751_9150411.html
https://simple.wikipedia.org/w/index.php?title=Trinidad_and_Tobago&oldid=9150411
13
1022917_9137710.html
https://simple.wikipedia.org/w/index.php?title=Daniel_Noboa&oldid=9137710
14
965349_9099732.html
https://simple.wikipedia.org/w/index.php?title=Power_Rangers_Cosmic_Fury&oldid=9099732
15
623621_9046693.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9046693
16
690874_9116781.html
https://simple.wikipedia.org/w/index.php?title=Bilal_Hassani&oldid=9116781
17
899880_9065156.html
https://simple.wikipedia.org/w/index.php?title=Ghassan_Kanafani&oldid=9065156
18
646739_9095007.html
https://simple.wikipedia.org/w/index.php?title=2026_FIFA_World_Cup&oldid=9095007
19
1040668_9038863.html
https://simple.wikipedia.org/w/index.php?title=Electrical_wiring_in_the_United_Kingdom&oldid=9038863
20
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
21
623621_9115338.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9115338
22
1052532_9125281.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9125281
23
9686_9123607.html
https://simple.wikipedia.org/w/index.php?title=Paragraph&oldid=9123607
24
93590_9141607.html
https://simple.wikipedia.org/w/index.php?title=SK_Rapid_Wien&oldid=9141607
25
50777_9131774.html
https://simple.wikipedia.org/w/index.php?title=Steve_Jobs&oldid=9131774
26
623621_9099168.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9099168
27
986335_9138410.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9138410
28
480662_9130478.html
https://simple.wikipedia.org/w/index.php?title=Hammenh%C3%B6gs_IF&oldid=9130478
29
623621_9147402.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9147402
30
847733_9105904.html
https://simple.wikipedia.org/w/index.php?title=Madongan_dam&oldid=9105904
31
910046_9098445.html
https://simple.wikipedia.org/w/index.php?title=Hazbin_Hotel&oldid=9098445
32
787689_9121483.html
https://simple.wikipedia.org/w/index.php?title=Aur%C3%A9lie_Groizeleau&oldid=9121483
33
770659_9128983.html
https://simple.wikipedia.org/w/index.php?title=Merano&oldid=9128983
34
1049714_9129279.html
https://simple.wikipedia.org/w/index.php?title=Susan_Graham&oldid=9129279
35
623621_9077830.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9077830
36
97945_9103207.html
https://simple.wikipedia.org/w/index.php?title=Arthur_%28TV_series%29&oldid=9103207
37
917970_9037014.html
https://simple.wikipedia.org/w/index.php?title=Eugene_Melnyk&oldid=9037014
38
182644_9111509.html
https://simple.wikipedia.org/w/index.php?title=Palestinian_people&oldid=9111509
39
1052180_9145097.html
https://simple.wikipedia.org/w/index.php?title=Ulm_Minster&oldid=9145097
40
623621_9115338.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9115338
41
562855_9128884.html
https://simple.wikipedia.org/w/index.php?title=Gautam&oldid=9128884
42
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
43
47138_9136474.html
https://simple.wikipedia.org/w/index.php?title=Real-time_strategy&oldid=9136474
44
10119_9091067.html
https://simple.wikipedia.org/w/index.php?title=2010s&oldid=9091067
45
929124_9153422.html
https://simple.wikipedia.org/w/index.php?title=Chanel_Terrero&oldid=9153422
46
319665_9117741.html
https://simple.wikipedia.org/w/index.php?title=Toys_%22R%22_Us&oldid=9117741
47
1052390_9112556.html
https://simple.wikipedia.org/w/index.php?title=Jon_Fosse&oldid=9112556
48
1052824_9115844.html
https://simple.wikipedia.org/w/index.php?title=List_of_law_enforcement_agencies_in_Florida&oldid=9115844
49
139165_9093215.html
https://simple.wikipedia.org/w/index.php?title=The_Jungle_Book_2&oldid=9093215
50
1055250_9133435.html
https://simple.wikipedia.org/w/index.php?title=List_of_United_States_representatives_from_Alabama&oldid=9133435
51
746617_9109828.html
https://simple.wikipedia.org/w/index.php?title=Warren_County%2C_Kentucky&oldid=9109828
52
962197_9100890.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100890
53
1041893_9039855.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9039855
54
912470_9145751.html
https://simple.wikipedia.org/w/index.php?title=Quaternion&oldid=9145751
55
1054556_9127454.html
https://simple.wikipedia.org/w/index.php?title=Pentag%C3%B3n_Jr.&oldid=9127454
56
4710_9147295.html
https://simple.wikipedia.org/w/index.php?title=Clothing&oldid=9147295
57
1052251_9137216.html
https://simple.wikipedia.org/w/index.php?title=List_of_mayors_in_Norway_2023%E2%80%932027&oldid=9137216
58
45104_9109925.html
https://simple.wikipedia.org/w/index.php?title=Western_Bloc&oldid=9109925
59
3581_9133458.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133458
60
3581_9143705.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9143705
61
182644_9121013.html
https://simple.wikipedia.org/w/index.php?title=Palestinian_people&oldid=9121013
62
932392_9128380.html
https://simple.wikipedia.org/w/index.php?title=Babar_Azam&oldid=9128380
63
984603_9123132.html
https://simple.wikipedia.org/w/index.php?title=Laurent_Mauvignier&oldid=9123132
64
1033557_9107858.html
https://simple.wikipedia.org/w/index.php?title=Henry_Jackman&oldid=9107858
65
922590_9141714.html
https://simple.wikipedia.org/w/index.php?title=French_language_in_Lebanon&oldid=9141714
66
716425_9148899.html
https://simple.wikipedia.org/w/index.php?title=Pietro_Ubaldi&oldid=9148899
67
34233_9144956.html
https://simple.wikipedia.org/w/index.php?title=Idi_Amin&oldid=9144956
68
962197_9101816.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9101816
69
674156_9124379.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9124379
70
536485_9121450.html
https://simple.wikipedia.org/w/index.php?title=Rob_Paulsen&oldid=9121450
71
171483_9110307.html
https://simple.wikipedia.org/w/index.php?title=Ticket_of_leave&oldid=9110307
72
1016646_9146067.html
https://simple.wikipedia.org/w/index.php?title=Renaissance_%28Lionel_Richie_album%29&oldid=9146067
73
971606_9130350.html
https://simple.wikipedia.org/w/index.php?title=Max_Hamburgers&oldid=9130350
74
623621_9130894.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9130894
75
962197_9100890.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100890
76
537152_9145387.html
https://simple.wikipedia.org/w/index.php?title=Benedict_of_Nursia&oldid=9145387
77
962197_9100890.html
https://simple.wikipedia.org/w/index.php?title=The_Wonderful_Ice_Cream_Suit&oldid=9100890
78
948805_9135860.html
https://simple.wikipedia.org/w/index.php?title=Philippine_Collective_Media_Corporation&oldid=9135860
79
986544_9153074.html
https://simple.wikipedia.org/w/index.php?title=Taylor_Louderman&oldid=9153074
80
984603_9123148.html
https://simple.wikipedia.org/w/index.php?title=Laurent_Mauvignier&oldid=9123148
81
1055054_9137637.html
https://simple.wikipedia.org/w/index.php?title=Fatah%E2%80%93Hamas_conflict&oldid=9137637
82
570951_9133216.html
https://simple.wikipedia.org/w/index.php?title=Guillermo_Lasso&oldid=9133216
83
122429_9153566.html
https://simple.wikipedia.org/w/index.php?title=Resident_Evil_5&oldid=9153566
84
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
85
1052901_9140432.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9140432
86
473755_9116904.html
https://simple.wikipedia.org/w/index.php?title=Rooster_Teeth&oldid=9116904
87
454146_9065029.html
https://simple.wikipedia.org/w/index.php?title=Virat_Kohli&oldid=9065029
88
674156_9123812.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9123812
89
1052149_9123096.html
https://simple.wikipedia.org/w/index.php?title=Barnabas_Dejen_Mondal&oldid=9123096
90
179290_9152985.html
https://simple.wikipedia.org/w/index.php?title=Shoreditch&oldid=9152985
91
76039_9111155.html
https://simple.wikipedia.org/w/index.php?title=Taylor_Swift&oldid=9111155
92
477156_9128599.html
https://simple.wikipedia.org/w/index.php?title=Enver_Hoxha&oldid=9128599
93
818327_9126236.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126236
94
997047_9107642.html
https://simple.wikipedia.org/w/index.php?title=Shelly_Oberoi&oldid=9107642
95
1031676_9139481.html
https://simple.wikipedia.org/w/index.php?title=Oliver_Wood&oldid=9139481
96
1021939_9101678.html
https://simple.wikipedia.org/w/index.php?title=Ahir_Kingdom&oldid=9101678
97
788842_9101890.html
https://simple.wikipedia.org/w/index.php?title=Hydrostatic_paradox&oldid=9101890
98
536485_9121450.html
https://simple.wikipedia.org/w/index.php?title=Rob_Paulsen&oldid=9121450
99
1037087_9103290.html
https://simple.wikipedia.org/w/index.php?title=Student_World_Impact_Film_Festival&oldid=9103290
100
1056248_9143478.html
https://simple.wikipedia.org/w/index.php?title=Marek_Suski&oldid=9143478
101
1049978_9093600.html
https://simple.wikipedia.org/w/index.php?title=Gudetama&oldid=9093600
102
1054377_9132175.html
https://simple.wikipedia.org/w/index.php?title=List_of_fish_common_names&oldid=9132175
103
575437_9130786.html
https://simple.wikipedia.org/w/index.php?title=Richard_C._Clark&oldid=9130786
104
1051294_9104299.html
https://simple.wikipedia.org/w/index.php?title=Muhammad_Ibn_Muhammad_Al-Fulani_Al-Kishwani&oldid=9104299
105
1049713_9125669.html
https://simple.wikipedia.org/w/index.php?title=Joris_Schouten&oldid=9125669
106
1053243_9120812.html
https://simple.wikipedia.org/w/index.php?title=All_Star_Comics&oldid=9120812
107
447687_9146026.html
https://simple.wikipedia.org/w/index.php?title=Narendra_Modi&oldid=9146026
108
1049901_9094606.html
https://simple.wikipedia.org/w/index.php?title=Diergaarde_Blijdorp&oldid=9094606
109
1052901_9118637.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9118637
110
1037079_9094706.html
https://simple.wikipedia.org/w/index.php?title=William_Sealy_Gosset&oldid=9094706
111
937590_9126987.html
https://simple.wikipedia.org/w/index.php?title=Family_of_Kamala_Harris&oldid=9126987
112
623621_9053290.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9053290
113
1052901_9134705.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9134705
114
518246_9137902.html
https://simple.wikipedia.org/w/index.php?title=Typeface&oldid=9137902
115
674156_9122624.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9122624
116
623621_9115338.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9115338
117
424291_9129748.html
https://simple.wikipedia.org/w/index.php?title=Hiroshi_Tanahashi&oldid=9129748
118
920642_9149839.html
https://simple.wikipedia.org/w/index.php?title=Crytek&oldid=9149839
119
8608_9149844.html
https://simple.wikipedia.org/w/index.php?title=Wallet&oldid=9149844
120
725904_9152431.html
https://simple.wikipedia.org/w/index.php?title=101955_Bennu&oldid=9152431
121
623621_9077830.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9077830
122
623621_9147402.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9147402
123
283441_9107652.html
https://simple.wikipedia.org/w/index.php?title=Aaron_Sherritt&oldid=9107652
124
456929_9100577.html
https://simple.wikipedia.org/w/index.php?title=Sveio&oldid=9100577
125
245735_9146825.html
https://simple.wikipedia.org/w/index.php?title=Alexandre_Pato&oldid=9146825
126
1057086_9149823.html
https://simple.wikipedia.org/w/index.php?title=Alma_Reville&oldid=9149823
127
1041560_9111946.html
https://simple.wikipedia.org/w/index.php?title=Climate_change_and_marine_ecosystems&oldid=9111946
128
18508_9131093.html
https://simple.wikipedia.org/w/index.php?title=Nikola_Tesla&oldid=9131093
129
788842_9101890.html
https://simple.wikipedia.org/w/index.php?title=Hydrostatic_paradox&oldid=9101890
130
199337_9151750.html
https://simple.wikipedia.org/w/index.php?title=United_States_Environmental_Protection_Agency&oldid=9151750
131
1038520_9101932.html
https://simple.wikipedia.org/w/index.php?title=Kashtbhanjan_Dev_Sarangpur&oldid=9101932
132
727618_9102991.html
https://simple.wikipedia.org/w/index.php?title=Keir_Starmer&oldid=9102991
133
674156_9123796.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9123796
134
1052901_9145377.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9145377
135
1051934_9114295.html
https://simple.wikipedia.org/w/index.php?title=FTW_Championship&oldid=9114295
136
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
137
518246_9137902.html
https://simple.wikipedia.org/w/index.php?title=Typeface&oldid=9137902
138
623621_9147402.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9147402
139
4654_9109934.html
https://simple.wikipedia.org/w/index.php?title=Leonardo_da_Vinci&oldid=9109934
140
1042486_9143587.html
https://simple.wikipedia.org/w/index.php?title=Semionotiformes&oldid=9143587
141
423325_9046781.html
https://simple.wikipedia.org/w/index.php?title=Babar%3A_King_of_the_Elephants&oldid=9046781
142
846675_9116194.html
https://simple.wikipedia.org/w/index.php?title=Alfredo_%28name%29&oldid=9116194
143
50777_9131774.html
https://simple.wikipedia.org/w/index.php?title=Steve_Jobs&oldid=9131774
144
9569_9128648.html
https://simple.wikipedia.org/w/index.php?title=A_Clockwork_Orange&oldid=9128648
145
986335_9150772.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9150772
146
623621_9077830.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9077830
147
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
148
25112_9118494.html
https://simple.wikipedia.org/w/index.php?title=Warner_Bros.&oldid=9118494
149
8608_9149844.html
https://simple.wikipedia.org/w/index.php?title=Wallet&oldid=9149844
150
1052901_9119451.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9119451
151
4077_9112607.html
https://simple.wikipedia.org/w/index.php?title=Fuel&oldid=9112607
152
170999_9038875.html
https://simple.wikipedia.org/w/index.php?title=Whopper&oldid=9038875
153
114299_9105218.html
https://simple.wikipedia.org/w/index.php?title=Sesame_Street&oldid=9105218
154
623621_9115338.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9115338
155
103150_9120165.html
https://simple.wikipedia.org/w/index.php?title=Salam&oldid=9120165
156
1052532_9115037.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9115037
157
182644_9112009.html
https://simple.wikipedia.org/w/index.php?title=Palestinian_people&oldid=9112009
158
807161_9055261.html
https://simple.wikipedia.org/w/index.php?title=Tony_Stark_%28Marvel_Cinematic_Universe%29&oldid=9055261
159
78545_9155022.html
https://simple.wikipedia.org/w/index.php?title=Airplane&oldid=9155022
160
1051448_9105860.html
https://simple.wikipedia.org/w/index.php?title=Angelo_Soliman&oldid=9105860
161
283017_9110310.html
https://simple.wikipedia.org/w/index.php?title=Murray%E2%80%93Darling_basin&oldid=9110310
162
1054083_9124265.html
https://simple.wikipedia.org/w/index.php?title=Vicente_Guerrero&oldid=9124265
163
623621_9152535.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9152535
164
623621_9112906.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9112906
165
832320_9115327.html
https://simple.wikipedia.org/w/index.php?title=Chris_Savino&oldid=9115327
166
674156_9123345.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9123345
167
423325_9046739.html
https://simple.wikipedia.org/w/index.php?title=Babar%3A_King_of_the_Elephants&oldid=9046739
168
475238_9058214.html
https://simple.wikipedia.org/w/index.php?title=%C3%89lisabeth_of_France&oldid=9058214
169
1000657_9107644.html
https://simple.wikipedia.org/w/index.php?title=Jadunath_Sarkar&oldid=9107644
170
1056157_9142337.html
https://simple.wikipedia.org/w/index.php?title=Hridaya_Shanker_Singh&oldid=9142337
171
986335_9127586.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9127586
172
9182_9153562.html
https://simple.wikipedia.org/w/index.php?title=Tiny_Tim&oldid=9153562
173
428338_9129721.html
https://simple.wikipedia.org/w/index.php?title=Bubba_Ray_Dudley&oldid=9129721
174
623621_9147402.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9147402
175
1051294_9104299.html
https://simple.wikipedia.org/w/index.php?title=Muhammad_Ibn_Muhammad_Al-Fulani_Al-Kishwani&oldid=9104299
176
938485_9141712.html
https://simple.wikipedia.org/w/index.php?title=Arabic_languages&oldid=9141712
177
114299_9119929.html
https://simple.wikipedia.org/w/index.php?title=Sesame_Street&oldid=9119929
178
1004212_9101942.html
https://simple.wikipedia.org/w/index.php?title=Short_U_%28Cyrillic%29&oldid=9101942
179
391393_9039904.html
https://simple.wikipedia.org/w/index.php?title=The_Weeknd&oldid=9039904
180
1052020_9111961.html
https://simple.wikipedia.org/w/index.php?title=Carson%2C_New_Mexico&oldid=9111961
181
623621_9105271.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9105271
182
1052532_9125281.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9125281
183
623621_9077830.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9077830
184
658023_9149846.html
https://simple.wikipedia.org/w/index.php?title=McGriddles&oldid=9149846
185
956790_9153333.html
https://simple.wikipedia.org/w/index.php?title=Matt_Walsh_%28political_commentator%29&oldid=9153333
186
1057082_9154089.html
https://simple.wikipedia.org/w/index.php?title=Deng_Nan&oldid=9154089
187
444830_9114075.html
https://simple.wikipedia.org/w/index.php?title=Erna_Solberg&oldid=9114075
188
1052532_9128011.html
https://simple.wikipedia.org/w/index.php?title=Narges_Mohammadi&oldid=9128011
189
1051448_9105860.html
https://simple.wikipedia.org/w/index.php?title=Angelo_Soliman&oldid=9105860
190
674156_9126729.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9126729
191
20031_9121039.html
https://simple.wikipedia.org/w/index.php?title=AFI%27s_100_Years..._100_Stars&oldid=9121039
192
623621_9142070.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9142070
193
103644_9129191.html
https://simple.wikipedia.org/w/index.php?title=Indian_Premier_League&oldid=9129191
194
801079_9133429.html
https://simple.wikipedia.org/w/index.php?title=2024_United_States_presidential_election&oldid=9133429
195
623621_9100308.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9100308
196
221991_9099951.html
https://simple.wikipedia.org/w/index.php?title=3rd_millennium&oldid=9099951
197